### ISSUE TITLE
passing NamedTuple as parameters

### ISSUE THREAD

**Issue by rveltz** [SciML/ModelingToolkit.jl#1001]
Hi,

I am not sure this is a mistake. The docs says:

```julia
using DiffEqBase, OrdinaryDiffEq
rn = @reaction_network begin
  p, ∅ → X
  d, X → ∅
end p d
p = [1.0,2.0]
u0 = [0.1]
tspan = (0.,1.)
prob = ODEProblem(rn,u0,tspan,p)
```

But if I do:

```julia
p = (p = 1.0, d = 2.0)
prob = ODEProblem(rn,u0,tspan,p)
```

it returns

```
julia> prob = ODEProblem(rn,u0,tspan,p)
ERROR: MethodError: no method matching create_array(::Type{NamedTuple{(:p, :d), Tuple{Float64, Float64}}}, ::Type{Float64}, ::Val{1}, ::Val{2}, ::Float64, ::Float64)
Closest candidates are:
  create_array(::Type{var"#s257"} where var"#s257"<:StaticArrays.SArray, ::Any, ::Val, ::Val{dims}, ::Any...) where dims at /Users/rveltz/.julia/packages/SymbolicUtils/9iQGH/src/code.jl:463
  create_array(::Type{var"#s257"} where var"#s257"<:LinearAlgebra.UpperTriangular{T, P}, ::Any, ::Val, ::Val, ::Any...) where {T, P} at /Users/rveltz/.julia/packages/SymbolicUtils/9iQGH/src/code.jl:454
  create_array(::Type{var"#s257"} where var"#s257"<:LinearAlgebra.Transpose{T, P}, ::Any, ::Val, ::Val, ::Any...) where {T, P} at /Users/rveltz/.julia/packages/SymbolicUtils/9iQGH/src/code.jl:450
  ...
```

**Comment by isaacsas** [comment]
I think this is more of a ModelingToolkit issue so I’m transferring it there. If this was supported for general system types it would work for Catalyst too.

**Comment by rveltz** [comment]
The dict seems a good solution for now. It's just that when you have many parameters, passing them with a vector is so much prone to errors that I never do that anymore.

**Comment by ChrisRackauckas** [comment]
I'm not sure this makes sense. `(p = 1.0, d = 2.0)` has `p` and `d` as syntactically `:p`, which is not necessarily `p` and would drop metadata. It doesn't optimize anything either.

>It's just that when you have many parameters, passing them with a vector is so much prone to errors that I never do that anymore.

Even with Pairs? That's equivalent to a Dict.

**Comment by YingboMa** [comment]
NamedTuple cannot be handled because it doesn't contain any variable information. Just use `Dict` or `Pair`s.

**Comment by ChrisRackauckas** [comment]
It's just `:a`, not `a(t)` with metadata of being a parameter and its units, etc.

**Comment by rveltz** [comment]
I see
