### ISSUE TITLE
Allow generic array types in modelingtoolkitize

### ISSUE THREAD

**Issue by bgroenks96** [SciML/ModelingToolkit.jl#1009]
Currently, `modelingtoolkitize` doesn't work on `ODEFunction`s that use `ComponentArray` or (presumably) other non-standard array types. See relevant discussion in jonniedie/ComponentArrays.jl#16.

I haven't looked at the implementation of `modelingtoolkitize`, so I don't know what specific changes need to be made.

But even in a function where I accept a generic array and construct a `ComponentArray`, e.g:

```
function (model::MyModelStruct)(_du,_u,p,t)
    du = ComponentArray(_du, getaxes(model.uproto))
    u = ComponentArray(_u, getaxes(model.uproto))
   ...
```

This still doesn't work because somehow `modelingtoolkitize` still turns it into a `Vector`:

```
ERROR: type Array has no field name
```
after `u.name` is used.

**Comment by bgroenks96** [comment]
Any way we could get some attention on this? I would really like to use `modelingtoolkitize` on my system.

**Comment by ChrisRackauckas** [comment]
Can you share a copy-paste runnable example?

**Comment by bgroenks96** [comment]
After updating everything, it seems to work now? At least on this example:

```julia
using DifferentialEquations, OrdinaryDiffEq, DiffEqOperators, DiffEqBase
using ModelingToolkit
using ComponentArrays
using BenchmarkTools

const nknots = 100
const h = 1.0/(nknots+1)

@inline function heat_conduction(du,u,p,t)
  du .= zero(eltype(u))
  u₃ = @view u.a[3:end]
  u₂ = @view u.a[2:end-1]
  u₁ = @view u.a[1:end-2]
  @. du.a[2:end-1] = ((u₃ - 2*u₂ + u₁)/h^2.0)
  nothing
end

const tspan = [0.0,1.0]
u0 = randn(300)
u0 = ComponentArray(a=u0)
prob = ODEProblem(heat_conduction, u0, tspan)
# sol = @time solve(prob, Rodas3(), abstol=1.0e-4, save_on=false)
sys = modelingtoolkitize(prob)
```
I'll have to play around with it some more to see if it still works for more complex cases, e.g. nested `ComponentArray`s.

**Comment by ChrisRackauckas** [comment]
okay cool, yeah, because I thought I generalized it a bit awhile ago. Without any code this just wasn't actionable though. Open a new one if you find some odd case.

**Comment by fkrauer** [comment]
I have an example, where LabelledArrays are not accepted. I'd love to use modelingtoolkitize, but I prefer to use labelled arrays to keep track of my parameters. Would be great if this could work. The modelingtoolkitized solution also loses the names for the states and returns x1..xn, which is a bit of a pity. 

This code:
```
using DifferentialEquations
using StatsPlots
using Turing
using Distributions
using Random
using StatsBase
using LabelledArrays
using ModelingToolkit
#using DynamicHMC

Random.seed!(42)

# ODE model: simple SIR model with seasonally forced contact rate
function SIR!(du,u,p,t)

    # states
    (S, I, R) = u[1:3]
    N = S + I + R
  
    # params
    β = p.β
    η = p.η
    φ = p.φ
    ω = 1.0/p.ω
    μ = p.μ
    σ = p.σ
      
    # FOI
    βeff = β * (1.0+η*cos(2.0*π*(t-φ)/365.0))
    λ = βeff*I/N

    # change in states
    du[1] = (μ*N - λ*S - μ*S + ω*R)
    du[2] = (λ*S - σ*I - μ*I)
    du[3] = (σ*I - μ*R - ω*R)
    du[4] = (σ*I) # cumulative incidence

end
  
# Solver settings
tmin = 0.0
tmax = 10.0*365.0
tspan = (tmin, tmax)
solvsettings = (abstol = 1.0e-6, 
                reltol = 1.0e-3, 
                saveat = 7.0,
                solver = AutoTsit5(Rosenbrock23()))

# Initiate ODE problem
theta_fix =  [1.0/(80*365)]
theta_est =  [0.28, 0.07, 365.0, 1.0/5.0, 0.1,]
p = @LArray [theta_est; theta_fix] (:β, :η, :ω, :φ, :σ, :μ)
u0 = @LArray [9998.0,1.0,1.0,1.0] (:S,:I,:R,:C)

# Initiate ODE problem
problem = ODEProblem(SIR!,u0,tspan,p)
problem_acc = ODEProblem(modelingtoolkitize(problem), u0, tspan, p, jac=true, sparse=true)

sol = solve(problem_acc, 
            solvsettings.solver, 
            abstol=solvsettings.abstol, 
            reltol=solvsettings.reltol, 
            isoutofdomain=(u,p,t)->any(x->x<0.0,u), 
            saveat=solvsettings.saveat)

```
throws an error:
```
ERROR: LoadError: type Array has no field β
```
But this works:
```
function SIR!(du,u,p,t)

    # states
    (S, I, R) = u[1:3]
    N = S + I + R
  
    # params
    β, η, ω, φ, σ, μ = p
      
    # FOI
    βeff = β * (1.0+η*cos(2.0*π*(t-φ)/365.0))
    λ = βeff*I/N

    # change in states
    du[1] = (μ*N - λ*S - μ*S + ω*R)
    du[2] = (λ*S - σ*I - μ*I)
    du[3] = (σ*I - μ*R - ω*R)
    du[4] = (σ*I) # cumulative incidence

end

p = [theta_est; theta_fix]

#--> plug p in code above
```

**Comment by ChrisRackauckas** [comment]
Open a separate issue on this. LabelledArrays is not generic persay, I think you want to match the variable names from that, so explicit handling of LabelledArrays (and NamedTuples?). That can be done. The generic handling, this issue, to make it so non-Array types work generally by indexing, and it sounds like that's been the case but precisely the issue in your example.
