### ISSUE TITLE
Nested systems with symbolic defaults/initial values don't get de-aliased

### ISSUE THREAD

**Issue by wsphillips** [SciML/ModelingToolkit.jl#1013]
Same error message as #991 results when trying to solve problems with `u0` of eltype `Any` (in this case, due to remaining unresolved symbolic expressions). Below is a minimum reproducer. I'm not (yet) qualified to diagnose, but looks like `alias_elimination` is missing substitutions inside symbolic default values.

Disclaimer, this is nonsense/dummy equations, but it's clear what's happening/wrong before you call `solve`:

```julia
using ModelingToolkit
using DifferentialEquations: solve

@variables t
D = Differential(t)

function subcomp(; name)
    states = @variables x(t) y(t)

    defaultmap = [y => 2x]

    eqs = [D(y) ~ 2y - 5x]

return ODESystem(eqs, t, states, []; defaults = defaultmap, name = name)
end


function comp(sub; name)

    states = @variables x(t)
    
    defaultmap = [x => 2.0]

    eqs = [x ~ sub.x
           D(x) ~ 2* sub.y^2*(5 - x)] 

    return ODESystem(eqs, t, states, []; defaults = defaultmap, name = name, systems = [sub])
end

@named sub1 = subcomp()
@named comp1 = comp(sub1)

# from here you can see that alias elimination has missed the substitution for x in the nested subsystem defaults
simp = structural_simplify(comp1) # default contains symbol that is no longer valid
prob = ODEProblem(simp, [], (0.0,10.0), []) # u0 of eltype Any, containing the symbolic initial value instead of resolved
sol = solve(prob) # errors
```
Output:

```
julia> @named sub1 = subcomp()
Model sub1 with 1 equations
States (2):
  x(t)
  y(t) [defaults to 2x(t)]
Parameters (0):

julia> @named comp1 = comp(sub1)
Model comp1 with 3 equations
States (3):
  x(t) [defaults to 2.0]
  sub1₊x(t)
  sub1₊y(t) [defaults to 2sub1₊x(t)]
Parameters (0):

julia>

julia>

julia> simp = structural_simplify(comp1)
Model comp1 with 2 equations
States (2):
  x(t) [defaults to 2.0]
  sub1₊y(t) [defaults to 2sub1₊x(t)]
Parameters (0):
Incidence matrix:
 ×  ⋅  ×  ×
 ⋅  ×  ×  ×

julia>

julia> states(simp)
2-element Vector{Any}:
 x(t)
 sub1₊y(t)

julia> prob = ODEProblem(simp, [], (0.0,10.0), [])
ODEProblem with uType Vector{Any} and tType Float64. In-place: true
timespan: (0.0, 10.0)
u0: 2-element Vector{Any}:
 2.0
  2sub1₊x(t)

julia> sol = solve(prob)
ERROR: StackOverflowError:
Stacktrace:
 [1] recursive_unitless_bottom_eltype(a::Type{Any}) (repeats 79984 times)
   @ RecursiveArrayTools ~/.julia/packages/RecursiveArrayTools/K3lTR/src/utils.jl:86
```

**Comment by YingboMa** [comment]
The `x` in `subcomp` is not the same as the `x` in `comp`, so the default map for `simp` is
```julia
julia> ModelingToolkit.defaults(simp)
Dict{Term{Real, Nothing}, Any} with 2 entries:
  sub1₊y(t) => 2sub1₊x(t)
  x(t)      => 2.0
```
Therefore, it's expected that the initial condition would contain symbols, due to the incomplete initialization.

**Comment by wsphillips** [comment]
I still don't understand @YingboMa why this isn't an issue. The fact that they are "not the same" should be resolved by the declaration `x ~ sub.x` should it not? It is substituted in the equations for instance compare the output of pre-simplification to post:

```julia
julia> @named comp1 = comp(sub1)
Model comp1 with 3 equations
States (3):
  x(t) [defaults to 2.0]
  sub1₊x(t)
  sub1₊y(t) [defaults to 2sub1₊x(t)]
Parameters (0):

julia> equations(comp1)
3-element Vector{Equation}:
 x(t) ~ sub1₊x(t)
 Differential(t)(x(t)) ~ 2(sub1₊y(t)^2)*(5 - x(t))
 Differential(t)(sub1₊y(t)) ~ 2sub1₊y(t) - (5sub1₊x(t))

julia> ModelingToolkit.defaults(simp)
Dict{Term{Real, Nothing}, Any} with 2 entries:
  sub1₊y(t) => 2sub1₊x(t)
  x(t)      => 2.0

julia> equations(simp)
2-element Vector{Equation}:
 Differential(t)(x(t)) ~ 2(sub1₊y(t)^2)*(5 - x(t))
 Differential(t)(sub1₊y(t)) ~ 2sub1₊y(t) - (5x(t))
```
The substitution for the `x` is subcomp is made as expected in all locations _except_ the default value. Essentially, shouldn't the concrete default value for `x` in `comp` propagate to all variables it is declared equal to?

**Comment by YingboMa** [comment]
Ah, this is a known problem. When the variable with initial condition is reduced by the system, we need to "backsolve" the non-reduced variable. This is not always doable. I guess we can try to do it for simple cases, but we always recommend specifying all initial conditions for this reason.

**Comment by wsphillips** [comment]
Gotcha. I managed to work around this by explicitly setting `sub.x => x` in the map of defaults used by `comp`. However, I also discovered that if I try to override an existing default (e.g. if `sub` already has a default value assigned to `x`) then the subsystem's default takes precedence, and the default provided in the parent `comp` is ignored.

**Comment by YangYuebao** [comment]
I also met this problem. In my case, 'default' transport the initial condition to ODEProblem as a type of  Vector{Real}. You can see **"ODEProblem with uType Vector{Real} and tType Int64."**. 

I manually change the default value into Float64 type like this:

```
a = ModelingToolkit.defaults(sys1)
u01 = [d_temp => 0]
for i in keys(a)
    global u01
    u01 = [u01; i => a[i]]
end
prob1 = ODAEProblem(sys1, u01, (0, 1))
```
My environment: Julia 1.7.2, MTK 8.5.5, DiffEq 7.1.0

**Comment by ChrisRackauckas** [comment]
It seems like the various cases here were fixed, comment if not.
