### ISSUE TITLE
Support for derivatives/interpolation with simplified systems?

### ISSUE THREAD

**Issue by lamorton** [SciML/ModelingToolkit.jl#1014]
It's really cool that MTK can recover the value of 'observed' variables that have been eliminated from a system by structural simplification.  I'm wondering if there's a way to extend this to get the derivatives of those variables. Presently, it looks like the ODESolution interpolation yields a struct that lacks the meta-information necessary to convert from the states back to the observed variables (and also doesn't allow to access the states by name, only by number). 

Here's an example of what I'm thinking of (jump to the last block first): 

```
using ModelingToolkit, OrdinaryDiffEq, Plots

#Declare the building-blocks of your model
@parameters t τ P α ρ w 
@variables E(t) atten(t) r(t)
D = Differential(t)

#System of equations relating the variables: can be differential OR algebraic
eqs = [atten ~ tanh((r-ρ)/w), #Algebraic
      r ~ cbrt(E),            #Algebraic
      D(E) ~ α*P*atten - E/τ, #Differential
      ]
sys = ODESystem(eqs)

#Solve the algebraic equations & substitutes into the differential ones
#Necessary to do this before feeding the system into the solver
sys_simp = structural_simplify(sys) 

#Initial conditions need to be specified for each free variable
u0 = [E => 0.3, # Only free variable left after simplification
      ]

#Parameter values
p  = [P => 10.0,
      τ => 0.1,
      α => 1,
      ρ => 0.2,
      w => 0.2]

#Convert equations into full problem by adding metadata
tspan = (0.0,1.0)
prob = ODEProblem(sys_simp,u0,tspan,p,jac=true)

#Chose a solver and solve the problem 
sol = solve(prob,Tsit5())

#Plot the solution & derived quantities 
#ModelingToolkit uses magic (algebra) to derive the 'lost' variable values from E (the only variable in the solution)
plot(sol,vars=(E));
plot!(sol,vars=(r));
plot!(sol,vars=(atten))

#This gets the derivative of E only, because that's the only 'state' in the simplified system:
derivs = sol.(sol.t,Val{1})

#This doesn't work ... yet
plot(derivs,vars=(E))
plot(derivs,vars=(r))
```

It would be necessary to:

1. Associate the equations defining the observed variables
2. Symbolically differentiate them
3. Plug the state derivatives in

Seems like it could be a chore to implement, but maybe the existing tooling would make it quick work?  My work-around for the moment is to add the derivatives of the quantities I want to the original equations, then let `structural_simplification` convert them to observed variables.

**Comment by ChrisRackauckas** [comment]
Indeed, this is missing and we need to get it working.

**Comment by ChrisRackauckas** [comment]
SII handles these cases now.
