### ISSUE TITLE
Handling of `conv` in `build_function`

### ISSUE THREAD

**Issue by dawbarton** [SciML/ModelingToolkit.jl#1020]
In a few places the `conv` keyword argument is used with `build_function` (e.g., `generate_function` with `OptimizationSystem` or `rungekutta_discretize` with `ControlSystem`) but the `conv` argument is ignored within `build_function` itself (see <https://github.com/JuliaSymbolics/Symbolics.jl/pull/242>). When the associated code is actually used, it generates an error. I don't know if this code should be considered to be dead code or what else should be done with it.

**Comment by dawbarton** [comment]
E.g., <https://github.com/SciML/ModelingToolkit.jl/blob/master/src/systems/control/controlsystem.jl#L151>; inserting an intentional error into <https://github.com/SciML/ModelingToolkit.jl/blob/master/src/systems/control/controlsystem.jl#L103> shows that `conv` has no effect.

**Comment by YingboMa** [comment]
This issue is resolved.
