### ISSUE TITLE
Nonlinear optimal control tutorial equation inconsistency

### ISSUE THREAD

**Issue by ThatcherC** [SciML/ModelingToolkit.jl#1024]
I think there's an inconsistency in the dynamics equations in the [Nonlinear Optimal Control tutorial](https://github.com/SciML/ModelingToolkit.jl/blob/b48c4468483de66547293c978d215d5bbcdf55e0/docs/src/tutorials/nonlinear_optimal_control.md) page:

The equations initially laid out are
```
$$ x^{′′} = u^3(t) $$
```
(second derivative of x is (u(t))^3)

which is then rewritten in first order form as

```
x^\prime = v
v^′ = u^3(t)
```

(first deriv of x is v, first deriv of v is (u(t))^3). All good.

But when the equations are translated into code, the tutorial shows this:
```julia
eqs = [
    D(x) ~ v - p[2]*x
    D(v) ~ p[1]*u^3 + v
]
```

I'm still learning how to use MTK and I see that this tutorial is marked as incomplete, but I would have thought the system described in the beginning of the guide should be encoded as this:

```julia
eqs = [
    D(x) ~ v
    D(v) ~ u^3
]
```

Is this just an error in the documentation? I'm super interested in using MTK for some controls problems so I'd love to help out clearing up documentation and guides if possible!

**Comment by ChrisRackauckas** [comment]
It's an error in the documentation. I think I changed the equations to test the use with parameters, and forgot to update the higher level math part of the description. 😅

**Comment by ChrisRackauckas** [comment]
Controlsystem was removed.
