### ISSUE TITLE
Help needed ...How to use bareiss! function from MTK ?

### ISSUE THREAD

**Issue by yewalenikhil65** [SciML/ModelingToolkit.jl#1029]
Hi,

I couldn't find properly /understand properly how to use `bareiss!` function from MTK ! Anybody could provide the description of arguments that the function `bareiss!` takes ?

**Comment by ChrisRackauckas** [comment]
That's probably a good thing. You shouldn't be relying on non-public APIs. There's no guarantee they won't break for your usage.

**Comment by YingboMa** [comment]
Yeah, don't use it.
