### ISSUE TITLE
Move expressions to RHS during lowering

### ISSUE THREAD

**Issue by akashkgarg** [SciML/ModelingToolkit.jl#1037]
I noticed this when creating a simple NonlinearProblem (see https://github.com/SciML/DiffEqOperators.jl/pull/400#issuecomment-858036932): 
```julia
    eqs = [a ~ 1,
           a + c - 2*b ~ 0,
           b + d - 2*c ~ 0,
           d ~ 1]
```

It turns out that this produces an invalid generated function. The equations need to be setup like this: 
```julia
    eqs = [0 ~ a - 1,
           0 ~ a + c - 2*b,
           0 ~ b + d - 2*c,
           0 ~ d - 1]
```

Automatically moving everything over to the RHS should happen during lowering as suggested by Chris here: https://github.com/SciML/DiffEqOperators.jl/pull/400#issuecomment-858039286

**Comment by asprionj** [comment]
Also noticed during development of the intro example that
```julia
@named fol_separate = ODESystem([ τ*D(x) ~ 1-x ])
```
does not work; throws:
```
ERROR: MethodError: isequal(::Sym{Real, Base.ImmutableDict{DataType, Any}}, ::Missing) is ambiguous. [...]
```

So I changed it to `D(x) ~ (1-x)/τ`, but isn't one advantage of using a symbolic framework not needing to manually do such rearrangements?

**Comment by ChrisRackauckas** [comment]
Yeah, we just haven't done this one. The first one is absurdly simple and just an oversight. The latter one has an interaction with tearing that needs to be a bit careful.

**Comment by YingboMa** [comment]
I don't why the first case is an oversight. It's not clear to me on why that's a problem. What do you need to do?

**Comment by YingboMa** [comment]
I see. We can move everything over to the RHS during construction time for NonlinearSystems.
