### ISSUE TITLE
Plotly plot is blank when plotting observed variable against another variable

### ISSUE THREAD

**Issue by lamorton** [SciML/ModelingToolkit.jl#1038]
If I try to plot an observed variable against another variable using Plotly as the backend, the plot shows up as blank when viewed in a web browser.  The GR backend work just fine.  If I open the Plotly html output with browser tools, I can see the data arrays inside.  

```
using ModelingToolkit, OrdinaryDiffEq, Plots
plotly()

@variables t E(t) z(t)
@parameters P
D = Differential(t)
eqs = [D(E) ~ P, 
            z ~ 2*E]

coupled = ODESystem(eqs)
sys_simp = structural_simplify(coupled)

u0 = [E => 0.1]
p  = [P => 1.0]
tspan = (0.0,10.0)
prob = ODEProblem(sys_simp,u0,tspan,p,jac=true)

sol = solve(prob,Tsit5())

plot(sol,vars=[E,z]) #works
plot(sol,vars=(z,E)) #plot is blank

#Works fine with gr()
```

Versions:
```
Julia v1.6.1
pkg> status
  [0c46a032] DifferentialEquations v6.17.1
  [23fbe1c1] Latexify v0.15.5
  [961ee093] ModelingToolkit v5.17.0
  [8913a72c] NonlinearSolve v0.3.8
  [1dea7af3] OrdinaryDiffEq v5.53.2
  [91a5bcdd] Plots v1.15.0
```
Edit: fixed a mistake w/ variable names in the example.

**Comment by ChrisRackauckas** [comment]
🤔 is this an MTK issue or a Plots issue? It sounds like it must be a Plots.jl issue, since we're just sending it arrays at that point. But the plot recipes need a complete rewrite at this point.

**Comment by lamorton** [comment]
It's probably that the plot recipe is hitting a corner case in Plots -- would you rather I move this over there? I guess at a minimum this should be an error message (rather than a failure) if there's a mistake in the plot recipe...

**Comment by ChrisRackauckas** [comment]
Yeah I think something needs to be isolated to send it there. I can't think of what we're doing that would cause a backend-specific plotting issue.

**Comment by lamorton** [comment]
The axes are labeled `true` and `false` in GR's output.  Maybe that's tripping Plotly up?

**Comment by ChrisRackauckas** [comment]
Ahh, pass axis labels?

**Comment by lamorton** [comment]
Yeah, that makes it work!  I can reproduce the error without ModelingToolkit now:  Just set one of the labels to `true`.

**Comment by ChrisRackauckas** [comment]
oh interesting. Cool. I guess the question is, how the heck did an axis label become true? It must be due to how the sym names are gotten.

**Comment by lamorton** [comment]
Beats me... but there's an [example already](https://user-images.githubusercontent.com/1814174/110242538-87461780-7f24-11eb-983c-4b2c93cfc909.png) at the bottom of the docs page for ModelingToolkit. Looks like that instance was just lucky b/c all 3 are `false`!

**Comment by lamorton** [comment]
New issue for Plots: https://github.com/JuliaPlots/Plots.jl/issues/3569

**Comment by ChrisRackauckas** [comment]
For some reason, Plots.jl eagerly evaluates the rhs of the `-->`, so a quick hack fixes this.

https://github.com/SciML/SciMLBase.jl/commit/0bed18cbb0ba641ad93439de8301508e39b6bc17

**Comment by lamorton** [comment]
Wow, that's ... interesting.  Glad you figured it out!
