### ISSUE TITLE
particle simulations; how to define forces which depend on several sub systems 

### ISSUE THREAD

**Issue by SteffenPL** [SciML/ModelingToolkit.jl#1050]
I'm trying to simulate N particles with some interaction dynamics.

I couldn't figure out how to do this efficiently. I'm posting here since you asked for test cases for ModelingToolkit.

Below is my best attempt so far.

Difficulties I have:
- How can I define a symbolic expression which depends on two components? (see overly complicated definition of the connections (e.g. cons_x))
- How to write symbolic (x > 0) ? 1.0 : 0.2? (see definition of geq)

PS: I know, that I can do these things much better with the DiffEq framework. But I love the idea of ModelingToolkit. That's why I would like to help to make this work.

```julia
using ModelingToolkit, OrdinaryDiffEq


N = 3
@parameters t
# Newtons equation for particles
function single_particle_system(k, N=N)
      @parameters α γ R
      @variables x(t) y(t) Fx[1:N] Fy[1:N]
      D = Differential(t)

      eqs = [
                  D(D(x)) ~ - α * x + γ * sum(Fx[l] for l=1:N),
                  D(D(y)) ~ - α * y + γ * sum(Fy[l] for l=1:N),
            ]

      return ODESystem(eqs, t, [x,y,Fx...,Fy...], [α,γ,R], name=Symbol("p_$(k)"))
end

particles = [single_particle_system(i) for i = 1:N]

# Computation of the interaction force
getcomp(sys, x,i) = getproperty(sys, Symbol( String(x) * ('₀' + i) ))

geq(a,b) = 0.5 + 0.5 * sign(a-b)   # symbolic great equal: geq(0,1) == 0,  geq(1,0) == 1
cons_x = [ ((i == j) ? 0 ~ getcomp(p, :Fx, i) : 0 ~ getcomp(p, :Fx, i) - geq((p.R+q.R)^2, (p.x - q.x)^2 + (q.y - q.y)^2)  * (p.x - q.x))
                  for (i,p) in enumerate(particles),
                      (j,q) in enumerate(particles)]
cons_y = [ ((i == j) ? 0 ~ getcomp(p, :Fy, i)  : 0 ~ getcomp(p, :Fy, i) - geq((p.R+q.R)^2, (p.x - q.x)^2 + (q.y - q.y)^2)  * (p.y - q.y))
                for (i,p) in enumerate(particles),
                    (j,q) in enumerate(particles)]
connections = vcat(cons_x[:], cons_y[:])


# initial conditions
xy0 = vcat( ([p.x => rand(), p.y => rand()]                     for p in particles)... )
F0 = vcat(  ([getcomp(p,:Fx,i) => 0.0, getcomp(p,:Fy,i) => 0.0] for p in particles for i in 1:N )... )
p0 = vcat( ([p.α => 0.1, p.γ => 0.1, p.R => 0.1*rand()]          for p in particles)... )
u0 = vcat(xy0,F0)


tspan = (0., 0.01)
prob = ODEProblem( connected, u0, tspan, p0)
sol = solve(prob, Rodas3())

# LinearAlgebra.SingularException
```

The resulting equations look correct to me:
```julia
 0 ~ p_1₊Fx₁
 0 ~ p_2₊Fx₂ - ((p_2₊x(t) - p_1₊x(t))*(0.5 + 0.5sign((p_1₊R + p_2₊R)^2 - ((p_2₊x(t) - p_1₊x(t))^2))))
 0 ~ p_3₊Fx₃ - ((p_3₊x(t) - p_1₊x(t))*(0.5 + 0.5sign((p_1₊R + p_3₊R)^2 - ((p_3₊x(t) - p_1₊x(t))^2))))
 0 ~ p_1₊Fx₁ - ((p_1₊x(t) - p_2₊x(t))*(0.5 + 0.5sign((p_1₊R + p_2₊R)^2 - ((p_1₊x(t) - p_2₊x(t))^2))))
 0 ~ p_2₊Fx₂
 ⋮
 Differential(t)(Differential(t)(p_1₊y(t))) ~ p_1₊γ*(p_1₊Fy₁ + p_1₊Fy₂ + p_1₊Fy₃) - (p_1₊α*p_1₊y(t))
 Differential(t)(Differential(t)(p_2₊x(t))) ~ p_2₊γ*(p_2₊Fx₁ + p_2₊Fx₂ + p_2₊Fx₃) - (p_2₊α*p_2₊x(t))
 Differential(t)(Differential(t)(p_2₊y(t))) ~ p_2₊γ*(p_2₊Fy₁ + p_2₊Fy₂ + p_2₊Fy₃) - (p_2₊α*p_2₊y(t))
 Differential(t)(Differential(t)(p_3₊x(t))) ~ p_3₊γ*(p_3₊Fx₁ + p_3₊Fx₂ + p_3₊Fx₃) - (p_3₊α*p_3₊x(t))
 Differential(t)(Differential(t)(p_3₊y(t))) ~ p_3₊γ*(p_3₊Fy₁ + p_3₊Fy₂ + p_3₊Fy₃) - (p_3₊α*p_3₊y(t))
```

**Comment by YingboMa** [comment]
Try calling `structural_simplify`?

**Comment by SteffenPL** [comment]
Yes, it gives that it can't handle it since the system is singular. (I'm running it again to show the exact message)

**Comment by SteffenPL** [comment]
Ok, the MWE had a few typos, I fixed that in the code above.


Here is the output of `structural_simplify`:

`InvalidSystemException: The system is structurally singular! Here are the problematic variables: 
 p_1₊Fx₃
 p_1₊Fy₃
 p_2₊Fx₃
 p_2₊Fy₃
 p_3₊Fx₂
 p_3₊Fy₂
check_consistency(s::SystemStructure) at utils.jl:84
structural_simplify(sys::ODESystem) at abstractsystem.jl:643
top-level scope at mk.jl:64
eval at boot.jl:360 [inlined]
`

**Comment by YingboMa** [comment]
Yes, it tells you that your model is structurally singular so it's impossible to solve.

**Comment by ChrisRackauckas** [comment]
For clarification, this system has less equations than unknowns. Specifically, there are no equations that define `Fx` and `Fy`. Are you sure those are states? To me those look like they should be a (potential) function or parameters.

**Comment by SteffenPL** [comment]
Thanks for the help, I guess it must be an error in my implementation.

I'm not sure, but I think the number of unknowns and equations is the same for the combined system `connected`. The connections give the formula how to compute `Fx` and `Fy` (see cons_x, cons_y).
```julia
julia> connected
Model ##ODESystem#257 with 24 equations
States (24):
  p_1₊x(t)
  p_1₊y(t)
  p_1₊Fx₁
⋮
Parameters (9):
  p_1₊α
  p_1₊γ
  p_1₊R
⋮
```


What I was trying to do is this:

System i = 1,...,N:
\ddot x_i = - alpha x_i + gamma \sum F_ij

where the forces F_ij are interaction forces between the systems. Since I couldn't find a better way, I compute them by defining the algebraic coupling equations
0 = F_ij - "formula for F_ij in terms of x_i , x_j"


I know how to do that with only using one system and indexing the symbolic variables myself, but I was wondering if there is a way to plug systems together with ModelingToolkit, hence, define the coupling forces as connections between subsystems.

**Comment by SteffenPL** [comment]
It was a typo. Now it is working and not singular anymore.

Sorry for the trouble. Thanks for your help. I still have to find ways to simplify the code, but it works as it should.

**Comment by ChrisRackauckas** [comment]
Cool!
