### ISSUE TITLE
Documentation comments

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#1053]
# Modeling toolkit documentation comments
As requested, I attempt to summarize some of my outstanding questions after having read the docs and played around with MTK for a while. I am perhaps a slightly unusual user in the sense that I'm not primarily trying to simulate things using MTK, but rather experimenting with  building control-systems tools on top of it. 

---
- Namespacing is not really documented well enough to become comfortable with it. 
I can find references to it in the docs is https://mtk.sciml.ai/dev/tutorials/ode_modeling/#Building-component-based,-hierarchical-models-1 but this section mentions it so briefly that I do not understand its importance. 
For instance, is `connected.fol_1.τ` the same as `fol_1.τ`? As a user I have the feeling that I just put `fol_1` into `connected`, so they should be referring to the same state, but they are not.
```julia
julia> isequal(connected.fol_1.τ, fol_1.τ)
false
```
It would be good to push on that in the docs because this goes against intuition.
Also, if I access `connected.fol_1.τ` I get
```
julia> connected.fol_1.τ
connected₊fol_1₊τ
```
but how do I understand what `connected₊fol_1₊τ` is? Why does it not print the same way as I access it? #907

- If I see something referred to in a display (REPL printout), I want to immediately know how to reference it. I currently don't know exactly what the notation `sys₊x` means, and if I want to refer to that state, how do I do it? `sys₊x` is invalid syntax.

I also find some description at https://mtk.sciml.ai/dev/basics/Composition/ which clarifies a bit (I have read it a few times now so not a first-time reader at this stage). This page does still not fully explain the problems associated with accessing states from different namespaces.

---
From Chris in #1052
> So what could we do about this? I think the solution is just to special case self-reference. I.e. for model.x, if x in get_states(model), then isequal(model.x,x). The other case would be model.subsys.x, which users would want sol[model.subsys.x] to plot sol[subsys.x]. I think this can be done by special casing the highest level index. The getproperty overload of model could see if x in get_states(model) and remove the reference (just like Main.x == x), and then when we recurse getproperty we can have a variable toplevel which is only true at first, and false in the recursion, since otherwise model.subsys.x would simplify back to x.

A discussion around this issue would be welcome in the docs, now or when the design has been changed. The docs do not really talk about the difference between accessing states from different namespaces. The suggestions to special case a few cases make me wonder if this helps the users sometimes, but at the same time makes it even harder to understand what is actually happening. 

---

- Not purely a docs issue, but error messages can sometimes be improved by, e.g., suggesting a fix or pointing to extended documentation. 
    -  `ERROR: InvalidSystemException: The system is unbalanced. There are 6 highest order derivative variables and 5 equations.` why is this a problem? This error can be introduced if a user tries to rename a variable by introducing a new state that is equal to another. 
    - Error messages often originate from the algorithms deep inside MTK, but the user would in some occasions be helped if such errors were checked for and detected early. I recall tearing errors and the like, but am failing to produce a MWE at the moment :/ If there is any chance to detect a misspecified problem early, it would be extremely valuable to the user.

---
- If `ode_order_lowering` is called on a system with differentials in the RHS, maybe issue a warning that this is not supported? I can't find this limitation documented in the docs. 
- `ode_order_lowering` produces integrated states with strange names. In the example below, I wasted a lot of time trying to understand how to refer to the state `P.q0ˍt` simply due to it looking like an underscore `_` but in reality it's another character `ˍ`. 
```julia
julia> P
Model tmm with 6 equations
States (6):
  q0ˍt(t)
  q1ˍt(t)
  q2ˍt(t)
  q0(t)
  q1(t)
  q2(t)
Parameters (0):

julia> P.q0_t
ERROR: ArgumentError: Variable q0_t does not exist

julia> P.q0ˍt
tmm₊q0ˍt(t)
```
It would be nice to have documented 
    - What states are introduced by `ode_order_lowering` and how to refer to them.
    - What it handles and what the limitations are.

---
- If I have put a registered function in an equation, how do I find references to it? E.g., how do I find `rfun` in
```julia
infil> eqs[2]
Differential(t)(loopgain₊C₊x2(t)) ~ rfun(t) - (100.0loopgain₊C₊x2(t)) - loopgain₊P₊x1(t)

# This attempt failed ▿
infil> ModelingToolkit.get_variables(eqs[2])
3-element Vector{Any}:
 t
 loopgain₊C₊x2(t)
 loopgain₊P₊x1(t)
 ```
 - `get_variables` appears to return only variables in RHS, not LHS? 
 - More generally, how do I figure out if a variable/state occurs in a system or equation, and what's the connection between `Num, Sym` states etc.? ( I mostly know this by now, but it has taken me a while of experimentation to figure out).

**Comment by ChrisRackauckas** [comment]
With the namespacing, @YingboMa and I had a big chat. The issue is not documentation but that namespacing has some non-intuitive behavior and needs to be changed. @YingboMa 's suggestion in https://github.com/SciML/ModelingToolkit.jl/issues/1052 looks to be the direction we're going.

**Comment by ChrisRackauckas** [comment]
@baggepinnen were these handled?
