### ISSUE TITLE
Order of spring-mass-damper not lowered

### ISSUE THREAD

**Issue by cadojo** [SciML/ModelingToolkit.jl#1066]
I'm writing some examples for `ModelingToolkit` as part of a control theory note set, and I'm trying to model a spring-mass-damper with the following code. 

```julia

using ModelingToolkit
using DifferentialEquations

@parameters t fₑ d k
@variables x(t)
δ = Differential(t)

eqs = [
    δ(δ(x)) + d*δ(x) + k*x ~ fₑ
] .|> simplify

model = (ode_order_lowering ∘ ODESystem)(eqs, t, [x], [fₑ, d, k]) 
```

This results in the following output on `ModelingToolkit v5.20.0`.

```julia
Model ##ODESystem#262 with 1 equations
States (1):
  x(t)
Parameters (3):
  fₑ
  d
  k
```

Am I specifying something incorrectly, or is this a bug?

**Comment by ChrisRackauckas** [comment]
Try:

```julia
eqs = [
    δ(δ(x))~ - d*δ(x) - k*x + fₑ
]
```

?

**Comment by cadojo** [comment]
Yup, that worked. I'll close the issue. I'll remember to provide equations in "highest order = sum of lower order" form from now on.

**Comment by ChrisRackauckas** [comment]
We should fix that.

**Comment by YingboMa** [comment]
Dup of #988

**Comment by cadojo** [comment]
@YingboMa is state selection as mentioned in the issue you linked the same thing as the `ode_order_lowering` behavior? Or is that something different?
