### ISSUE TITLE
Model Debugging: Return the unbalanced equations/variables

### ISSUE THREAD

**Issue by bolognam** [SciML/ModelingToolkit.jl#1068]
When calling `structural_simplify()` on an `ODESystem` a very common issue can be unbalanced equations/variables. When there's 500+ equations/variables, it's hard to debug what's wrong quickly. It would be nice to return the unbalanced equations/variables with the error message of an unbalanced system.

**Comment by ChrisRackauckas** [comment]
@YingboMa has something in mind for this, though it'll take some time.

**Comment by YingboMa** [comment]
Yeah, I talked with @bolognam about this, so he filed an issue to keep track of this.
