### ISSUE TITLE
Dispatchable systems

### ISSUE THREAD

**Issue by jonniedie** [SciML/ModelingToolkit.jl#1071]
I find myself often wanting to dispatch on different types of systems I've made. For example, let's say I want a system called a `Vector3` whose state variables are `x`, `y`, and `z` but can also be indexed like a vector.

```julia
@parameters t
const D = Differential(t)

function Vector3(; name, x=0, y=0, z=0)
    defaults = [x, y, z]
    r = @variables x(t) y(t) z(t)
    return ODESystem(Equation[], t, r, []; name)
end
```
Now I'd like to be able to use it as a vector in another system while keeping it's states as named `x`, `y`, and `z` variables.
```julia
function PointMass(; name, mass, force=[0, 0, 0])
    @parameters m, F[1:3]
    @named r = Vector3()
    @named v = Vector3()
    
    # This part doesn't currently work
    eqs = [
        D.(r) .~ v
        D.(v) .~ F./m
    ]
    defaults = [m=>mass, F.=>force]
    return ODESystem(eqs, t, [], [m; F]; name, defaults, systems=[r, v])
end
```
In this particular case, if I was able to write a `getindex` method for `Vector3`, things would work out fine. I know it would be easy enough to break the derivative equations down into each x, y, and z component, but that gets pretty boilerplatey. And in general, there are a lot of other cases where I would like my constructed `ODESystem`s to be able to participate in the multiple dispatch machinery. The best solution I've come up with is making wrapper types and then unwrapping them when I need to compose systems (i.e. something like  `systems=unwrap.([r, v])` where `unwrap` just grabs the inner system if it's a wrapped type). 

Is there a better way to do this?

**Comment by ChrisRackauckas** [comment]
See `@connector` in https://github.com/SciML/ModelingToolkit.jl/blob/master/examples/electrical_components.jl#L6. It uses the abstract type in the ODESystem

**Comment by jonniedie** [comment]
Ah, I think I see. So if I want to dispatch on `Pin`, in this case, I'd do something like:
```julia
f(sys) = _f(sys.connection_type, sys)
_f(::Type{Pin}, sys) = "It's a Pin named $(ModelingToolkit.getname(sys))!"
_f(_, _) = "It's not a Pin!"
```
How specific is that to connectorness? Is there any danger in using this mechanism for things that aren't being used as connector-y way? Or rather, is there anything inside the ModelingToolkit internals that handles things with a defined `connection_type` differently than things without?

**Comment by ChrisRackauckas** [comment]
It's not really specific to connectors. Maybe it should even be renamed, though it's heavily used by connectors.

**Comment by ChrisRackauckas** [comment]
Components as functions can dispatch.
