### ISSUE TITLE
Abstract time dependent/independent system types

### ISSUE THREAD

**Issue by lamorton** [SciML/ModelingToolkit.jl#1082]
@ChrisRackauckas mentioned wanting to have abstract time dependent/independent system types to classify (for example) `ODESystem` vs `NonlinearSystem` types. I'm thinking to have `PDESystem` get its own abstract type like `AbstractMultivariateSystem`. Then functions `generate_tgrad` `calculate_tgrad` and `independent_variable` could specialize on `AbstractTimeDependentSystem` b/c they expect a single independent variable. Does that seem reasonable? Any other functions that should get specialized?

**Comment by ChrisRackauckas** [comment]
I think that makes sense.

**Comment by lamorton** [comment]
Hitting errors related to `get_variable`.  It looks like there are 4 functions one could use to get at independent variable(s):
```
get_iv 
get_indvars 
independent_variables # Not implemented.
independent_variable
```
 This is a bit confusing, given the light documentation. Looks like the 1st two are generated automatically based on fieldnames (for ODE-like and PDE-like systems, respectively), so I guess those should stay as-is (although renaming `indvars` -> `ivs` would make things more parallel). 

Should `independent_variables` be specific to PDE-like systems with multiple independent variables, or a catch-all that returns a set or vector of independent variables that can have 0,1, or many elements?

**Comment by ChrisRackauckas** [comment]
`get_indvars` is one I didn't know existed... I think like other values there should be `get_iv` and `independent_variable`, which might need to be `independent_variables` to have a parallel for PDEs, so maybe scrap `independent_variable`. Good point we need to simplify this.

**Comment by lamorton** [comment]
Close by #1091 .
