### ISSUE TITLE
Add `sparsity` to ODEProblem on construction

### ISSUE THREAD

**Issue by bolognam** [SciML/ModelingToolkit.jl#1087]
I don't need sparse, but the Jacobian sparsity used when creating an ODEProblem. Right now in order to add sparsity I have to:
```
ff = prob.f
newfun = @set ff.sparsity = ModelingToolkit.jacobian_sparsity(simplified_model)
newprob = remake(prob, f=newfun)
```

**Comment by ChrisRackauckas** [comment]
It should just do the default and match `jac_prototype` doesn't it already?

**Comment by YingboMa** [comment]
The current behavior either makes the Jacobian sparse or dense w/o coloring. Michael wants dense Jacobian with coloring.

**Comment by ChrisRackauckas** [comment]
I see, so we need another kwarg?

**Comment by YingboMa** [comment]
Yeah, should be EZ to add.

**Comment by ChrisRackauckas** [comment]
`sparse=true` was added
