### ISSUE TITLE
reparametrizing ODESystem independent variable 

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#1100]
when using the models and readers for SBML and CellML, often you will get an issue where one has a different IV than the other. ie x(t) and y(time). I know as a human that these are intended to be the same. 

I don't see an easy way to change all of the x(time) => x(t) system-wide for ODESystem. i realize other system types would be harder.

the reason that the readers don't handle this is that the writer of the SBML or CellML model writes the IV how they wish (for the case of CellML at least I know this is true)

**Comment by YingboMa** [comment]
```julia
help?> convert_system
search: convert_system

  convert_system(::Type{var"#s7"} where var"#s7"<:ODESystem, sys, t; name) -> ODESystem


  Convert a NonlinearSystem to an ODESystem or converts an ODESystem to a new ODESystem with a different independent variable.
```
I think that also works for ODESystems

**Comment by anandijain** [comment]
you rock
