### ISSUE TITLE
ODESystem with equations in symbolic matrix form throws hasmetadata error

### ISSUE THREAD

**Issue by ograsdijk** [SciML/ModelingToolkit.jl#1109]
Using a symbolic matrix form for the equations input into `ODESystem` throws the following error: `MethodError: no method matching hasmetadata(::Missing, ::Type{Symbolics.VariableDefaultValue})`

Julia 1.6.1
ModelingToolkit 5.22.0

Minimum working example
```Julia
using ModelingToolkit

@variables t x[1:3,1:3](t)
D = Differential(t)

sys = ODESystem(D(x) ~ x)
```

**Comment by ChrisRackauckas** [comment]
@YingboMa I assume you got this?

**Comment by lungd** [comment]
What about `ODESystem(collect(D.(x) .~ x))` or `ODESystem([D(xi) ~ xi for xi in x])` ?

**Comment by YingboMa** [comment]
Yeah, I got this.

**Comment by YingboMa** [comment]
Oh, the system is wrong.
