### ISSUE TITLE
provide  type stable access to ODESolution by Num observed object

### ISSUE THREAD

**Issue by bgctw** [SciML/ModelingToolkit.jl#1112]
Will it be possible to access observed variables of a simplified DAE system in a type stable manner?
Currently, the `@code_warntype soltrue[dx]` returns type `Any` in the code below.

```
using ModelingToolkit, DifferentialEquations, DiffEqFlux, Flux

@parameters α β δ γ
@variables t x(t) y(t) dx(t) obs1(t)
D = Differential(t)
# based on example in https://diffeqflux.sciml.ai/stable/examples/optimization_ode/
eqs = [
  dx ~ α*x - β*x*y,  # testing observed variables
  D(x) ~ dx,
  D(y) ~ -δ*y + γ*x*y,
]
@named lv = ODESystem(eqs)
syss = structural_simplify(lv) 
parms = [α => 1.5, β => 1.0, δ => 3.0, γ => 1.0]
x0 = [x => 1.0, y => 1.0]
tsteps = 0.0:0.1:10.0
prob = ODEProblem(syss, x0, extrema(tsteps), parms, jac = true)
soltrue = solve(prob, Rodas5(), saveat = tsteps);

# note accessing the observed  dx by a Num object in the solution (declared with @variables above)
pred_dx = soltrue[dx]
@code_warntype soltrue[dx]
```

This kind of access is very common in cost-functions in fitting DAE systems to observations.
So far, it works(-around) for me to explicitly assure the return object to be the same type as the observations:
`pred_dx = soltrue[dx]::typeof(observed_dx)` to make the loss or cost function type-stable.

Maybe related to [this solved issue](https://github.com/SciML/ModelingToolkit.jl/issues/972).

**Comment by bgctw** [comment]
The workaround with explicit type assurance does actually not work with `ForwardDiff`:

`ERROR: TypeError: in typeassert, expected Vector{Float64}, got a value of type Vector{ForwardDiff.Dual{ForwardDiff.Tag{Turing.Core.var"#f#3"{DynamicPPL.TypedVarInfo{NamedTuple{(:p,), Tuple{DynamicPPL.Metadata{Dict{AbstractPPL.VarName{:p, Tuple{Tuple{Int64}}}, Int64}, Vector{Distribution{Univariate, Continuous}}, Vector{AbstractPPL.VarName{:p, Tuple{Tuple{Int64}}}}, Vector{Float64}, Vector{Set{DynamicPPL.Selector}}}}}, Float64}, DynamicPPL.Model{var"#22#23", (:qobs, :T), (:T,), (), Tuple{Vector{Float64}, Type{Float64}}, Tuple{Type{Float64}}}, DynamicPPL.Sampler{NUTS{Turing.Core.ForwardDiffAD{40}, (), AdvancedHMC.DiagEuclideanMetric}}, DynamicPPL.DefaultContext}, Float64}, Float64, 4}}
`

**Comment by ChrisRackauckas** [comment]
We would need some idea of "type-pure" to solve this well, where given a symbol we can know what type it would be...

@YingboMa any suggested solution on your end? Build the type-assert into the observed function wouldn't work I think

**Comment by YingboMa** [comment]
Does type-assert actually improve performance? There're function barriers. I don't see nice ways to make this type stable.

**Comment by ChrisRackauckas** [comment]
Completed with SII v0.3
