### ISSUE TITLE
Allowing discrete Difference equations in ODESystem 

### ISSUE THREAD

**Issue by sharanry** [SciML/ModelingToolkit.jl#1122]
The [proposed plan](https://github.com/SciML/ModelingToolkit.jl/issues/1088#issuecomment-876649631) is to support difference equations containing `DIfference` operator in `ODESystem`s using `PeriodicCallback`s.

This could involve the following workflow:

Difining difference and differential equations together:
```julia
using ModelingToolkit
@parameters t σ ρ β
@variables x(t) y(t) z(t)
δ = Differential(t)
D = Difference(t; dt=0.01)

eqs = [
       δ(x) ~ σ*(y-x),
       δ(y) ~ x*(ρ-z)-y,
       δ(z) ~ x*y - β*z,
       D(y) ~ x
       ]
```

Manually mentioning which are the difference variables while defining the ODESystem using an optional kwarg:
```julia
sys = ODESystem(eqs,t,[x,y,z],[σ,ρ,β]; differencevars=[y])
```

Producing the ODEProblem and the callback
```julia
prob = ODEProblem(sys,u0,tspan,p,jac=true)
difference_cb = generate_difference_cb(sys)
```

Mention the callback while solving the problem:
```julia
solve(prob, Rodas5(); cb=difference_cb)
```

@ChrisRackauckas @YingboMa 
Does this kind of workflow seem reasonable to begin with? 
OR do we want more automation that might involve API changes? 
OR did you have something else in mind?

**Comment by ChrisRackauckas** [comment]
No, just put the callback in the problem. The user shouldn't have to deal with it. And automatically detect the difference equations and move them from eqs.
