### ISSUE TITLE
extend forget a variable ...

### ISSUE THREAD

**Issue by YJR78** [SciML/ModelingToolkit.jl#1133]
Hello,
I've defined a partial compliant of the following form
```
function PartialCompliant(;name)
    @named flangeA = Flange() 
    @named flangeB = Flange()
    sts = @variables l(t) = 1.0 f(t)=1.0
    eqs = [
            l ~ flangeB.x - flangeA.x
            0 ~ flangeB.f + flangeA.f
            f ~ flangeB.f
          ]
    compose(ODESystem(eqs, t, sts, []; name=name),flangeA, flangeB)
end 
```
Then I extend it as a spring with

```
function Spring(;name, K=1.0,L0=0.0)
    @named partialCompliant = PartialCompliant()
    @unpack l, f = partialCompliant
    ps = @parameters K=K L0=L0
    eqs = [
            f ~ K*(L0-l)
          ]
    extend(ODESystem(eqs, t, [], ps; name=name), partialCompliant)
end

```

But flange A is part of spring as expected but it misses flange B....
Any clues ?
BR

**Comment by YingboMa** [comment]
I cannot reproduce the issue. `Flange` is not defined.

**Comment by YJR78** [comment]
oh sorry here is the full code
`using ModelingToolkit
using Plots
using DifferentialEquations

@parameters t
@connector function Flange(;name)
    sts = @variables x(t)=1.0 f(t)=1.0 # s=position f=force
    ODESystem(Equation[], t, sts, []; name=name)
end

function ModelingToolkit.connect(::Type{Flange}, ps...)
    eqs = [
           0 ~ sum(f->f.f, ps) # Newton ∑F=0
          ]
    for i in 1:length(ps)-1
        push!(eqs, ps[i].x ~ ps[i+1].x) # all flange position is unique
    end
    return eqs
end

function Fixed(;name)
    @named flange = Flange()
    eqs = [flange.x ~ 0]
    compose(ODESystem(eqs, t, [], []; name=name), flange)
end

function PartialCompliant(;name)
    @named flangeA = Flange() 
    @named flangeB = Flange()
    sts = @variables l(t) = 1.0 f(t)=1.0
    eqs = [
            l ~ flangeB.x - flangeA.x
            0 ~ flangeB.f + flangeA.f
            f ~ flangeB.f
          ]
    compose(ODESystem(eqs, t, sts, []; name=name),flangeA, flangeB)
end 


function Mass(;name, M=1)
    @named flange = Flange()
    ps = @parameters M=M
    sts = @variables v(t)
    D = Differential(t)
    eqs = [
            D(flange.x) ~ v # speed
            D(v) ~ flange.f/M
          ]
    compose(ODESystem(eqs, t, sts, ps; name=name), flange)
end


function Spring(;name, K=1.0,L0=0.0)
    @named partialCompliant = PartialCompliant()
    @unpack l, f = partialCompliant
    ps = @parameters K=K L0=L0
    eqs = [
            f ~ K*(L0-l)
          ]
    extend(ODESystem(eqs, t, [], ps; name=name), partialCompliant)
end

function Damper(;name, Kd=1)
    @named partialCompliant = PartialCompliant()
    @unpack l, f = partialCompliant
    D = Differential(t)
    ps = @parameters Kd=Kd
    sts = @variables v(t) = 0.0
    eqs = [
            D(l) ~ v
            f ~ - Kd*v
          ]
    extend(ODESystem(eqs, t, sts, ps; name=name), partialCompliant)
end

function Force1(;name, F = 1.0) # one side constant force
    @named flange = Flange() #connector
    ps = @parameters F=F
    eqs = [
           flange.f ~ F 
          ]
    compose(ODESystem(eqs, t, [], ps; name=name), flange)
end
##
@named mass = Mass(M=0.1)
@named spring = Spring(K=10,L0=0)
@named damper = Damper(Kd=0.1)
@named fixed = Fixed()


msd_eqs = [
          connect(fixed.flange, spring.flangeA, damper.flangeA)
          connect(spring.flangeB, mass.flange, damper.flangeB)
         ]
@named msd_model = compose([ODESystem(msd_eqs, t),
                           spring, damper, mass, fixed])
u0=[
    mass.flange.x => 1.0
    mass.v => 0.0
]
sys = structural_simplify(msd_model)
prob = ODEProblem(sys, u0, (0, 10.0))
sol = solve(prob)
plot(sol)`

**Comment by YJR78** [comment]
In previous code changing all occurrences of flangeB by flangeC solves the issue ... I think there is a bug somewhere ... 
the spring component defined with flangeB has following content:
K         L0         f          flangeA    flangeA₊f  flangeA₊x  flangeB₊f  flangeB₊x  l     # flangeB is missing
Using flangeC leads to:
K         L0         f          flangeA    flangeA₊f  flangeA₊x  flangeC    flangeC₊f  flangeC₊x  l # which is correct...
...

**Comment by ChrisRackauckas** [comment]
The scoping seems wrong in your example. If this still exists please make a simplified example of the bug.
