### ISSUE TITLE
Supporting multi-clock discrete systems

### ISSUE THREAD

**Issue by sharanry** [SciML/ModelingToolkit.jl#1137]
Currently, DiscreteSystem and ODESystem both support only single clock systems.

1) For multi-clock discrete transitions using the Difference operator in ODESystem, the plan is to have separate periodic callbacks for each set of synchronous discrete transitions. We could later extend this to a single customized discrete callback if the need arises.

2) In order to support multi-clock DiscreteSystems, we might need to group each set of the synchronous transitions and generate a separate function for each such group. We could then call each of these functions as a function of time (t) by an outer function. Is there a better way to do this? 

3) It is also possible that each of these "clocks" starts at different times, I am not sure how common such scenarios are in practice. If we want to support these kinds of systems, we might need to add an extra field indicating the start time to the difference operator which defaults to 0. This start time could later be fetched while creating the periodic callback. 

@ChrisRackauckas @YingboMa We have already discussed 1. Any thoughts on 2 and 3?

**Comment by ChrisRackauckas** [comment]
The actual hard thing about multi-clock is dependencies. If you have a clock at 3 and a clock at 5, and D(x) ~ y, D(y) ~ x, which one do you do first at 15? Is it an implicit system? I think we'd want to just error in that case for now.

**Comment by ChrisRackauckas** [comment]
@YingboMa @baggepinnen this is done?

**Comment by baggepinnen** [comment]
Yeah, the rest of the work required have other issues tracking it, like
- #1939
