### ISSUE TITLE
`connect` different types of `@connectors`

### ISSUE THREAD

**Issue by ven-k** [SciML/ModelingToolkit.jl#1168]
For 2 connectors of type `PinT` and `PinS`,

```
@named pt = PinT()
@named ps = PinS()

connect(pt, ps)
```
throws `ERROR: LoadError: ArgumentError: Don't know how to connect systems of type Main.Modulename.PinT and Main.Modulename.PinS`

The reason for this is [promote_connect_rule](https://github.com/SciML/ModelingToolkit.jl/blob/fc34034daa87f8f8fc683ede7a88e8f360f3d41f/src/systems/abstractsystem.jl#L852) promotes it to `Union{}` which dispatches to [this](https://github.com/SciML/ModelingToolkit.jl/blob/fc34034daa87f8f8fc683ede7a88e8f360f3d41f/src/systems/abstractsystem.jl#L873) and throws an error.

If this is changed to `promote_connect_rule(::Type{T}, ::Type{S}) where {T, S} = Union{Type{T}, Type{S}}`

One could define (in their module):
```
const SuperPin = Union{Type{PinT}, Type{PinS}}
function MTK.connect(::Type{SuperPin}, ps...) ... end
```
Currently, I am dispatching a `promote_connect_rule` for each pair of distinct connectors. If this is acceptable, I'll make a PR.

**Comment by YingboMa** [comment]
Why cannot you write `ModelingToolkit. promote_connect_rule(::Type{PinT}, ::Type{PinS}) = PinT` and just define `connect` on `PinT`?

**Comment by ven-k** [comment]
`PinT` and `PinS` have a couple of dissimilar variables so `PinT` can't be treated as a supertype.

But yeah, promoting connect_rule to `Union{Type{T}, Type{S}` will require redifining `connect` even when `PinT` is supertype of `PinS`

BTW, how can one specify the supertype of a connector?

**Comment by ValentinKaisermayer** [comment]
```julia
abstract type AbstractPin end

ModelingToolkit.promote_connect_rule(::Type{PinS}, ::Type{PinT}) = AbstractPin 
ModelingToolkit.promote_connect_rule(::Type{PinT}, ::Type{PinS}) = AbstractPin 
ModelingToolkit.promote_connect_rule(::Type{PinT}, ::Type{AbstractPin}) = AbstractPin 
ModelingToolkit.promote_connect_rule(::Type{AbstractPin}, ::Type{PinS}) = AbstractPin 

```

**Comment by ven-k** [comment]
Thanks!
