### ISSUE TITLE
Bounds checking partially not turned off in generated function bodies

### ISSUE THREAD

**Issue by wsphillips** [SciML/ModelingToolkit.jl#1174]
When calling the `ODAEProblem` constructor on a structurally simplified `ODESystem` the output expression looks like it's omitting a call to `@inbounds` in the body of the function. Below is a cleaned up example output made using the script [here](https://github.com/wsphillips/Conductor.jl/blob/efd2c231390a9200951954576ea59a66f7cfe93c/gen/hh_testgen.jl), where I'm taking the output of `structural_simplify` and passing it directly to [`build_torn_function`](https://github.com/SciML/ModelingToolkit.jl/blob/89fdee8bd59c11011eecc27b534d6989b2a5b712/src/structural_transformation/codegen.jl#L181) with the kwarg `expression = true`. There's `@inbounds` for the unloading of the state/parameter vectors, but it's missing from the body. Notably, this differs from the behavior of vanilla `build_function` and manually inserting `@inbounds` in front of either the parent or nested `let` block cleans up the emitted LLVM IR.

```julia

function hh_generated!(du, u, p, t)
    let neuron₊Isyn = @inbounds(u[1]),
        neuron₊Vₘ = @inbounds(u[2]),
        neuron₊NaV₊m = @inbounds(u[3]),
        neuron₊NaV₊h = @inbounds(u[4]),
        neuron₊Kdr₊n = @inbounds(u[5]),
        neuron₊cₘ = @inbounds(p[1]),
        neuron₊aₘ = @inbounds(p[2]),
        neuron₊ENa = @inbounds(p[3]),
        neuron₊EK = @inbounds(p[4]),
        neuron₊El = @inbounds(p[5]),
        neuron₊NaV₊gbar = @inbounds(p[6]),
        neuron₊Kdr₊gbar = @inbounds(p[7]),
        neuron₊leak₊g = @inbounds(p[8])

        let
            du[1] = 0
            du[2] =
                (
                    if t > 100.0
                        if t < 200.0
                            0.0004
                        else
                            0.0
                        end
                    else
                        0.0
                    end +
                    -1neuron₊Isyn +
                    -1 * neuron₊aₘ * neuron₊leak₊g * (neuron₊Vₘ + -1neuron₊El) +
                    -1 *
                    neuron₊Kdr₊gbar *
                    neuron₊aₘ *
                    neuron₊Kdr₊n^4.0 *
                    (neuron₊Vₘ + -1neuron₊EK) +
                    -1 *
                    neuron₊NaV₊gbar *
                    neuron₊aₘ *
                    neuron₊NaV₊h *
                    neuron₊NaV₊m^3.0 *
                    (neuron₊Vₘ + -1neuron₊ENa)
                ) *
                inv(neuron₊aₘ) *
                inv(neuron₊cₘ)
            du[3] =
                (1 + -1neuron₊NaV₊m) * if neuron₊Vₘ == -40.0
                    1.0
                else
                    (4.0 + 0.1neuron₊Vₘ) * inv(1.0 + -1 * exp(-4.0 + -0.1neuron₊Vₘ))
                end +
                -4.0 *
                neuron₊NaV₊m *
                exp(-3.6111111111111107 + -0.05555555555555555neuron₊Vₘ)
            du[4] =
                -1 * neuron₊NaV₊h * inv(1.0 + exp(-3.5 + -0.1neuron₊Vₘ)) +
                0.07 * exp(-3.25 + -0.05neuron₊Vₘ) * (1 + -1neuron₊NaV₊h)
            du[5] =
                if neuron₊Vₘ == -55.0
                    0.1
                else
                    (0.55 + 0.01neuron₊Vₘ) * inv(1.0 + -1 * exp(-5.5 + -0.1neuron₊Vₘ))
                end * (1 + -1neuron₊Kdr₊n) +
                -0.125 * neuron₊Kdr₊n * exp(-0.8125 + -0.0125neuron₊Vₘ)
            nothing
        end
    end
end
```

**Comment by wsphillips** [comment]
I think it's because the call to `SetArray` in `build_torn_function` [doesn't apply the `!` operator to the keyword `checkbounds` ](https://github.com/SciML/ModelingToolkit.jl/blob/5a47dd69a6c401f3ba53a8d980b4ad860ebdba7f/src/structural_transformation/codegen.jl#L195-L199)like it does normally (e.g. [in Symbolics.jl](https://github.com/JuliaSymbolics/Symbolics.jl/blob/d2512e5ec2e0fdef764920c533e1b94b2269d38b/src/build_function.jl#L359) )? See also [here](https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/daed7eec037a9d6a7dbcdfbbf548e45521ee97b2/src/code.jl#L309). I will check if that's a fix and submit my 1 character PR if so :stuck_out_tongue:

**Comment by ChrisRackauckas** [comment]
Yeah that looks like a typo.

**Comment by YingboMa** [comment]
Yes, do submit a PR.
