### ISSUE TITLE
Add support to variables with custom type

### ISSUE THREAD

**Issue by ronisbr** [SciML/ModelingToolkit.jl#1194]
Hi!

If I want to port a satellite simulator to MTK, I will need to have some variables that has custom types. For example, for the attitude, I might want to use quaternions that has a specific algebra for multiplication and propagation given an angular velocity. I know I can model all the algebra inside MTK, but it will not be optimal since we have packages that implement the quaternion algebra already.

I tried with this MWE:

```julia
using ModelingToolkit
using OrdinaryDiffEq
using ReferenceFrameRotations
import Base: zero

zero(::Type{Quaternion{T}}) where T = Quaternion{T}(0, 0, 0, 0)

@variables t x(t)
D = Differential(t)
@named quat_model = ODESystem(D(x) ~ Quaternion{Float64}(0, 0, 0, 0))
prob = ODEProblem(quat_model, [x => Quaternion(1.0, 0.0, 0.0, 0.0)], (0.0, 10.0))
sol = solve(prob, Tsit5())
```

However, this returns the following error:

```julia
ERROR: LoadError: setindex! not defined for Quaternion{Float64}
```

I just cannot set the method `setindex!` for `Quaternion` because it is immutable.

Is there any plan to support variables with custom types?

Note: The `Quaternion` of Quaternions.jl works because it is `<: Number` whereas `Quaternion` of ReferenceFrameRotations.jl is `<:AbstractVector`. For some specificities involving how the attitude is propagated, it is better to treat a quaternion as a 4x1 vector.

**Comment by YingboMa** [comment]
The support for custom types are there. `Quaternion` should be `<: Number` if it's a number.

**Comment by ronisbr** [comment]
For attitude propagation, we treat quaternions as a 4x1 vector instead of an extension of complex numbers.

<img width="1369" alt="Captura de Tela 2021-08-16 às 18 39 55" src="https://user-images.githubusercontent.com/1068295/129632889-401cf5b5-a4a3-4733-9de3-fc97313147af.png">

[1] https://ntrs.nasa.gov/api/citations/20030093641/downloads/20030093641.pdf

**Comment by YingboMa** [comment]
Could you point me to the relavent part of the code?

**Comment by ronisbr** [comment]
Sorry, I think I did not understand. Which code?

**Comment by YingboMa** [comment]
Could you point me to the relavent part of the code that requires `Quaternion <: AbstractVector`?

**Comment by ronisbr** [comment]
oh, https://github.com/JuliaSpace/ReferenceFrameRotations.jl/blob/b6129b3032dc2b92104699d0fe7646e0ecf613bb/src/quaternion.jl#L703

This property is used when you propagate the attitude. In this case, you transform a quaternion into a vector, obtain the propagation matrix here:

https://github.com/JuliaSpace/ReferenceFrameRotations.jl/blob/b6129b3032dc2b92104699d0fe7646e0ecf613bb/src/quaternion.jl#L811

And then convert back to quaternion.

**Comment by ronisbr** [comment]
The code inside the simulator is:

```julia
    # Time derivative of the quaternion.
    dw.q_b_i = dquat(q_b_i, w_bi_b)
```

where the getters and setters in `dw` are defined as:

```julia
Base.@propagate_inbounds _getindex(a::Workspace{T}, ::Val{:q_b_i}) where T   = Quaternion(view(getfield(a, :x), 6:9))

Base.@propagate_inbounds Base.setindex!(a::Workspace, v, ::Val{:q_b_i})    = setindex!(getfield(a, :x), v, 6:9)
```

**Comment by ChrisRackauckas** [comment]
I think you're mixing up the mathematical vector with the computational vector. you want to treat the quaternion as a mathematical vector, but that does not mean that a mutable array is the right computational representation of it. An immutable number would be much faster (and safer) for this use case.

**Comment by ronisbr** [comment]
@ChrisRackauckas in my case, `Quaternion <: AbstractVector` but it is immutable. That's why I had that problem.

**Comment by ronisbr** [comment]
I think some part of the code saw that `x` is `AbstractVector` and assumed it is mutable, trying to call `setindex!`.

**Comment by ChrisRackauckas** [comment]
Yes, make it a `StaticArrays.FieldVector`?

**Comment by ronisbr** [comment]
> Yes, make it a `StaticArrays.FieldVector`?

Hum, nice suggestion, I will try :) I think it will not break anything.

**Comment by YingboMa** [comment]
I have a fix locally.

**Comment by ronisbr** [comment]
@ChrisRackauckas I changed to `Quaternion{T} <: FieldVector{4, T}`, but I still get this error when trying to solve the system:

```julia
ERROR: setfield!: immutable struct of type Quaternion cannot be changed
```

meaning that `setfield!` is being called at some point.

**Comment by ronisbr** [comment]
I just noticed that the problem also happens if `x` is a `SVector`:

```julia
using StaticArrays
using ModelingToolkit
using OrdinaryDiffEq

ModelingToolkit.get_unit(x::SVector) = ModelingToolkit.unitless

@variables t x(t)
D = Differential(t)
@named quat_model = ODESystem(D(x) ~ SVector{4, Float64}(0.05, 0, 0, 0))
prob = ODEProblem(quat_model, [x => SVector{4, Float64}(1.0, 0.0, 0.0, 0.0)], (0.0, 10.0))
sol = solve(prob, Tsit5())
```

```
ERROR: LoadError: setindex!(::SVector{4, Float64}, value, ::Int) is not defined.
```

**Comment by ronisbr** [comment]
Sorry @YingboMa I posted before seeing your post.

**Comment by YingboMa** [comment]
With https://github.com/SciML/RecursiveArrayTools.jl/pull/167 and https://github.com/JuliaSymbolics/Symbolics.jl/pull/349

```julia
using modelingtoolkit
using ordinarydiffeq
using referenceframerotations
using recursivearraytools
using arrayinterface

arrayinterface.ismutable(::type{<:quaternion}) = false

@inline function ordinarydiffeq.calculate_residuals(ũ::quaternion, u₀::quaternion, u₁::quaternion,
        α, ρ, internalnorm, t)
    internalnorm(ũ, t) / (α + max(internalnorm(u₀,t), internalnorm(u₁,t)) * ρ)
end

base.zero(::type{quaternion{t}}) where t = quaternion{t}(0, 0, 0, 0)
base.convert(::type{<:quaternion{t}}, x::number) where t = quaternion{t}(x, zero(x), zero(x), zero(x))

@variables t x(t)
d = differential(t)
@named quat_model = odesystem(d(x) ~ quaternion{float64}(0, 0, 0, 0))
prob = odeproblem(quat_model, [x => quaternion(1.0, 0.0, 0.0, 0.0)], (0.0, 10.0))
sol = solve(prob, tsit5())
```
works
```julia
julia> sol = solve(prob, Tsit5())
retcode: Success
Interpolation: specialized 4th order "free" interpolation
t: 7-element Vector{Float64}:
  0.0
  9.999999999999999e-5
  0.0010999999999999998
  0.011099999999999997
  0.11109999999999996
  1.1110999999999995
 10.0
u: 7-element Vector{Vector{Quaternion{Float64}}}:
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
```

**Comment by ChrisRackauckas** [comment]
Why overload calculate_residuals instead of doing a norm?

**Comment by ronisbr** [comment]
Using the PR JuliaSymbolics/Symbolics.jl#349 and without overloading the `calculate_residuals` I got this error:

```julia
julia> sol = solve(prob, Tsit5())
ERROR: MethodError: Cannot `convert` an object of type Vector{Float64} to an object of type Float64
Closest candidates are:
  convert(::Type{T}, ::DomainSets.DomainPoint) where T at /Users/ronan.arraes/.julia/packages/DomainSets/Qqvhf/src/applications/coordinates.jl:7
  convert(::Type{T}, ::VectorizationBase.AbstractSIMD) where T<:Union{Bool, Float16, Float32, Float64, Int16, Int32, Int64, Int8, UInt16, UInt32, UInt64, UInt8, VectorizationBase.Bit} at /Users/ronan.arraes/.julia/packages/VectorizationBase/pTvQj/src/base_defs.jl:154
  convert(::Type{T}, ::Static.StaticFloat64{N}) where {N, T<:AbstractFloat} at /Users/ronan.arraes/.julia/packages/Static/SG32r/src/float.jl:26
  ...
Stacktrace:
  [1] setindex!(A::Vector{Float64}, x::Vector{Float64}, i1::Int64)
    @ Base ./array.jl:839
  [2] macro expansion
    @ ~/.julia/packages/DiffEqBase/WKucm/src/calculate_residuals.jl:96 [inlined]
  [3] macro expansion
    @ ./simdloop.jl:77 [inlined]
  [4] calculate_residuals!
    @ ~/.julia/packages/DiffEqBase/WKucm/src/calculate_residuals.jl:95 [inlined]
```

Using the code of @YingboMa it does not give any errors, but the result does not seem right. If I change the derivative, the result is the same:

```julia
using ModelingToolkit
using OrdinaryDiffEq
using ReferenceFrameRotations
using RecursiveArrayTools
using ArrayInterface

ArrayInterface.ismutable(::Type{<:Quaternion}) = false

@inline function OrdinaryDiffEq.calculate_residuals(ũ::Quaternion, u₀::Quaternion, u₁::Quaternion,
        α, ρ, internalnorm, t)
    internalnorm(ũ, t) / (α + max(internalnorm(u₀,t), internalnorm(u₁,t)) * ρ)
end

Base.zero(::Type{Quaternion{T}}) where T = Quaternion{T}(0, 0, 0, 0)
Base.convert(::Type{<:Quaternion{T}}, x::Number) where T = Quaternion{T}(x, zero(x), zero(x), zero(x))

@variables t x(t)
D = Differential(t)
@named quat_model = ODESystem(D(x) ~ Quaternion{Float64}(0.05, 0, 0, 0))
prob = ODEProblem(quat_model, [x => Quaternion(1.0, 0.0, 0.0, 0.0)], (0.0, 10.0))
sol = solve(prob, Tsit5())
```

**Comment by ronisbr** [comment]
Hi!

Due to a lot of problems, `Quaternion` in ReferenceFrameRotations.jl does not have a super type anymore. In Flux.jl, I was having many problems because `Quaternion` was an array in which the multiplication `q * q` (2 4x1 vector) was leading to another 4x1 vector. After removing this, I could propagate the quaternion using this code:

```julia
using DiffEqBase
using RecursiveArrayTools
using ReferenceFrameRotations

import DiffEqBase: UNITLESS_ABS2, NAN_CHECK, recursive_length

UNITLESS_ABS2(q::Quaternion) = norm(q)
NAN_CHECK(q::Quaternion) = isnan(q.q0) || isnan(q.q1) || isnan(q.q2) || isnan(q.q3)
recursive_length(v::Vector{T}) where T<:Quaternion = length(v) * 4

import RecursiveArrayTools: recursivecopy!

function recursivecopy!(
    out::Vector{T},
    in::Vector{T}
) where T<:Quaternion

    for i in 1:length(out)
        out[i] = in[i]
    end

    return nothing
end

using OrdinaryDiffEq
using ModelingToolkit
using ReferenceFrameRotations

@inline function OrdinaryDiffEq.calculate_residuals(ũ::Quaternion, u₀::Quaternion, u₁::Quaternion,
        α, ρ, internalnorm, t)
    internalnorm(ũ, t) / (α + max(internalnorm(u₀,t), internalnorm(u₁,t)) * ρ)
end

import Base: zero

zero(::Type{Quaternion{T}}) where T = Quaternion{T}(0, 0, 0, 0)

@variables t x(t)
D = Differential(t)

eqs = [
    D(x) ~ Quaternion{Float64}(0, 0.05, 0, 0),
]

@named quat_model = ODESystem(eqs)

prob = ODEProblem(
    quat_model,
    [x => Quaternion(1.0, 0.0, 0.0, 0.0)], (0.0, 10.0),
)
sol = solve(prob, Tsit5())
```

The only problem now is to find a way to add the restriction `norm(q) ~ 1`, which I could not do.

```julia
retcode: Success
Interpolation: specialized 4th order "free" interpolation
t: 3-element Vector{Float64}:
  0.0
  4.47213595499958
 10.0
u: 3-element Vector{Vector{Quaternion{Float64}}}:
 [Quaternion{Float64}: + 1.0 + 0.0⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.223607⋅i + 0.0⋅j + 0.0⋅k]
 [Quaternion{Float64}: + 1.0 + 0.5⋅i + 0.0⋅j + 0.0⋅k]
```

**Comment by ronisbr** [comment]
This is now working! See the code in #1458
