### ISSUE TITLE
Incorrect error msg

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/ModelingToolkit.jl#1198]
https://github.com/SciML/ModelingToolkit.jl/blob/6e16d4782bfc03bc4523c63508adf01edea03df5/src/systems/abstractsystem.jl#L159

The message tells me to use `alias_elimination` to init the system structure, however in the last line of the method:
https://github.com/SciML/ModelingToolkit.jl/blob/6e16d4782bfc03bc4523c63508adf01edea03df5/src/systems/alias_elimination.jl#L61
the structure is set to `nothing`.

I think it should state `sys = initialize_system_structure(alias_elimination(sys))`.

**Comment by YingboMa** [comment]
This is correct.
