### ISSUE TITLE
Support mass matrices on ODESystem

### ISSUE THREAD

**Issue by HarrisonGrodin** [SciML/ModelingToolkit.jl#120]
Currently, `ODESystem` doesn't support having a mass matrix attached:

```
u' = f(u,p,t)  # current
Mu' = f(u,p,t)  # future
```

We should support this by extending the data structure. Given `n` dependent variables, we should just need to store an additional nxn `Matrix{Float64}` (and extend it when necessary after transformations).

**Comment by ChrisRackauckas** [comment]
Completed in https://github.com/SciML/ModelingToolkit.jl/pull/267
