### ISSUE TITLE
`@register`-ed function with composite type arguments fail `check_units()`

### ISSUE THREAD

**Issue by bolognam** [SciML/ModelingToolkit.jl#1221]
This is a follow-up to #1218 .

@YingboMa made me aware of adding in my composite types as `@parameters` in MTK. So in order to support composite types as `@parameters` in `@register`-ed functions, there needs to be another fix to unit checking, this time it's `safe_get_unit()` @lamorton .

I do need this fix, because I can't `structural_simplify()` without `check_units()` passing. So, a hot fix for this would be to turn off type checking when calling `structural_simplify()`.

```
using ModelingToolkit
# Composite type parameter in registered function
@parameters t

struct NewType
    f
end
@register dummycomplex(complex::Num, scalar)
dummycomplex(complex, scalar) = complex.f - scalar

c = NewType(1)
sts = @variables a(t)=0
ps = @parameters s=-1 c=c
eqs = [a ~ dummycomplex(c, s);]
ODESystem(eqs, t, [sts...;], [ps...;], name=:sys)
# You can turn off `checks` on the above line, but `structural_simplify()` will fail afterwards
```

**Comment by YingboMa** [comment]
@lamorton could you take a look?

**Comment by lamorton** [comment]
Yeah, I had intended to eventually make transformations set the `checks=false` for any constructors they call, b/c the checks should be redundant if the the transformations are mathematically correct. Looks like I should expedite that for working around issues like this.

I don't think it's possible to make a generic `get_unit` that will work for any arbitrary user-defined type, because how should it know where the metadata is located? We should prompt users to specialize `get_unit` for custom types like this. Either that, or they should subtype an existing type that `get_unit` knows how to handle.

**Comment by lamorton** [comment]
Actually, I was able to get this to work with `checks=false` for the constructor -- it passes `structural_simplify` already.  (I'm on v6.4.2 right now).

```julia
sys = ODESystem(eqs, t, [sts...;], [ps...;], name=:sys,checks=false)
sys_simple = structural_simplify(sys)
```

**Comment by bolognam** [comment]
@lamorton My MWE ends up with zero equations after simplifying, so you can modify it to produce a simplified system with equation(s) that include the registered function. Then you'll see how `structural_simplify()` runs `check_units()` on all the available `Equation`s.

**Comment by lamorton** [comment]
This should also help: #1225

**Comment by lamorton** [comment]
I think we can close this now.

**Comment by bolognam** [comment]
Looks like you updated the docs and the example in #1229 (pasted below) would be the correct solution for my MWE?

```using ModelingToolkit
# Composite type parameter in registered function
@parameters t
D = Differential(t)
struct NewType
    f
end
@register dummycomplex(complex::Num, scalar)
dummycomplex(complex, scalar) = complex.f - scalar

c = NewType(1)
MT.get_unit(x::NewType) = MT.get_unit(x.f)
function MT.get_unit(op::typeof(dummycomplex),args)
    argunits = MT.get_unit.(args)
    MT.get_unit(-,args)
end

sts = @variables a(t)=0 [unit = u"cm"]
ps = @parameters s=-1 [unit = u"cm"] c=c [unit = u"cm"]
eqs = [D(a) ~ dummycomplex(c, s);]
sys = ODESystem(eqs, t, [sts...;], [ps...;], name=:sys)
sys_simple = structural_simplify(sys)
```

**Comment by lamorton** [comment]
Yeah, I tested that with the latest PR, should work.

**Comment by bolognam** [comment]
Yeah that's nice that you removed unit checking if there's no units.

Cool, I can close this then. I probably won't re-test with the latest MTK until tomorrow morning.
