### ISSUE TITLE
release notes / news equivalent for breaking changes or new features

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#1245]
I know SciML libraries don't currently do this, but it would be great to have a NEWS.md / RELEASES.md type file that succinctly summarizes breaking changes in new versions as they appear. Sometimes it can be hard to keep up with breaking interface changes in MT, or changes in recommended functions/approaches to use as features are added. Having one file that tracks releases and briefly mentions new functions and depreciations would be very helpful (especially to libraries built on MT that may not be updated as frequently). Since this would be aimed more at developers I would think just a sentence or two on each change would be enough for them to dig deeper to figure out how their code should be modified.

Going along with this would be making sure that PRs that add major new functionality or make breaking changes should also update this file before being merged.

**Comment by ChrisRackauckas** [comment]
yeah... or @YingboMa @shashi stop breaking things 😆

**Comment by shashi** [comment]
I think having a NEWS.md is easier...
