### ISSUE TITLE
Functions created by `build_function` should supported passing parameters using NamedTuples and Dicts

### ISSUE THREAD

**Issue by gzheng92** [SciML/ModelingToolkit.jl#1259]
Functions created by `build_function` take parameters as arguments, where the mapping from args to parameter values is order dependent.  It would be helpful if these functions could accept a NamedTuple or a Dict and unpack the relevant parameters inside that NamedTuple to use as parameter values

An example:

```
@parameters a b
@variables x

y = x + a

f = build_function([y], [x], [a])[1]

f(5, 3) # this is how it works now
# 8

paramMap = Dict(a => 3, b => 4)
f(5, paramMap) # This doesn't work right now, but would also return 8
# Note that b is a key in paramMap and won't get used
```

I think this is a very useful feature because I often have 10+ parameters in my model.  It's a huge pain to:
- refer to the function definitions to make sure I'm passing the exact 3 parameters that this function needs, and
- refer to the function definitions to make sure I've passed them in the right order

Being able to pass all the parameters and let the function do the unpacking (similar to how the `@unpack` macro from `Parameters.jl` works) would be a god-send.

**Comment by ChrisRackauckas** [comment]
See the new parameters interface
