### ISSUE TITLE
parameters returns non-unique set of parameters

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#1267]
Should the `parameters` function have redundant entires (i.e. not call `unique` as `states` does), or am I using `ParentScope` incorrectly?
```julia
@parameters p1 p2
@variables t v1(t) v2(t)
eqs1 = [v1 ~ p1]
eqs2 = [ParentScope(v1) ~ ParentScope(p1)*v2 + p2]
@named osys2 = ODESystem(eqs2, t, [ParentScope(v1),v2],[ParentScope(p1),p2])
@named osys1 = ODESystem(eqs1, t, [v1], [p1], systems=[osys2])
```
then
```julia
julia> parameters(osys1)
3-element Vector{Sym{Real, Base.ImmutableDict{DataType, Any}}}:
 p1
 p1
 osys2₊p2
```
while `states` correctly gives
```julia
julia> states(osys1)
2-element Vector{Term{Real, Base.ImmutableDict{DataType, Any}}}:
 v1(t)
 osys2₊v2(t)
```

**Comment by ChrisRackauckas** [comment]
It should be unique. How did it not be unique? That seems like an extend bug @YingboMa ?

**Comment by isaacsas** [comment]
This doesn't use `extend`, it is just that `states` applies a `unique` filter before returning but `parameters` (and some other accessors) does not.
