### ISSUE TITLE
Fast symbolic derivatives

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#127]
https://www.microsoft.com/en-us/research/wp-content/uploads/2016/02/main-65.pdf

**Comment by jlumpe** [comment]
Very cool. Are you planning on adding an external symbolic math library as a dependency?

**Comment by ChrisRackauckas** [comment]
I don't think we need to. Rewrite.jl + Terms.jl + ModelingToolkit + etc. are a symbolic math library which will be using interchangeable terms formats.
