### ISSUE TITLE
incorrect ODEs when child ODESystem contains ParentScope'd state

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#1274]
```julia
@parameters p1 p2
@variables t A(t) 
D = Differential(t)
@named os2 = ODESystem([D(ParentScope(A)) ~ -p2*ParentScope(A)],t,[ParentScope(A)],[p1])
@named os1 = ODESystem([D(A) ~ -p1*A],t,[A],[p1])  
os = compose(os1,[os2])   # or set systems=[os2] in os1
```
then we get
```julia
julia> equations(os)
2-element Vector{Equation}:
 Differential(t)(A(t)) ~ -p1*A(t)
 Differential(t)(A(t)) ~ -os2₊p2*A(t)
```

This may seem silly, but in Catalyst hierarchical models a reaction that uses a parent scoped variable will lead to a sub-system having an ODE for that variable when being converted, giving such doubled equations. I guess we could solve this there by flattening before conversion, but it seemed like maybe this isn't the desired behavior for a collection of ODESystems either?

**Comment by ChrisRackauckas** [comment]
Fixed by complete
