### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by harrisonrobin** [SciML/ModelingToolkit.jl#1280]
Running the component-based model of a spring-mass system in the documentation results in 

`ERROR: LoadError: StackOverflowError:
Stacktrace:
 [1] recursive_unitless_bottom_eltype(a::Type{Any}) (repeats 99 times)
   @ RecursiveArrayTools ~/.julia/packages/RecursiveArrayTools/USU0j/src/utils.jl:96
in expression starting at /home/********/mass_spring.jl:47
`

the line the strace is 

`sol = solve(prob, Rosenbrock23())`

**Env**
- ModelingToolkit v6.5.2
- DifferentialEquations v6.18.0

**Comment by ChrisRackauckas** [comment]
@YingboMa I think the latest merge may have broken defaults of array variables. Basically, `@variables x[1:2] = [1.0,2.0]` seems to now be producing `Term`s as the initial condition. Can you take a look? It may be a merge error between the changes I had done to the initial condition code and then your update code.

**Comment by ChrisRackauckas** [comment]
Was fixed awhile back.
