### ISSUE TITLE
Time-shift operator for discrete-time control systems

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#1307]
MTK currently has the `Difference` operator that operates on `x(t)`, producing `x(t+dt) - x(t)`. Control-systems design and analysis in discrete time typically employs the shift operator, which operates on `x(t)` and produces `x(t+dt)`. The shift operator is the time-domain analog to the Z-transform operator, and allow you to write pulse-transfer functions like
```julia
TransferFunction{Discrete{Int64}, ControlSystems.SisoRational{Float64}}
1.5714702966431753z^3 + 0.5706479289308617z^2 - 0.3953765256425884z + 0.3354448928377647
----------------------------------------------------------------------------------------
       1.0z^3 + 0.5728489416081901z^2 - 0.1695044578033371z + 0.11243834527436224
```
in a natural way.

The easiest way to introduce this operator would be to define it in terms of the difference operator, i.e.,
```julia
struct TimeShift
    d::Difference
end
(q::TimeShift)(x) = q.d(x) + x
```
But that might conflict with assumptions such as the LHS of dynamics equations only containing a difference operator etc. (if such assumptions exist).

cf: https://github.com/SciML/ModelingToolkit.jl/issues/1180#issuecomment-896063856

**Comment by ValentinKaisermayer** [comment]
Isn't there such a thing already?
https://github.com/JuliaSymbolics/Symbolics.jl/blob/c310aabc7854d64af4461ed64ef42018a63324d9/src/difference.jl#L33

**Comment by baggepinnen** [comment]
Yes, it was hiding behind a name unfamiliar to me ^^
https://github.com/JuliaSymbolics/Symbolics.jl/pull/453 renames this operator to `Shift`

**Comment by ValentinKaisermayer** [comment]
However, I think for `ODESystems`, `DiscreteUpdate` is really a ZOH (updates variables at certain discrete timestamps - as the name suggests):

https://github.com/SciML/ModelingToolkit.jl/blob/9cc6f21c1ffb1299d1a2d120c848f036d5f232c9/src/systems/diffeqs/abstractodesystem.jl#L129

Maybe it is different for `DiscreteSystem`. However, I still would like to have the update operator for ODESystems.

**Comment by ValentinKaisermayer** [comment]
Maybe @YingboMa can clarify what he indented this operator for?

**Comment by baggepinnen** [comment]
`DiscreteUpdate` acts as a sample-and-hold on continuous variables, but in discrete systems it was a shift operator. I think MTK needs to be a bit clearer on the definitions here, similar to how modelica distinguishes between these different concepts quite clearly and has very well-defined semantics for the transition between continuous and discrete time domains.

**Comment by ValentinKaisermayer** [comment]
I think you are right, there needs to be a clear definition (see [ModelicaSpec v3.4](https://modelica.org/documents/ModelicaSpec34.pdf) p. 197 for an example).

**Comment by baggepinnen** [comment]
I'm working on a little proposal which will replace https://github.com/JuliaSymbolics/Symbolics.jl/pull/453 for how these operators can be defined and behave.

**Comment by ChrisRackauckas** [comment]
And the Shift operator should apply to continuous variables to describe delay differential equations as well?

**Comment by baggepinnen** [comment]
> And the Shift operator should apply to continuous variables to describe delay differential equations as well?

That's an interesting idea! I was planning to use the operators to infer whether a signal lives in the continuous or discrete time domain, so perhaps a separate `Delay` operator could be used so that the input and output domains of the operator can be distinguished. And help with model checking.

An alternative approach would be to explicitly encode the domain in the variable, like
```julia
@variables x(t) [discrete=true]
```
and avoid the domain inference, at the expense of a bit more hassle for the user. Modelica does this inference automatically by requiring discrete equations to be separate from continuous equations and continuous variables can only appear in discrete equations through the `sample` operator (or with the `when sampleTrigger` construct). Page 197 of https://modelica.org/documents/ModelicaSpec34.pdf has a nice overview. The semantics of `pre`, which is their equivalent of `Shift` in the PR above, is outlined on page 30, it operates on discrete variables, but the discrete nature is inferable from other language constructs.

**Comment by ChrisRackauckas** [comment]
I think I see where our difference is. You see two domains, discrete and continuous, with operators converting between the two. I don't see two domains. `t` is always continuous, and there are operators which describe how things change along `t` and how to access other values at `t`. It's an abstraction of the system to see that `dt` is the same for all variables in a system and thus it can just discretely step it as `x(t)`, `x(t+dt)`, etc., but even then `x(t + dt/2)` is still defined as the right-continuous extension, i.e. `x(t) == x(t+dt/2)`. I believe this interpretation is just as expressable but uses less operators to do so, and it matches what is actually plotted (otherwise discrete values would only ever be able to be scatter plotted).

Is there a time when this interpretation does not make sense?

**Comment by ValentinKaisermayer** [comment]
I think a discrete variable can be viewed as a continuous, that is piecewise-constant and only changes at `t=n*dt` where `n ={0,1,2,3...}`. This would also make sample time convertions easy. So essentially there would be no need for a `hold` operator.
If a variable is defined only via variables that stem from `sample` operations, it must be piecewise-constant as well. This includes transformations via `shift`. Those variables could inferred and be updated (written to) in a periodic callback but otherwise used (read from) as all other variables. I think at leas for an `ODESystem`. 
I think Simulink does this the same way, there is no need for converting a signal (e.g. from a discrete controller) to continuous again, see this [post](https://de.mathworks.com/matlabcentral/answers/258448-ho-to-convert-a-signal-from-discrete-to-continuous-in-simulink-block-diagram).

**Comment by baggepinnen** [comment]
Discrete systems may arise from discretization of a continuous system, but a system may also be inherently discrete. A discrete system models a sequence, where the independent variable is the sequence index. Examples of inherently discrete systems are iterative algorithms, models of digital circuits and models of discrete events. Digital circuits have explicit electrical components performing the hold operation (often built into sampling devices, sample-and-hold), in order to couple the discrete evolution of the digital circuit to the continuous surroundings. The sample-and-hold circuit is often referred to as an analog to digital converter, exactly matching the semantics of sample and hold used in modelica. 

Another case where models are inherently discrete is if they model discretely defined events. Christmas occurs once per year, and inbetween it's "not defined". If the model `x(k+1) = 2x(k)` models how crazy people get about Christmas shopping each year, there is actually no continuous independent variable. We think of the time betweeen these events as continuous, but you can not refine the discretization of this model and obtain a more accurate one, neither would the `hold` semantics be appropriate for plotting the response of the model, since the event Christmas does not extend for a whole year.

Plotting the response of discrete systems with step functions is only common when the discrete nature is due to discretization and there is an understood hold operation. For sequential systems where there is no notion of a continuous variable, it's more common to plot a pulse train or just points.

Modelica has the notion of a clock, the clock attributes time to the sequence of computations in a discrete system. Without the clock, time doesn't exist. It makes total sense to have a discrete system with no notion of time or length of a step, only when the system is a discretized version of something continuous does the discrete step have a length.

The to me most intuitive notion of the interface between the continuous world and the discrete is the sample operator. This operator is very clear about taking a snapshot of something continuous at a single time point, everywhere else the value of the continuous variable that was sampled is unknown to the discrete world. Similarly, if the discrete system has no clock, it can operate infinitely fast as seen from the continuous world.

In the real world, communicating devices usually have their own clocks. Even if they use the same time step, those steps may be of different lengths and the exact trigger times may drift apart etc. The hold operator extends a discrete signal to a continuous one using the clock of the signal source, while the sample operator uses the receiving clock, which may or may not be different from the source clock. Modelica allows you to model all of this with great detail, since it's extremely important in practice. Things like sample time jitter and clock drift are important for control performance and simulating them is common.

**Comment by baggepinnen** [comment]
Sec. 16.1.2 Rationale for Clocked Semantics of https://specification.modelica.org/v3.4/Ch16.html
has an explicit comparison of implicit sample and hold semantics vs. Clocked semantics.

**Comment by ValentinKaisermayer** [comment]
A few comments

> The sample-and-hold circuit is often referred to as an analog to digital converter, exactly matching the semantics of sample and hold used in modelica.

A sample-and-hold is part of an ADC but it is not the ADC. Since a digital signal may only take on finitely many values, an important part of any [ADC](https://reference.wolfram.com/language/guide/ControlSystems.html) is the quantization. This is not what we talk about in MTK. The signals are time discrete but not really digital. 

For the Christmas example: Why would subsampling not be allowed in this case (i.e. how crazy are people about Christmas at the 1th of June in year `k`)? The simplest guess would be `x(k)` (zero-oder-hold). But also first-order-hold and second-order-hold would be possible. This is up to the user, I guess. 

From the definition of clocked variables in the Modelica specs:

> At time instants where the associated clock is not active, the value of a clocked variable can be inquired by using an explicit cast operator, see below. In such a case a “hold” semantics is used, in other words the value of the clocked variable from the last event instant is used. 

This is a ZOH.

I see the value in different hold operators but if only one (ZOH) is used it has no value and is simply implicit, I think. 

```julia
yd(k) ~ Sample(y, dt)
ud(k) ~ kp * (r - yd(k))
D(x) ~ -x + Hold(ud)
y~x
```
vs.
```julia
yd(k) ~ Sample(y, dt) 
ud(k) ~ kp * (r - yd(k))
D(x) ~ -x + ud
y~x
```
Maybe even the `yd(k) ~ Sample(y, dt)` is implicit. Since `yd(k)` already tells you that it is the value at time instance `k`. And it has a sample time associated to it. 

How would you propose to describe the clock jitter?
Two different `k`?

**Comment by baggepinnen** [comment]
> A sample-and-hold is part of an ADC but it is not the ADC. Since a digital signal may only take on finitely many values, an important part of any ADC is the quantization.

I agree, it was a sloppy definition of an ADC. The point I was trying to make was that the sample and hold operators are not invented solely for the purpose of modeling, they have direct equivalents in electronics where the continuous and discrete worlds interface.

The details of the modelica spec state the following

> Clocked variables (such as yd, xd, ud) are associated uniquely with a clock and can only be directly accessed when the associated clock is active. Since all variables in a clocked equation must belong to the same clock, clocking errors can be detected at compile time. If variables from different clocks shall be used in an equation, explicit cast operators must be used, such as sample(..) to convert from continuous-time to clocked discrete-time or hold(..) to convert from clocked discrete-time to continuous-time.

The key here is that they do require the explicit use of the `hold` operator to go from discrete to continuous.

Let me be more precise about the Christmas model. Let `x(k)` be the total sales of a store during the month of December year `k`. This variable is only defined for integers `k`, and it makes no sense to try to define it in a continuous fashion. You could ask "what was the last value it had", which is the modelica `pre` operator, and you could access it at `k+0.5` by using *an explicit cast operator, hold*. 

In your examples, the implicit `Sample` in `y(k)` is implemented in 
- https://github.com/SciML/ModelingToolkit.jl/pull/1383

It's not too implicit since the indexing occurs with a special operator that is explicit about sampling. 
The remaining question is whether or not we should require `hold` when using the discrete variable `ud` in the continuous equation `D(x) ~ -x + ud`. Modelica requires this for clocked variables, and they have a explanation of their design rationale and the drawbacks of implicit sample and hold, see [16.1.2 Rationale for Clocked Semantics](https://specification.modelica.org/v3.4/Ch16.html). The modelica clocked module is rather new and came about exactly because their old way of doing it was problematic. Further details are provided in their paper on the subject
https://mediatum.ub.tum.de/doc/1285847/file.pdf
and the block-diagram examples in the paper even has the sample and hold operators as distinct graphical elements.

Before clock jitter could be expressed, I think we have to work a bit on how to handle clocks in general. The clock jitter could potentially be expressed using a subtype of a clock which leads to sampling not being lowered to a `PeriodicCallback` but rather a `ContinuousCallback` where the `condition` is updated at each clock trigger to point to a new clock trigger at a random time point in the future. We currently keep track of the discrete time step in many places, but this could possibly be replaced by an instance of a `clock` or similar.

**Comment by ValentinKaisermayer** [comment]
So you want to use the `Sample` and `Hold` operators as boundaries for inference of one or more clocked partitions and the continuous part of the model - as Modelica does?

```julia
dt = 0.1
@variables t x(t) y(t) u(t) yd(t) ud(t)
k = SampledTime(t; dt)
D = Derivative(t)

# controller (time discrete part `dt=0.1`)
yd(k) ~ Sample(y, dt)
ud(k) ~ kp * (r - yd(k))

# plant (time continuous part)
u ~ Hold(ud(k))
D(x) ~ -x + u
y~x
```
With the operator defined in https://github.com/SciML/ModelingToolkit.jl/pull/1383 this would expand into:

```julia
# controller
Sample(t; dt=0.1)(yd(t)) ~ Sample(t; dt=0.1)(y(t))
Sample(t; dt=0.1)(ud(t)) ~ kp * (r - Sample(t; dt=0.1)(yd(t)))

# plant
u(t) ~ Hold()Sample(t; dt=0.1)(ud(t))
Derivative(t)(x(t)) ~ -x(t) + u(t)
y(t)~x(t)
```
And a more compact form:
```julia
dt = 0.1
@variables t y(t)
D = Derivative(t)
D(y) ~ -y + Hold(kp * (r - Sample(y, dt)))
```

**Comment by baggepinnen** [comment]
> So you want to use the Sample and Hold operators as boundaries for inference of one or more clocked partitions and the continuous part of the model - as Modelica does?

More or less, yes. I also think it helps the user to expose the fact that there is a distinct difference between the discrete domain, typically things that happen in a computer, and the continuous domain, e.g., physics. Most graphical modeling tools allow you to highlight signals that are discrete differently from continuous, [this is how it looks in simulink](https://blogs.mathworks.com/simulink/2008/10/24/r2008b-simulink-sample-time-colors/). 

Being able to detect and error for sample-time mismatch etc. will be very valuable for larger models. A, car, aircraft or chemical processing plant, can have in the order of 100's of individual computers interfacing the real world, all operating using their own clock. A robot controller typically has several internal sample rates in the same computer, where, for example, low-level joint control occurs at 8kHz, feedforward control occurs at 1kHz and trajectory planning is asynchronous and occurs based on events. Between the 1kHz and 8kHz levels the `hold` semantics is not always the correct one, and higher-order interpolation might be more suitable. The problem with zero-order-hold in this context is that the large discontinuity in reference causes a very large control action when using high-gain controllers, and this induces wear and tear as well as vibrations in the machine.

I think the next step has to be improving the lowering of the discrete indexing. The example you highlighted
```julia
Sample(t; dt=0.1)(yd(t)) ~ Sample(t; dt=0.1)(y(t))

**Comment by baggepinnen** [comment]
Ok, I have something that appears to be working for simple cases. A slightly modified version of @ValentinKaisermayer's problem above
```julia
dt = 0.1
@variables t x(t) y(t) u(t) yd(t) ud(t) r(t)
@parameters kp
k = SampledTime(t, dt)
D = Differential(t)

eqs = [
    # controller (time discrete part `dt=0.1`)
    yd ~ Sample(t, dt)(y)
    ud ~ kp * (r - yd)

    # plant (time continuous part)
    u ~ Hold(ud)
    D(x) ~ -x + u
    y ~ x
]
```
infers to

```julia
eqmap, varmap = ModelingToolkit.equation_and_variable_time_domains(eqs)

julia> varmap
Dict{Any, Any} with 7 entries:
  yd(t) => Clock(t, 0.1)
  ud(t) => Clock(t, 0.1)
  u(t)  => Continuous()
  kp    => nothing
  y(t)  => Continuous()
  r(t)  => Clock(t, 0.1)
  x(t)  => Continuous()

julia> eqs .=> eqmap
5-element Vector{Pair{Equation}}:
 yd(t) ~ Sample(t; clock=Clock(t, 0.1))(y(t)) => Clock(t, 0.1)
                    ud(t) ~ kp*(r(t) - yd(t)) => Clock(t, 0.1)
                         u(t) ~ Hold()(ud(t)) => Continuous()
          Differential(t)(x(t)) ~ u(t) - x(t) => Continuous()
                                  y(t) ~ x(t) => Continuous()
```

**Comment by ValentinKaisermayer** [comment]
Looks great!

So if we assume an `ODESystem`, the clocked equations (first two) are excluded (have to be changed) and the variables `yd(t)` and `ud(t)` are updated via a `FunctionMap` in a generated `PerdiodicCallback(cb!, 0.1)`. For this to work `yd(t)` and `ud(t)` have to be states of the overall system. If the update involves observed variables, those can be computed from the states and parameters, using the method generated by `build_explicit_observed_function`.

I hacked something together yesterday that functions similarly: https://github.com/SciML/ModelingToolkit.jl/issues/1180#issuecomment-981908237

What if there are two clock partitions (i.e. inner and outer control loop)? Do the sample times have to be integer multiples of each other and only one `PerdiodicCallback(cb!, dt_inner)` would be generated, where the slower part would be executed every `n` calls e.g. when `mod(int.t, dt_outer) == 0`?

**Comment by baggepinnen** [comment]
So far, the clock inference handles multiple different sample rates
```julia
julia> varmap
Dict{Any, Any} with 9 entries:
  yd2(t) => Clock(t, 0.2)
  u(t)   => Continuous()
  kp     => nothing
  y(t)   => Continuous()
  ud1(t) => Clock(t, 0.1)
  r(t)   => Inferred()
  ud2(t) => Clock(t, 0.2)
  x(t)   => Continuous()
  yd1(t) => Clock(t, 0.1)

julia> eqs .=> eqmap
7-element Vector{Pair{Equation}}:
               yd1(t) ~ Sample(t; clock=Clock(t, 0.1))(y(t)) => Clock(t, 0.1)
 ud1(t) ~ kp*(Sample(t; clock=Clock(t, 0.1))(r(t)) - yd1(t)) => Clock(t, 0.1)
               yd2(t) ~ Sample(t; clock=Clock(t, 0.2))(y(t)) => Clock(t, 0.2)
 ud2(t) ~ kp*(Sample(t; clock=Clock(t, 0.2))(r(t)) - yd2(t)) => Clock(t, 0.2)
                      u(t) ~ Hold()(ud1(t)) + Hold()(ud2(t)) => Continuous()
                         Differential(t)(x(t)) ~ u(t) - x(t) => Continuous()
                                                 y(t) ~ x(t) => Continuous()
```
but to correctly handle this when simulating, I assume a compiler pass that orders the equations is required. Such a compiler pass will be aided by upcoming improvements to express causality, e.g., input and output relations. The simplification passes in `structural_simplify` do currently not work for discrete systems, but it might not take many fixes for them to work. 

I don't think the sample times always have to be multiples of each other, if separate callbacks are generated for each clock partition we should be able to support arbitrary sample rates. The question to think about is how to order things when the sample rates are in fact multiples of each other. Modelica has special support for this in a few different ways
1. You may define sample rates as fractions (in order to robustly know for sure they are multiples of each other).
2. Modelica also defines `subSample` and `superSample` operators which creates a faster or slower version of a clock. See [sec 4](https://mediatum.ub.tum.de/doc/1285847/file.pdf).
3. There is a special `PeriodicExactClock` for which special rules apply

If you look at the examples in https://mediatum.ub.tum.de/doc/1285847/file.pdf (many of which are cascade controllers :) ) They all have fixed causality between different clocked partitions, i.e., all lines leading to and from `subSample` and `superSample` have arrows, indicating that the causality is fixed. I don't know if modelica *requires* this, but it might be a reasonable thing to require until we can solve the problem in general (if possible).

Some more discussion about this was held in 
- https://github.com/SciML/ModelingToolkit.jl/issues/1137

In real-world contexts where this occurs, the causality is usually explicitly introduced. In modelica, one can also handle this with clock offsets, so one of the clocks is offset by a small epsilon to ensure that it triggers after another etc. I haven't yet implemented clock offsets, but it should be straightforward to add an `offset` field to the `Clock` type.

**Comment by baggepinnen** [comment]
Regarding the `hold` operator: 

If we require the explicit hold operator, the signal `r` in the following example can be inferred to be discrete. If the user connects a continuous signal to `r` from outside of this subsystem, it's an error. If `hold` is implicit, the equation `ud ~ kp * (r - yd)` can be either continuous or discrete depending on what `r` the user supplies, if a continuous state is connected to `r`, the controller will erroneously be run in continuous time, but with ZoH measurements. 
```julia
D = Differential(t)
eqs = [
    # controller (time discrete part `dt=0.1`)
    yd ~ Sample(t, dt)(y)
    ud ~ kp * (r - yd)

    # plant (time continuous part)
    u ~ Hold(ud)
    D(x) ~ -x + u
    y ~ x
]
```
This is an example of the following two points from the modelica rationale for avoiding implicit hold
>  If a variable belongs to a particular clock, then all other equations where this variable is used, with the exception of as argument to certain special operators, belong also to this clock, as well as all variables that are used in these equations. This property is used for “clock inference” and allows to define an associated clock only at a few places (above only in the sampler, whereas in the discrete controller and the hold the sampling period is inferred)

> If the controller is built-up with several building blocks, then the clock condition (sampling) must be explicitly propagated to all blocks. This is tedious and error prone. With clocked equations, the clock condition need to be defined only at one place, and otherwise is automatically propagated by clock inference.

Another strong reason to require the explicit `hold` is simply error checking, debugging a large model because an equation is running unexpectedly in the wrong time domain can be hard. @crlaugh might have additional insight to share?

**Comment by ChrisRackauckas** [comment]
>If the controller is built-up with several building blocks, then the clock condition (sampling) must be explicitly propagated to all blocks. This is tedious and error prone. With clocked equations, the clock condition need to be defined only at one place, and otherwise is automatically propagated by clock inference.

What, why? That can just be done with abstract interpretation which is simple and error free?

**Comment by baggepinnen** [comment]
> That can just be done with abstract interpretation which is simple and error free?

What they call clock inference is this abstract interpretation. For this to work, there needs to be sufficiently many constraints, in the example above, these constraints are introduced by the operators `Sample, Hold`. Without the `Hold`, the inference result for the equation `ud ~ kp * (r - yd)` depends on `r` which is undesired since `r` is an input, and the user could supply both continuous and discrete inputs, but only discrete inputs of the same clock as the `Sample` are correct. What they mean with having to propagate sample times manually if you have implicit `hold` is that you'd have to specify the sample times for all signals in a block, since inference can't do it for you.

**Comment by ChrisRackauckas** [comment]
So from other discussions, it seems the main reason to keep discrete and continuous variables separate is actually due to none of this but to help with inference in a compute efficiency setup. Discrete variables should not be states of the ODE. We could in theory try to do inference for this, but it might be difficult to automatically figure out continuous algebraic variables vs discrete variables, since discrete variables may not require a discrete update equation (maybe they just show up in an event).

@YingboMa what do you think about that?

**Comment by baggepinnen** [comment]
The semantics of an equation does depend on where you insert the `hold`, the following two systems of equations
```julia
yd ~ Sample(t, dt)(y)
ud ~ kp * (r - yd)
u ~ Hold(ud)
```
```julia
yd ~ Sample(t, dt)(y)
ud ~ kp * (r - Hold(yd))
u ~ ud
```
do not mean the same thing if `r` is continuous. With implicit hold, the second version is correct if the user connects a continuous signal `r`, and the only way around it if we're not using the `hold` operator is to force `r` to be discrete be explicitly specifying the clock of `r`. You could do that, early modelica did, but it was deemed "tedious and error prone".

With the hold operator explicit, inference of the clocks is straightforward ([and implemented](https://github.com/SciML/ModelingToolkit.jl/compare/master...baggepinnen:clock_inference?expand=1#diff-33f8e68d1bb215cfb4f58a4d4095db9092ac27462119c70ab9c2ca7d7ac2d422R179-R216))

**Comment by ChrisRackauckas** [comment]
Old discrete was removed.
