### ISSUE TITLE
Failure of a tutorial example due to the missing `name` keyword

### ISSUE THREAD

**Issue by hurak** [SciML/ModelingToolkit.jl#1326]
The tutorial example for [Building component-based, hierarchical models](https://mtk.sciml.ai/dev/tutorials/ode_modeling/#Building-component-based,-hierarchical-models) fails at the end. Here is the complete code:

```julia
using ModelingToolkit

function fol_factory(separate=false;name)
    @parameters τ
    @variables t x(t) f(t) RHS(t)

    eqs = separate ? [RHS ~ (f - x)/τ,
                      D(x) ~ RHS] :
                      D(x) ~(f - x)/τ

    ODESystem(eqs;name)
end

@named fol_1 = fol_factory()
@named fol_2 = fol_factory(true) # has observable RHS

connections = [ fol_1.f ~ 1.5,
                fol_2.f ~ fol_1.x ]
```
I show the last line of the code together with the (error) output:
```julia
julia> @named connected = compose(ODESystem(connections), fol_1, fol_2)
ERROR: ArgumentError: The `name` keyword must be provided. Please consider using the `@named` macro
Stacktrace:
 [1] ODESystem(deqs::Vector{Equation}, iv::Sym{Real, Base.ImmutableDict{DataType, Any}}, dvs::Vector{Any}, ps::OrderedCollections.OrderedSet{Any}; controls::Vector{Num}, observed::Vector{Num}, systems::Vector{ODESystem}, name::Nothing, default_u0::Dict{Any, Any}, default_p::Dict{Any, Any}, defaults::Dict{Any, Any}, connection_type::Nothing, preface::Nothing, checks::Bool)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/P76eb/src/systems/diffeqs/odesystem.jl:115
 [2] ODESystem(deqs::Vector{Equation}, iv::Sym{Real, Base.ImmutableDict{DataType, Any}}, dvs::Vector{Any}, ps::OrderedCollections.OrderedSet{Any})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/P76eb/src/systems/diffeqs/odesystem.jl:115
 [3] ODESystem(eqs::Vector{Equation}, iv::Nothing; kwargs::Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/P76eb/src/systems/diffeqs/odesystem.jl:185
 [4] ODESystem(eqs::Vector{Equation}, iv::Nothing) (repeats 2 times)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/P76eb/src/systems/diffeqs/odesystem.jl:151
 [5] top-level scope
   @ none:1
```
I am afraid I am not able to decipher this. Honestly, I still do not get the whole issue with the `name` keyword and the `@named` macro. I can read at [https://mtk.sciml.ai/dev/tutorials/ode_modeling/](https://mtk.sciml.ai/dev/tutorials/ode_modeling/) that "Also note that the @named macro simply ensures that the symbolic name matches the name in the REPL. If omitted, you can directly set the name keyword" but I just do not understand what it says. Even consulting the [docs for ODESystem](https://mtk.sciml.ai/dev/systems/ODESystem/) does not really help.

**Comment by anandijain** [comment]
the docstring for `@named` its pretty helpful here. the issue is that `@named` isn't working with the compose, since it's stashing the kwarg in the `compose` call (im guessing), not the `ODESystem` call. 

mainly, anytime you create a System, you need to name it

**Comment by anandijain** [comment]
so you could do `connected = compose(ODESystem(connections; name=:connected), fol_1, fol_2)

**Comment by hurak** [comment]
> the docstring for `@named` its pretty helpful here. 

I am about to reveal that I am a complete ignorant but I just do not know how to get that helpful docstring. Is this
```julia
help?> @named
  @named y = foo(x)
  @named y[1:10] = foo(x)
  @named y 1:10 i -> foo(x*i)

  Rewrite @named y = foo(x) to y = foo(x; name=:y).

  Rewrite @named y[1:10] = foo(x) to y = map(i′->foo(x; name=Symbol(:y_, i′)), 1:10).

  Rewrite @named y 1:10 i -> foo(x*i) to y = map(i->foo(x*i; name=Symbol(:y_, i)), 1:10).

  Examples:

  julia> using ModelingToolkit
  
  julia> foo(i; name) = i, name
  foo (generic function with 1 method)
  
  julia> x = 41
  41
  
  julia> @named y = foo(x)
  (41, :y)
  
  julia> @named y[1:3] = foo(x)
  3-element Vector{Tuple{Int64, Symbol}}:
   (41, :y_1)
   (41, :y_2)
   (41, :y_3)
  
  julia> @named y 1:3 i -> foo(x*i)
  3-element Vector{Tuple{Int64, Symbol}}:
   (41, :y_1)
   (82, :y_2)
   (123, :y_3)
```
what you mean?

I cannot find anything in the [web documentation](https://mtk.sciml.ai/dev/) either.

**Comment by anandijain** [comment]
yes that is the docstring. 
```julia
  Rewrite @named y = foo(x) to y = foo(x; name=:y).

  Rewrite @named y[1:10] = foo(x) to y = map(i′->foo(x; name=Symbol(:y_, i′)), 1:10).

  Rewrite @named y 1:10 i -> foo(x*i) to y = map(i->foo(x*i; name=Symbol(:y_, i)), 1:10).
```
now imagine what would happen if you tried to `@named baz = bar(foo(x), a, b)`, it would rewrite to 
`baz = bar(foo(x), a, b; name=:baz)` which does not do what you want

**Comment by hurak** [comment]
Many thanks for the explanation. Now I need to digest it (it is too late at night here). I may prepare a PR for this example tomorrow. 

But I am still afraid that other users who just read the online tutorial will stumble similarly with this `@named` issue. In the online docs it is not really explained well.
