### ISSUE TITLE
Variable names not kept when solving `DiscreteProblem`s

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#1329]
When solving `DiscreteProblem`s, the solution can not be indexed by variable names
An MWE is given in the example file for discrete systems
https://github.com/SciML/ModelingToolkit.jl/blob/c36c429d5cd883b41c2a1a268a10ece5097e6ff0/test/discretesystem.jl#L36
```julia
sol_map[S]
sol_map[sys.S]
```
both fails with
```
ERROR: Indexing symbol S(t) is unknown
```

**Comment by ChrisRackauckas** [comment]
This is missing dispatches in SciMLBase.

**Comment by baggepinnen** [comment]
For a continuous solution, there are symbols stored in
```
julia> sol.prob.f.syms
2-element Vector{Symbol}:
 Symbol("int₊x(t)")
 Symbol("int₊u(t)")
```
but not for a discrete solution
```
julia> sol_map.prob.f.syms
```
Has the problem happened already when the `f` function is generated?
