### ISSUE TITLE
FMI support?

### ISSUE THREAD

**Issue by asprionj** [SciML/ModelingToolkit.jl#135]
The [Functional Mockup Interface](https://fmi-standard.org/) is an open standard for model exchange and co-simulation. I feel like any new "modelling environment" should provide export to this "format". Would this have to be provided by MT or by the higher-level tools built around it? I'm leaning towards the former, since the export of the equations and/or the co-simulation binary should clearly be handled by the engine actually handling all that stuff...

**Comment by ChrisRackauckas** [comment]
Yes, we could add support to spit out FMI binaries, but it's not something that has a good use case for because, well, we don't need those binaries to use any solvers from Julia. So I don't plan on working on it unless there's funding attached to it, but of course we'd be happy to have someone donate a PR for FMI export.

**Comment by ChrisRackauckas** [comment]
There is some form of FMI support coming. More details coming at JuliaCon time.

**Comment by greenwoodms06** [comment]
@ChrisRackauckas howdy. I wanted to see about if there was an update as you mentioned regarding JuliaCon... Is FMI finally coming to Julia?!?!?! 😄

**Comment by ChrisRackauckas** [comment]
Yes, you can find some of it documented here: https://help.juliahub.com/JuliaSim/Tutorials/FMUs/

**Comment by qnikil7** [comment]
I was able to find the documentation in the link, would like to know if "FMUs" is available outside Julia Sim in any package.

**Comment by Sciemon** [comment]
Maybe [FMI.jl](https://github.com/ThummeTo/FMI.jl) can be used for your application.

**Comment by ThummeTo** [comment]
[FMI.jl](https://github.com/ThummeTo/FMI.jl) is open source, import/simulation of FMI2 is very robust (we are doing FMI cross checks). You can use the full DifferentialEquations.jl solver suite to simulate challenging FMUs. Even FMU export is possible, see [FMIExport.jl](https://github.com/ThummeTo/FMIExport.jl). Support for FMI3 is comming soon. 

However, I don't know if there is already a MTK-Interface available somewhere.
