### ISSUE TITLE
Can't register function from Interpolations (MWE)

### ISSUE THREAD

**Issue by elbert5770** [SciML/ModelingToolkit.jl#1354]
This is for a forcing function to a model, which is based on measurements.  I'm open to using an alternative to Interpolations.jl.

```
using ModelingToolkit
using Interpolations


Tdata = collect(0:5)
Mdata = [0.0, 0.03, 0.04, 0.02, 0.01, 0.005]

interp_linear = LinearInterpolation(Tdata, Mdata)

@variables t
@register interp_linear(t) #LoadError: cannot define function interp_linear; it already has a value
```

**Comment by ChrisRackauckas** [comment]
They don't need to be registered. They have registration dispatches in the library.

**Comment by elbert5770** [comment]
Thank you Chris.  Could you advise how to make the forcing function work without registering it?  MWE below:

```
using ModelingToolkit
using Interpolations
using DifferentialEquations


Tdata = collect(0:5)
Mdata = [0.0, 0.03, 0.04, 0.02, 0.01, 0.005]

interp_linear = LinearInterpolation(Tdata, Mdata)
@parameters alpha,beta
@variables t, x(t), y(t)

D = Differential(t)
@named diff_eq_test= ODESystem([f ~ interp_linear(t)
                                D(x) ~ f - alpha*x
                                D(y) ~ alpha*x - beta*y])
prob = ODEProblem(structural_simplify(diff_eq_test), [x => 0.0,y => 0.0], (0.0,5.0), [alpha => 1.0,beta => 10.0])


sol = solve(prob)
```
ERROR: LoadError: TypeError: non-boolean (Num) used in boolean context
Stacktrace:
 [1] inbounds_index
   @ C:\Users\elbertdl\.julia\packages\Interpolations\3gTQB\src\extrapolation\extrapolation.jl:111 [inlined]
 [2] inbounds_position
   @ C:\Users\elbertdl\.julia\packages\Interpolations\3gTQB\src\extrapolation\extrapolation.jl:102 [inlined]
 [3] (::Interpolations.Extrapolation{Float64, 1, Interpolations.GriddedInterpolation{Float64, 1, Float64, Gridded{Linear{Throw{OnGrid}}}, Tuple{Vector{Int64}}}, Gridded{Linear{Throw{OnGrid}}}, Throw{Nothing}})(x::Num)
   @ Interpolations C:\Users\elbertdl\.julia\packages\Interpolations\3gTQB\src\extrapolation\extrapolation.jl:48
 [4] top-level scope
   @ C:\Users\elbertdl\Documents\MATLAB\MTK_forcingfunction_MWE3.jl:17
 [5] eval
   @ .\boot.jl:360 [inlined]
 [6] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1094
in expression starting at C:\Users\elbertdl\Documents\MATLAB\MTK_forcingfunction_MWE3.jl:17

**Comment by ChrisRackauckas** [comment]
What version are you on?

**Comment by elbert5770** [comment]
Julia Version 1.6.4 (2021-11-19)
  [c52e3926] Atom v0.12.35
  [fbb218c0] BSON v0.3.4
  [6e4b80f9] BenchmarkTools v1.2.0
  [336ed68f] CSV v0.9.11
  [a93c6f00] DataFrames v1.2.2
  [82cc6244] DataInterpolations v3.7.0
  [aae7a2af] DiffEqFlux v1.44.0
  [41bf760c] DiffEqSensitivity v6.60.3
  [0c46a032] DifferentialEquations v6.20.0
  [587475ba] Flux v0.12.8
  [f6369f11] ForwardDiff v0.10.23
  [a75be94c] GalacticOptim v2.2.0
  [a98d9a8b] Interpolations v0.13.4
  [e5e0dc1b] Juno v0.8.4
  [23992714] MAT v0.10.1
  [961ee093] ModelingToolkit v7.1.2
  [2774e3e8] NLsolve v4.5.1
  [429524aa] Optim v1.5.0
  [1dea7af3] OrdinaryDiffEq v5.67.0
  [91a5bcdd] Plots v1.23.6
  [0c5d862f] Symbolics v4.1.0
  [e88e6eb3] Zygote v0.6.30

**Comment by elbert5770** [comment]
Same error message with Julia 1.6.3.

FYI, DataInterpolations has a similar but distinct issue:

```
using ModelingToolkit
using DataInterpolations
using DifferentialEquations
using Plots

gr()


Tdata = collect(0.0:5.0)
Mdata = [0.0, 0.03, 0.04, 0.02, 0.01, 0.005]

interp_linear = LinearInterpolation(Mdata, Tdata)
@show interp_linear(2.5)
@parameters alpha,beta
@variables t, x(t), y(t),f(t)
D = Differential(t)
@named diff_eq_test= ODESystem([f ~ interp_linear(t)
                                D(x) ~ f - alpha*x
                                D(y) ~ alpha*x - beta*y])
prob = ODEProblem(structural_simplify(diff_eq_test), [x => 0.0,y => 0.0], (0.0,5.0), [alpha => 1.0,beta => 10.0])


sol = solve(prob)
display(plots(sol))
```
ERROR: LoadError: MethodError: no method matching -(::Term{Any, Nothing}, ::Term{Real, Base.ImmutableDict{DataType, Any}})
Closest candidates are:
  -(::VectorizationBase.CartesianVIndex, ::Any) at C:\Users\elbertdl\.julia\packages\VectorizationBase\xHOp9\src\cartesianvindex.jl:58
  -(::Term, ::Symbolics.ComplexTerm) at C:\Users\elbertdl\.julia\packages\SymbolicUtils\fgHzN\src\methods.jl:50
  -(::Term, ::Num) at C:\Users\elbertdl\.julia\packages\SymbolicUtils\fgHzN\src\methods.jl:50
  ...
Stacktrace:
 [1] initialize_system_structure(sys::ODESystem; quick_cancel::Bool)
   @ ModelingToolkit.SystemStructures C:\Users\elbertdl\.julia\packages\ModelingToolkit\frHXN\src\systems\systemstructure.jl:128
 [2] alias_elimination(sys::ODESystem)
   @ ModelingToolkit C:\Users\elbertdl\.julia\packages\ModelingToolkit\frHXN\src\systems\alias_elimination.jl:6
 [3] structural_simplify(sys::ODESystem; simplify::Bool)
   @ ModelingToolkit C:\Users\elbertdl\.julia\packages\ModelingToolkit\frHXN\src\systems\abstractsystem.jl:857
 [4] structural_simplify(sys::ODESystem)
   @ ModelingToolkit C:\Users\elbertdl\.julia\packages\ModelingToolkit\frHXN\src\systems\abstractsystem.jl:857
 [5] top-level scope
   @ C:\Users\elbertdl\Documents\MATLAB\MTK_forcingfunction_MWE3.jl:20
 [6] eval
   @ .\boot.jl:360 [inlined]
 [7] include_string(mapexpr::typeof(identity), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1116
in expression starting at C:\Users\elbertdl\Documents\MATLAB\MTK_forcingfunction_MWE3.jl:20

**Comment by ChrisRackauckas** [comment]
Interesting. @YingboMa could you guess why this wouldn't be caught by the existing definitions? This looks like it's the right version.

**Comment by thompsonmj** [comment]
Found a solution to the registration issue on [Discourse](https://discourse.julialang.org/t/register-multidimensional-interpolation-in-modelingtoolkit/80136)

Use `@register_symbolic` with an intermediate function rather than `@register`.

> @named diff_eq_test= ODESystem([f ~ interp_linear(t)

This fixes your MWE (also needed to add `f(t)` to list of variables):
```
using ModelingToolkit
using Interpolations
using DifferentialEquations


Tdata = collect(0:5)
Mdata = [0.0, 0.03, 0.04, 0.02, 0.01, 0.005]

interp_linear = LinearInterpolation(Tdata, Mdata)

@parameters alpha,beta
@variables t, x(t), y(t), f(t) #<

interp_linear_f(t) = interp_linear(t)
@register_symbolic interp_linear_f(t)

D = Differential(t)
@named diff_eq_test= ODESystem([f ~ interp_linear_f(t)
                                D(x) ~ f - alpha*x
                                D(y) ~ alpha*x - beta*y])
prob = ODEProblem(structural_simplify(diff_eq_test), [x => 0.0,y => 0.0], (0.0,5.0), [alpha => 1.0,beta => 10.0])

sol = solve(prob)
```

And for the [MOL data BC docs](http://methodoflines.sciml.ai/dev/tutorials/icbc_sampled/):
```
@parameters t x
A_x = 1.:2.:40.
A = [log10(x) for x in A_x]
itp = interpolate(A, BSpline(Cubic(Line(OnGrid()))))
sitp1 = scale(itp, A_x)
sitp1_f(x) = sitp1(x)
@register_symbolic sitp1_f(y)
```
(similarly for 2D)
