### ISSUE TITLE
Alias elimination internal error

### ISSUE THREAD

**Issue by tshort** [SciML/ModelingToolkit.jl#1358]
This model is two resistors in series.

```julia
@variables t
@variables v1(t) v2(t) i1(t) i2(t)
eq = [
    v1 ~ sin(2pi*t)
    v1 - v2 ~ i1
    v2 ~ i2
    i1 ~ i2
]
@named sys = ODESystem(eq)
sys = structural_simplify(sys)
```
The error is:
```
julia> sys = structural_simplify(sys)
ERROR: AssertionError: r == 0
Stacktrace:
 [1] exactdiv(a::Int64, b::Int64)
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\alias_elimination.jl:303
 [2] locally_structure_simplify!(adj_row::ModelingToolkit.CLILVector{Int64, Int64}, pivot_col::Int64, ag::ModelingToolkit.AliasGraph, may_eliminate::Bool)
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\alias_elimination.jl:347
 [3] (::ModelingToolkit.var"#lss!#576"{ModelingToolkit.AliasGraph, ModelingToolkit.SparseMatrixCLIL{Int64, Int64}, Vector{Int64}})(ei::Int64)
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\alias_elimination.jl:261
 [4] foreach(f::ModelingToolkit.var"#lss!#576"{ModelingToolkit.AliasGraph, ModelingToolkit.SparseMatrixCLIL{Int64, Int64}, Vector{Int64}}, itr::StepRange{Int64, Int64})
   @ Base .\abstractarray.jl:2141
 [5] alias_eliminate_graph!(graph::BipartiteGraph{Int64, Nothing}, varassoc::Vector{Int64}, mm_orig::ModelingToolkit.SparseMatrixCLIL{Int64, Int64})
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\alias_elimination.jl:265
 [6] alias_elimination(sys::ODESystem)
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\alias_elimination.jl:12
 [7] structural_simplify(sys::ODESystem; simplify::Bool)
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\abstractsystem.jl:857
 [8] structural_simplify(sys::ODESystem)
   @ ModelingToolkit C:\Users\xxxxxx\.julia\packages\ModelingToolkit\frHXN\src\systems\abstractsystem.jl:857
 [9] top-level scope
   @ REPL[53]:1
```

**Comment by ChrisRackauckas** [comment]
This isn't an ODE. There are no differential variables. Did you mean NonlinearSystem?

**Comment by tshort** [comment]
I realize it's not an ODE, but I'm hoping MTK can handle DAE's without differential variables. 

The MTK Standard Library has several examples of this type of system (like [this](https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/986436310582194c78d3200326e34bc770b2c2bb/test/analog.jl#L22-L33)).

**Comment by ChrisRackauckas** [comment]
Recognizing and handling this is something that hasn't been implemented.

**Comment by tshort** [comment]
Thanks, Chris. Currently, it's hard to know which non-D models will work with `ODESystem`/`structural_simplify` and which need a `NonlinearSystem`.

**Comment by ChrisRackauckas** [comment]
All

**Comment by tshort** [comment]
I also managed to get the same `AssertionError: r == 0` error after including a differential term:

```julia
using ModelingToolkit
const D = Differential(t)
@variables t
@variables v1(t) v2(t) i1(t) i2(t) i3(t)
eq = [
    v1 ~ sin(2pi*t)
    v1 - v2 ~ i1
    v2 ~ i2
    i1 ~ i2
    D(i3) ~ v1
]
@named sys = ODESystem(eq)
sys = structural_simplify(sys)
```

It's a DAE, but the source drives one differential term and another set of equations without differential terms.

**Comment by ChrisRackauckas** [comment]
Interesting, that's a separate issue then that currently hits the same error. If the error gets fixed the first case will still not work well though as it will fail in the solver.

**Comment by tshort** [comment]
The Rosenbrock23 solver works for at least some systems without differential terms. It's used in the tests for the ModelingToolkitStandardLibrary ([this example](https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/986436310582194c78d3200326e34bc770b2c2bb/test/analog.jl#L22-L33) has no differential terms).

**Comment by YingboMa** [comment]
Thanks for the bug report. This is an internal error in MTK that should never happen in principle.
