### ISSUE TITLE
How to avoid needing CSE?

### ISSUE THREAD

**Issue by dpsanders** [SciML/ModelingToolkit.jl#136]
```
julia> @variables x y;

julia> function f(x, y)
       a = x + y
       return a + a^2
       end
f (generic function with 1 method)

julia> f(x, y)
(x() + y()) + (x() + y()) ^ 2
```

How can we prevent `x + y` being expanded each time that the intermediate `a` is used? This seems to be a bad idea, since it's giving more work for compiler later to do CSE. (Is this already implemented somehow?)

**Comment by HarrisonGrodin** [comment]
This is not yet implemented, but it will be soon. Once [Terms.jl](https://github.com/HarrisonGrodin/Terms.jl) is finished, we will have an API for defining terms with custom behavior; then, the CSE-like behavior will happen inside the term itself, likely in the form of treating terms as DAGs and using "graph rewriting".

**Comment by asprionj** [comment]
What's the status here? There's been a lot going on w.r.t. components (i.e. connected systems); how do those developments relate to terms, CSE (and possibly automatic calculation of those intermediate values from the solution)?

**Comment by ChrisRackauckas** [comment]
The component system makes it so there's a lot of calculations that are automatically reused, but not within a single expression. This is still something that could exist, but it's not the biggest deal in the grand scheme of things.

**Comment by ChrisRackauckas** [comment]
CSE is a build_function Symbolics.jl thing now, and I wouldn't worry about it on the model building side since it rejiggers the equations into an optimized form.
