### ISSUE TITLE
Tearing partitioning doesn't consider solvability

### ISSUE THREAD

**Issue by Keno** [SciML/ModelingToolkit.jl#1362]
(I may have messed up the example, below, but this is here mostly for discussion - I may be wrong about the issue also).

I believe there is an issue with the way that the current tearing/partitioning code approaches solvability.
As the simplest possible example, consider a system like:

```
@parameters t
@variables x(t) y(t) z(t)
D = Differential(t)
eqs = [
               D(z) ~ y
               0 ~ y^2 - x
               0 ~ x^2 - z
       ]
ODESystem(eqs, t)
```

Over the reals, this has an analytic solution of `z = 4x^(5/4)/5`. MTK turns this into something like:
```
function f!(u, z)
    x = nlsolve(x->x^2 - z)
    y = nlsolve(x->y^2 - x)
    u[] = y
end
```

The issue arises because MTK has torn the non-linear solve for `x`, allowing it to potentially chose the negative branch for `x`, which of course will cause the second `nlsolve` to always fail to converge. This is of course the most trivial example, but in general, you can't just arbitrarily tear nlsolves like that.

In fact, we do already have the notion of solvability that determines whether we can rewrite an equation involving `x` to solve for `x`. The issue is that in the absence of algebraic loops, we don't actually take solvability into account in tearing.

I believe the correct solution is to separate the partitioning from the tearing code. Once tearing has determined a matching, we need to rerun an appropriate graph algorithm to determine what the solvable components are.

**Comment by ChrisRackauckas** [comment]
@YingboMa was this handled?

**Comment by YingboMa** [comment]
MTK doesn't tear nonlinear equations and ODAEProblem is removed so it's not a problem. It might be a problem when we add inlined nonlinear solves. Hitting branch cuts is probably extremely unlikely during integration. We just need to be careful when solving for consistent initializations.
