### ISSUE TITLE
Access to subsystems and variables of these systems

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/ModelingToolkit.jl#1366]
If I use the RC example from MTK:
```julia
rc_model = let
    @named resistor = Resistor(R=1)
    @named capacitor = Capacitor(C=1)
    @named source = ConstantVoltage(V=1)
    @named ground = Ground()

    rc_eqs = [
            connect(source.p, resistor.p)
            connect(resistor.n, capacitor.p)
            connect(capacitor.n, source.n)
            connect(capacitor.n, ground.g)
            ]

    @named rc_model = ODESystem(rc_eqs, t)
    compose(rc_model, [resistor, capacitor, source, ground])
end
```
I can access the subsystems directly:
```julia
julia> propertynames(rc_model)
18-element Vector{Symbol}:
 :resistor
 :capacitor
 :source
 :ground
 :source₊p₊i
 :resistor₊p₊i
 :source₊p₊v
 :resistor₊p₊v
 :capacitor₊p₊i
 :resistor₊n₊i
 :resistor₊n₊v
 :capacitor₊p₊v
 :capacitor₊n₊i
 :source₊n₊i
 :capacitor₊n₊v
 :source₊n₊v
 :ground₊g₊i
 :ground₊g₊v
```
However, if I apply `rc_model_simp = structural_simplify(rc_model)` I can no longer access the subsystems (`:resistor, :capacitor, :source, :ground`):
```julia
julia> propertynames(rc_model_simp)
23-element Vector{Symbol}:
 :capacitor₊v
 :resistor₊i
 :resistor₊R
 :capacitor₊C
 :source₊V
 :capacitor₊i
 :source₊i
 :source₊p₊i
 :source₊n₊i
 :capacitor₊p₊v
 :ground₊g₊i
 :capacitor₊n₊i
 :resistor₊n₊v
 :source₊n₊v
 :capacitor₊n₊v
 :ground₊g₊v
 :source₊v
 :resistor₊n₊i
 :resistor₊v
 :resistor₊p₊v
 :resistor₊p₊i
 :capacitor₊p₊i
 :source₊p₊v
```
So the structure changed I guess.

How can I access a specific variable?
In the documentation this is always done via a direct reference to the subsystems like:
```julia
u0 = [
      capacitor.v => 0.0
     ]
```
or 
```julia
sol[resistor.v]
```
However, apart from some test scripts I will not always have those around.
I find e.g. `rc_model_simp.capacitor₊v` odd because of  the unicode characters. 

So what is the indented way of accessing a variable?

**Comment by ChrisRackauckas** [comment]
`sol[resistor.v]` works.

**Comment by ValentinKaisermayer** [comment]
Maybe I didn't formulate my post correctly, but my question was how do I get the variable if I do not have the reference to `resistor` and only the simplified model anymore? Thx

**Comment by ChrisRackauckas** [comment]
```julia
@unpack rc_model_simp = resistor
sol[resistor.v]
```
should be fine?

**Comment by ValentinKaisermayer** [comment]
@ChrisRackauckas Sry, in advance I think this should have been a discourse post and not an issue.
So what I think happens, is that `rc_model` still has all the model structure (in it's field `systems`) and so I'm able to access for instance `rc_model.capacitor.p.i`.
However, after the `structural_simplify` this structure ist lost and the system no longer has it's structure (the field `systems` ist empty). All variables are now flattened out via their namespace i.e. `capacitor₊p₊i`, which has to be understood as one variable name. Am I correct?

At least for me, a section in the docs about name-spacing in general (what e.g.`@unpack`, `@nonamespace` does) would be helpful. For instance the [structural_simplify](https://mtk.sciml.ai/stable/basics/Composition/#Structural-Simplify) section is maybe too short.

It is not always clear why some things work:
`sol[@nonamespace rc_model_simp.capacitor₊v]` or `sol[capacitor.v]`
and others not:
`sol[rc_model.capacitor.v]`

**Comment by ChrisRackauckas** [comment]
`sol[rc_model.capacitor.v]` this doesn't work because that never works, even without structural simplify, because `rc_model` is not a variable.

**Comment by ChrisRackauckas** [comment]
@YingboMa could we just extend getproperty of a system for that to work?

**Comment by ValentinKaisermayer** [comment]
But it evaluates to a variable, which might not exist, if interpret the name-spacing correctly:
```julia
julia> rc_model.capacitor.v
rc_model₊capacitor₊v(t)
```
