### ISSUE TITLE
Unable to build torn function

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/ModelingToolkit.jl#1379]
Consider the following example:
```julia
using ModelingToolkit, DifferentialEquations

@variables t
function Plant(;name, x0=zeros(2))
    D = Differential(t)
    sts = @variables x1(t)=x0[1] x2(t)=x0[2] y(t) u(t)
    eqs= [
        D(x1) ~ x2
        D(x2) ~ -x1 - 0.5 * x2 + u
        y ~ 0.9 * x1 + x2
    ]
    ODESystem(eqs, t, sts, []; name)
end
@named plant_block = Plant()
@named sys = ODESystem([plant_block.u ~ sin(t)], systems=[plant_block])
```
If one would try to directly make an `ODAEProblem` out of it, one would get an error message:
> ERROR: LoadError: ArgumentError: SystemStructure is not yet initialized, please run `sys = initialize_system_structure(sys)` or `sys = alias_elimination(sys)`.

So one would try to do that:
```julia
sys = initialize_system_structure(sys)
julia> prob = ODAEProblem(sys, [], (0.0, 10.0))
ERROR: LoadError: KeyError: key 5 not found
Stacktrace:
 [1] getindex
   @ .\dict.jl:482 [inlined]
 [2] torn_system_jacobian_sparsity(sys::ODESystem)
```
```julia
sys = alias_elimination(sys)
julia> prob = ODAEProblem(sys, [], (0.0, 10.0))
ERROR: LoadError: KeyError: key 5 not found
Stacktrace:
 [1] getindex
   @ .\dict.jl:482 [inlined]
 [2] torn_system_jacobian_sparsity(sys::ODESystem)
```
However, there seems to be a problem.

`structural_simplify` works fine:
```julia
sys = structural_simplify(sys)
prob = ODAEProblem(sys, [], (0.0, 10.0))
sol = solve(prob, Tsit5())
```

**Comment by YingboMa** [comment]
You always need to call `structural_simplify` before `ODAEProblem`

**Comment by baggepinnen** [comment]
Maybe the problem constructor should make that call automatically?

**Comment by ChrisRackauckas** [comment]
No, calling structural simplify a second time can change the system. It should just error if simplification has not been done and give an informative message that ss is required.

**Comment by ChrisRackauckas** [comment]
ODAEProblem removed.
