### ISSUE TITLE
Catlab.Formula as a potential application of MT

### ISSUE THREAD

**Issue by jpfairbanks** [SciML/ModelingToolkit.jl#138]
In the package Catlab.jl, @epatters rolled his own Formula type to do some modeling. Definition: https://github.com/epatters/Catlab.jl/blob/d5aed81ec6966beecbeb282d3202cbb8d9367c83/src/algebra/Tree.jl#L40. This might be another use case for "all symbolic math in Julia runs through one place" would be helpful. On SemanticModels we would like to combine the symbolic math of MT with the category theoretic properties of Catlab to talk about the relationships between categories built out of mathematical expressions. Even if the answer is for Catlab and MT to maintain different representations of formulas, we should be learning from one another.

**Comment by ChrisRackauckas** [comment]
Maybe the proper connection is Catlab to use SymbolicUtils like MT, and when kicking out ODEs to use MT? (not sure if it ever does ODEs/SDEs/ etc.)

**Comment by jpfairbanks** [comment]
Yeah I think at this point we want to generate symbolic expressions compatible with symbolicutils and then use that for simplification by rewriting. I’m concerned about how symbolicutils is treating types and if that is compatible with the GAT approach. GATs use dependent types to check that expressions are well formed, and that is an important feature for us. When you have rewriting rules in a GAT, the applicability of a rule depends on information in the dependent type. For example, consider the case of matrices where the type encodes the dimensions so an n by m matrix is of type `Matrix(n,m)` you can have rewrite rules that require that the dimensions match up. Like `oplus(A,B) * oplus(C,D) == oplus(A*C, B*D)` iff the dimensions match up. Oplus in this context means direct sum aka concatenation of vector spaces. 

Can SymbolicUtils handle that kind of rule?

**Comment by ChrisRackauckas** [comment]
Not sure, but that can be taken over to SymbolicUtils.jl
