### ISSUE TITLE
Continuous event / `affect` not working

### ISSUE THREAD

**Issue by tshort** [SciML/ModelingToolkit.jl#1386]
I'm trying to implement a simple sample and hold using events. The events are not triggering, or the update to `vmeasured` isn't working. In the solution, `vmeasured` is always zero.

```jl
using ModelingToolkit, OrdinaryDiffEq
const D = Differential(t)
@variables t

@variables vs(t) v(t) vmeasured(t)
eq = [
    vs ~ sin(2pi*t)
    D(v) ~ vs - v
    D(vmeasured) ~ 0.0
]
ev = sin(20pi*t) ~ 0.0 => vmeasured ~ v
@named sys = ODESystem(eq, continuous_events = ev)
sys = structural_simplify(sys)
prob = ODAEProblem(sys, zeros(2), (0.0, 5.0))
sol = solve(prob, Tsit5(), tstops = 0.05:0.05:5.0)
```
Ant tips on debugging this sort of model?

**Comment by ChrisRackauckas** [comment]
The generated problem doesn't have any events. @baggepinnen did you make sure to handle ODAEProblem, DAEProblem, and SDEProblem?

**Comment by baggepinnen** [comment]
No, the other problem constructors need support for the event generation.

While experimenting a bit with this problem, I get out of memory in some cases, the example below works as expected, but if I set the `tspan` to end at `5.0` instead, it doesn't, and if I use the commented `tstops`, I get the same problem. I wonder if there's an interaction between the condition function and the integrator trying to hit the same time points for other reason that causes it to take too many steps?

```julia
@variables t
Dt = Differential(t)

@variables vs(t)=0 v(t)=0 vmeasured(t)=0
eq = [
    vs ~ sin(2pi*t)
    Dt(v) ~ vs - v
    Dt(vmeasured) ~ 0.0
]
ev = [sin(20pi*t) ~ 0.0] => [vmeasured ~ v]
@named sys = ODESystem(eq, continuous_events = ev)
sys = structural_simplify(sys)
prob = ODEProblem(sys, [], (0.0, 5.1))
sol = solve(prob, Tsit5())#, tstops = 0.05:0.05:5.0)
plot(sol)

```
