### ISSUE TITLE
Add Github repository to package manager

### ISSUE THREAD

**Issue by vnikoofard** [SciML/ModelingToolkit.jl#1388]
Hi,
Adding the direct link of Github repositoty of ModelingToolkit to package manager by

`add https://github.com/SciML/ModelingToolkit.jl`

causes the following error. 

`(@v1.6) pkg> add https://github.com/SciML/ModelingToolkit.jl
    Updating git-repo `https://github.com/SciML/ModelingToolkit.jl`
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ModelingToolkit [961ee093]:
 ModelingToolkit [961ee093] log:
 ├─possible versions are: 8.0.0 or uninstalled
 ├─ModelingToolkit [961ee093] is fixed to version 8.0.0
 └─restricted to versions 6-7 by NeuralPDE [315f7962] — no versions left
   └─NeuralPDE [315f7962] log:
     ├─possible versions are: 4.0.1 or uninstalled
     └─NeuralPDE [315f7962] is fixed to version 4.0.1
`

The latest version of ModelingToolkit is 7.1.3 but it seems that the package manager is assuming that it's 8.0.0

**Comment by ChrisRackauckas** [comment]
Yes, don't use unreleased versions except for developing the package.
