### ISSUE TITLE
What is possible to do in an affect statement?

### ISSUE THREAD

**Issue by JKRT** [SciML/ModelingToolkit.jl#1395]
Hi! 

Disclaimer:
I think this is a documentation issue more so than an actual issue with ModelingToolkit. 

I have the following Julia program (Note automatically generated), and I have been looking into using the new Hybrid event features of MTK to simplify some things in my code generator.
Currently, I generate callbacks using the old way that is pretty much bolted them onto my models.
My first question is, what can I do using affect? I know I can change variables is there other things that are possible like for instance call a print function? Basically, what do I lose in flexibility compared to using callbacks?

My second question is: Is it possible to mix custom callbacks with the new high-level constructs of the modeling toolkit? 

Model below for reference:
 
```julia
using ModelingToolkit
using DiffEqBase
using DifferentialEquations

function BouncingBallRealsModel(tspan = (0.0, 1.0))
    @variables t        #= C:\Users\johti17\Projects\Programming\JuliaPackages\OM.jl\OMBackend.jl\src\CodeGeneration\MTK_CodeGeneration.jl:98 =#
    parameters = ModelingToolkit.@parameters((e, g)) #= C:\Users\johti17\Projects\Programming\JuliaPackages\OM.jl\OMBackend.jl\src\CodeGeneration\MTK_CodeGeneration.jl:99 =#
    vars = ModelingToolkit.@variables((h(t), v(t))) #= C:\Users\johti17\Projects\Programming\JuliaPackages\OM.jl\OMBackend.jl\src\CodeGeneration\MTK_CodeGeneration.jl:106 =#
    der = Differential(t)
    eqs = [der(h) ~ v, der(v) ~ -g]
    root_eqs = [h ~ 0]  # the event happens at the roof  h = 5
    affect   = [ () -> print("Hello") ] # What can I do here?
    nonLinearSystem = ModelingToolkit.ODESystem(
        eqs,
        t,
        vars,
        parameters,
        name = :($(Symbol("BouncingBallReals"))),
        continuous_events = root_eqs => affect,
    )
    pars = Dict(e => float(0.3), g => float(9.81))
    initialValues = [h => 1.0, v => 0.0]
    firstOrderSystem = ModelingToolkit.ode_order_lowering(nonLinearSystem)
    reducedSystem = firstOrderSystem
    local event_p = [0.3, 9.81]
    local discreteVars = collect(values(Dict([])))
    local event_vars = vcat(collect(values(Dict([h => 1.0, v => 0.0]))), discreteVars)
    local aux = Array{Array{Float64}}(undef, 2)
    aux[1] = event_p
    aux[2] = event_vars
    problem = ModelingToolkit.ODEProblem(
        reducedSystem,
        initialValues,
        tspan,
        pars,
        callback = BouncingBallRealsCallbackSet(aux),
    )
    return (problem, initialValues, reducedSystem, tspan, pars, vars)
end
begin
    saved_values_BouncingBallReals = SavedValues(Float64, Tuple{Float64,Array})
    function BouncingBallRealsCallbackSet(aux)
        local p = aux[1]
        local reals = aux[2]
        begin
            condition1 = ((x, t, integrator) -> x[1] - 0.0)
            affect1! = (integrator -> integrator.u[2] = -(p[1] * integrator.u[2]))
            cb1 = ContinuousCallback(
                condition1,
                affect1!,
                rootfind = true,
                save_positions = (true, true),
                affect_neg! = affect1!,
            )
        end
        begin
            savingFunction(u, t, integrator) =
                let
                    (t, deepcopy(integrator.p))
                end
            cb2 = SavingCallback(savingFunction, saved_values_BouncingBallReals)
        end
        return CallbackSet(cb1, cb2)
    end
end
(BouncingBallRealsModel_problem, _, _, _, _, _) = BouncingBallRealsModel()
function BouncingBallRealsSimulate(tspan)
    solve(BouncingBallRealsModel_problem, tspan = tspan)
end
function BouncingBallRealsSimulate(tspan = (0.0, 1.0); solver = Rodas5())
    solve(BouncingBallRealsModel_problem, tspan = tspan, solver)
end
```

Cheers,
John

**Comment by baggepinnen** [comment]
Hello John and thanks for the issue!

The `affect` equations must be on assignment form, e.g., `assigned_state ~ other + stuff`. It should support everything that you can represent symbolically and `build_function` can generate code for.
The form `affect   = [ () -> print("Hello") ]` is not supported at the moment, `affect` has to be an `Equation`.
This could potentially be extended to support arbitrary affect functions that take the integrator as argument. When the symbolic affect equation is supplied, the state order and the final name of states is not known, so I'm not sure how well it would work in practice, but it would allow you to print etc.

**Comment by JKRT** [comment]
> This could potentially be extended to support arbitrary affect functions that take the integrator as argument. When the symbolic affect equation is supplied, the state order and the final name of states is not known, so I'm not sure how well it would work in practice, but it would allow you to print etc.

Thanks for the reply and the clarification, so if I understood you correctly it is currently not possible to do arbitrary function calls (with side effects). 

How does it work when mixing custom callbacks with high-level callbacks, Is it possible to do or would you advise against it? (That is assigning callbacks to the system and the model but in separation)

**Comment by baggepinnen** [comment]
> so if I understood you correctly it is currently not possible to do arbitrary function calls (with side effects).

You might be able to hack it in using `@register`, but it's not something that is tested or explicitly supported at the moment.

> How does it work when mixing custom callbacks with high-level callbacks, Is it possible to do or would you advise against it? (That is assigning callbacks to the system and the model but in separation)

It should be possible to use them both at the same time, the constructor for `ODEProblem` looks like this (simplified to the relevant parts)


```julia
function DiffEqBase.ODEProblem{iip}(sys::AbstractODESystem,u0map,tspan,
                                    parammap=DiffEqBase.NullParameters(); callback=nothing, kwargs...) where iip
    has_difference = any(isdifferenceeq, equations(sys))
    f, u0, p = process_DEProblem(ODEFunction{iip}, sys, u0map, parammap; has_difference=has_difference, kwargs...)

    event_cb = generate_rootfinding_callback(sys; kwargs...)
    cb = merge_cb(cb, callback)
    ODEProblem{iip}(f, u0, tspan, p; callback=cb, kwargs...)
end

merge_cb(x, y) = CallbackSet(x, y)
```
so the user-supplied `callback` gets merged with the symbolic event callbacks into a `CallbackSet`. There is no explicit test for this, so if you do make use of this and have a small example that works (or doesn't), feel free to submit it as a PR or in this issue and we can add it as a test

**Comment by JKRT** [comment]
> > so if I understood you correctly it is currently not possible to do arbitrary function calls (with side effects).
> 
> You might be able to hack it in using `@register`, but it's not something that is tested or explicitly supported at the moment.
> 
> > How does it work when mixing custom callbacks with high-level callbacks, Is it possible to do or would you advise against it? (That is assigning callbacks to the system and the model but in separation)
> 
> It should be possible to use them both at the same time, the constructor for `ODEProblem` looks like this (simplified to the relevant parts)
> 
> ```julia
> function ODEProblem(sys::AbstractODESystem,u0map,tspan; callback=nothing)
>     f, u0, p = process_DEProblem(ODEFunction{iip}, sys, u0map)
> 
>     event_cb = generate_rootfinding_callback(sys; kwargs...)
>     cb = merge_cb(cb, callback)
>     ODEProblem{iip}(f, u0, tspan, p; callback=cb, kwargs...)
> end
> 
> merge_cb(x, y) = CallbackSet(x, y)
> ```
> 
> so the user-supplied `callback` gets merged with the symbolic event callbacks into a `CallbackSet`. There is no explicit test for this, so if you do make use of this and have a small example that works (or doesn't), feel free to submit it as a PR or in this issue and we can add it as a test

Great thanks for the clarifications Fredrik! 👍  I will make a PR and supply such a test
