### ISSUE TITLE
Broadcasting differential not allowed for array of size 1

### ISSUE THREAD

**Issue by JTaets** [SciML/ModelingToolkit.jl#1402]
I think the title is self explanatory.
You might argue that defining `y`  as a vector is pointless, but in my case I allow models of different sizes and I would hope that size 1 also works. 

``` julia
using ModelingToolkit
@variables t
D = Differential(t)
x,y = @variables x[1:2](t) y[1:1](t)
D.(x) # works
D.(y) # KeyError: key i not found
```

**Comment by baggepinnen** [comment]
THe same issue as https://github.com/JuliaSymbolics/Symbolics.jl/issues/448
Should be fixed by https://github.com/JuliaSymbolics/Symbolics.jl/pull/458
