### ISSUE TITLE
Passing default parameters is broken for vectors

### ISSUE THREAD

**Issue by JTaets** [SciML/ModelingToolkit.jl#1403]
In the following, parameters aren't correct.

``` julia 
@variables t
D = Differential(t)
xs = @variables x(t)=0
ps, = @parameters P[1:2]=0
@named sys = ODESystem([D(x) ~ -x + sum(P)], t, xs, ps)
prob = ODEProblem(sys,[],(0,1),[sys.P[1] => 1, sys.P[2] => 2])
println(prob.p) # wrong: [0, 0]

prob = ODEProblem(sys,[],(0,1),[sys.P => [1, 2]])
println(prob.p) # wrong: [0, 0]
```

Could it be related to here where u0map and parammap should be switched?
https://github.com/SciML/ModelingToolkit.jl/blob/80d4aad2347086d10bc71e30c3c20f5792d5d8c6/src/systems/diffeqs/abstractodesystem.jl#L547-L564

**Comment by baggepinnen** [comment]
That does indeed look flipped. Perhaps @pepijndevos knows?

**Comment by pepijndevos** [comment]
I think your problem is in the namespacing.
```
julia> ODEProblem(sys,[],(0,1),[@nonamespace sys.P[1] => 1, @nonamespace sys.P[2] => 2]).p
1-element Vector{Tuple{Pair{Num, Int64}, Pair{Num, Int64}}}:
 (P[1] => 1, P[2] => 2)

julia> ODEProblem(sys,[],(0,1),[P[1] => 1, P[2] => 2]).p
2-element Vector{Int64}:
 1
 2
```

**Comment by JTaets** [comment]
Thank you, this also works for me.

Perhaps an warning or error could be thrown if a parameter that isn't in the `sys` is used in the `parammap`? Because this seems a bit counterintuitive and I guess many more will make this mistake.
