### ISSUE TITLE
Inputs outputs in MTK

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#1411]
Not connected inputs are "time-dependent parameters", and connected inputs should be reduced. Outputs can always be reduced. Derivative of inputs should be reduced as well. E.g.
```julia
using ModelingToolkit
@variables t x(t) i(t) [input=true]
D = Differential(t)
eqs = [D(x) ~ D(i)]
@named sys = ODESystem(eqs)
sys = extend(ODESystem([i ~ sin(t)], name=:foo), sys)
```

**Comment by ChrisRackauckas** [comment]
@YingboMa was this handled?

**Comment by ChrisRackauckas** [comment]
@YingboMa comment if it wasn't, but I'm pretty sure it was.
