### ISSUE TITLE
Silent error in unlowered ODE

### ISSUE THREAD

**Issue by ctessum** [SciML/ModelingToolkit.jl#1417]
Hi,

I posted a question [here](https://discourse.julialang.org/t/modelingtoolkit-second-derivative-only-gives-first-derivative/70703) a while ago. The gist of it is that I was trying to do this:

``` julia
using ModelingToolkit
using DifferentialEquations
using Plots
using Unitful

@variables t [unit = u"s"] x(t) [unit = u"m"] v(t) [unit = u"m/s"]
@parameters g=-9.8 [unit = u"m/s^2"]
Dt = Differential(t)
Dt2 = Differential(t)^2

@named eqs = ODESystem([
	Dt2(x) ~ g,
])
prob = ODEProblem(structural_simplify(eqs), [x => 0.0], (0.0,10.0))
sol = solve(prob, saveat=1)

plot(sol)
```

which is just a standard high-school-physics falling ball problem, and I was getting the wrong answer. It was pointed out that to fix the problem I need to add `ode_order_lowering` and also another initial condition:

``` julia
prob = ODEProblem(structural_simplify(ode_order_lowering(eqs)), [x => 0.0, Dt(x) => 0.0], (0.0,10.0))
sol = solve(prob, saveat=1)
plot(sol)
```

That's fine, but I feel like there's an issue here, where this type of user error is going to be common (it's literally the first thing I did) but it currently fails silently and subtly, which could potentially cause a lot of wrong results for users.

Would it be possible to throw an error or a warning when there is a system of equations that includes higher-order derivatives but not the lower order derivatives that correspond to them?

**Comment by YingboMa** [comment]
Fixed by https://github.com/SciML/ModelingToolkit.jl/issues/1417
