### ISSUE TITLE
Akzo Nobel DAEProblem fails after recent MTK update 

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#1428]
This DAEProblem benchmark was running fine a few days ago. Now

ModelingToolkit.@parameters begin
      k₁=18.7
      k₂=0.58
      k₃=0.09
      k₄=0.42
      kbig=34.4
      kla=3.3
      ks=115.83
      po2=0.9
      hen=737
end

@variables begin
      t
      y₁(t)  = 0.444
      y₂(t)  = 0.00123
      y₃(t)  = 0.0
      y₄(t)  = 0.007
      y₅(t)  = 1.0
      y₆(t)  = 115.83*0.444*0.007 # ks*y₁*y₄
end

D = Differential(t)

r₁  = k₁ * (y₁^4.)*sqrt(abs(y₂))
r₂  = k₂ * y₃ * y₄
r₃  = k₂/kbig * y₁ * y₅
r₄  = k₃*y₁*(y₄^2)
r₅  = k₄*(y₆^2)*sqrt(abs(y₂))
fin = kla*(po2/hen-y₂)

eqs = [
      D(y₁) ~ -2. * r₁ + r₂ - r₃ - r₄
      D(y₂) ~ -0.5 * r₁ - r₄ - 0.5*r₅ + fin
      D(y₃) ~ r₁ - r₂ + r₃
      D(y₄) ~ -r₂ + r₃ - 2. * r₄
      D(y₅) ~ r₂ - r₃ + r₅
      0. ~ ks * y₁ * y₄ - y₆
]

ModelingToolkit.@named sys = ModelingToolkit.ODESystem(eqs)

tspan = (0.0, 180.0)
mmprob = ODEProblem(sys, [], tspan)
sol = solve(mmprob, Rodas4(),abstol=1/10^14,reltol=1/10^14)
odaeprob = ODAEProblem(structural_simplify(sys),[],tspan)
ode_ref_sol = solve(odaeprob,CVODE_BDF(),abstol=1/10^14,reltol=1/10^14);

du = mmprob.f(mmprob.u0,mmprob.p,0.0)
du0 = D.(states(sys)) .=> du
daeprob = DAEProblem(sys,du0,[],tspan)
ref_sol = solve(daeprob,IDA(),abstol=1/10^14,reltol=1/10^14);

probs = [mmprob,daeprob,odaeprob]
refs = [ref_sol,ref_sol,ode_ref_sol];

gives this error:

MethodError: no method matching SymbolicUtils.Code.Let(::Vector{SymbolicUtils.Code.Assignment}, ::SymbolicUtils.Code.SetArray, ::Bool)
Closest candidates are:
  SymbolicUtils.Code.Let(::Any, ::Any) at C:\Users\Denis\.julia\packages\SymbolicUtils\0KTj4\src\code.jl:196
  SymbolicUtils.Code.Let(::Vector{Union{SymbolicUtils.Code.Assignment, SymbolicUtils.Code.DestructuredArgs}}, ::Any) at C:\Users\Denis\.julia\packages\SymbolicUtils\0KTj4\src\code.jl:196

Stacktrace:
 [1] build_torn_function(sys::ODESystem; expression::Bool, jacobian_sparsity::Bool, checkbounds::Bool, max_inlining_size::Nothing, kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit.StructuralTransformations C:\Users\Denis\.julia\packages\ModelingToolkit\E78WB\src\structural_transformation\codegen.jl:305
 [2] build_torn_function(sys::ODESystem)
   @ ModelingToolkit.StructuralTransformations C:\Users\Denis\.julia\packages\ModelingToolkit\E78WB\src\structural_transformation\codegen.jl:237
 [3] ODAEProblem{true}(sys::ODESystem, u0map::Vector{Any}, tspan::Tuple{Float64, Float64}, parammap::SciMLBase.NullParameters; callback::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit.StructuralTransformations C:\Users\Denis\.julia\packages\ModelingToolkit\E78WB\src\structural_transformation\codegen.jl:486
 [4] ODAEProblem{true}(sys::ODESystem, u0map::Vector{Any}, tspan::Tuple{Float64, Float64}, parammap::SciMLBase.NullParameters) (repeats 2 times)
   @ ModelingToolkit.StructuralTransformations C:\Users\Denis\.julia\packages\ModelingToolkit\E78WB\src\structural_transformation\codegen.jl:486
 [5] ODAEProblem(::ODESystem, ::Vararg{Any}; kw::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit.StructuralTransformations C:\Users\Denis\.julia\packages\ModelingToolkit\E78WB\src\structural_transformation\codegen.jl:464
 [6] ODAEProblem(::ODESystem, ::Vararg{Any})
   @ ModelingToolkit.StructuralTransformations C:\Users\Denis\.julia\packages\ModelingToolkit\E78WB\src\structural_transformation\codegen.jl:464
 [7] top-level scope
   @ In[3]:1
 [8] eval
   @ .\boot.jl:373 [inlined]
 [9] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)
   @ Base .\loading.jl:1196

**Comment by YingboMa** [comment]
I cannot reproduce this. What version of MTK are you using?

**Comment by finmod** [comment]
MTK v8.3.1

**Comment by baggepinnen** [comment]
I had the same issue but it was resolved by updating Symbolics and SymbolicUtils to their latest versions

**Comment by finmod** [comment]
Updated to Symbolics v.4.3.0 and added SymbolicUtils v0.18.2 but same outcome

**Comment by finmod** [comment]
SOLVED! by bumping up to SymbolicUtils#master.

**Comment by finmod** [comment]
@baggepinnen A subsidiary question: I notice that you have introduced a nice `Dₜ = Differential(t)` notation. Do you have a solution for text subscripts in variable names e.g. $y_d$ where the subscript is text? I cannot find any example of this notation in MTK Julia code.
