### ISSUE TITLE
Reaction Network DSL in modeling toolkit / new equation types

### ISSUE THREAD

**Issue by jpfairbanks** [SciML/ModelingToolkit.jl#143]
I was thinking about how one would express the reaction network DSL from DiffEqBiological in modeling toolkit, and you would need some additional operators like the arrow to make it work.

For example:
```julia
@reaction begin
c1, A+B -> C
c2, C     -> D + E
c3, E     -> A
end, c1, c2, c3
```

would make sense in ModelingToolkit as:

```julia
@variables A, B, C, D, E, c1, c2, c3
reaction = [
    C ~ c1(A+B),
    D+E ~ c2(C),
    A ~ c3(A)]
```
or 
```julia
@variables A, B, C, D, E, c1, c2, c3
reaction = [
     C ~ A+B,
     D+E ~ C,
     A ~ E]
parameters = [c1, c2, c3]
```

But chemists would find it more natural to write them out with the reaction DSL because it uses the `reagents -> products` notation they are used to from textbooks.

Would it make sense to add new types of equations that use different operators like the `->`?

**Comment by ChrisRackauckas** [comment]
Indeed, this has been planned from the start, but no one has had the gusto to really finish it. A prototype is here: https://github.com/AleMorales/ReactionDSL.jl .

Reactions do need to be represented at a high level since they aren't an ODE/SDE/Gillespie equation, and instead contain more information than that. They have a transformation into each of them. Equality misses the directionality, as well as the reaction rates and the thing I am still not sure about is what to do with the function forms (how to say it's Michaelis-Menton?).

I really want to get this done soon though, since the sooner DiffEqBiological is on ModelingToolkit, the sooner we can support just one compilation process.

**Comment by jlumpe** [comment]
Are you looking for pretty much just a direct translation of this package into ModelingToolkit?

**Comment by ChrisRackauckas** [comment]
A direct translation, not really. Moreso we would like to be able to represent the primitives of a reaction network as some struct in the language, have a ReactionNetworkSystem type, and allow that to transform into ODEs/SDEs/etc.

**Comment by jlumpe** [comment]
Ok, sounds like something I might be interested in taking a shot at. Would this be as a new package or a restructuring of DiffEqBiological itself?

**Comment by ChrisRackauckas** [comment]
What we need is arrow primatives and a ReactionSystem struct here. Then, all of the compilation and transformation steps. Then we make DiffEqBiological's macro lower to this form instead of SymEngine.

**Comment by jpfairbanks** [comment]
Yeah, @ChrisRackauckas summarized my perspective too. I think that modeling toolkit is/(should be) extensible enough for people to add new types of modeling domains but sharing in the common infrastructure of datastructures and term manipulation (rewriting).

For example we can do this: 

```julia
julia> @variables A, B, C, D, E, c1, c2, c3
(A(), B(), C(), D(), E(), c1(), c2(), c3())

julia> function →(a,b) return a=>b end
julia> Operation(→, [A + B, 2C]) |> dump
Operation
  op: → (function of type typeof(→))
  args: Array{Expression}((2,)) Expression[A() + B(), 2 * C()]
```

And then `Operation(→, [A + B, 2C])` is an Expression that we can translate into ODEs or SDE or Gillespie simulations when we add the fact that it is Michalis-Mentin dynamics with a well mixed chemical system. Maybe something like the following makes would already be possible? Especially 

```julia
struct MMReaction
   eqns::Vector{Pair{Expression, Expression}}
end

system = [(A+B) → C,
  C → (D+E),
  E → A]
pode = convert(ODEProblem, MMReaction(system))
psde = convert(SDEProblem, MMReaction(system))
gilles = convert(GillespeProblem, MMReaction(system))
```

**Comment by jpfairbanks** [comment]
It is really nice that the `Operation.op` is a function type ie, `Operation(+, A, B).op == typeof(+)`. It lets you write code that uses multiple dispatch to control the "interpretation" of an Expression tree. so you could add the arrow and then people could dispatch on it to say what to do with it.

**Comment by ChrisRackauckas** [comment]
Completed in https://github.com/SciML/ModelingToolkit.jl/pull/251
