### ISSUE TITLE
docs: Simulink listed among the equation-based modeling languages 

### ISSUE THREAD

**Issue by hurak** [SciML/ModelingToolkit.jl#1431]
In the documentation section on [Comparison of ModelingToolkit vs Equation-Based Modeling Languages](https://github.com/SciML/ModelingToolkit.jl/blob/master/docs/src/comparison.md), Simulink is listed among those languages. But Simulink is certainly not an equation-based modelling language. At least not it [the sense how the term equation-based modelling is used within Modelica community](https://modelica.org/publications/papers/1998-06-fritzson-para98LNCS1541-equationbasedmodelingandHighPerformance.pdf). In fact, it is a prominent example of the assignment-based, or block diagram-based, or signal flow graph-based, or – if you like – causal modeling. An antithesis of equation-based modelling. 

True, it is stated later within the paragraph. But the title of that page is misleading, I am afraid. [Simscape](https://www.mathworks.com/products/simscape.html), which is a kind of The Mathworks' own remake of Modelica, is equation-based, indeed. But still a lot of models that are out there are implemented in pure Simulink and do not follow the equation-based paradigm.

**Comment by hurak** [comment]
Now that I am thinking about it a bit more, I can perhaps guess where the motivation for using the term "equation-based modeling" comes from. In the end it all boils down to equations, doesn't it? This might be in contrast with, say, data-driven modeling when no equations are extracted. But let me explain that in some part of the modelling community (at least those who use Simulink, Simscape, and/or Modelica) that equation-based modeling is used in contrast with the so-called assignment-based modelling (and a few more names as given in my original post). As an example, consider the famous Ohm's law. In assignment-based modeling (with Simulink as the prominent example), we have to decide which variable plays the role of the input and which variable will be the output. That is, we have to decide if we implement the model as v = R*i, or i = v/R. In the graphical form this amounts to implementing the model as 
```
      +------------+                            +------------+
      |            |                            |            |
------+     R      +---->      or         ------+     1/R    +---->
      |            |                            |            |
      +------------+                            +------------+
```
It would not be quite practical to have two version of a model of a resistor, wouldn't it? That is why in pure Simulink there are no such physical libraries. It is only the alternative framework – the equation-based one – that offers a remedy. A prominent example is Modelica, but Spice (for electronics) is another one, which predates is by quite some time. Within Simulink you can nowadays use The Mathworks' own remake of Modelica called Simscape. In all these, Ohm's law would be modelled just as an equation (and not an assignment): i*R = v, or perhaps i*R == v if the single equality sign is so much (ab)used for assignment today. Perhaps this comment might explain why I objected against the usage of "equation-based modelling" when it comes to classical Simulink.

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/ModelingToolkit.jl/commit/a18de3038f555682b2cef01ca3fa3578208f5f59
