### ISSUE TITLE
Parameter Identifiability in ODE Models

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#1441]
@iliailmer and @ChrisRackauckas  Great addition to MTK tutorials on DAE-ODE systems. 

Just like to mention typos at "We will start by **illustrating** local identifiability" and "In this part **of the** tutorial". 

More interesting, can we have the same examples pushed to DataDrivenDiffEq `ContinuousDataDrivenProblem` to validate the complete workflow MTK, StructuralIdentifiability and model discovery from data using DataDrivenDiffEq. @AlCap23

**Comment by iliailmer** [comment]
@finmod Thank you for pointing out the typos, I created a pr #1443 to fix them! I will take a look at `ContinuousDataDrivenProblem` soon

**Comment by AlCap23** [comment]
Hey! Nice work! 

I've discussed this topic briefly with Chris. This could definitely improve the consistency of the `DataDrivenResult`. 
The `DataDrivenProblem` on its own is model agnostic, the method brings in the information. So if we could provide something to check the discovered model after the fitting, this would be really nice.  👍

**Comment by ChrisRackauckas** [comment]
Implemented as tutorials
