### ISSUE TITLE
Poor UTF input dictionary in the formulation of symbolic models 

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#1446]
Problem: the current dictionary of UTF inputs is extremely limited. Some Greek letters but not all, subscripts and superscripts limited to numbers and not letters. How to deal with  symbolic `πₑ` as different from numerical `pi`.   What you find in the examples appears to be the only dictionary available.

Suggestions:  1) have the standard UTF inputs in Julia https://docs.julialang.org/en/v1/manual/unicode-input/ recognized in MTK; 2) In the docs of MTK, have a better description of how to code symbolic models or define a model specific dictionary.

**Comment by ChrisRackauckas** [comment]
It just uses Julia's unicode support. All should work. Do you have any examples of valid unicode not working in MTK that works as a Julia variable?

**Comment by finmod** [comment]
There are many problems here. 
The first one is: using U+003C9 | ω | \omega | Greek Small Letter Omega from the standard Julialang manual as a variable of the model 

The output of ModelingToolkit.@named sfcinventory = ModelingToolkit.ODESystem(sfc) is correct:
![image](https://user-images.githubusercontent.com/12710434/152974880-5530e57f-2b40-408a-9f5a-eb24bc5c553c.png)

but then: equations(sfcinventory), parameters(sfcinventory), states(sfcinventory) do not reproduce any output.

Next, if you use: U+1D6DA | 𝛚 | \bfomega | Mathematical Bold Small Omega as a variable i.e. using bold for all variables to differentiate them from plain parameters, you get:
![image](https://user-images.githubusercontent.com/12710434/152976661-6dc3a658-e2e1-40f1-9d88-9a05c899d7d6.png)
and equations(sfcinventory), parameters(sfcinventory), states(sfcinventory) do not produce any output.

Finally, there is ηₑ=0.8 type notation that appears as n_e whereas η₁=0.8 appears correctly and  πₑ  perceived as numerical `pi` by ODEProblem.

**Comment by ChrisRackauckas** [comment]
That looks more like a Latexify.jl issue @korsbo

**Comment by korsbo** [comment]
I have not really kept up with the MTK development of late so I don't know what's going on with "equations(sfcinventory), parameters(sfcinventory), states(sfcinventory)" but the bottom image looks like a latexify issue. Could you provide an MWE that I can just run to reproduce the problem?

If you're calling lateixfy explicitly then I would imagine that the `convert_unicode = false` kwarg might help. That would punt the problem of dealing with unicode away from latexify and to whatever is actually rendering the latex code. That's not a particularly nice solution though, so an MWE would be good.

**Comment by finmod** [comment]
Here is the MWE. 

using DataDrivenDiffEq
using LinearAlgebra
using ModelingToolkit
using DifferentialEquations: solve
using NonlinearSolve
using OrdinaryDiffEq, Sundials
using Plots; gr()
using Plots.PlotMeasures
using Random
using Symbolics: scalarize
using Latexify
import ModelingToolkit: Interval, infimum, supremum

ModelingToolkit.@parameters begin
      η=500
      C=0.33
      b=0.135
      α=0.025
      β=0.02
      δ=0.05
      r=0.03
      Φ₀=0.0401
      Φ₁=6.41e-05
      k₀=-0.0065
      k₁=-5.0
      k₂=20
      ηu=0.2
      u_b=0.9
      m=1.2
      γ=0.4
      fd=0.1
      η₁=0.8
      η₂=0.2
      η₃=0.7
      ηₑ=0.8
      ξ₁=0.9 
      ξ₂=0.8
      ξ₃=-5.0 
      e₁=0.0
      g₂= α + β
end    

@variables begin
      t
      𝛚(t) = 0.9
      λ(t) = 0.90
      d₁(t) = 0.5
      y₂(t) = 0.9
      u(t) = 0.8
      y₁(t) = 0.9
      ν(t) = 3.0
      φ(t)
      ι(t)
      κ(t)
      πₑ(t)
      θ(t)
      g(t)  
end

Dₜ = Differential(t)
tmax = 25.0

domains = [t ∈ Interval(0.0, tmax),
           𝛚 ∈ Interval(0.0, 1.0),
           λ ∈ Interval(0.0, 1.0),
           d₁ ∈ Interval(0.0, 2.5),
           y₂ ∈ Interval(0.0, 2.5),
           u ∈ Interval(0.0, 2.5),
           y₁ ∈ Interval(0.0, 1.0)]

πₑ = y₂*(1 - 𝛚) - r*d₁
ν  = (1/C)*((1 -  𝛚)/b)^(-1/η)
φ  = -Φ₀ + Φ₁/((1 - λ)^2)
ι   = η₁*(m*𝛚 − 1) + η₂*(y₁ - y₂)
κ  = k₀ + exp(k₁+ k₂*πₑ) + ηu*(u - u_b)
θ  = ξ₁/((1 + ξ₂*exp(ξ₃*𝛚))^(1/η₂))
g  = (fd*(g₂ + η₃) + 1.0)*(y₂*g₂ +ηₑ*(y₁ - y₂)) + η₃*(y₁ - 1)

sfc = [
      Dₜ(𝛚)  ~ 𝛚*(η/(1 + η))*(φ - α - (1 - γ)*ι)
      Dₜ(λ)  ~ λ*(g - α - β)
      Dₜ(d₁) ~ d₁*(r - g - ι) + 𝛚 - θ
      Dₜ(y₂) ~ y₂*(α + β - g) + ηₑ*(y₁ - y₂)
      Dₜ(u)  ~ u*(g - κ/ν + δ)
      0. ~ y₁ - θ - κ/u
]
ModelingToolkit.@named sfcinventory = ModelingToolkit.ODESystem(sfc);

equations(sfcinventory)
parameters(sfcinventory)
states(sfcinventory)
reducedsfc = structural_simplify(sfcinventory)
equations(reducedsfc)

**Comment by ChrisRackauckas** [comment]
That's not the MWE. The MWE is probably just `latexify` on `𝛚`.

**Comment by finmod** [comment]
`latexify(𝛚)` effectively gives `\bfomega(t)`

**Comment by ChrisRackauckas** [comment]
Yup, and `\bfomega(t)` isn't valid Latex. It should be `{\bf \omega(t)}` or something. So Latexify needs some kind of mapping for unicode modifiers, but it's not related to MTK. MTK just uses Latexify to display the equations in notebooks.

**Comment by finmod** [comment]
@ChrisRackauckas . This is tough going. The latexify issue is solved by sticking to orthodox latex codes: \mathbf , \boldsymbol and not much else.
Then, in MTK, subscripts of variables can only be numerals and not letters with the exception of D_t which I found at @baggepinnen. This gives a correct formulation and restitution of the model:
![image](https://user-images.githubusercontent.com/12710434/153864345-50242e4b-6225-495b-b40a-34dbfbcfe4d7.png)

However when 
reducedsfc = structural_simplify(dae_index_lowering(sfcinventory))
equations(reducedsfc)
is applied the substitution of the zero order variable in the first order system does not take place.
![image](https://user-images.githubusercontent.com/12710434/153865102-c953fe1f-63c6-469c-874e-e7e97e098a25.png)

**Comment by ChrisRackauckas** [comment]
As mentioned, this is not an issue for ModelingToolkit.jl to fix though. Open an issue on Latexify.jl about UTF modifiers causing latexification issues. ModelingTookit.jl simply calls Latexify.jl on the symbols so it would need to be fixed there, and that's a discussion to have with @korsbo

**Comment by korsbo** [comment]
If I'm reading this correctly then I think there's more than one thing going on here. One is the `\bf` issue with Latexify. Pretty straight forward although a bit annoying since a fix would have to touch some pretty gnarly regex-based string substitution code. 

The other is that, reportedly, `equations(reducedsfc)` does not show equations that accurately reflect the simplification. That may or may not be a problem in the latexify recipes of MTK or Symbolics.jl but it would not be a problem coming from Latexify.jl itself.

I'd advise you to split up the problem into one issue per separate problem and provide some minimal working example. Probably only one line long for the latexify issue and probably a few lines and a 2-equation model to simplify for the other problem. As it is now, I'm sure that one of the problems will land on me but I don't know about the other one. Is it just that the displayed equations are wrong or are the simplified equations themselves wrong?

**Comment by ChrisRackauckas** [comment]
>The other is that, reportedly, equations(reducedsfc) does not show equations that accurately reflect the simplification. That may or may not be a problem in the latexify recipes of MTK or Symbolics.jl but it would not be a problem coming from Latexify.jl itself.

If that is the case, that's a separate issue. What I was seeing is just the issue:

> One is the \bf issue with Latexify. Pretty straight forward although a bit annoying since a fix would have to touch some pretty gnarly regex-based string substitution code.

which is what I was referencing. I don't know how to solve it, don't know how you will, but it's not a fix that should be in this repo if it can exist.

**Comment by finmod** [comment]
Ok. Got it. The first issue about UTF modifiers and latexification issues is now here: UTF modifiers causing latexification issues #206.

The second issue is that `equations()` of a structural_simplify model does not print the correct reduced form of the structural model although the mechanics under the hood appears to be correct by producing the correct number of variables. This is simple to demonstrate using the ChemicalAkzoNobel benchmark.
Compare the output of 
>ModelingToolkit.@named sys = ModelingToolkit.ODESystem(eqs) 
with the ouput of
>reduced=(structural_simplify(sys))
>equations(reduced)

The zero order variable has disappeared from the output but the first order variables remain unchanged.

But the benchmark solution produced by ODAEProblem is identical to the ODEProblem and the DAEProblem solutions.

Is this an MTK or a Latexify issue?

**Comment by ChrisRackauckas** [comment]
It didn't "disappear", the equation was removed and was changed to an observed.

**Comment by finmod** [comment]
Then `equation(reducedsystem)` should print the composition of the reducedsystem = ODAEsystem **with** the observed variables. This should be realtively easy after `sructural_simplify` as been applied to a DAE system.

**Comment by ChrisRackauckas** [comment]
No, it should not print out the composition because it shouldn't return the composition. The equations should always be the same size as the number of states.

**Comment by finmod** [comment]
The docs on DAE in MTK is far too cryptic. It should lean on standard presentation of DAE systems like https://en.wikipedia.org/wiki/Differential-algebraic_system_of_equations or https://modiasim.github.io/ModiaBase.jl/stable/index.html. In these presentations, there is a clear definitional distinction between DAE and ODE differentiable variables and purely algebraic variables that do not appear differentiated in the DAE system. 
Note that in this context `observed` is a misleading label for purely algebraic variables. The latter are mathematical identities/linear dependance invalidating the Jacobian matrix of the DAE system.  In the context of Automated Index Reduction, the missing definition is: `latent equations` and its connection to structural models (see https://arxiv.org/abs/2101.05702). This has a link to unobservable variables like expectations and the need to apply AIR to eliminate them.

Since the ambition and the contribution of `structural_simplify` is to automatically convert any DAE system into an ODE system that can be handled by DifferentialEquations, it should have a `restitution` or `result` output that documents how the variables have been classified with the nomenclature mentioned above. In any case, I maintain that the printed ODAE system submitted to the ODE solver should replace on the RHS any purely algebraic variables by their definition in terms of ODE state variables only. This is the reduced form of the structural model that avoids singularity of the Jacobian matrix.

**Comment by isaacsas** [comment]
@finmod when I tried to use the code that you pasted as plain text above it didn't run, and it seems to require an enormous number of packages that are not relevant for the problem you are concerned about (i.e. whether ModelingToolkit is correctly substituting into the original equations or not). 

It would be very helpful to everyone here in trying to understand if there is an actual bug beyond the Latex formatting if you could post a minimal example that actually runs to completion (minimal meaning it only loads a small set of packages, variables, parameters and equations to show the problem). Please paste your code using Github markdown so it is displayed as code and not text. This link shows how to use Github Markdown for "fenced code blocks":

https://enterprise.github.com/downloads/en/markdown-cheatsheet.pdf

Just replace the word "javascript" in their example with "julia". You can use Github's "preview" functionality to check you have correctly formatted the code in this way. If everything is working your code should look like:
```julia
using ModelingToolkit
@variables t, A(t)
eqs = [0 ~ 2*A]
```
 Before submitting your comment, please start a new Julia session and paste your code, ensuring it runs and reproduces the problem you are having. 

If you can take the time to cleanup your example it would make it much easier for the ModelingToolkit developers to run it themselves, and see if everything is working as expected (or if there is indeed a bug in the substitution as you seem to indicate).

**Comment by finmod** [comment]
@isaacsas Here is a MWE from [https://benchmarks.sciml.ai/html/DAE/ROBERDAE.html] where you can observe that `equations(simpsys)` displays the same RHS as `sys` without the substitution of y₃.

```julia
using ModelingToolkit, Sundials, Plots
using LinearAlgebra

@variables t y₁(t)=1.0 y₂(t)=0.0 y₃(t)=0.0
@parameters k₁=0.04 k₂=3e7 k₃=1e4
D = Differential(t)
eqs = [
  D(y₁) ~ -k₁*y₁ + k₃*y₂*y₃
  D(y₂) ~  k₁*y₁ - k₃*y₂*y₃ - k₂*y₂^2
  0 ~  y₁ + y₂ + y₃ - 1
]
@named sys = ODESystem(eqs)
simpsys = structural_simplify(sys)
equations(simpsys)
odaeprob = ODAEProblem(simpsys,[],(0.0,1e5))
ode_ref_sol = solve(odaeprob,CVODE_BDF(),abstol=1/10^14,reltol=1/10^14);
plot(ode_ref_sol, vars = [y₁,y₂,y₃])
```

**Comment by isaacsas** [comment]
@finmod I think one now needs to call `full_equations` to get the substituted equations. If you look at `generate_function(simpsys, states(simpsys), parameters(simpsys), expression=Val{false})`, which is used internally to generate the ODE rhs function, you'll see that the formula for y3 is indeed being used to determine it in terms of y1 and y2. It seems like this is just a matter of `equations` behavior being changed and moved into `full_equations`, and not any issue in the underlying system or codegen. I guess this hasn't yet been updated in the docs (it seems like a breaking change, so maybe this was added in version 8?).

@YingboMa is that right about `equations` vs. `full_equations` now?

**Comment by finmod** [comment]
MTK is v8.4.1. `full_equations` resolves the MWE above. Yet, it does not produce the correct reduced form ODE system in the case of the Automatic Index Reduction example. For the pendulum example in the docs, `full_equations` does not print the reduced form ODE system handled by ODAEProblem. In brief, after `structural_simplify` `equations` should print the ODE system and its dimensions fed into ODAEProblem.
```julia
using ModelingToolkit
using LinearAlgebra
using OrdinaryDiffEq
using Plots

function pendulum!(du, u, p, t)
    x, dx, y, dy, T = u
    g, L = p
    du[1] = dx
    du[2] = T*x
    du[3] = dy
    du[4] = T*y - g
    du[5] = x^2 + y^2 - L^2
    return nothing
end
pendulum_fun! = ODEFunction(pendulum!, mass_matrix=Diagonal([1,1,1,1,0]))
u0 = [1.0, 0, 0, 0, 0]
p = [9.8, 1]
tspan = (0, 10.0)
pendulum_prob = ODEProblem(pendulum_fun!, u0, tspan, p)
traced_sys = modelingtoolkitize(pendulum_prob)
pendulum_sys = structural_simplify(traced_sys)
full_equations(pendulum_sys)
```

**Comment by isaacsas** [comment]
What I'm getting from both `full_equations(pendulum_sys)` and `generate_function` on 8.4 looks like the same set of equations given in this section: https://mtk.sciml.ai/dev/mtkitize_tutorials/modelingtoolkitize_index_reduction/#Transforming-Higher-Order-DAEs-to-Index-1-DAEs. So it looks like lowering is occurring as part of `structural_simplify` now but (maybe?) wasn't at the time the tutorial was written. That should probably get updated (if correct). `ODAEProblem` appears to apply further modifications to the system in generating a `ODEProblem`. I'm not sure if there is any way to see the final equations it is actually solving in symbolic form.

In any case, it is probably better to move any further discrepancies you find between the doc examples and observed behavior to new issues. (Since this issue is closed and on a different topic -- Latexify's displaying of unicode.)

**Comment by finmod** [comment]
Transfered to #1459. Using VS Code, `full_ equations` is now printing the correct reduced form of DAE system. There is only one puzzling issue: at the end of each equation, there is a number `(1)` which is always 1 in every equation. Is this an equation number or the order of the equation?
