### ISSUE TITLE
Julia crashes when trying to evaluate ODEFunction of large MTK structure

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#1452]
Background:
I have a large biochemical reaction network model on which I am trying to run some benchmarks on. When I try to load it as a ReactioSystem and evaluate the problem function, Julai crashes. The cause seems that it is just very big. I would paste the model into code, but it is simply too big. Instead, I provide two files, in one (first mwe) I have saved it as an ODEFunction. The second (mwe) simply shows the original form. This is all done on ubuntu, using the latest version of Julia and packages.

MWE 1:
```julia
using Serialization, ModelingToolkit

odefun,u₀,p = deserialize("BCR_tobig_odefun.txt")
odefun(zeros(1122),u₀,p,0.0)
```

MWE 2:
```julia
using OrdinaryDiffEq
using ReactionNetworkImporters

model = loadrxnetwork(BNGNetwork(), "BCR.txt")
oprob = ODEProblem(model.rn, model.u₀, (0.,0.000001), model.p);

oprob.f(zeros(1122),model.u₀,model.p,0.0)
```

finally, for reference, this is the code with which I generated the odefun (used in mwe 1) from the original BCR.net file:
```julia
using ReactionNetworkImporters
using Serialization, ModelingToolkit
[mwe_catalyst_crash (copy).txt](https://github.com/SciML/ModelingToolkit.jl/files/8052081/mwe_catalyst_crash.copy.txt)

model = loadrxnetwork(BNGNetwork(), "BCR.txt")
odefun = ODEFunction(convert(ODESystem,model.rn));
[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8053206/BCR.txt)

[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8052068/BCR.txt)
[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8053218/BCR.txt)
[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8053221/BCR.txt)

[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8052069/BCR.txt)

p = model.p
[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8052090/BCR.txt)

u₀ = model.u₀;
[BCR.txt](https://github.com/SciML/ModelingToolkit.jl/files/8052078/BCR.txt)

serialize("BCR_tobig_odefun.txt",(odefun,u₀,p))
```
(usually, I would use .net and .jls for file extensions, but GitHub does not accept those)

I tried to attach the files, not sure if it worked, so I am trying to share them via dropbox as well: 
https://www.dropbox.com/sh/5fktars2o2u1q5n/AAA87lDCR9LkJl8faNDPLlcVa?dl=0

**Comment by TorkelE** [comment]
Finally, a reason that is is interesting is that other simulation software (e.g. Copasi) do not have any problems with this file.

**Comment by ChrisRackauckas** [comment]
@shashi could you look into the stackoverflow of the generated functions here?

**Comment by YingboMa** [comment]
MWE:
```julia
using OrdinaryDiffEq
using ReactionNetworkImporters
using Downloads
Downloads.download("https://github.com/SciML/ModelingToolkit.jl/files/8053206/BCR.txt", "BCR.txt")
model = loadrxnetwork(BNGNetwork(), "BCR.txt")
oprob = ODEProblem(model.rn, model.u₀, (0.,0.000001), model.p)

oprob.f(zeros(1122),model.u₀,model.p,0.0)
```

**Comment by YingboMa** [comment]
Oh, note that `model.u₀` and `model.p` are dictionaries.
