### ISSUE TITLE
Wrong initial conditions when creating the ODEProblem

### ISSUE THREAD

**Issue by ronisbr** [SciML/ModelingToolkit.jl#1458]
Hi!

I am still trying to propagate a quaternion using MTK. The current code (which seems pretty close to what I need) is:

```julia
using ModelingToolkit
using OrdinaryDiffEq
using ReferenceFrameRotations
using StaticArrays

function vectdquat(vq, w)
    q = Quaternion(vq)
    dq = dquat(q, w)
    return @SVector [dq[1], dq[2], dq[3], dq[4]]
end

@variables t vq[1:4](t)
@parameters w[1:3]
@register vectdquat(vq, w)
D = Differential(t)

eqs = [
    collect(D.(vq)[2:4] .~ vectdquat(vq, w)[2:4])...
    0 ~ 1 - vq[1] * vq[1] - vq[2] * vq[2] - vq[3] * vq[3] - vq[4] * vq[4]
]

@named att_prop = ODESystem(eqs)

prob = ODEProblem(
    att_prop,
    [vq[1] => 1.0, vq[2] => 0.0, vq[3] => 0.0, vq[4] => 0.0],
    (0.0, 100.0),
    [w[1] => 0.05, w[2] => 0.0, w[3] => 0.0]
)
```

However, here I hit a problem. When the `ODEProblem` is created, I get:

```julia
julia> prob = ODEProblem(
           att_prop,
           [vq[1] => 1.0, vq[2] => 0.0, vq[3] => 0.0, vq[4] => 0.0],
           (0.0, 100.0),
           [w[1] => 0.05, w[2] => 0.0, w[3] => 0.0]
       )
ODEProblem with uType Vector{Float64} and tType Float64. In-place: true
timespan: (0.0, 100.0)
u0: 4-element Vector{Float64}:
 0.0
 0.0
 0.0
 1.0
```

Notice that the initial condition `u0` has `u0[4] = 1.0` instead of `u0[1] = 1.0`. I can solve this system using `Rosenbrock23()` but it gives wrong answers since the initial condition is not correct. It seems that the system is rearranging the variables. Is it expected?

**Comment by YingboMa** [comment]
Well, did you check what is `states(att_prop)`? The ordering is not determined.

**Comment by ronisbr** [comment]
Hi @YingboMa !

Yes, I did, it is indeed in a different order. However, inside a callback, when I just have access to `u`, this can lead to some errors. In this particular case, `Quaternion(integrator.u)` will create a completely wrong quaternion. Is there any workaround?

**Comment by ronisbr** [comment]
The only thing I though was to obtain the indices before running the solver and pass it as a vector in the parameters. Is there any simpler way?

**Comment by ronisbr** [comment]
Thanks!
