### ISSUE TITLE
docs for `full_equations()`

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#1459]
There is no docs on the command `full_equations()`, its relation to `structural_simplify`, ODAE systems and differences with `equations()`.

**Comment by ChrisRackauckas** [comment]
@YingboMa take this one?

**Comment by finmod** [comment]
I confirm that `full_equations()` should be renamed as `reduced_form()` of a ODAE system. The defining characteristic of `reduced_form()` is that its Jacobian is invertible whereas the Jacobian of the structural model is not.

This brings up another issue: `observed` should be renamed `algebraic` or `definition` or `identity`. The main characteristic of `identity` is : it can be a zero or any order accounting identity or budget constraint but it can never be an SDE because the Jacobian of such DAE system is made singular by introducing the identity.

Finally, in DAE Index-reduction, there should be a definition of `latent` variable or `unobserved` as opposed to `measured` variables in StructuralIdentifiability. This is used to eliminate by differentiation variables that belong to the structural model but that are not measured or obvervable like expectations.

**Comment by ChrisRackauckas** [comment]
Part of https://github.com/SciML/ModelingToolkit.jl/issues/1822
