### ISSUE TITLE
Acausal Modelling Changes in MTK: Error on ground element (Electrical)

### ISSUE THREAD

**Issue by TS-CUBED** [SciML/ModelingToolkit.jl#1460]
I've been developing acausal models for circulation systems in MTK 7 and wanted to move to MTK 8. However my models don't seem to work anymore.

I could trace the error down to a change in the connector definition but then got stuck.

I then tested the tutorial example on https://mtk.sciml.ai/stable/tutorials/acausal_components/#acausal and found that they don't work either:

When defining the `@named ground = Ground()` I get the error:

`Parameters (0):ERROR: InvalidSystemException: The system is missing an equation for g₊i(t).`

**Comment by ChrisRackauckas** [comment]
@YingboMa can you look into this? Seems the equation balancer is triggering too early there?

**Comment by YingboMa** [comment]
That was just a printing bug. It should be fixed now.
