### ISSUE TITLE
Long compilation time some numbers + included examples

### ISSUE THREAD

**Issue by JKRT** [SciML/ModelingToolkit.jl#1461]
Hi, 

I would like to start by apologizing for a long text... 

I have the following models, note these models are automatically generated based on different parameters to the following Modelica model 
```
model Casc
  parameter Integer N = 10 "Order of the system"; // This parameter can be changed to increase the number of equations
  final parameter Real tau = T/N "Individual time constant";
  parameter Real T = 1 "System delay";
  Real x[N] (each start = 0, each fixed = true);
equation
  tau*der(x[1]) = 1 - x[1];
  for i in 2:N loop
    tau*der(x[i]) = x[i-1] - x[i];
  end for;
end Casc;
```

The corresponding MTK model for `N = 10 ` (Take note that this code is automatically generated) is: 
```
    using ModelingToolkit
    using DifferentialEquations
    begin
        begin
            saved_values_Casc10 = SavedValues(Float64, Tuple{Float64,Array})
            function Casc10CallbackSet(aux)
                local p = aux[1]
                local reals = aux[2]
                nothing
                return CallbackSet()
            end
        end
        function Casc10Model(tspan = (0.0, 1.0))
            @variables t            #= C:\Users\johti17\Projects\Programming\JuliaPackages\OM.jl\OMBackend.jl\src\CodeGeneration\MTK_CodeGeneration.jl:219 =#
            parameters = ModelingToolkit.@parameters((N, tau, T)) #= C:\Users\johti17\Projects\Programming\JuliaPackages\OM.jl\OMBackend.jl\src\CodeGeneration\MTK_CodeGeneration.jl:220 =#
            vars = ModelingToolkit.@variables((
                x_1(t),
                x_2(t),
                x_3(t),
                x_4(t),
                x_5(t),
                x_6(t),
                x_7(t),
                x_8(t),
                x_9(t),
                x_10(t),
            )) #= C:\Users\johti17\Projects\Programming\JuliaPackages\OM.jl\OMBackend.jl\src\CodeGeneration\MTK_CodeGeneration.jl:227 =#
            der = Differential(t)
            eqs = [
                der(x_1) ~ (1.0 - x_1) / tau,
                der(x_2) ~ (x_1 - x_2) / tau,
                der(x_3) ~ (x_2 - x_3) / tau,
                der(x_4) ~ (x_3 - x_4) / tau,
                der(x_5) ~ (x_4 - x_5) / tau,
                der(x_6) ~ (x_5 - x_6) / tau,
                der(x_7) ~ (x_6 - x_7) / tau,
                der(x_8) ~ (x_7 - x_8) / tau,
                der(x_9) ~ (x_8 - x_9) / tau,
                der(x_10) ~ (x_9 - x_10) / tau,
            ]
            nonLinearSystem = ModelingToolkit.ODESystem(
                eqs,
                t,
                vars,
                parameters,
                name = :($(Symbol("Casc10"))),
            )
            nonLinearSystem = ModelingToolkit.structural_simplify(nonLinearSystem)
            pars = Dict(N => float(10), tau => float(T / 10.0), T => float(1.0))
            initialValues = [
                x_1 => 0.0,
                x_2 => 0.0,
                x_3 => 0.0,
                x_4 => 0.0,
                x_5 => 0.0,
                x_6 => 0.0,
                x_7 => 0.0,
                x_8 => 0.0,
                x_9 => 0.0,
                x_10 => 0.0,
            ]
            firstOrderSystem = ModelingToolkit.ode_order_lowering(nonLinearSystem)
            reducedSystem = firstOrderSystem
            local event_p = [10, 0, 1.0]
            local discreteVars = collect(values(Dict([])))
            local event_vars = vcat(
                collect(
                    values(
                        Dict([
                            x_1 => 0.0,
                            x_2 => 0.0,
                            x_3 => 0.0,
                            x_4 => 0.0,
                            x_5 => 0.0,
                            x_6 => 0.0,
                            x_7 => 0.0,
                            x_8 => 0.0,
                            x_9 => 0.0,
                            x_10 => 0.0,
                        ]),
                    ),
                ),
                discreteVars,
            )
            local aux = Array{Array{Float64}}(undef, 2)
            aux[1] = event_p
            aux[2] = event_vars
            problem = ModelingToolkit.ODEProblem(
                reducedSystem,
                initialValues,
                tspan,
                pars,
                callback = Casc10CallbackSet(aux),
                cse = true,
            )
            return (problem, initialValues, reducedSystem, tspan, pars, vars)
        end
    end
    (Casc10Model_problem, _, _, _, _, _) = Casc10Model()
    function Casc10Simulate(tspan)
        return solve(Casc10Model_problem, tspan = tspan)
    end
    function Casc10Simulate(tspan = (0.0, 1.0); solver = Rodas5())
        return solve(Casc10Model_problem, tspan = tspan, solver)
    end
```

A sample current timings (On my laptop) MTK compilation + Simulation 
```
10:
  0.305501 seconds (477.56 k allocations: 27.560 MiB, 90.20% compilation time)
100:
  1.420337 seconds (1.56 M allocations: 80.551 MiB, 93.48% compilation time)

200: 
  3.867602 seconds (2.81 M allocations: 147.689 MiB, 93.44% compilation time)

400: (Up a lot from 200, memory is linear though)
 26.180517 seconds (5.33 M allocations: 305.115 MiB, 1.05% gc time, 97.28% compilation time)

800:
 99.175782 seconds (10.28 M allocations: 708.155 MiB, 0.21% gc time, 95.19% compilation time)
```

Sorry for a long post, I suppose a related issue is #1286 and #1285

Models are attached for reference. I uploaded them as txt files since the GitHub issue API do not seem to support .jl files 
[Casc10.txt](https://github.com/SciML/ModelingToolkit.jl/files/8102681/Casc10.txt)
[Casc100.txt](https://github.com/SciML/ModelingToolkit.jl/files/8102682/Casc100.txt)
[Casc200.txt](https://github.com/SciML/ModelingToolkit.jl/files/8102685/Casc200.txt)
[Casc400.txt](https://github.com/SciML/ModelingToolkit.jl/files/8102683/Casc400.txt)
[Casc800.txt](https://github.com/SciML/ModelingToolkit.jl/files/8102684/Casc800.txt)
[Casc1600.txt](https://github.com/SciML/ModelingToolkit.jl/files/8102687/Casc1600.txt)

It also takes quite some time just including the models, say that I have a model like the ones attached, how could I decompose the system better in order to reduce the compilation time overhead? 

I suppose splitting the declarations of variables into separate functions might do something?
See https://github.com/JuliaLang/julia/issues/19158 

But then the question is how could I go about splitting the declaration of variables and equations to built it up in parts? 

Say that I want to register 100 variables at the time using @variables

(Feel free to rework these Julia models so that they look more idiomatic and use them for benchmarking)

Cheers,
John 🚀

**Comment by ChrisRackauckas** [comment]
Thanks for the test case. @YingboMa has been looking into compile time growth (and expanding the use of symbolic arrays) and can use this as a test case. Julia v1.8 (unreleased) has numerous changes as well to accommodate some compile time fixes here.

**Comment by JKRT** [comment]
@ChrisRackauckas Thanks, 

I did some testing for Julia 1.8 this is the numbers I got. 

A small little script below, what this does is to compile the MTK model to machine code in memory (but it does not execute)

```
using Revise
import OMFrontend
import OMBackend

function runTest(filePath, modelName)
  @info "Trying to run $modelName through the pipeline"
  @info "Time of generating the AST"
  @time ast = OMFrontend.parseFile("./$(filePath)")
  @info "Time of generating SCode"
  @time scodeProgram = OMFrontend.translateToSCode(ast)
  @info "Time to flat DAE"
  @time (dae, cache) = OMFrontend.instantiateSCodeToDAE(modelName, scodeProgram)
  #  Base.dump(dae)
#  @info dae
  #= Translate and load it into our environment =#
  @info "Time of backend transformation"
  @time OMBackend.translate(dae; BackendMode = OMBackend.MTK_MODE)
  #= Simulate using the backend =#
#  @info "Time of simulation"
# Do not execute MTK yet
#  @time res = OMBackend.simulateModel(modelName, tspan = (0.0, 1.0));
  return 0
#  OMBackend.plot(res)
end

function writeCascToFile(path, model)
  runTest(path, model)
  OMBackend.writeModelToFile(model, "./CascModels/$(model).txt"; keepComments = false, formatFile = true, mode = OMBackend.MTK_MODE)
  println("Done writing to file")
end

println("Casc 10:")
writeCascToFile("./Models/Casc10.mo", "Casc10")
println("Casc 100:")
writeCascToFile("./Models/Casc100.mo", "Casc100")
println("Casc 200:")
writeCascToFile("./Models/Casc200.mo", "Casc200")
println("Casc 400:")
writeCascToFile("./Models/Casc400.mo", "Casc400")
println("Casc 800:")
writeCascToFile("./Models/Casc800.mo", "Casc800")
println("Casc 1600:")
writeCascToFile("./Models/Casc1600.mo", "Casc1600")
println("Casc 3200:")
writeCascToFile("./Models/Casc3200.mo", "Casc3200")
println("Casc 6400:")
writeCascToFile("./Models/Casc6400.mo", "Casc6400")
```
In this test I generate MTK models up to 6400 equations and variables for the example 

Total time for doing this (unscientific measurements using time once on my laptop)

Julia 1.7.1:
`159.302903 seconds (1.21 G allocations: 40.454 GiB, 8.14% gc time, 0.06% compilation time)`

Julia 1.9-DEV:
`140.535181 seconds (1.21 G allocations: 40.389 GiB, 6.74% gc time, 0.06% compilation time)
`

So I manage to compile the models a little a bit faster (roughly 13%) on Julia 1.9 dev. 
However, if I try to run and simulate the results are a bit different  

Julia 1.7.1:

```
Casc10:
[ Info: Time of simulation
  0.289369 seconds (455.41 k allocations: 26.606 MiB, 94.41% compilation time)

Casc100:
[ Info: Time of simulation
  1.539921 seconds (1.36 M allocations: 71.389 MiB, 93.58% compilation time)

Casc200:
[ Info: Time of simulation
  3.818414 seconds (2.40 M allocations: 127.000 MiB, 96.15% compilation time)

Casc400:
[ Info: Time of simulation
  17.513228 seconds (4.48 M allocations: 256.559 MiB, 96.44% compilation time)

Casc800:
  [ Info: Time of simulation
 92.846937 seconds (8.57 M allocations: 583.215 MiB, 0.16% gc time, 94.78% compilation time)
```

```
Julia 1.9-DEV:
Casc10:
[ Info: Time of simulation
  0.383642 seconds (803.45 k allocations: 42.876 MiB, 95.80% compilation time)
Casc100:
[ Info: Time of simulation
  2.853880 seconds (3.43 M allocations: 179.410 MiB, 5.79% gc time, 96.34% compilation time)
Casc200:
[ Info: Time of simulation
  6.223935 seconds (6.39 M allocations: 340.632 MiB, 95.81% compilation time)
Casc400:
[ Info: Time of simulation
 40.227598 seconds (29.13 M allocations: 1.704 GiB, 1.30% gc time, 98.32% compilation time)
[ Info: Time of simulation
  163.416695 seconds (50.70 M allocations: 3.303 GiB, 1.11% gc time, 94.46% compilation time)
```

It seems the MTK part of running the code in 1.9-DEV is a regression, however, the compilation time (from the Julia side seems to have improved in 1.9)

(I will include some more models to play around with, I think these really huge functions are one issue (So what I would need is some way of constructing a function gradually before creating a system), however, compiling them in Julia is not that bad in the first experiment so I will try to reduce them by smarter construction)

I also included some more Casc models here (Although for this test I did not go beyond 800)
[Casc3200.txt](https://github.com/SciML/ModelingToolkit.jl/files/8108213/Casc3200.txt)
[Casc6400.txt](https://github.com/SciML/ModelingToolkit.jl/files/8108214/Casc6400.txt)

Cheers,
John

**Comment by JKRT** [comment]
Still, issues with growing compilation although far from as severe as before. 
Some new models are included below (as .txt files) from 10 to 1600. 
[Casc10Experimental.txt](https://github.com/SciML/ModelingToolkit.jl/files/8109797/Casc10Experimental.txt)
[Casc100Experimental.txt](https://github.com/SciML/ModelingToolkit.jl/files/8109804/Casc100Experimental.txt)
[Casc200Experimental.txt](https://github.com/SciML/ModelingToolkit.jl/files/8109805/Casc200Experimental.txt)
[Casc400Experimental.txt](https://github.com/SciML/ModelingToolkit.jl/files/8109808/Casc400Experimental.txt)
[Casc800Experimental.txt](https://github.com/SciML/ModelingToolkit.jl/files/8109809/Casc800Experimental.txt)
[Casc1600Experimental.txt](https://github.com/SciML/ModelingToolkit.jl/files/8109811/Casc1600Experimental.txt)

**Comment by ChrisRackauckas** [comment]
JuliaSimCompiler is the answer.
