### ISSUE TITLE
Invalid redefinition of constant lambda or other variable name

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#1466]
In my attempt to implement a change of variable to keep a variable in the interval [0, 1], the change of variable `lambda` to `tan(lambda)` and back is creating an error that I cannot debug.
```julia
 using LinearAlgebra
using ModelingToolkit
using OrdinaryDiffEq, Sundials
using Plots; gr()
using Random


ModelingToolkit.@parameters begin
      
      η=500
      𝛎=3.          #C=0.33
      b=0.135
      α=0.025
      β=0.02
      δ=0.05
      r=0.03
  
      ϕ₀=0.0401
      ϕ₁=6.41e-05
  
      k₀=-0.0065
      k₁=-5.0
      k₂=20
      ηᵤ=0.2
      u_b=0.9 
  
      m=1.2
      γ=0.4
      f_d=0.1
      
      η₁=0.8
      η₂=0.2
      η₃=0.7
      ηₑ=0.8 
      
      θ₀=0.03
      θ₁=0.9
      θ₂=0.8 
      θ₃=1.0
      e₁=0.0
      𝐠ₑ= α + β
end    

@variables begin
      t
      omega(t) = 0.9
      ln𝛚(t) = 
      lambda(t) = 0.90
      tn𝛌(t)= 
      𝐝(t) = 0.5
      𝐲ₑ(t) = 0.9
      𝐮(t) = 0.8
      𝐲𝒹(t) = 0.9
      
      #𝛎(t) = 3.0
      phillips(t)
      inflation(t)
      investment(t)                     # 𝛋(t) in paper
      𝛑ₑ(t)
      consumption(t) 
      𝐠(t)  
end

Dₜ = Differential(t)
tmax = 25.0

# Behavioural equations

ln𝛚 = (t, omega)  ->                   log(omega)
tn𝛌 = (t, lambda)  ->                  tan((lambda - 0.5)*pi)
omega = (t, ln𝛚) ->                    exp(ln𝛚)
lambda = (t, tn𝛌) ->                   atan((tn𝛌/pi)+0.5)
𝛑ₑ = (t, omega, 𝐲ₑ, 𝐝) ->              𝐲ₑ*(1 - omega) - r*𝐝
#𝛎  = (t, 𝛚) ->                      (((1 -  𝛚)/b)^(-1/η))/C
phillips = (t, lambda) ->              -ϕ₀ + ϕ₁/((1 - lambda)^2)
inflation = (t, omega, 𝐲𝒹, 𝐲ₑ) ->      η₁*(m*omega − 1) + η₂*(𝐲𝒹 - 𝐲ₑ)
investment = (t, 𝛑ₑ, 𝐮) ->             k₀ + exp(k₁+ k₂*𝛑ₑ(t, omega, 𝐲ₑ, 𝐝)) + ηᵤ*(𝐮 - u_b)
consumption  = (t, omega) ->           θ₁/(1 + exp(-omega))  
𝐠  = (t, 𝐲𝒹, 𝐲ₑ) ->                    (f_d*(𝐠ₑ + η₃) + 1.0)*(𝐲ₑ*𝐠ₑ +ηₑ*(𝐲𝒹 - 𝐲ₑ)) + η₃*(𝐲𝒹 - 1)

sfcsys = [
      Dₜ(ln𝛚)  ~ (η/(1 + η))*(phillips(t,lambda) - α - (1 - γ)*inflation(t,omega, 𝐲𝒹, 𝐲ₑ))
      Dₜ(tn𝛌)  ~ (1 + tn𝛌^2)*pi*lambda(t,tn𝛌)*(𝐠(t, 𝐲𝒹, 𝐲ₑ) - α - β)
      Dₜ(𝐝) ~ 𝐝*(r - 𝐠(t, 𝐲𝒹, 𝐲ₑ) - inflation(t, omega, 𝐲𝒹, 𝐲ₑ)) + omega(t, ln𝛚) - consumption(t, omega)
      Dₜ(𝐲ₑ) ~ 𝐲ₑ*(𝐠ₑ - 𝐠(t, 𝐲𝒹, 𝐲ₑ)) + ηₑ*(𝐲𝒹 - 𝐲ₑ)
      Dₜ(𝐮)  ~ 𝐮*(𝐠(t, 𝐲𝒹, 𝐲ₑ) - investment(t, 𝛑ₑ, 𝐮)/𝛎 + δ)
      0. ~ 𝐲𝒹 - consumption(t, omega) - investment(t, 𝛑ₑ, 𝐮)/𝐮
]
ModelingToolkit.@named structuralDAE = ModelingToolkit.ODESystem(sfcsys)
```
 invalid redefinition of constant lambda

Stacktrace:

  [1] top-level scope

    @ c:\Users\Denis\dev\DataDrivenDiffEq.jl-master\General SFC modeldev.ipynb:72

  [2] eval

    @ .\boot.jl:373 [inlined]

  [3] include_string(mapexpr::typeof(REPL.softscope), mod::Module, code::String, filename::String)

    @ Base .\loading.jl:1196

  [4] #invokelatest#2

    @ .\essentials.jl:716 [inlined]

  [5] invokelatest

    @ .\essentials.jl:714 [inlined]

  [6] (::VSCodeServer.var"#150#151"{VSCodeServer.NotebookRunCellArguments, String})()

    @ VSCodeServer c:\Users\Denis\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\VSCodeServer\src\serve_notebook.jl:18

  [7] withpath(f::VSCodeServer.var"#150#151"{VSCodeServer.NotebookRunCellArguments, String}, path::String)

    @ VSCodeServer c:\Users\Denis\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\VSCodeServer\src\repl.jl:185

  [8] notebook_runcell_request(conn::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, params::VSCodeServer.NotebookRunCellArguments)

    @ VSCodeServer c:\Users\Denis\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\VSCodeServer\src\serve_notebook.jl:14

  [9] dispatch_msg(x::VSCodeServer.JSONRPC.JSONRPCEndpoint{Base.PipeEndpoint, Base.PipeEndpoint}, dispatcher::VSCodeServer.JSONRPC.MsgDispatcher, msg::Dict{String, Any})

    @ VSCodeServer.JSONRPC c:\Users\Denis\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\JSONRPC\src\typed.jl:67

 [10] serve_notebook(pipename::String; crashreporting_pipename::String)

    @ VSCodeServer c:\Users\Denis\.vscode\extensions\julialang.language-julia-1.5.11\scripts\packages\VSCodeServer\src\serve_notebook.jl:94

 [11] top-level scope

    @ c:\Users\Denis\.vscode\extensions\julialang.language-julia-1.5.11\scripts\notebook\notebook.jl:12

 [12] include(mod::Module, _path::String)

    @ Base .\Base.jl:418

 [13] exec_options(opts::Base.JLOptions)

    @ Base .\client.jl:292

 [14] _start()

    @ Base .\client.jl:495

**Comment by YingboMa** [comment]
Note that you wrote
```julia
@variables begin
      t
      omega(t) = 0.9
      ln𝛚(t) = 
      lambda(t) = 0.90
      tn𝛌(t)= 
```

**Comment by YingboMa** [comment]
You should read the stack trace, and try to debug it yourself first. That's not a MTK issue.
