### ISSUE TITLE
Integrator doesn't support symbolic indexing

### ISSUE THREAD

**Issue by AayushSabharwal** [SciML/ModelingToolkit.jl#1470]
The integrator interface doesn't allow supplying symbolic (`Num`) indexes

MWE:
```julia
@variables x[1:2](t)
# ...
# ...
sol = solve(prob, Tsit5())
sol(1.23, idxs=[x[1]])
# works!
int = init(prob, Tsit5())
# step it a bunch of times
int(1.23, idxs=[x[1]])
# ERROR: ArgumentError: invalid index: x[1](t) of type Num
```

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/SciMLBase.jl/blob/master/src/solutions/solution_interface.jl#L45-L118

The sym dispatches from here need to be added to the integrator interface.

**Comment by AayushSabharwal** [comment]
From stepping into the function, it looks like this would have to be added somewhere in `ode_interpolant` in `OrdinaryDiffEq/src/dense/generic_dense.jl`? It doesn't look like integrators have `getindex` methods, so I tried tracing through `int[1.23]` to see where the call stack goes

**Comment by ChrisRackauckas** [comment]
adding getindex methods to the integrators may be the way to go.

**Comment by AayushSabharwal** [comment]
Would [all these](https://github.com/SciML/SciMLBase.jl/blob/08766043c1ac630ae74075e16f526d5116497f75/src/solutions/solution_interface.jl#L31-L136) methods need to be overloaded for `DEIntegrator` (That _looks_ like the appropriate type), or just a few? Looking at [this](https://github.com/SciML/OrdinaryDiffEq.jl/blob/08b52dbf5bb9cb33944e57fd3fee0b914e919e97/src/integrators/type.jl#L78-L126) it seems like the struct has the required fields. I'm just not sure if the fields serve the same purpose or not. If so, it seems like a straightforward PR

**Comment by ChrisRackauckas** [comment]
No, just the indexing. Everything else uses the indexing.
