### ISSUE TITLE
Acausal model with serial resistors fails with `UndefVarError` - MTK 8.X.X

### ISSUE THREAD

**Issue by TS-CUBED** [SciML/ModelingToolkit.jl#1478]
There seems to be a regression in MTK 8.5.1

If I change the tutorial example (https://mtk.sciml.ai/stable/tutorials/acausal_components/) to include a second resistor in series with the first (something we use quite a lot in our models, e.g. the heart valves are resistors with a pressure dependent resistance and a Boolean term), then the system is created correctly, and it solves correctly. But when I try to plot one of the observed variables I get an `UndefVarError` for one of the other variables. Looking at the `states` and `observed` of the system looks fine and shows the variables the are allegedly missing.

Test code (all the initialisation is the same as the tutorial case, so omitted here). The only change is the `resistor2`, which is directly in series with `resistor`:

```
R = 1.0
C = 1.0
V = 1.0
@named resistor = Resistor(R=R)
@named resistor2 = Resistor(R=R)
@named capacitor = Capacitor(C=C)
@named source = ConstantVoltage(V=V)
@named ground = Ground()

rc_eqs = [
          connect(source.p, resistor.p)
          connect(resistor.n, resistor2.p)
          connect(resistor2.n, capacitor.p)
          connect(capacitor.n, source.n)
          connect(capacitor.n, ground.g)
         ]

@named _rc_model = ODESystem(rc_eqs, t)
@named rc_model = compose(_rc_model,
                          [resistor, resistor2, capacitor, source, ground])
sys = structural_simplify(rc_model)
u0 = [
      capacitor.v => 0.0
     ]
prob = ODAEProblem(sys, u0, (0, 10.0))
sol = solve(prob, Tsit5())
plot(sol)

plot(sol, vars = [source.p.i])
```

Everything works nicely, but for the last plot command, which gives:

```
ERROR: LoadError: UndefVarError: resistor2₊v(t) not defined
```

and a lengthy stacktrace, that I can post, if required.

The variable `resistor2.v(t)` is in `states(sys)` in this case.

**Comment by YingboMa** [comment]
Thanks for the bug report. The dependency analysis for ODAEProblem is a bit buggy. I will try to refactor it.

**Comment by TS-CUBED** [comment]
Just checked, and the problem is still there in 8.5.4

Changing title accordingly (last version to work is 7.1.3
