### ISSUE TITLE
Linear systems of SDEs & Spectral Analysis

### ISSUE THREAD

**Issue by kaandocal** [SciML/ModelingToolkit.jl#1483]
Does MT currently provide any functionality for linear systems of SDEs such as explicit computations of covariances (via Lyapunov equations) or power spectrum analysis? These are very common in some modelling contexts but I haven't found anything related to this in Julia yet...

**Comment by baggepinnen** [comment]
For linear systems
https://github.com/JuliaControl/ControlSystems.jl/blob/cd46c638852297ad59441a8310803321fa760c50/src/matrix_comps.jl#L150
computes the steady-state covariance

**Comment by kaandocal** [comment]
Thanks for the hint, this looks just what I would need! Is there any functionality related to power spectra or autocorrelations in this package? I haven't found anything, but I reckon Control Theory might use some terminology that I'm not primed for. Otherwise it should not be too much work to open a pull request if I have time...
