### ISSUE TITLE
Easier vectorial differential equations

### ISSUE THREAD

**Issue by doppioandante** [SciML/ModelingToolkit.jl#1485]
The only modeling domain I'm familiar with are ODE systems from automation theory, I don't know if this could be useful in other domains.
Say I want to model a simple 2x2 linear autonomous system. Currently, the easiest way I have found is the following:
```julia
@variables t x[1:2](t)
@parameters A[1:2, 1:2]
Dt = Differential(t)
@named sys = ODESystem([
	(Dt.(x) ~ -A*x)...
])
```
This is quite easy, but I guess it would be even more intuitive like this:
```julia
@named sys = ODESystem([
	Dt.(x) ~ -A*x
])
```
Or maybe even:
```
Dt(x) ~ -A*x
```

**Comment by ChrisRackauckas** [comment]
```julia
Dt(x) ~ -A*x
```

should be, in the end, a valid equation. `A*x` gives a vector, and `x` is a vector, so `Dt(x)` is a vector derivative. We just haven't gotten array symbolics working everywhere, so the fallback is always scalarizing and broadcasting.

**Comment by ChrisRackauckas** [comment]
This was fixed in v9
