### ISSUE TITLE
Accessing and plotting states (and observables) without namespacing pitfalls

### ISSUE THREAD

**Issue by rschiemann1** [SciML/ModelingToolkit.jl#1488]
See [here](https://discourse.julialang.org/t/modelingtoolkit-some-questions-on-usage-best-practices/77426).

With an MTK variable `Tgas[1:n]` defined for `sys = ODESystem(...)`, intended variable access (e.g. for plotting) seems to be:
`plot(sol, vars=(sys.Tgas[1]))`

This however gives the following error:
```
# ArgumentError: sys₊Tgas[1](t) is either an observed nor a state variable.
# (should it read "_n_either... nor"?)
```

Namespacing of the variable:
```
sys.Tgas[1]
# sys₊Tgas[1](t)
```

Additional info:
```
Pkg.status()
#  [165a45c3] DASKR v2.8.0
#  [e993076c] DASSL v2.6.0
#  [0c46a032] DifferentialEquations v7.1.0
#  [28b8d3ca] GR v0.64.0
#  [33e6dc65] MKL v0.5.0
#  [961ee093] ModelingToolkit v8.5.1
#  [1dea7af3] OrdinaryDiffEq v6.7.0
#  [91a5bcdd] Plots v1.26.0
#  [d236fae5] PreallocationTools v0.2.4
#  [c3572dad] Sundials v4.9.2
#  [0c5d862f] Symbolics v4.3.0
```

**Comment by ChrisRackauckas** [comment]
@YingboMa I thought you fixed this awhile back? Whatever happened to that?

**Comment by YingboMa** [comment]
Yeah, I thought I fixed it, but I cannot find the commit anymore. Maybe a merge error?
