### ISSUE TITLE
The solution object can't be accessed by symbols

### ISSUE THREAD

**Issue by jake484** [SciML/ModelingToolkit.jl#1497]
Hi , my question is the problem can be solved., and the symbol can be observed. But when use this symbol to access the solution object, it shows that UndefVarError. Like this.
 
![image](https://user-images.githubusercontent.com/69461969/159839605-ca98336a-ec9a-4d2d-bac0-c9c0fcfc6baa.png)

Other problem can access as usual,but this can't. What happened? maybe I lost something with function structure?

**Comment by ChrisRackauckas** [comment]
Try `sol[sys.Isource.i]`?

**Comment by YingboMa** [comment]
MWE?

**Comment by YingboMa** [comment]
https://github.com/SciML/ModelingToolkit.jl/pull/1499 might solve your issue, but I am not sure.

**Comment by jake484** [comment]
> #1499 might solve your issue, but I am not sure.
it works! thanks!
