### ISSUE TITLE
Initial conditions not respected when using generator function

### ISSUE THREAD

**Issue by ctessum** [SciML/ModelingToolkit.jl#1505]
Hi!

I've encountered something that I think is a bug, but it could also just be me doing things wrong. Starting from [this example](https://catalyst.sciml.ai/stable/tutorials/reaction_systems/#Directly-Building-the-Repressilator-with-ReactionSystems), I've made the following system:

``` julia
@parameters δ=0.1;
@variables t m₁(t)=10;
rxs = [Reaction(δ, [m₁], nothing)]
@named repressilator = ReactionSystem(rxs, t)

tspan = (0.0, 4.0)
u0 = [m₁ => 1.0] ###### Set new initial condition
p = [δ=>0.1]

# solve ODEs
oprob = ODEProblem(repressilator, u0, tspan, p)
osol = solve(oprob, Tsit5())
```

which gives the following output:

```
retcode: Success
Interpolation: specialized 4th order "free" interpolation
t: 4-element Vector{Float64}:
 0.0
 0.15852100443841718
 1.5574392236923962
 4.0
u: 4-element Vector{Vector{Float64}}:
 [1.0]
 [0.9842728828131936]
 [0.8557783085166383]
 [0.6703200628623242]
```

The key here is that default initial condition for m1 is 10, but before running we substitute in a value of 1.0, and in the result the first value of u is 1.0. This is all working as expected so far.

However, I am interested in creating a module that has multiple reaction systems, so I don't want all the parameters and variables to be global variables. Therefore, I tried doing this:

``` julia
function make_repressilator()
    @parameters δ=0.1;
    @variables t m₁(t)=10;
    
    rxs = [Reaction(δ, [m₁], nothing)]
    
    @named repressilator = ReactionSystem(rxs, t)    
end

r2 = make_repressilator()
u0 = [r2.m₁ => 1.0] ##### Set new initial condition
p = [r2.δ=>0.1]

# solve ODEs
oprob = ODEProblem(repressilator, u0, tspan, p)
osol = solve(oprob, Tsit5())
```

which gives this result:

```
retcode: Success
Interpolation: specialized 4th order "free" interpolation
t: 4-element Vector{Float64}:
 0.0
 0.15849248890571244
 1.5571590639162443
 4.0
u: 4-element Vector{Vector{Float64}}:
 [10.0]
 [9.842756895237533]
 [8.558022843178138]
 [6.703200628745608]
```

As you can see here, are again using a substituting in an initial value of 1.0, but the first value of u in the result is 10, when I believe it should be 1.0. 

 I think the key is here: `u0 = [r2.m₁ => 1.0]` where we are using the field `r2.m1` rather than the global variable m1. It seems that this should work like it does in the [MTK tutorial](https://mtk.sciml.ai/stable/tutorials/acausal_components/), but it seems not to.

Any suggestions regarding what I'm doing wrong, or how this can be fixed if it is indeed a bug? Thanks!

**Comment by isaacsas** [comment]
I’m going to transfer this to ModelingToolkit since this isn’t really a Catalyst specific issue.

**Comment by isaacsas** [comment]
@ctessum you can always
```julia
@unpack m₁ = r2
```
to bring `m₁` into the local scope. Then you can use it in the parameter or initial condition mappings.

**Comment by ctessum** [comment]
Thanks! That fixes my problem.
