### ISSUE TITLE
Inconsistent Differential across Julia versions.

### ISSUE THREAD

**Issue by korsbo** [SciML/ModelingToolkit.jl#152]
I ran across a problem when I tried to add support for ModelingToolkits to Latexify.jl: when constructing an Equation, I get different results when using different Julia versions, even though the ModelingToolkit version is the same.

From the first example in the readme:
```julia
using ModelingToolkit

# Define some variables
@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]
```

Results using julia 1.1 and 1.2-rc2:

![image](https://user-images.githubusercontent.com/16306680/61290682-5c91d300-a7c4-11e9-8abb-15e92baf4714.png)

note the first part of each `Equation`.

**Comment by korsbo** [comment]
I just updated everything on Julia 1.1 but the discrepancy persisted.

**Comment by ChrisRackauckas** [comment]
We don't support the earlier Julias now which fixes this in some sense.
