### ISSUE TITLE
The callback problem of modelingtoolkit

### ISSUE THREAD

**Issue by lilianping** [SciML/ModelingToolkit.jl#1527]
Recently, I was using callback to solve some modeling toolkit problems. I used the model of RC circuit, and finally added a callback. The code is as follows：

`using ModelingToolkit, Plots, DifferentialEquations

@variables t
@connector function Pin(;name)
    sts = @variables v(t)=1.0 i(t)=1.0 [connect = Flow]
    ODESystem(Equation[], t, sts, []; name=name)
end

function Ground(;name)
    @named g = Pin()
    eqs = [g.v ~ 0]
    compose(ODESystem(eqs, t, [], []; name=name), g)
end

function OnePort(;name)
    @named p = Pin()
    @named n = Pin()
    sts = @variables v(t)=1.0 i(t)=1.0
    eqs = [
           v ~ p.v - n.v
           0 ~ p.i + n.i
           i ~ p.i
          ]
    compose(ODESystem(eqs, t, sts, []; name=name), p, n)
end

function Resistor(;name, R = 1.0)
    @named oneport = OnePort()
    @unpack v, i = oneport
    ps = @parameters R=R
    eqs = [
           v ~ i * R
          ]
    extend(ODESystem(eqs, t, [], ps; name=name), oneport)
end

function Capacitor(;name, C = 1.0)
    @named oneport = OnePort()
    @unpack v, i = oneport
    ps = @parameters C=C
    D = Differential(t)
    eqs = [
           D(v) ~ i / C
          ]
    extend(ODESystem(eqs, t, [], ps; name=name), oneport)
end

function ConstantVoltage(;name, V = 1.0)
    @named oneport = OnePort()
    @unpack v = oneport
    ps = @parameters V=V
    eqs = [
           V ~ v
          ]
    extend(ODESystem(eqs, t, [], ps; name=name), oneport)
end

R = 1.0
C = 1.0
V = 1.0
@named resistor = Resistor(R=R)
@named capacitor = Capacitor(C=C)
@named source = ConstantVoltage(V=V)
@named ground = Ground()

rc_eqs = [
          connect(source.p, resistor.p)
          connect(resistor.n, capacitor.p)
          connect(capacitor.n, source.n)
          connect(capacitor.n, ground.g)
         ]

@named _rc_model = ODESystem(rc_eqs, t)
@named rc_model = compose(_rc_model,
                          [resistor, capacitor, source, ground])
sys = structural_simplify(rc_model)
u0 = [
      capacitor.v => 0.0
     ]
p = [resistor.R=>1.0,source.V=>3.0]
prob = ODAEProblem(sys, u0, (0, 10.0))
Condition(p,t,integrator)=t-1
affect!(integrator)=integrator.p[3]=5
cb=ContinuousCallback(Condition,affect!)
sol=solve(prob,Tsit5(),callback=cb)
plot(sol)
`

But there are only two parameters in my vector p, what I understand is that the p in effect!(integrator)=integrator.p is to take into account all the p of my above model, so p[3] will appear, So if my model is very complex, is there any way for me to precisely locate the parameters I want to change?

Also when I run the following code
`prob = ODAEProblem(sys, u0, (0,10.0),p)
Condition(p,u,integrator)= u==2
affect!(integrator)=integrator.p[100]=10
cb=DiscreteCallback(Condition,affect!)
sol=solve(prob,Tsit5(),callback=cb)
plot(sol)`

I found that even if I choose p[100], this code still does not report an error, why is this?

**Comment by YingboMa** [comment]
```julia
Condition(p,u,integrator)= u==2
```
is wrong.

**Comment by ChrisRackauckas** [comment]
`Condition(u,p,integrator)= u[i] ==2` for the right `i`. https://mtk.sciml.ai/dev/basics/FAQ/. This is of course being worked on with symbolic events, but for now this will get you working.

**Comment by lilianping** [comment]
> ```julia
> Condition(p,u,integrator)= u==2
> ```
> 
> is wrong.

yeah,thanks.Later I found out,do you know anything about the specified index above, thanks again

**Comment by lilianping** [comment]
> `Condition(u,p,integrator)= u[i] ==2` for the right `i`. https://mtk.sciml.ai/dev/basics/FAQ/. This is of course being worked on with symbolic events, but for now this will get you working.

OKOK，thanks，I'll take a look at these，thanks again
