### ISSUE TITLE
ExtraEquationsSystemException - worked in 8.5.5 - related to  #1539 and #1537?

### ISSUE THREAD

**Issue by TS-CUBED** [SciML/ModelingToolkit.jl#1544]
The following system worked in MTK8.5.5, but now claims the system is unbalanced. This is most likely the same problem as #1537 and #1539

 ```
R = 1.0
C = 1.0
V = 1.0
@named resistor1 = Resistor(R=R)
@named resistor2 = Resistor(R=2*R)
@named capacitor = Capacitor(C=C)
@named source = ConstantVoltage(V=V)
@named ground = Ground()

rc_eqs = [
          connect(source.p, resistor1.p)
          connect(resistor1.n, capacitor.p, resistor2.p)
          connect(resistor2.n, source.n, ground.g)
          capacitor.n.v ~ 1.0
         ]

@named _rc_model = ODESystem(rc_eqs, t)
@named rc_model = compose(_rc_model,
                          [resistor1, resistor2, capacitor, source, ground])
sys = structural_simplify(rc_model)
```

Error:

```
ERROR: ExtraEquationsSystemException: The system is unbalanced. There are 6 highest order derivative variables and 7 equations.
More equations than variables, here are the potential extra equation(s):

Stacktrace:
 [1] error_reporting(state::TearingState{ODESystem}, bad_idxs::Vector{Int64}, n_highest_vars::Int64, iseqs::Bool)
   @ ModelingToolkit.StructuralTransformations ~/.julia/packages/ModelingToolkit/2ALr4/src/structural_transformation/utils.jl:27
 [2] check_consistency(state::TearingState{ODESystem})
   @ ModelingToolkit.StructuralTransformations ~/.julia/packages/ModelingToolkit/2ALr4/src/structural_transformation/utils.jl:66
 [3] structural_simplify(sys::ODESystem; simplify::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/2ALr4/src/systems/abstractsystem.jl:930
 [4] structural_simplify(sys::ODESystem)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/2ALr4/src/systems/abstractsystem.jl:927
 [5] top-level scope
   @ ~/Documents/Julia/TEST_RCR.jl:79
```

**Comment by YingboMa** [comment]
```julia
         capacitor.n.v ~ 1.0
```
is extra.

**Comment by TS-CUBED** [comment]
But that would mean that the negative side is not connected to anything.

This is exactly the problem. If I connect the negative terminal to a given potential (in the actual application this is a variable potential that depends on other elements), then MTK 8.6.0 and later fails, while in MTK 8.5.5 it works as expected.

In your solution the capacitor is not doing anything, as it is only connected at the positive terminal.

So MTK 8.5.5 works, MTK 8.6.0 and later does not.

**Comment by TS-CUBED** [comment]
In the actual application (coronary blood supply), the backplate of that capacitor is linked to the pressure in the heart muscle, and the model works up to 8.5.5.

There the equations looks something like:

LCA.C.n.p ~ LV.p
RCA.C.n.p ~ LV.p

where LCA and RCA are left and right coronary and LV is the left ventricle.

In MTK 8.5.5 these work, and I get the correct blood flow into the coronaries. In MTK 8.6.0 and later I can get the model to run, but only if I take these equations out, which implicitely means that the back-plate potential is zero, rather than the pressure in the muscle.

**Comment by TS-CUBED** [comment]
> ```julia
>          capacitor.n.v ~ 1.0
> ```
> 
> is extra.
> 
> ```julia
> rc_eqs = [
>          connect(source.p, resistor1.p)
>          connect(resistor1.n, capacitor.p, resistor2.p)
>          connect(resistor2.n, source.n, ground.g)
>         ]
> 
> @named _rc_model = ODESystem(rc_eqs, t)
> @named rc_model = compose(_rc_model,
>                          [resistor1, resistor2, capacitor, source, ground])
> sys = structural_simplify(rc_model)
> ```
> 
> would work.

Yes it would work, but it would be wrong :-)

**Comment by YingboMa** [comment]
It's clear that with `capacitor.n.v ~ 1.0`, the system is unbalanced though.
```julia
julia> expand_connections(rc_model)
Model rc_model with 27 equations
States (26):
  capacitor₊n₊v(t) [defaults to 1.0]
...
```

Does `8.5.5` give the correct solution though?

Also, v8.7.0 changed the implementation of `connect` so that it conforms with the Modelica standard. You can check the generated connection equations by
```julia
julia> sys, csets = ModelingToolkit.generate_connection_set(rc_model);

julia> csets
7-element Vector{ModelingToolkit.ConnectionSet}:
 <source₊p.v(t)::inner, resistor1₊p.v(t)::inner>
 <source₊p.i(t)::inner, resistor1₊p.i(t)::inner>
 <resistor1₊n.v(t)::inner, capacitor₊p.v(t)::inner, resistor2₊p.v(t)::inner>
 <resistor1₊n.i(t)::inner, resistor2₊p.i(t)::inner, capacitor₊p.i(t)::inner>
 <resistor2₊n.v(t)::inner, source₊n.v(t)::inner, ground₊g.v(t)::inner>
 <resistor2₊n.i(t)::inner, ground₊g.i(t)::inner, source₊n.i(t)::inner>
 <capacitor₊n.i(t)::inner>

julia> ceqs, instream_csets = ModelingToolkit.generate_connection_equations_and_stream_connections(csets);

julia> ceqs
9-element Vector{Equation}:
 source₊p₊v(t) ~ resistor1₊p₊v(t)
 0 ~ resistor1₊p₊i(t) + source₊p₊i(t)
 resistor1₊n₊v(t) ~ capacitor₊p₊v(t)
 resistor1₊n₊v(t) ~ resistor2₊p₊v(t)
 0 ~ capacitor₊p₊i(t) + resistor1₊n₊i(t) + resistor2₊p₊i(t)
 resistor2₊n₊v(t) ~ source₊n₊v(t)
 resistor2₊n₊v(t) ~ ground₊g₊v(t)
 0 ~ ground₊g₊i(t) + resistor2₊n₊i(t) + source₊n₊i(t)
 0 ~ capacitor₊n₊i(t)
```

Note that `capacitor₊n₊i` is already determined by `capacitor₊v(t) ~ capacitor₊p₊v(t) - capacitor₊n₊v(t)`.

**Comment by YingboMa** [comment]
Ah, I see. You want
```julia
R = 1.0
C = 1.0
V = 1.0
@named resistor1 = Resistor(R=R)
@named resistor2 = Resistor(R=2*R)
@named capacitor = Capacitor(C=C)
@named source = ConstantVoltage(V=V)
@named ground = Ground()

function SetV(;name, V)
    @parameters V=V
    @named s = Pin()
    eqs = [s.v~V]
    compose(ODESystem(eqs, t; name), s)
end

@named sv = SetV(V=1.0)

rc_eqs = [
         connect(source.p, resistor1.p)
         connect(resistor1.n, capacitor.p, resistor2.p)
         connect(resistor2.n, source.n, ground.g)
         connect(capacitor.n, sv.s)
        ]

@named _rc_model = ODESystem(rc_eqs, t)
@named rc_model = compose(_rc_model,
                         [resistor1, resistor2, capacitor, source, ground, sv])
sys = structural_simplify(rc_model)
```
don't you?

**Comment by TS-CUBED** [comment]
> It's clear that with `capacitor.n.v ~ 1.0`, the system is unbalanced though.
> 
> ```julia
> julia> expand_connections(rc_model)
> Model rc_model with 27 equations
> States (26):
>   capacitor₊n₊v(t) [defaults to 1.0]
> ...
> ```

I'd say it shouldn't. Without that equation the state at the negative terminal of C is not defined.

> Does `8.5.5` give the correct solution though?

Yes. The large model, this is a part of gives the same solution as a hand-derived MATLAB model that is the benchmark. This little model is just a minimal model that shows the problem.

In 8.5.5 the full model gives the correct solution, and this toy model behaves as expected for different values of the negative plate potential.

> Also, v8.7.0 changed the implementation of `connect` so that it conforms with the Modelica standard. You can check the generated connection equations by
> 
> ```julia
> julia> sys, csets = ModelingToolkit.generate_connection_set(rc_model);
> 
> julia> csets
> 7-element Vector{ModelingToolkit.ConnectionSet}:
>  <source₊p.v(t)::inner, resistor1₊p.v(t)::inner>
>  <source₊p.i(t)::inner, resistor1₊p.i(t)::inner>
>  <resistor1₊n.v(t)::inner, capacitor₊p.v(t)::inner, resistor2₊p.v(t)::inner>
>  <resistor1₊n.i(t)::inner, resistor2₊p.i(t)::inner, capacitor₊p.i(t)::inner>
>  <resistor2₊n.v(t)::inner, source₊n.v(t)::inner, ground₊g.v(t)::inner>
>  <resistor2₊n.i(t)::inner, ground₊g.i(t)::inner, source₊n.i(t)::inner>
>  <capacitor₊n.i(t)::inner>
> 
> julia> ceqs, instream_csets = ModelingToolkit.generate_connection_equations_and_stream_connections(csets);
> 
> julia> ceqs
> 9-element Vector{Equation}:
>  source₊p₊v(t) ~ resistor1₊p₊v(t)
>  0 ~ resistor1₊p₊i(t) + source₊p₊i(t)
>  resistor1₊n₊v(t) ~ capacitor₊p₊v(t)
>  resistor1₊n₊v(t) ~ resistor2₊p₊v(t)
>  0 ~ capacitor₊p₊i(t) + resistor1₊n₊i(t) + resistor2₊p₊i(t)
>  resistor2₊n₊v(t) ~ source₊n₊v(t)
>  resistor2₊n₊v(t) ~ ground₊g₊v(t)
>  0 ~ ground₊g₊i(t) + resistor2₊n₊i(t) + source₊n₊i(t)
>  0 ~ capacitor₊n₊i(t)
> ```
> 
> Note that `capacitor₊n₊i` is already determined by `capacitor₊v(t) ~ capacitor₊p₊v(t) - capacitor₊n₊v(t)`.

OK, so I may need to change my component library for 8,7. But this error occurs in 8.6.0 as well.

In any case `capacitor.n.v` is not defined without that equation, unless there is an implicit definition. Where does the `capacitor.n.i` come from? I don't think that should be there.

We use a "dangling" capacitor, that is connected to a constant potential, but not the same ground as the rest of the circuit. That is a somewhat common analogy for an expanding vessel. So that ground potential would be a current sink/source, but not set the current to be zero - if that was changed in MTK, then I think that may be the source of the issue. But it would mean that one cannot use this common modelling trick anymore and would need to move to a different model for an expanding model. Basically it means we cannot use the electrical analogy anymore.

I have to admit, I am myself not necessarily a friend of the electrical analogy for circulatory system models, and have an alternate vessel model. It would just mean I need to convince the rest of the research community to give up the dangling capacitors - and won't be able to implement 1-2-1 equivalents to the models which means I'll have more convincing to do.

**Comment by TS-CUBED** [comment]
> Ah, I see. You want
> 
> ```julia
> R = 1.0
> C = 1.0
> V = 1.0
> @named resistor1 = Resistor(R=R)
> @named resistor2 = Resistor(R=2*R)
> @named capacitor = Capacitor(C=C)
> @named source = ConstantVoltage(V=V)
> @named ground = Ground()
> 
> function SetV(;name, V)
>     @parameters V=V
>     @named s = Pin()
>     eqs = [s.v~V]
>     compose(ODESystem(eqs, t; name), s)
> end
> 
> @named sv = SetV(V=1.0)
> 
> rc_eqs = [
>          connect(source.p, resistor1.p)
>          connect(resistor1.n, capacitor.p, resistor2.p)
>          connect(resistor2.n, source.n, ground.g)
>          connect(capacitor.n, sv.s)
>         ]
> 
> @named _rc_model = ODESystem(rc_eqs, t)
> @named rc_model = compose(_rc_model,
>                          [resistor1, resistor2, capacitor, source, ground, sv])
> sys = structural_simplify(rc_model)
> ```
> 
> don't you?

Not quite, that potential needs to be variable (dependent on the state of the rest of the full model), the `capacitor.n.v ~ 1.0` is just a placeholder for a connection to the state of another component (which is not a `connect`, since it does not allow flow, but just equalises the pressure/potential).

**Comment by TS-CUBED** [comment]
If I understand the problem correctly then the new MTK does implicitly set the flow at `capacitor.n` to zero, since it is not connected to anything. While in the old implementation that flow/current was defined by `capacitor.p.v - capacitor.n.v` and the capacitor ODE.

So the question is: is that a new feature, or is that a bug (setting the current to zero in my original case). If the former, I can work around it, but it breaks the dangling capacitor model, which is quite common - even if it is electrically a weird thing - in cardiovascular modelling.

**Comment by YingboMa** [comment]
That's a new feature to conform with Modelica standard. So you should always use `connect` on connectors instead of setting it explicitly like
```julia
function SetV(;name, V)
    @parameters V=V
    @named s = Pin()
    eqs = [s.v~V]
    compose(ODESystem(eqs, t; name), s)
end

@named sv = SetV(V=1.0)

rc_eqs = [
         connect(source.p, resistor1.p)
         connect(resistor1.n, capacitor.p, resistor2.p)
         connect(resistor2.n, source.n, ground.g)
         connect(capacitor.n, sv.s)
        ]
```

See: https://specification.modelica.org/master/connectors-and-connections.html#generation-of-connection-equations
> [Rationale: If these variables are not connected they will generate a set comprised only of this element, and thus they will be implicitly set to zero (see below). If connected, this set will be merged and adding this at the start has no impact.]

It's necessary to make composition of models just work. e.g. https://github.com/SciML/ModelingToolkit.jl/blob/24a3fd284418abb954140684d79651628914f9ce/test/components.jl#L169-L214

**Comment by TS-CUBED** [comment]
I use submodels quite a lot, in a similar form to what you have there, but more complex.

And if the back-plate potential of that capacitor is constant, then I use a construct just as the one you described with `setV`. But I need a variable back-plate potential ground, so to speak.

I don't see a way, yet, to do what we need with this new constraint. So far, MTK was more flexible than Modelica or CellML (which is one of the reasons why I use it).

How do I make a connection from one pin in one component to another pin in another component, so it will have the same potential `v`, but zero `i`?

Do I need to define a new OnePort derivative that has something like:

```
eqs = [
          0 ~ i
          0 ~ p.v - n.v
          ]
```

could that work?

**Comment by TS-CUBED** [comment]
Ok, so taking everything together, the issue arises from the new requirement that all pins need to be connected to something or the flow will be set to zero implicitly.

**Comment by YingboMa** [comment]
Yes, so you just need to define a component to set them, and use the connect statement.

**Comment by TS-CUBED** [comment]
> Yes, so you just need to define a component to set them, and use the connect statement.

Thanks. So the dangling capacitor is out (actually, good riddance) - and I need to reimplement and revalidate the model using a compliance model, rather than a capacitor.

Thanks for the help.

And, while we're talking: A thousand thanks and kudos for developing this to you and Chris, and the other contributors :1st_place_medal:
