### ISSUE TITLE
Making sure doc examples run

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#1570]
MTK currently does not use the features of Documenter.jl that runs code while building the documentation and signals if the code fails. As a consequence, we often get reports from users that the examples do not run, which may result in an unfortunate first impression of MTK. Activating this feature is rather simple and comes with obvious benefits, but also some drawbacks:

1. Docs take longer to build.
2. If large figures are produced, occasional cleaning of the `gh-pages` branch may be required (not too difficult). 

The benefits are that
1. We effectively increase our test set to include all docs examples as well.
2. We ensure that updates do not break examples
3. If we make changes that affect the output produced by example code, the resulting figures are automatically updated. (Figures are currently hard-coded into the docs)

**Comment by ValentinKaisermayer** [comment]
There is some very verbose output now, e.g. [here](https://mtk.sciml.ai/dev/tutorials/tearing_parallelism/) .
It seems the standard output is Latex, which is inconsistent with what a user would see.
