### ISSUE TITLE
Change printing of variables

### ISSUE THREAD

**Issue by saschatimme** [SciML/ModelingToolkit.jl#158]
The current printing of variables looks as follows
```julia
@variables t x(t) z
(t(), x(t()), z())
```
In particular in bigger expressions this leads to a lot of visual noise.
Instead I would like to see the variables printed as follows:
```julia
@variables t x(t) z
(t, x(t), z)
```

This seems to be same behaviour as the recently introduced `simplified_expr`.

**Comment by ChrisRackauckas** [comment]
Fixed!
