### ISSUE TITLE
Difference ODEProblem ODAEProblem

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/ModelingToolkit.jl#1611]
https://mtk.sciml.ai/dev/tutorials/acausal_components/#Simplifying-and-Solving-this-System
Docs say 2 states for ODEProblem, 1 state for ODAEProblem, but it looks to me like both are reduced to 1 state?

**Comment by ChrisRackauckas** [comment]
@YingboMa ? Did it get better and removing equations 😅

**Comment by ChrisRackauckas** [comment]
The answer is that ODEProblem exists and ODAEProblem was removed.
