### ISSUE TITLE
Passing initial state of submodel silently fails

### ISSUE THREAD

**Issue by JTaets** [SciML/ModelingToolkit.jl#1638]
This first codeblock is slightly adopted from the docs (and works).
``` Julia
@variables t x(t)=0.0 RHS(t)
@parameters τ=3.0

D = Differential(t) 
@named fol = ODESystem([ D(x)  ~ (1 - x)/τ])

prob = ODEProblem(fol, [x => 0.1], (0.0,10.0), [])
@assert prob.u0[1] == 0.1
```
In the next codeblock, the initial state `[fol.x => 0.1]` is ignored even without throwing an error.
``` Julia
function Fol(;name)
    @variables t x(t)=0.0 RHS(t)
    @parameters τ=3.0
    D = Differential(t) 
    ODESystem([ D(x)  ~ (1 - x)/τ];name)
end
@named fol = Fol()

prob = ODEProblem(fol, [fol.x => 0.1], (0.0,10.0), [])
@assert prob.u0[1] == 0.1
```
IMHO, this is an intuitive way to me atleast of setting the initial state, I was kinda surprised that it fails.
So how do I do this correctly?

EDIT: related is #1299

**Comment by YingboMa** [comment]
Use `@unpack x = fol`.

**Comment by baggepinnen** [comment]
```julia
prob = ODEProblem(fol, [fol.x => 0.1], (0.0,10.0), [])
```
I make this error *all the time* and it really is a huge footgun. It would be nice to detect any incoming variable specification that starts with `fol` in this case and throw a warning (or error if more appropriate).

**Comment by ChrisRackauckas** [comment]
Fixed by complete
