### ISSUE TITLE
Roadmap questions

### ISSUE THREAD

**Issue by saschatimme** [SciML/ModelingToolkit.jl#165]
I would like to see two features in ModelingToolkit, and I am also willing to put these in existents, but I wanted to get some feedback / thoughts first.

My final goal is to be able to generate efficient evaluation functions for the following problem:

Let `u[1:2]` and `A[1:3,1:4]` be parameters and `x[1:4]` be variables.
I want to compute zeros of the gradient of the function

	(u[1] - l1/l3) * (u2 - l2/l3)

where l_i = A[i,:]*x and u.
For this I need the Jacobian of this system (i.e. the hessian) and also the derivatives of the gradient with respect to the parameters.

These expression become quite nasty through the linear forms. Therefore the question: Do we want to rely on the future cse to develop an efficient formulation of this problem? Or do we want to have a way of registering custom symbolic functions?
In particular, @HarrisonGrodin any thoughts / comments on this?

Another feature which I think comes handy is the possibility of doing substitutions of variables with arbitrary expressions / operations.

**Comment by ChrisRackauckas** [comment]
>Do we want to rely on the future cse to develop an efficient formulation of this problem? Or do we want to have a way of registering custom symbolic functions?

We already have registering of symbolic functions. See the `@register` macro in the README. That plus CSE should be all we need.

**Comment by saschatimme** [comment]
But this has now support for automatically defining the derivatives right?

```julia
julia> using ModelingToolkit

julia> l1(x,y,z) = x + y + z
l1 (generic function with 1 method)

julia> @variables x y z
@(regx(), y(), z())

julia> @register l1(x,y,z)
l1 (generic function with 8 methods)

julia> methods(l1)
# 8 methods for generic function "l1":
[1] l1(x::Expression, y::Expression, z::Expression) in Main
[2] l1(x::Number, y::Expression, z::Expression) in Main
[3] l1(x::Expression, y::Number, z::Expression) in Main
[4] l1(x::Number, y::Number, z::Expression) in Main
[5] l1(x::Expression, y::Expression, z::Number) in Main
[6] l1(x::Number, y::Expression, z::Number) in Main
[7] l1(x::Expression, y::Number, z::Number) in Main
[8] l1(x, y, z) in Main at REPL[1]:1

julia> l1(x,y,z)^3
l1(x(), y(), z()) ^ 3

julia> ModelingToolkit.gradient(l1(x,y,z)^3)
ERROR: MethodError: no method matching gradient(::Operation)
Closest candidates are:
  gradient(::Operation, ::AbstractArray{Operation,1}; simplify) at /Users/sascha/.julia/dev/ModelingToolkit/src/direct.jl:2
Stacktrace:
 [1] top-level scope at none:0

julia> ModelingToolkit.gradient(l1(x,y,z)^3, [x,y,z])
ERROR: MethodError: no method matching derivative(::typeof(l1), ::Tuple{Operation,Operation,Operation}, ::Val{1})
Closest candidates are:
  derivative(::Operation, ::Any) at /Users/sascha/.julia/dev/ModelingToolkit/src/differentials.jl:97
  derivative(::typeof(asind), ::Tuple{Any}, ::Val{1}) at /Users/sascha/.julia/dev/ModelingToolkit/src/differentials.jl:104
  derivative(::typeof(log1p), ::Tuple{Any}, ::Val{1}) at /Users/sascha/.julia/dev/ModelingToolkit/src/differentials.jl:104
  ...
Stacktrace:
 [1] derivative(::Operation, ::Int64) at /Users/sascha/.julia/dev/ModelingToolkit/src/differentials.jl:97
 [2] (::getfield(ModelingToolkit, Symbol("##8#9")))(::Int64) at /Users/sascha/.julia/dev/ModelingToolkit/src/differentials.jl:54
 [3] _mapreduce(::getfield(ModelingToolkit, Symbol("##8#9")), ::typeof(Base.add_sum), ::IndexLinear, ::UnitRange{Int64}) at ./reduce.jl:313
 [4] _mapreduce_dim(::Function, ::Function, ::NamedTuple{(),Tuple{}}, ::UnitRange{Int64}, ::Colon) at ./reducedim.jl:308
 [5] #mapreduce#548 at ./reducedim.jl:304 [inlined]
 [6] mapreduce at ./reducedim.jl:304 [inlined]
 [7] _sum at ./reducedim.jl:653 [inlined]
```

**Comment by ChrisRackauckas** [comment]
If you register a function then you need to define the derivative if you want to take derivatives of it (only errors when you `expand_derivatives`). That's kind of the whole point of it: you get to add simplified nodes to the compute graph. You can use ModelingToolkit to trace compute the derivative though if you wanted, and then define the derivative function by that trace.

**Comment by saschatimme** [comment]
Yes, wouldn't it be nice to do this in an automated way?

**Comment by ChrisRackauckas** [comment]
`@define_derivative ...` sure

**Comment by saschatimme** [comment]
Okay, I will try to come up with something nice :)

**Comment by ChrisRackauckas** [comment]
I think we've covered what's asked for here.
