### ISSUE TITLE
Tree flattening 

### ISSUE THREAD

**Issue by saschatimme** [SciML/ModelingToolkit.jl#166]
The tree flattening in `_simplify_constants` can collide with the differentiation rules. For me this was triggered in the Hessian computation, but here is a simple example
```julia
julia> @variables z
julia> O = ModelingToolkit._simplify_constants((-1) * (1 / z) * z, true);
julia> expand_derivatives(Differential(z)(O))
ERROR: MethodError: no method matching derivative(::typeof(*), ::Tuple{ModelingToolkit.Constant,Operation,Operation}, ::Val{1})
```

**Comment by ChrisRackauckas** [comment]
Yeah, this is something I am just going to punt to Rewrite.jl

**Comment by ChrisRackauckas** [comment]
Fixed by SymbolicUtils. Another win for @shashi
