### ISSUE TITLE
Updating packages changed the system efficiency

### ISSUE THREAD

**Issue by DoaaAboelyazeed** [SciML/ModelingToolkit.jl#1664]
I am using the modeling toolkit package to solve a nonlinear system. I realized considerable changes in the system efficiency when updating some packages. Here is a MWE and the following table shows the difference in time taken for running the MWE using different packages versions. The older packages were faster.
 ```
using ModelingToolkit, NonlinearSolve, Polynomials
@variables x  
@parameters σ 
# Define a nonlinear system
eqs = [0 ~ x^2 - 3 * x + σ]

@named ns = NonlinearSystem(eqs, [x],[σ])

guess = [x => 0.0]

ps = [ σ => 2.0]

prob = NonlinearProblem(ns,guess,ps)
@time sol = solve(prob,NewtonRaphson())
```

[
![image](https://user-images.githubusercontent.com/97982507/175426134-50c27706-6cd4-49b3-bc26-1533bc8cf8dc.png)
](url)

**Comment by DoaaAboelyazeed** [comment]
May be the difference in time here seems not effective so I am showing below the behavior of both versions with for loop for solving the quadratic equation using different bquad and cquad values.
```
using ModelingToolkit, NonlinearSolve, Polynomials

function nl_prob()

    @variables x  
    @parameters β, σ 
    # Define a nonlinear system
    eqs = [0.0 ~ x^2 + β * x + σ]

    @named ns = NonlinearSystem(eqs, [x],[β, σ])

    guess = [x => 0.0]

    ps = [β => -3.0, σ => 2.0]

    prob = NonlinearProblem(ns,guess,ps)
    return prob
end

bquad_arr = [-2.0, 3.0, 2.0, 3.0, -8.0, 3.0, 8.0, 5.0, 6.0, 29.0, -5.0, 2.0, 10.0, 2.0, -12.0, -2.0, 4.0, 6.0, 12.0, 13.0]
cquad_arr = [-15.0, -28.0, -15.0, -4.0, 12.0, -10.0, 15.0, -14.0, -27.0, 180.0, -6.0, -24.0, 9.0, 48.0, -28.0, -3.0, 3.0, -8.0, 20.0, 30.0]

y = zeros(20)
@time for i in 1:20
    println(i)
    bquad = 
    bquad_arr[i]
    cquad = cquad_arr[i]
    ps = [bquad, cquad]

    np = nl_prob()
    prob = remake(np; p = ps)
    sol = solve(prob, NewtonRaphson(), jac = true)
    y[i] = sol[1]

end 
```
![image](https://user-images.githubusercontent.com/97982507/175810459-1f56a21e-b30f-4092-9959-dcedea7ecd1f.png)

**Comment by ChrisRackauckas** [comment]
@shashi can you take a look at this? I assume it might be `build_function` regressions?

**Comment by DoaaAboelyazeed** [comment]
I was investigating my original system and just realized the difference in performance of both versions for this set of points which I think is more clear than the previous examples. I think the value of the guess is effective.
```
using ModelingToolkit, NonlinearSolve, Polynomials
@variables x  
@parameters β, σ
# Define a nonlinear system
eqs = [0 ~ x^2 + β * x + σ]

@named ns = NonlinearSystem(eqs, [x],[β, σ])

guess = [x => 483002.0260870451]

ps = [ β => -106341.5198661637, σ => -1.05306073143182e11]


prob = NonlinearProblem(ns,guess,ps)
@time sol = solve(prob,NewtonRaphson())
```
![image](https://user-images.githubusercontent.com/97982507/175965569-9c396e26-62bc-4882-8168-07f8fefdef4c.png)

**Comment by shashi** [comment]
Taking a look at this today.

**Comment by shashi** [comment]
I tried your second example as well. They give me similar timings. Please reopen if the problem persists!

**Comment by DoaaAboelyazeed** [comment]
Did you try the last example with putting initial guess?

**Comment by shashi** [comment]
Yes I did that too. Similar results on both MTK versions. Try updating the other two packages.

**Comment by DoaaAboelyazeed** [comment]
I tried again the third example https://github.com/SciML/ModelingToolkit.jl/issues/1664#issuecomment-1167428837 
using :
MTK 8.14.1
Polynomials 3.1.3
NonlinearSolve 0.3.20
NLsolve 4.5.1
Still the same issue persists? Are there any other packages I need to update?!

**Comment by DoaaAboelyazeed** [comment]
@shashi Can you please reopen the issue?

**Comment by shashi** [comment]
Yes that's the example I ran, I didn't run the second one, sorry.
