### ISSUE TITLE
varmap_to_vars fails when used inside of loss function for optimization.

### ISSUE THREAD

**Issue by mzhen77** [SciML/ModelingToolkit.jl#1692]
If I want to guarantee the order of parameters during the optimization I need to use varmap_to_vars, e.g:

loss function:

```julia
function loss(p::Vector{Float64})

    p1 = [param_vars[1] => p[1], param_vars[2] => p[2], param_vars[3] => p[3]]
    p2 = ModelingToolkit.varmap_to_vars(p1, param_vars)

    pred_sol = solve(prob, Tsit5(), p=p2, saveat=t_save)
    pred = Array(pred_sol')
    mse = mean((pred - obs_vals) .^ 2)
    return mse
end
```
where `param_vars` are the parameters of the MTK model.

The error I get:

`ERROR: Compiling Tuple{Type{Dict}, Vector{Pair{Sym{Real, Base.ImmutableDict{DataType, Any}}, Float64}}}: try/catch is not supported.
Refer to the Zygote documentation for fixes.`

The full code description is [here](https://discourse.julialang.org/t/modelingtoolkitstandardlibrary-and-optimization/84146)

**Comment by ChrisRackauckas** [comment]
If you do `idxs = ModelingToolkit.varmap_to_vars(1:3, param_vars)`, then `idxs` should be the index map for how to permute `p`. So then inside of your loss function, you can use `

```julia
function loss(p::Vector{Float64})
    pred_sol = solve(prob, Tsit5(), p=p[idxs], saveat=t_save)
    pred = Array(pred_sol')
    mse = mean((pred - obs_vals) .^ 2)
    return mse
end
```

with `idxs` being constant. Or just use `indexof` to do this.

If this is a good workaround, then we should document this in the FAQ.

**Comment by mzhen77** [comment]
@ChrisRackauckas Thank you for your response.

But I can't understand it...

If I run the command as you adviced: `idxs = ModelingToolkit.varmap_to_vars(1:3, param_vars)` I get the error:
`ERROR: MethodError: no method matching create_array(::Type{UnitRange{Int64}}, ::Type{Float64}, ::Val{1}, ::Val{3}, ::Float64, ::Float64, ::Float64)`

If you mean something like that:

`idxs = ModelingToolkit.varmap_to_vars([1,2,3], param_vars)`
 then the result will be `[1,2,3]` and doesn't depend on `param_vars`, so how can it help?

**Comment by ChrisRackauckas** [comment]
I just meant generate an index map.

```julia
using ModelingToolkit
p = @parameters x y z
idxs = ModelingToolkit.varmap_to_vars([p[1] => 1, p[2] => 2, p[3] => 3], p)
p[Int.(idxs)]
```

**Comment by lamorton** [comment]
@ChrisRackauckas varmap_to_vars produces a vector of the default values, not indexes. I think you meant a different function, but not sure what it is.
