### ISSUE TITLE
ODEFunction is type-unstable

### ISSUE THREAD

**Issue by gabrevaya** [SciML/ModelingToolkit.jl#1697]
Hi! Maybe this is not an issue, but just in case it is useful I'm reporting it:
I realized that `ODEFunction` is type-unstable. Probably the performance consequences of this are not very serious because `solve` is still type-stable. However, the cause for `ODEFunction` being type-unstable may also be making other methods type-unstable.

```julia
using DifferentialEquations, ModelingToolkit
function rober(du,u,p,t)
  y₁,y₂,y₃ = u
  k₁,k₂,k₃ = p
  du[1] = -k₁*y₁+k₃*y₂*y₃
  du[2] =  k₁*y₁-k₂*y₂^2-k₃*y₂*y₃
  du[3] =  k₂*y₂^2
  nothing
end
prob = ODEProblem{true}(rober,[1.0,0.0,0.0],(0.0,1e5),(0.04,3e7,1e4))
sys = modelingtoolkitize(prob)
@code_warntype ODEFunction{true}(sys)
```

```julia
MethodInstance for (ODEFunction{true})(::ODESystem)
  from (ODEFunction{iip})(sys::ModelingToolkit.AbstractODESystem) where iip in ModelingToolkit at /Users/ger/.julia/packages/ModelingToolkit/yOJMn/src/systems/diffeqs/abstractodesystem.jl:253
Static Parameters
  iip = true
Arguments
  #self#::Type{ODEFunction{true}}
  sys::ODESystem
Body::ODEFunction{true}
1 ─ %1 = ModelingToolkit.states(sys)::Any
│   %2 = ModelingToolkit.parameters(sys)::Any
│   %3 = (#self#)(sys, %1, %2, ModelingToolkit.nothing)::ODEFunction{true}
└──      return %3
```

As you see, the responsible for the type-instability are `ModelingToolkit.states(sys)` and `ModelingToolkit.parameters(sys)`. Tracking it down, you can find that it is caused by `getfield(sys, $(QuoteNode(prop)))`, in abstractsystem.jl, which is used for getting all the files of sys, that's why I guess it may be causing other type-stability issues.

```julia
(@v1.8) pkg> st
Status `~/.julia/environments/v1.8/Project.toml`
  [0c46a032] DifferentialEquations v7.2.0
  [961ee093] ModelingToolkit v8.16.0
```

```julia
julia> VERSION
v"1.8.0-rc3"
```

**Comment by YingboMa** [comment]
Yes, it's type unstable, but it doesn't matter as you should never generate more functions in a loop.
