### ISSUE TITLE
Does `structural_simplify` work well for DAE problems? And a problem about #1575

### ISSUE THREAD

**Issue by YangYuebao** [SciML/ModelingToolkit.jl#1704]
# This issue takes two aspects

- `structural_simplify` may have a bug.
- a problem of DAEProblem in MTK 8.18

## `structural_simplify` may have a bug.

The logic of `structural_simplify` seemingly changed a lot after the release of MTK 8.12.0

Lets see the different simplified result of the same pendulum system in #1575 with MTK version 8.18 and 8.10

Code:

```
using ModelingToolkit, DifferentialEquations

@variables t
@variables x(t) ,y(t), λ(t)
@parameters L g

D=Differential(t)

eqs=[
    D(D(x)) ~ λ * x
    D(D(y)) ~ λ *y - g
    0 ~ x^2 + y^2 - L^2
]

@named model=ODESystem(eqs, t)

sys=structural_simplify(model)
```

In MTK 8.18, the result is:

```
julia> sys
Model model with 4 equations
States (4):
  y(t)
  yˍt(t)
  x(t)
  λ(t)
Parameters (2):
  g
  L
...

julia> equations(sys)
4-element Vector{Equation}:
 Differential(t)(y(t)) ~ yˍt(t)
 Differential(t)(yˍt(t)) ~ yˍtt(t)
 0 ~ y(t)*λ(t) - g - yˍtt(t)
 0 ~ x(t)^2 + y(t)^2 - (L^2)
```

In MTK 8.15.2

```
julia> sys
Model model with 5 equations
States (5):
  y(t)
  yˍt(t)
  x(t)
  λ(t)
  xˍt(t)
Parameters (2):
  g
  L
...

julia> equations(sys)
5-element Vector{Equation}:
 Differential(t)(y(t)) ~ yˍt(t)
 Differential(t)(yˍt(t)) ~ y(t)*λ(t) - g
 0 ~ x(t)^2 + y(t)^2 - (L^2)
 Differential(t)(y(t)) ~ (-x(t)*xˍt(t)) / y(t)
 0 ~ 2(xˍt(t)^2) + 2(Differential(t)(y(t))^2) + 2x(t)*xˍtt(t) + 2y(t)*Differential(t)(yˍt(t))
```

In MTK 8.10

```
julia> sys
Model model with 5 equations
States (5):      
  xˍt(t)
  yˍt(t)
  x(t)
  y(t)
  λ(t)
Parameters (2):  
  g
  L
...

julia> equations(sys)
5-element Vector{Equation}:
 Differential(t)(xˍt(t)) ~ x(t)*λ(t)
 Differential(t)(yˍt(t)) ~ y(t)*λ(t) - g
 Differential(t)(x(t)) ~ xˍt(t)
 Differential(t)(y(t)) ~ yˍt(t)
 0 ~ 2(xˍt(t)^2) + 2(yˍt(t)^2) + 2(y(t)*λ(t) - g)*y(t) + 2(x(t)^2)*λ(t)
```
Firstly, I think the simplified result of 8.18 is wrong. `sys` of 8.18 actually has **5 variables**:    `y(t)  yˍt(t)  x(t)  λ(t) and y_tt(t)` , while `y_tt(t)` doesn't appear in `states(sys)`, but in the second and third equations in `equations(sys)`, which has **4 equations** .

And secondly, the result in 8.10 is right as it is corresponding to the simplified result by [Pantelides algorithm](https://ptolemy.berkeley.edu/projects/embedded/eecsx44/lectures/Spring2013/modelica-dae-part-2.pdf) which mentioned [here](https://mtk.sciml.ai/dev/mtkitize_tutorials/modelingtoolkitize_index_reduction/#Automating-the-Index-Reduction)

I have a different opinion about @YingboMa 's point in #1575 

> The ModelingToolkitStandardLibrary test failure is actually a good thing. It's now detecting some ODEs are actually implicit DAEs so MTK rejects to build the wrong problem. We need better implicit DAE handling to make ModelingToolkitStandardLibrary pass again.

`structural_simplify` should transform a high-index DAE to 1-index DAE or ODE. I think what we need is not a better implicit DAE handling but a good way to implement the reduction of DAE's index.

## A problem of DAEProblem in MTK 8.18.1

after `sys=structural_simplify(model)`, code behind, which is the same as that in #1575, can work on MTK 8.15.2, but can't on 8.18

```
u0=[
    x=>0.5,
    y=>sqrt(1-0.5^2),
    D(x)    => 0.0,
    D(y)    => 0.0,
    λ       => 0.0
]

p=[
    L=>1
    g=>9.8
]

prob_auto = DAEProblem(sys,zeros(length(u0)),u0,(0.0,10.0),p);

sol = solve(prob_auto, DFBDF())
```

In MTK 8.18
```
ERROR: ArgumentError: Sizes of u0 and du0 must be the same.
Stacktrace:
 [1] _
   @ C:\Users\hasee\.julia\packages\SciMLBase\QzHjf\src\problems\dae_problems.jl:82 [inlined]
 [2] (DAEProblem{true})(sys::ODESystem, du0map::Vector{Float64}, u0map::Vector{Pair{Num, Float64}}, tspan::Tuple{Float64, Float64}, 
parammap::Vector{Pair{Num, Float64}}; check_length::Bool, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit C:\Users\hasee\.julia\packages\ModelingToolkit\mQkI6\src\systems\diffeqs\abstractodesystem.jl:681
 [3] (DAEProblem{true})(sys::ODESystem, du0map::Vector{Float64}, u0map::Vector{Pair{Num, Float64}}, tspan::Tuple{Float64, Float64}, 
parammap::Vector{Pair{Num, Float64}})
   @ ModelingToolkit C:\Users\hasee\.julia\packages\ModelingToolkit\mQkI6\src\systems\diffeqs\abstractodesystem.jl:666
 [4] DAEProblem(::ODESystem, ::Vector{Float64}, ::Vararg{Any}; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
   @ ModelingToolkit C:\Users\hasee\.julia\packages\ModelingToolkit\mQkI6\src\systems\diffeqs\abstractodesystem.jl:611
 [5] DAEProblem(::ODESystem, ::Vector{Float64}, ::Vararg{Any})    
   @ ModelingToolkit C:\Users\hasee\.julia\packages\ModelingToolkit\mQkI6\src\systems\diffeqs\abstractodesystem.jl:611
 [6] top-level scope
   @ e:\Programs\julia\ModelingToolkit\MTK8_15_test.jl:32
```

By the way, in 8.10, this code can work:

```
prob=ODAEProblem(sys,u0,(0.0,10.0),p)

sol=solve(prob, Tsit5())
```

status:
MTK 8.18.1, 8.15.2, 8.10
DE 7.2.0

**Comment by YingboMa** [comment]
The error message says:
> ERROR: ArgumentError: Sizes of u0 and du0 must be the same.

So just check that. It should be
```julia
prob_auto = DAEProblem(sys,zeros(length(states(sys))),u0,(0.0,10.0),p);
```

**Comment by YangYuebao** [comment]
It works, thank you.
And I have one more question.
The simplified system in 8.18 is different from that in 8.10. Will it result in different accuracy and stability when solve the problem by DE?

**Comment by YingboMa** [comment]
It's a bit hard to explain. The new lowering would improve constraint satisfaction, but it could lead to singularities at runtime that we I have to use dynamic state selection to handle. It's not implemented yet, but it's planned. You can checkout this paper https://www.researchgate.net/publication/235324214_Index_Reduction_in_Differential-Algebraic_Equations_Using_Dummy_Derivatives for more details.

**Comment by YangYuebao** [comment]
Sincerely thank you for your reply. This will be really helpful for my questions.
