### ISSUE TITLE
Event trigger directionality

### ISSUE THREAD

**Issue by paulflang** [SciML/ModelingToolkit.jl#1715]
I am trying to introduce directionality in an event trigger (i.e. only fire as either up or downpass). IIUC [this](https://diffeq.sciml.ai/stable/features/callback_functions/#SciMLBase.ContinuousCallback) correctly it should be possible in principle with `affect_neg!=nothing` in the ContinuousVectorCallback .
But in MTK, I am using a `Pair{Vector{Equation}, Vector{Equation}}[]` that is passed to `continuous_events` in the ODESystem constructor. Is there a good way to introduce directionality in a trigger using the ODESystem constructor/continuous_events keyword? [My current code is here](https://github.com/SciML/SBMLToolkit.jl/blob/02e228fc6a4eb8082ae582858534c7939d9cb82f/src/events.jl#L10). Perhaps rather than using `~` in the trigger equation `<` or `>` could be used?

**Comment by isaacsas** [comment]
`SymbolicContinuousCallback`s could be modified to accept an `affect_neg!` function too:

https://github.com/SciML/ModelingToolkit.jl/blob/01186a4b41c0100dfd65f84dd188d0739f238976/src/systems/callbacks.jl#L73

**Comment by paulflang** [comment]
@isaacsas : that would be great. But not urgent rn.

**Comment by isaacsas** [comment]
I'm trying to finish off getting normal events into SDEs and jump processes first: https://github.com/SciML/ModelingToolkit.jl/pull/1714

**Comment by SLiemann** [comment]
Hi, has there been any progress on this issue yet?

**Comment by cuihantao** [comment]
I have the same need for a directional callback. Currently using `ifelse` but thinking a directional callback can be more efficient.

**Comment by paulflang** [comment]
We were discussing this more recently in https://github.com/SciML/SBMLToolkit.jl/issues/101. I close it there, let's continue discussing here.

**Comment by isaacsas** [comment]
@BenChung this should now be handled by https://github.com/SciML/ModelingToolkit.jl/pull/2911 right?

**Comment by ChrisRackauckas** [comment]
yes
