### ISSUE TITLE
RFC: Domain symbolics

### ISSUE THREAD

**Issue by Roger-luo** [SciML/ModelingToolkit.jl#175]
A short recap of slack discussion: currently, we have `Expression <: Number`, however, if a generic function is defined on `Real`, this won't "just work".

The simplest fix as proposed by @ChrisRackauckas is to move `Expression <: Real`. However, this will fail if there are symbolic complex numbers (which is also crucial in Yao's case). In fact, I believe we will need some kind of domain inference/ types to represent domains instead of letting the IR expression to handle it.

My proposal is to separate the IR with domain types, which mean `Expression` will not be subtype of `Real` nor `Number`, we will have a wrap type to help the dispatch, which can just be

```jl
struct SymReal <: Real
    data
end
``` 

where data can be `Expression` or `Variable` or other things that is defined as real number or inferred as real number and same for complex number and other kind of numbers or even matrices, linear maps etc. I'm trying out this idea in my toy symbolic engine, I'll make that public soon.

This is actually a similar idea with `Tracker`, the implementation of `TrackedReal` looks like following:

```jl
struct TrackedReal{T} <: Real
   tape::Tracked
   data::T
end
```

Update: I implemented some of my ideas here [Sym.jl](https://github.com/Roger-luo/Sym.jl)

**Comment by ChrisRackauckas** [comment]
What's a case where this actually shows up? Using `Number` gets the symbolics through the generic codes I've tried, such as linear algebra. For special functions, we have those in the computation graph anyways, so that's fine. I haven't found a concrete case where it errors on Number but not on Real.

**Comment by Roger-luo** [comment]
as long as there is something stricter (asking for `Integer` or `Real`), so either we redefine all the instructions and block definitions or we need a symbol that is `Real` e.g

https://github.com/QuantumBFS/YaoArrayRegister.jl/blob/master/src/instruct.jl#L216

https://github.com/QuantumBFS/YaoArrayRegister.jl/blob/master/src/instruct.jl#L239

and more... we can't just say yeah one can use complex number or something not real for phases in the definition. 

PS. I just played it a bit, it seems my idea works pretty well currently, one can feed it into Yao without doing anything else.

**Comment by ChrisRackauckas** [comment]
FWIW this is the kind of style I used in the PDE formulation here: https://github.com/JuliaDiffEq/DifferentialEquations.jl/issues/469 .

**Comment by ChrisRackauckas** [comment]
This is now all about the Symbolics.jl metadata system, so I'll close it here.
