### ISSUE TITLE
What's the use of field `substitutions` in `ODESystem` and how to handle it in system transformation methods? 

### ISSUE THREAD

**Issue by bowenszhu** [SciML/ModelingToolkit.jl#1754]
I am developing some model reduction functions, but I'm not sure how to correctly handle the field `substitutions` of `ODESystem`.

When `substitutions` of the input `ODESystem` is `nothing` or empty, it seem that I can safely ignore this field. But when it's not, I am wondering how to handle it if I would like to replace the original equations with a set of new equations and also add new dependent variables.

The doc of the filed `substitutions` is not clear.

https://github.com/SciML/ModelingToolkit.jl/blob/e180e14bf3ea8468d4bcbe4c343009770b8c72bf/src/systems/diffeqs/odesystem.jl#L114-L117

And unfortunately, its corresponding struct `Substitutions` doesn't have doc.

https://github.com/SciML/ModelingToolkit.jl/blob/e180e14bf3ea8468d4bcbe4c343009770b8c72bf/src/systems/abstractsystem.jl#L132-L136

I create an `ODESystem` and call `structural_simplify`. Occasionally, `structural_simplify` adds something to the field `substitutions`. Then, I do some processing to the equations `ODESystem.eqs` and set the new equations to `ODESystem.eqs` and set new variables to `ODESystem.states`. But when I call `ODEProblem`, it throws a KeyError saying some key is not found. `ODEProblem` internally calls `full_equations`, but `full_equations` ignores the new equations I just set if `substitutions` is not empty.

I read through the code of structural transformation and found this method `tearing_substitution`.

https://github.com/SciML/ModelingToolkit.jl/blob/e180e14bf3ea8468d4bcbe4c343009770b8c72bf/src/structural_transformation/symbolics_tearing.jl#L93-L97

`tearing_substitution` sets the result of `full_equations` to the field `eqs` and sets `substitutions` to `nothing`, which seem to be useful in my case.

So I am wondering if can just call `tearing_substitution` in the beginning of my system transformation method and then safely ignore `substitutions`.

**Comment by YingboMa** [comment]
Yes, I recommend you to call `tearing_substitution` for now. I want to refactor the tearing lowering code soon.
