### ISSUE TITLE
Get all states

### ISSUE THREAD

**Issue by Antomek** [SciML/ModelingToolkit.jl#1757]
Hello,

It would be nice to have a function to get all the states, including the variables that have been eliminated after calling `structural_simplify`.
Some kind of analogue for `full_equations`, essentially.
Maybe this function once existed, as there is a function called `get_states` listed in the [docs for the `AbstractSystem` interface](https://mtk.sciml.ai/stable/basics/AbstractSystem/),
but this function does not exist (nor does `get_systems` incidentally).

Currently, the only way I have found of discovering these eliminated variables is by going in the repl, typing the name of the system, and doing `sys. <TAB>` to get these variables via autocompletion, which is not ideal.
Maybe a way exists that I haven't found yet, but scouring the docs has not helped me so far!

Thank you.

**Comment by bowenszhu** [comment]
https://github.com/SciML/ModelingToolkit.jl/blob/5281b3f48f08cfa8d7595ae3276526bb37b7d7f8/src/systems/abstractsystem.jl#L196-L199

The getter methods are not exported. You need to qualify the function name with a module path:

```julia
ModelingToolkit.get_states(sys)
```

Or you can access the field values of the composite object using the traditional `.` notation:

```julia
sys.states
```

The same applies to other fields.

```julia
julia> fieldnames(ODESystem)
(:eqs, :iv, :states, :ps, :var_to_name, :ctrls, :observed, :tgrad, :jac, :ctrl_jac, :Wfact, :Wfact_t, :name, :systems, :defaults, :torn_matching, :connector_type, :connections, :preface, :continuous_events, :tearing_state, :substitutions)

julia> fieldnames(SDESystem)
(:eqs, :noiseeqs, :iv, :states, :ps, :var_to_name, :ctrls, :observed, :tgrad, :jac, :ctrl_jac, :Wfact, :Wfact_t, :name, :systems, :defaults, :connector_type)
```

**Comment by Antomek** [comment]
Good point, I should have spotted that 😃 

But this doesn't answer my original question unfortunately, as `ModelingToolkit.get_states` returns the same variables for me as `states`.

I know these other states exist, as I can find them in the REPL and plot them with `Plots`, but it would be nice to know if there was a better way of finding them.

**Comment by bowenszhu** [comment]
Could you check `observed`?

The section Observables and Variable Elimination in doc is useful for you.

https://mtk.sciml.ai/dev/internals/#Observables-and-Variable-Elimination

**Comment by Antomek** [comment]
I did check if `observed` worked; this function produces a vector of all the equations (including the equations that were eliminated by `structural_simplify`).

I read that section in the documentation, but I don't think it has the answer to the question.

Essentially, I'm looking for an `observed` equivalent for the variables.

**Comment by isaacsas** [comment]
I don't think there is a function that returns the eliminated states. 

One could maybe do something like
```julia
observed_states = [eq.lhs for eq in observed(sys)]
```
but that would only work if MTK guarantees that observed equations are of the form
```julia
observed_var ~ formula
```
which I'm not sure is guaranteed. @YingboMa can one assume that?

Otherwise you would have to use something like `Symbolics.get_variables` on each `eq.lhs` and `eq.rhs` to collect the variables within the observed equations, and then union those with `states(sys)` to get the complete set of state variables.

**Comment by wsphillips** [comment]
https://github.com/SciML/ModelingToolkit.jl/blob/078f1e583bbb521bf77d7c124c3fe1a2777019bf/src/systems/abstractsystem.jl#L972

**Comment by isaacsas** [comment]
@wsphillips thanks for pointing that out! Nice to know that it is guaranteed that observed have that form then.

**Comment by Antomek** [comment]
> https://github.com/SciML/ModelingToolkit.jl/blob/078f1e583bbb521bf77d7c124c3fe1a2777019bf/src/systems/abstractsystem.jl#L972

Thank you Wiktor!
This solves the issue, though I'd advocate for a little utility function e.g. `observed_states` being included in ModelingToolkit to do this.
