### ISSUE TITLE
Automated sparse Jacobian webpage = hard to navigate

### ISSUE THREAD

**Issue by Datseris** [SciML/ModelingToolkit.jl#1772]
My puny laptop cannot actually navigate this page https://mtk.sciml.ai/stable/mtkitize_tutorials/sparse_jacobians/  due to the rendering of thousands (millions?) of latex entries.

**Comment by Datseris** [comment]
Related with https://github.com/SciML/ModelingToolkit.jl/issues/1658

**Comment by isaacsas** [comment]
That tutorial should just not display the output of using `modelingtoolkitize`. Even if it rendered correctly it wouldn’t be useful to read given the large number of equations

**Comment by ChrisRackauckas** [comment]
Agreed. It needs to fix the Latex for other pages, but this page should put a `;`
