### ISSUE TITLE
DAE Index Reduction

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#18]
Index reduction algorithms for DAEs are described here:

https://www.modelica.org/events/modelica2017/proceedings/html/submissions/ecp17132565_OtterElmqvist.pdf

**Comment by ChrisRackauckas** [comment]
Assigned @YingboMa since I know he wants to tackle this. Before doing this though, it would probably be wise to do https://github.com/JuliaDiffEq/SciCompDSL.jl/issues/17 since that kind of a much simpler version.

**Comment by chakravala** [comment]
Very interesting, are there any other important papers specifically related to this?

**Comment by ChrisRackauckas** [comment]
Mathematica's writeup is particularly good here: http://reference.wolfram.com/language/tutorial/NDSolveDAE.html#128085219

https://epubs.siam.org/doi/abs/10.1137/0909014

**Comment by ChrisRackauckas** [comment]
https://arxiv.org/pdf/1712.02582.pdf

https://www.researchgate.net/profile/Gustaf_Soederlind/publication/235324214_Index_Reduction_in_Differential-Algebraic_Equations_Using_Dummy_Derivatives/links/56444cf908ae451880a71288/Index-Reduction-in-Differential-Algebraic-Equations-Using-Dummy-Derivatives.pdf

**Comment by ChrisRackauckas** [comment]
Completed in https://github.com/JuliaComputing/StructuralTransformations.jl
