### ISSUE TITLE
Proposal for `@constants`

### ISSUE THREAD

**Issue by lamorton** [SciML/ModelingToolkit.jl#1802]
What if we introduced a new category of `@constants`, alongside `@parameters`? My use case is including physical constants or unit conversion factors. These don't belong in parameter vectors, especially not the anonymous conversion factors generated by the unit conversion pass. 

Basically, we'd add a new metadata tag `MTKConstantCtx`, analogous to `MTKParameterCtx`.  The `@constants` macro would require a default value. `build_function` would just use the default value. 

This method is less flexible than something like a tag on the parameter vector (b/c it requires rebuilding the system to change a parameter to a constant). However, I want these constants to not appear in the parameter vector at all. So we'd have two different ways to make some thing constant. I'm wondering if that's too confusing.

**Comment by YingboMa** [comment]
That's a good idea.

**Comment by crlaugh** [comment]
Agreed.  The same idea also exists in Modelica.

**Comment by lamorton** [comment]
Working on a prototype. I hit a bug where `structural_simplify` decides that the constants are variables & sets them to zero somehow.  The relevant bit is here: [systemstructure.jl](https://github.com/SciML/ModelingToolkit.jl/blob/74e25718011c3e0a9b33f554c5e74f2176262778/src/systems/systemstructure.jl#L242-L247)

How does that even work? None of the variables in that block refer to `sys` or anything defined in terms of it -- is it some kind of pointer trick?

**Comment by lamorton** [comment]
I'm stuck on how to treat these during flattening/renamespacing. @YingboMa Do we want to assume these are global or should we allow to have different values for different subsystems? I'm leaning toward the former - if it's not global, it's not a real constant, it's just a fixed parameter.

**Comment by lamorton** [comment]
[Prototype is here.](https://github.com/SciML/ModelingToolkit.jl/compare/master...lamorton:ModelingToolkit.jl:constants2) Still needs more work before it's ready for a PR, but I'd like feedback on my strategy first.

**Comment by lamorton** [comment]
Done!
