### ISSUE TITLE
State reordering on `structural_simplify`

### ISSUE THREAD

**Issue by cadojo** [SciML/ModelingToolkit.jl#1817]
Is there any way to specify the order of the states on a `structural_simplify` call? I was unknowingly relying on the order of the states being stable after `structural_simplify`. I can pass the order to `ODEFunction`, but I was wondering if there was a way to specify the order with `states(model)`, `equations(model)`, `parameters(model)`, etc.

**Comment by baggepinnen** [comment]
That would make an improvement to simplification, that remove additional states etc., a breaking change right? 
In general, you have no guarantee which states will remain states after simplification.

**Comment by cadojo** [comment]
That makes sense. I know some states can be removed, or added. I was relying on the untouched states having the same order. I know that's not good to rely on!

But for documentation purposes, I'd like to be able to tell users "here's a pre-computed ODEFunction, it takes the arguments in _this_ order."

Is there any way to set the order of states and equations in a model explicitly? Otherwise you can't call ODEFunction with the default arguments and have it "just work."

**Comment by baggepinnen** [comment]
I don't think there's a way to accomplish that at the moment. What you could do is give them the ODEFunction and the vector of `x = states(simplified_sys)` which they could use together with `ModelingToolkit.varmap_to_vars`. I realize that this is quite awkward though. Why would the user need to know the order of the states? To provide the initial condition, `varmap_to_vars` should be quite usable. For plotting purposes, the state names are saved in the solution.

**Comment by cadojo** [comment]
So there's some cases where I want to provide a model, but I also want to provide default constructors for an `ODEFunction` for the same model. For example, in the Circular Restricted Three-body Problem in astrodynamics you use the `ODEFunction` for that problem in an iterative periodic-orbit-finding algorithm. So providing the users a function called `CR3BPFunction` is helpful. 

The question I asked here has been answered, "it is not supported," and by writing more I am not asking for more work from y'all! For anyone interested, here's my full use case...

---

For `AstrodynamicalModels.jl` I provide the following functions for each model:

1. `Model`
2. `ModelFunction`

Where "Model" is the name of the model. For example, the Restricted Two-body Problem (R2BP).

```julia
import Memoize: @memoize
import ModelingToolkit

"""
A `ModelingToolkit.ODESystem` for the Restricted Two-body Problem.

The order of the states follows: `[x, y, z, ẋ, ẏ, ż]`.

The order of the parameters follows: `[μ]`.

# Extended Help
The Restricted Two-body Problem is a simplified dynamical model
describing one small body (spacecraft, etc.) and one celestial
body. The gravity of the celestial body exhibits a force on the
small body. This model is commonly used as a simplification to
descibe our solar systems' planets orbiting our sun, or a
spacecraft orbiting Earth.

### Usage
    model = R2BP() 
"""
@memoize function R2BP(; stm=false, structural_simplify=false, name=:R2BP)

    ModelingToolkit.@parameters t μ
    ModelingToolkit.@variables x(t) y(t) z(t) ẋ(t) ẏ(t) ż(t)
    δ = ModelingToolkit.Differential(t)
    r = [x,y,z]
    v = [ẋ,ẏ,ż]

    eqs = vcat(
        δ.(r) .~ v,
        δ.(v) .~ -μ .* (r ./ norm(r)^3)
    )

    if stm
        ModelingToolkit.@variables (Φ(t))[1:6,1:6]
        Φ = ModelingToolkit.scalarize(Φ)
        A = ModelingToolkit.jacobian(map(el -> el.rhs, eqs), vcat(r,v))

        LHS = map(δ, Φ)
        RHS = map(ModelingToolkit.simplify, A * Φ)

        eqs = vcat(eqs, [LHS[i] ~ RHS[i] for i in eachindex(LHS)])
    end

    if string(name) == "R2BP" && stm
        modelname = Symbol("R2BPWithSTM")
    else
        modelname = name
    end

    sys = ModelingToolkit.ODESystem(
        eqs, t, stm  ? vcat(r,v,Φ...) : vcat(r,v), [μ];
        name = modelname
    )
    return structural_simplify ? ModelingToolkit.structural_simplify(sys) : sys
end

"""
Returns an `ODEFunction` for R2BP dynamics.
Results are cached with `Memoize.jl`.

The order of the states follows: `[x, y, z, ẋ, ẏ, ż]`.

The order of the parameters follows: `[μ]`.

# Extended Help

### Usage

The `stm`, `structural_simplify`, and `name` keyword arguments
are passed to `R2BP`. All other keyword arguments are passed
directly to `SciMLBase.ODEFunction`.

    f = R2BPFunction(; stm=false, structural_simplify=true, name=:R2BP, jac=true)
    let u = randn(6), p = randn(1), t = 0
        f(u, p, t)
    end
"""
@memoize function R2BPFunction(; stm=false, structural_simplify=false, name=:R2BP, kwargs...)
    defaults = (; jac=true)
    options  = merge(defaults, kwargs)

    return ModelingToolkit.ODEFunction(
        R2BP(; stm=stm, structural_simplify=structural_simplify, name=name);
        options...
    )
end
```

This is a kind of recipe. The `Model` function allows for optional "structural simplification" via `ModelingToolkit.structural_simplify`, and let's you change the default name of the model. The `ModelFunction` function
returns an `ODEFunction` for the `Model`. 

I've actually been toying around with making a new Julia package which provides a macro to build this pattern automatically. 

Automatically calling `structural_simplify` is nice because it speeds up the calculations. I know these equations, and I know that no variables will be reduced, so I want to somehow set the states to `[x(t), y(t), z(t), ẋ(t), ẏ(t), ż(t)]` **after** calling `structural_simplify` so the order of the arguments to `R2BPFunction` is stable over time.

**Comment by ChrisRackauckas** [comment]
With the improved SymbolicIndexingInterface, the reordering can just be done by getu/setu or other interface functions.
