### ISSUE TITLE
Documentation for `equations, equations, full_equations`

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#1822]
While trying to implement a new features in MTK, I realized that I am not 100% sure about the difference between these three functions. The documentation makes me no wiser
```julia
help?> ModelingToolkit.get_eqs
  No documentation found.

help?> ModelingToolkit.equations
  No documentation found.

help?> ModelingToolkit.full_equations
  No documentation found.
```

**Comment by LalitChauhan56** [comment]
1. get_eqs: This function likely retrieves a list of equations or expressions that define the model. It may be used to extract the equations of motion for a physical system or the mathematical relationships between variables in a more general model.

2. equations: This function may be used to generate a symbolic representation of the equations or expressions that define a model. It may be used to simplify or manipulate the equations before they are solved numerically or to export them to another program or language.

3.full_equations: This function may return the full set of equations that define a model, including any auxiliary equations or constraints. It may be useful for analyzing or debugging a model.

Is this of any help? If yes then should I make the required changes?

**Comment by ChrisRackauckas** [comment]
* `get_eqs` is the local list of equations in a given component.
* `equations` is the flattened equations for a component which includes the equations of all subcomponents. It may include some abbreviations and aliases represented by some observed variables as a form of common subexpression elimination (CSE). This is generally the one most useful in debugging.
* `full_equations` is the flattened equations with all substitutions performed. This is the form that matches the generated code.
