### ISSUE TITLE
Better initial condition handling for dummy derivatives

### ISSUE THREAD

**Issue by ValentinKaisermayer** [SciML/ModelingToolkit.jl#1830]
The dummy derivatives that are introduced also need initial conditions, however they are counted as states in the `DAE` case. This leads to the funny case that I have to specify `D(some_state)` in `umap` . See for instance here:
https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/a8bb6885682cbe2130dda902355394fe4ba0431d/test/Mechanical/rotational.jl#L70-L73

I would prefer it if the initial conditions for the dummy derivatives are somehow chosen by MTK.

**Comment by ChrisRackauckas** [comment]
Zero initial conditions were added as a default guess on the initialization for dummy derivatives, and the initialization system then handles it from there. This was pre-initialization, and is now handled.
