### ISSUE TITLE
Output order for `ODEFunction`

### ISSUE THREAD

**Issue by cadojo** [SciML/ModelingToolkit.jl#1873]
Related to #1817

I am using the `dvs` and `ps` arguments to set the order of the arguments to an `ODEFunction`, but the order of the outputs appears to be unchanged. I assumed the order of the outputs would match the order of the states. Is this a bug?

```julia
import Pkg
Pkg.activate(tempdir())
Pkg.develop("ModelingToolkit")

using ModelingToolkit

@variables t 
u = @variables x(t) y(t) z(t) ẋ(t) ẏ(t) ż(t)
p = @parameters μ
δ = ModelingToolkit.Differential(t)


r = [x,y,z]
v = [ẋ,ẏ,ż]

eqs = vcat(
  δ.(r) .~ v,
  δ(ẋ)   ~ x + 2ẏ - (μ*(x + μ - 1)*(sqrt(y^2 + z^2 + (x + μ - 1)^2)^-3)) - ((x + μ)*(sqrt(y^2 + z^2 + (x + μ)^2)^-3)*(1 - μ)),
  δ(ẏ)   ~ y - (2ẋ) - (y*(μ*(sqrt(y^2 + z^2 + (x + μ - 1)^2)^-3) + (sqrt(y^2 + z^2 + (x + μ)^2)^-3)*(1 - μ))),
  δ(ż)   ~ z*(-μ*(sqrt(y^2 + z^2 + (x + μ - 1)^2)^-3) - ((sqrt(y^2 + z^2 + (x + μ)^2)^-3)*(1 - μ)))
 )

sys = structural_simplify(
  ModelingToolkit.ODESystem(eqs, t, u, p; name = :CR3BP)
)

hcat(
  u, states(sys),
) # states were re-ordered

f = ODEFunction(sys, u, p) # specify the original order of states and parameters

f(u, p, t) # not equal to eqs, the order of states(sys) is used for the outputs
```

**Comment by cadojo** [comment]
I've tracked the issue to `generate_function` in [abstractodesystem.jl](https://github.com/SciML/ModelingToolkit.jl/blob/master/src/systems/diffeqs/abstractodesystem.jl#L127). If the system is `implicit_dae` is true, the outputs depend on the provided order of the inputs. Otherwise (the case for my equations) the order of the inputs does not affect the order of the outputs.

This seems inconsistent to me, and worth changing. If y'all agree, I would be interested in leading this change, but I'll need a bit of help with where the best place for this change should go.

**Comment by ChrisRackauckas** [comment]
Indeed it seems like a bug.

**Comment by YingboMa** [comment]
This is not a bug. You cannot force a particular ordering in anyway.

**Comment by cadojo** [comment]
I am a bit confused by that. We seem to be able to force the ordering for implicit DAE problems. If the ordering is not stable, then how can ODEFunction be used? If the order of outputs does not match the order of inputs, and there is no way to find the order of outputs, I don't see any way to use ODEFunction. 

This isn't the case for Symbolics.build_function. This seems like an inconsistency, or a bug, to me.

**Comment by YingboMa** [comment]
There are no ways to do that for DAE problems either.

**Comment by cadojo** [comment]
Okay, two things:

1. Am I misreading this [line](https://github.com/SciML/ModelingToolkit.jl/blob/2905e79270a73ae389e949779684fb96c78776c1/src/systems/diffeqs/abstractodesystem.jl#L139) then? It seems to me that `ddvs` sets the order of the derivatives produced by the function.
2. If we cannot predict or change the order of the `ODEFunction` outputs, is it not a "useless" external function? To me, that basically resigns `ODEFunction` to an internal API function, and users should only ever use `ODEProblem` with SciML solvers. If that's the intent of `ODEFunction`, then that's the intent. But I thought `ODEFunction` was a public facing functionality, and I cannot see a way to use it if we cannot either: 1) predict the output order, or 2) change the output order.

**Comment by cadojo** [comment]
Apologies for the follow up @ChrisRackauckas @YingboMa, I don't mean to be a pest. Right now, `ODEFunction` allows users to set the input argument order, but the corresponding output order is not set unless MTK determines the model is an implicit DAE. This difference in behavior for implicit DAE models is at least worth correcting, in my opinion. 

If we do not want to support custom ordering for inputs and outputs, then that's fine, but we have to at least be able to predict the order of the outputs of a generated function, right? The ability to either predict or set the order of inputs and outputs to a generated function seems to me to be borderline necessary. **If users cannot predict or set the order of the outputs of a generated function, how can they use the generated function?**
How would `DifferentialEquations` solvers create an `ODEProblem` using the constructor which takes an `ODEFunction` argument, as opposed to an `AbstractODESystem` argument?

Am I correct in my understanding that this is behavior that is worth correcting? If so, are PRs welcome for this? I'm very surprised that this has not caused other issues, outside of `AstrodynamicalModels.jl`.

**Comment by YingboMa** [comment]
Isn't the order the same with `states(sys)`? The states of implicit DAEs can be freely permuted because it's implicit, so the output doesn't have any particular meaning. But semi-implicit ODEs' mass matrix would have to be modified when the states are permuted.

**Comment by cadojo** [comment]
Yes, the order is the same as `states(sys)`. For differential equation solvers, the non-allocation method for an ODEFunction will have the derivatives with a different order than the states. Is that handled internally somehow? Or will that cause solvers to associate the wrong derivatives with each state?

Either way, I understand why ordering states for a model type is complicated and not worth it, but when generating a function, is there not a way to re-order the equations based on the provided order of the states?

**Comment by YingboMa** [comment]
Isn't that information stored in the mass matrix?

**Comment by cadojo** [comment]
Apologies for the late reply. The information may be in the mass matrix (I don't know enough about this to have an opinion one way or the other), but I think my question more has to do with high-level use of `ODEFunction`.

I'd expect the `dvs` argument to set the input order, as well as the _output_ order. The state vector input should have the same order as the state derivative output, no? If this is not the case, then users have no way to use `ODEFunction` in any replicate-able way. Users can pass a dictionary to `ODEProblem` to specify a problem's initial conditions, but if users wish to compute the jacobian or vector field for a model, they have no way of...

1. Knowing the order of the output
2. Setting the order of the output

I asked for state-reordering above, but I think that is not necessary. But, I still think a deterministic order for the output of `ODEFunction` is necessary for users to use it. 

I have a small MWE below which I hope illustrates my point, if I'm not clear here.

```julia
using ModelingToolkit

@variables t x(t) y(t) z(t)
@parameters a b c
d = Differential(t)

eqs = [
  d(x) ~ a * y,
  d(y) ~ b * z,
  d(z) ~ c * x,
]

model = ODESystem(eqs; name=:Example) |> structural_simplify

# 
# The order of the states is now non-deterministic. 
# How can I use ODEFunction below?
#

f = ODEFunction(model)
dx, dy, dz = f([x,y,z],[a,b,c],t) # potentially incorrect

f = ODEFunction(
  model, 
  [model.x, model.y, model.z], 
  [model.a, model.b, model.c]
)
dx, dy, dz = f([x,y,z],[a,b,c],t) # outputs not affected by the dvs argument, still potentially incorrect

```
