### ISSUE TITLE
solution indexing with symbolic expressions that include parameters

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#1874]
i realized you cant index sol with expressions including parameters of the system. 
if anyone from the future wants a hack to make it work, this does it for my case.

i think it is fairly common to want to plot an observed expression after solving. 
i could just make the system again with a new equation, but this is nice for interactivity.

sometime in the future i might try to edit the actual solution code

```julia

using OrdinaryDiffEq, ModelingToolkit

# assumes parameters are constant
function my_getindex(sol, num)
    f = sol.prob.f
    hasproperty(f, :sys) || error()
    sol[substitute(Symbolics.scalarize(num), Dict(parameters(f.sys) .=> sol.prob.p))]
end

@parameters t p=1
@variables x(t)
D = Differential(t)
eqs = [D(x) ~ p*x]
@named s = ODESystem(eqs)
sol = solve(ODEProblem(s, [x => 1.0], (0.0, 10.0)), Tsit5())
@test_throws Any sol[p*x[1]] # ERROR: ArgumentError: p is neither an observed nor a state variable.

my_getindex(sol, p*x)
my_getindex(sol, [p*x, p^2*x])
```

**Comment by ChrisRackauckas** [comment]
Handled in the new SII
