### ISSUE TITLE
Variable is not a function of independent variable error for trivial example

### ISSUE THREAD

**Issue by oameye** [SciML/ModelingToolkit.jl#1880]
I am trying out the `ModelingToolkit.jl` package and I get this weird error when defing the classical harmonic oscillator with the following code
```julia
using ModelingToolkit,
@variables t x(t)
@parameters ω₀
Dₜ = Differential(t)
@named sys = ODESystem([Dₜ(Dₜ(x)) + ω₀^2*x ~ 0])
````
It produces the error
```
ArgumentError: Variable x(t) is not a function of independent variable (ω₀^2)*x(t).
```
I do not understand the where the error comes from. Just putting the second term on the other side gets rid of the error, i.e.
```julia
using ModelingToolkit,
@variables t x(t)
@parameters ω₀
Dₜ = Differential(t)
@named sys = ODESystem([Dₜ(Dₜ(x)) ~ - ω₀^2*x])
````
runs just fine. My apologies if this error comes from my lack of understanding how the package must be used.

**Comment by YingboMa** [comment]
It should be `@named sys = ODESystem([Dₜ(Dₜ(x)) + ω₀^2*x ~ 0], t, [x], [ω₀])`

**Comment by ChrisRackauckas** [comment]
Why does the automatic detection of states and parameters fail here? Seems like a reasonable case for it to work?
