### ISSUE TITLE
mathengine

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/ModelingToolkit.jl#1910]
Why is mathengine passed in the middle of keywords?
I don't understand how documentation building is even working, there is not supposed to be a method for this?
https://github.com/SciML/ModelingToolkit.jl/blob/8f784408217350b07045c36b87599e85141eb794/docs/make.jl#L15-L33
https://juliadocs.github.io/Documenter.jl/stable/lib/internals/writers/#Documenter.Writers.HTMLWriter.HTML

**Comment by ChrisRackauckas** [comment]
that's equivalent to `mathengine = mathengine` since Julia v1.4 or something around that time.
