### ISSUE TITLE
MTK -- basic questions

### ISSUE THREAD

**Issue by B-LIE** [SciML/ModelingToolkit.jl#1925]
I've been looking into the index 3 pendulum model, and just discovered that there is an example of this system in the documentation under **ModelingTookitize Tutorials**, section on **Automated Index Reduction of DAEs**. I've defined a symbolic representation, though. [I use Julia 1.8.2 and the latest versions of MTK, etc.]
```julia
@parameters g
@variables t, q₁(t), q₂(t), v₁(t), v₂(t), λ(t)
D = Differential(t)

eqs = [D(q₁) ~ v₁,
        D(q₂) ~ v₂,
        D(v₁) ~ -λ*q₁,
        D(v₂) ~ -λ*q₂ - g,
        0 ~ q₁^2 + q₂^2 - 1]

@named sys = ODESystem(eqs)
```

Some issues... 

1. When it comes to *transformations*, the documentation suggests that `dae_index_lowering` uses Pantelides' algorithm and produces an index 1 system. And that the "end-user" should use `structural_simplify` instead, which does the same thing. 

One problem is that `dae_index_lowering` and `structural_simplify` produces different systems; the first transformation produces a system with 4 differential equations and 5 "states", while the second produces a system with 2 differential equations and 4 "states. Also, the system equations are different in the two cases. 

2. If I use the transformation `dae_index_lowering`, the system/states stay more or less the same whether I follow this transformation with `structural_simplify` or not. Simulating the resulting system seems to work both if I:

-- use the `ODEProblem` constructor with solver `Rodas4()` and no additional kwargs
```julia
q20 = sqrt(0.5)
q10 = sqrt(1-q20^2)
v20 = -1
v10 = -q20*v20/q10
g0 = 9.81
lam0 = (v20^2 - g0*q20*q10^2)/q10^2

u0 = [q₂ => q20,
        v₂ => v20,
        q₁ => q10,
        v₁ => v10,
        λ => lam0]

p = [g => g0]

tspan = (0.0,10.0)

prob = ODEProblem(dae_index_reduction(sys),u0,tspan,p)

sol = solve(prob,Rodas4())

plot(sol)
```

-- or whether I use the `ODAEProblem` constructor with solver `Tsit5()` and tolerances set to `1e-8`. 

The results are different, though -- contrary to the example you have in the documentation. Perhaps because I use different initial values, my system is more sensitive??

3. If I use the transformation `structural_simplify` first, the resulting simulations crash.

**Questions**
A: What is the difference between `dae_index_lowering` and `structural_simplify`? For my system, `dae_index_lowering` seems to give ok results (in the sense that the system can be simulated), while `structural_simplify` does not.

B: This system actually has only 2 initial values which can be specified freely. In most books on DAEs that I have seen, it is common to denote the variables for which freely selectable values can be given, by *state*. The choice of state is not unique -- any invertible transformation of states is also a state. This concept of state is often interpreted as the "memory" of the system, in the sense that if the state value is given at time 0, the model + *future* inputs is sufficient to predict the future. In other words, with the state known, it is not necessary to know the past inputs to predict the future.

In MTK, "state" seems to be used for the unknowns instead. The unknowns are sometimes referred to as the *descriptor* in DAE literature. In the book "Continuous System Modeling" by Francois E. Cellier, Springer, 1991, he talks about a "set of internal variables including both the state variables and any auxiliary algebraic variables".  My understanding is that Cellier uses the word "state" in the classical meaning of "memory". 

Since "states" in the classical meaning are the freely selectable initial values, it follows that all other unknowns can be found by solving algebraic constraints. In Modelica (which I know better than MTK...), it normally suffices to specify the "states" in the classical meaning. HOWEVER, if the additional algebraic constraints are implicit and have multiple possible solutions, it is possible to give good initial guesses to the algebraic solver. But it is clear whether *states* are specified (i.e., with keyword `fixed = true`) or initial guesses of algebraic variables (keyword `fixed = false`).

In MTK at the moment, all unknowns are denoted "states" -- which is confusing to me. It also seems to be the case that all these unknowns *must* be specified, and also must be specified in the sense of fulfilling the algebraic constraints. If the algebraic constraints are *linear* in the algebraic unknowns, it shouldn't be necessary to specify the algebraic initial values.

-- Is my understanding above correct? I.e., you use "state" to mean all unknowns? 
-- Is it required to specify initial values for all "states"? [Which most of the literature I'm familiar with would denote the "descriptor" or the "unknowns"]
-- Is it possible to specify that the initial values of *states* (in the classical meaning) are "fixed", while only approximate guesses for algebraic expressions are given? In other words so that the initial values of the algebraic values are refined to completely satisfy the algebraic constraints while the *states* (in the classical meaning) are untouched?

C: I understand that the `ODEProblem()` constructor puts the index 1 problem in mass matrix form. OK. But I haven't been able to find a documentation of `ODAEProblem()`...

-- What does `ODAEProblem()` do? Change the system to ODEs?

== ==
OK - lots of questions... essentially things I need to understand in order to start to use MTK :-o.

**Comment by xtalax** [comment]
"States" is used to refer to unknowns in MTK. If an unknown is fully determined by the system of equations, it will be moved from the list of `states` to the list of `observed` variables (calculated automatically from the states) when you call `structural_simplify`.

It shouldn't be needed to specify defaults for all variables at the problem construction stage, just those that are states, and those that are parameters. If you are unsure which variables will end up states or observed or parameters after structural simplification, you can supply them as a dict of defaults at the system construction stage.

I don't believe it is possible to specify that a state is fixed.

`structural_simplify` will call `dae_index_lowering`, using both will likely cause an error.

As for ODAEProblem, I am also not too clear on this, maybe @YingboMa can explain.

**Comment by B-LIE** [comment]
Thanks, @xtalax. 

```julia
@parameters g
@variables t, q₁(t), q₂(t), v₁(t), v₂(t), λ(t)
D = Differential(t)

eqs = [D(q₁) ~ v₁,
        D(q₂) ~ v₂,
        D(v₁) ~ -λ*q₁,
        D(v₂) ~ -λ*q₂ - g,
        0 ~ q₁^2 + q₂^2 - 1]

@named sys = ODESystem(eqs)
```
followed by `structural_simplify(sys)` gives:
![image](https://user-images.githubusercontent.com/54220415/200345090-02180f8f-209e-43a5-9662-f01c10c7afc3.png)

If I instead do `dae_index_lowering`, I get:

![image](https://user-images.githubusercontent.com/54220415/200345419-0c0cd627-ae7c-4b2e-875e-3a6a48a45947.png)

There is now problem in doing either of `structural_simplify |> dae_index_lowering |> sys` or `dae_index_lowering |> structural_simplify sys`. In both cases, it is the first transformation that defines the result and the second does (apparently) nothing. And the results are different.

Regarding simulation of this system -- I am only able to get reliable results when I use the `dae_index_lowering` transformation.

**Comment by ChrisRackauckas** [comment]
Just do `structural_simplify`. Using the internal pieces comes at your own risk, and doing it without alias elimination and other bits can lead to unstable systems.

**Comment by B-LIE** [comment]
OK. I'll stick with `structural_simplify` ... (it is a pity that that does not lead to a stable index reduction of the pendulum system, though -- maybe I do something wrong?)

**Comment by YingboMa** [comment]
ModelingToolkit doesn't have dynamic state selection yet. There's only one degree of freedom in pendulum's position, but neither `x` nor `y` can parameterize pendulum's position smoothly globally. E.g. when `x = 0` or `y = 0`, then they break down. The solution is to write the system in a globally non-singular coordinate. For example:
```julia
using ModelingToolkit, OrdinaryDiffEq
@parameters g L
@variables t q₁(t) q₂(t) v₁(t) v₂(t) λ(t) θ(t)
D = Differential(t)

eqs = [D(q₁) ~ v₁,
       D(q₂) ~ v₂,
       D(v₁) ~ -λ*q₁,
       D(v₂) ~ -λ*q₂ - g,
       q₁ ~ L * sin(θ),
       q₂ ~ L * cos(θ),]

@named model = ODESystem(eqs)
sys = structural_simplify(model)
prob = ODEProblem(sys, [θ => pi/4, D(θ) => 0.01, λ => 0.0, D(D(θ)) => 0.0], (0, 10.0), [g => 9.8, L => 1.0])
sol = solve(prob, Rodas5P())

using Plots
plot(sol, idxs=[D(θ), θ])
```

**Comment by B-LIE** [comment]
Thanks. I understand that using a globally non-singular coordinate is advantageous. However, your example at https://mtk.sciml.ai/stable/mtkitize_tutorials/modelingtoolkitize_index_reduction/ seems to handle the problem well... so why doesn't my symbolic implementation of the same model work?

**Comment by YingboMa** [comment]
I should change the tutorial example to use theta. It used to just drop the lower index constraints, although it doesn't have the singularity problem, the solution would drift. We then implemented dummy derivative, so it no longer violates constraints, but would have the singularity problem.

**Comment by ChrisRackauckas** [comment]
States was renamed to unknowns. Tutorials were updated.
