### ISSUE TITLE
thoughts on being stricter when constructing Problems from systems?

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#1933]
```julia
using ModelingToolkit

@parameters t p=1 p2=1
@variables x(..) = 10.
D = Differential(t)

eqs = [D(x(t)) ~ -p*x(t)]

@named de = ODESystem(eqs; tspan=(0, 1000.0))
prob = ODEProblem(de, [x => 0], (0, 50), [p => 0])
@test prob.u0 == [10.]

prob2 = ODEProblem(de, [x(t) => 0], (0, 50), [p2 => 0]) # notice x(t) not x
@test prob2.u0 == [0]
```
While I don't think many people use CallWith currently, I imagine in the future for PDEs and Delays, it will be used more. 
My guess is this will be a pretty common mistake people (me) will make. 

This is another example when I forget to change a variable name, which happens semi frequently

```julia 
@variables x(t) = 10.
D = Differential(t)
eqs = [D(x) ~ -p*x]
myvar = 1
@named de = ODESystem(eqs; tspan=(0, 1000.0))
prob = ODEProblem(de, [myvar => 0], (0, 50), [p => 0])
```

also defaults for observables 
```julia
prob = ODEProblem(structural_simplify(ODESystem(x(t) ~ 0;tspan=(0, 100), name=:foo)), [x(t)=>1])
@test ModelingToolkit.defaults(probfoo.f.sys)[x(t)] == 10
```

Thoughts on defaulting to enforcing that all symbols in provided u0map/paramaps are in states/observed/parmeters?
A warning is another possibility. 
Is there a use case for providing values in the maps that don't occur in the system that I don't see?

we should probably add a label for debug/checking features like this and https://github.com/SciML/ModelingToolkit.jl/issues/1747

**Comment by ChrisRackauckas** [comment]
Yeah it should be strict and check/warn/error.

**Comment by anandijain** [comment]
another case of potential confusion is when the default values are not satisfiable with provided equations

```julia 
using ModelingToolkit, DifferentialEquations
@parameters t
D = Differential(t)
@variables x(t)=1 y(t)=100

eqs = [
    D(x) ~ 0,
    y ~ 0
]

@named sys = ODESystem(eqs)
ssys = structural_simplify(sys)
prob = ODEProblem(ssys, [], (0, 100))
sol = solve(prob)
```
It doesn't cause any problems since `all(iszero, sol[y])` but could lead to confusion.

I think this case is maybe a bit harder though

**Comment by ChrisRackauckas** [comment]
These checks/warns/errors have been added. But also, these cases now just work.
