### ISSUE TITLE
DOC issue: link to a 403 page

### ISSUE THREAD

**Issue by bertrandhaut** [SciML/ModelingToolkit.jl#1935]
Dear,

On the documentation page https://mtk.sciml.ai/stable/basics/Events/ there is a link to https://docs.sciml.ai/stable/modules/DiffEqDocs/features/callback_functions/ 

At time of writing, this page leads to
```
403 Forbidden
Code: AccessDenied
Message: Access Denied
RequestId: T1W5YMEJ3CFD9574
HostId: U2/ILfryw+a2lO09R3qIwh7XbR+kCoGPwbe+WYuyPUDSe1VO6reBYNhV+19JlH9YOIJ9kamkqGs=
```

**Comment by YingboMa** [comment]
It seems to be fixed now.
