### ISSUE TITLE
independent variable for complex numbers not working

### ISSUE THREAD

**Issue by davidschlegel** [SciML/ModelingToolkit.jl#1947]
When I explicitly define variables to be complex, ModelingToolkit does not find the independent variable.
Here is a minimal working example that gives the error:
```
using ModelingToolkit
using Symbolics
@variables t::Real, α(t)::Complex
D = Differential(t)
ODESystem(D(α) ~ α, t; name=:odesys)

>>>ERROR: ArgumentError: An ODESystem can only have one independent variable.
```

I believe that somehow the function `ModelingToolkit.iv_from_nested_derivative` needs to be adjusted to work for this type.

**Comment by lamorton** [comment]
AFAIK complex numbers aren't yet supported: https://github.com/SciML/ModelingToolkit.jl/issues/1456#issuecomment-1039680030

**Comment by YingboMa** [comment]
Close because of duplication.
