### ISSUE TITLE
Error introduced somewhere between MTK 8.22.1 and 8.29.1 - Regression

### ISSUE THREAD

**Issue by xtalax** [SciML/ModelingToolkit.jl#1948]
A new error has been introduced - which is not present if an earlier version of MTK is used. The error is suggestive of a program error, occurring within a Symbolics macro with an `UndefVarError`.  

I was not able to reproduce in an MWE, but the error has come up consistently for other users, see the discussion 
https://github.com/SciML/MethodOfLines.jl/issues/189 (full stacktrace)
https://github.com/SciML/MethodOfLines.jl/issues/194

Isolating this will probably take stepping through MTK versions between 8.22.1 and 8.29.1 and seeing where it is introduced, and analysing surrounding code. I'm willing to help in this, but thought it best to let you know about it first.

**Comment by YingboMa** [comment]
It's a bug in the discretization code. `Num` should never appear inside an expression
```julia
julia> sys, tspan = SciMLBase.symbolic_discretize(pdesys, discretization);

julia> x = equations(sys)[1].lhs
Differential(t)((C(t))[2]) + ifelse(vip1(t) > 0, (5.0(C(t))[2] - 5.0(C(t))[1])*vip1(t), (5.0(C(t))[3] - 5.0(C(t))[2])*vip1(t))

julia> typeof.(Symbolics.arguments(Symbolics.arguments(x)[2]))
3-element Vector{DataType}:
 Term{Bool, Nothing}
 Num
 Num
```

**Comment by xtalax** [comment]
Worth knowing, thanks. I'll add this assumption to the symbolics docs.
