### ISSUE TITLE
Defining mixed stock flow models in ModelingToolkit

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#196]
Observing the basic differences between DSL (PUMAS and DiffEQBiological) and IR, ModelingToolkit should include in the definition and characteristics of the variable set the distinction between **state/stock and flow variables**. This is an important dimension of continuous time dynamical **systems** in economics, climate change, hydrology, energy and others.  There are implications in terms of order of the ODE system in flow or in stock of the continuous dynamical system as well as the potential order reduction procedure built-in.

There are implications in terms exact discrete equivalents to the continuous dynamical system when the model is matched to actual data measurements.

Another issue is observable/non-observable variables. non-observable variables can be substituted by differentiation thus increasing the order of the dynamical system. This can also lead to parameter identification problems. Should I raise this as a separate issue or is it part of the definition of the set of variables?

Finally, where should I address   @ChrisRackauckas to envisage the creation of a package dealing with **continuous time dynamical systems** in economics and other fields mentioned above? A sort of DiffEqEcon that would be a clone of PUMAS, DiffEqBiological, QuantumOptics and JuliaDynamics based on ModellingTookit as an IR.

**Comment by ChrisRackauckas** [comment]
>Finally, where should I address @ChrisRackauckas to envisage the creation of a package dealing with continuous time dynamical systems in economics and other fields mentioned above? A sort of DiffEqEcon that would be a clone of PUMAS, DiffEqBiological, QuantumOptics and JuliaDynamics based on ModellingTookit as an IR.

A DSL that targets ModelingToolkit would be the right thing.

>Another issue is observable/non-observable variables. non-observable variables can be substituted by differentiation thus increasing the order of the dynamical system. This can also lead to parameter identification problems. Should I raise this as a separate issue or is it part of the definition of the set of variables?

Yes, this is something we need to mark for components.

>Observing the basic differences between DSL (PUMAS and DiffEQBiological) and IR, ModelingToolkit should include in the definition and characteristics of the variable set the distinction between state/stock and flow variables. This is an important dimension of continuous time dynamical systems in economics, climate change, hydrology, energy and others. There are implications in terms of order of the ODE system in flow or in stock of the continuous dynamical system as well as the potential order reduction procedure built-in.

Do you actually need this if you can instead just state equivalences between components? A flow vs stock variable just has to do with whether you bring components together by equality or a summation condition on the terms.

**Comment by ChrisRackauckas** [comment]
I think this is covered by the latest tutorials
