### ISSUE TITLE
getproperty incompatible with ParentScope and DelayParentScope

### ISSUE THREAD

**Issue by jamesjscully** [SciML/ModelingToolkit.jl#1973]
Accessing a parameter or variable whos scope was defined with `ParentScope()` errors.

```julia
using ModelingToolkit, Test
@parameters t a
p = [
     ParentScope(a)
]

level0 = ODESystem(Equation[], t, [], p; name = :level0)
level1 = ODESystem(Equation[], t, [], []; name = :level1) ∘ level0

ModelingToolkit.getname(parameters(level1)[1]) # a

level1.a # this errors, claiming a is not defined
```

**Comment by jamesjscully** [comment]
I will submit a PR for this, but there is a design decisions that I have a question

Should you be able to access variables that have been parentscoped before they reach their localscope has been created? Following the example above:

`level0.a` is defined, but 'a' really belongs in level1. My inclination is to have both defined because it could be convenient for the user to access the parameters that way, and I don't see any harm in it.

If I want to

**Comment by YingboMa** [comment]
I would be inclined to cache the information during construction so that `sys.a` can be fast even for large and deeply nested models.

**Comment by ChrisRackauckas** [comment]
Fixed in the v9 with the enforced complete.
