### ISSUE TITLE
paramters in optimizations FAQ

### ISSUE THREAD

**Issue by kakila** [SciML/ModelingToolkit.jl#1982]
The block in the FAQ

https://github.com/SciML/ModelingToolkit.jl/blob/9271b4d9b72bf38a5336f18100922cad111b84b8/docs/src/basics/FAQ.md?plain=1#L90

Is not consistent: what is `p` in this case?
From the first line one would infer `p` is a vector of numeric values of the parameters.
From the second line one would infer `p` is a vector of Symbolic parameters.

Am I seeing this wrongly?

**Comment by kakila** [comment]
I am not so sure. It is useful that remake accepts maps, but when used in optimization the input to the loss function will be a vector. So the user still needs a quick way to assign elements of the vector to a map. This is specially true if the optimization does not cover all the parameters in the model.
```julia
function loss(pv) # receives a vector of parameter values, might not cover all model parameters
  # build map for ModelingToolkit model
   _pm = subset_model_params .=> pv[permutation]  # The permutation orders the parameter vector,
                                                  # could be the identity.
                                                  # There might be cleverer way to do this
  remake(p = _pm)
  solve(...)
  ...
end

```

**Comment by ChrisRackauckas** [comment]
Either all handled in the remake already or is an instance of https://github.com/SciML/ModelingToolkit.jl/issues/2338
