### ISSUE TITLE
A bug in discrete events 

### ISSUE THREAD

**Issue by yanshuchang** [SciML/ModelingToolkit.jl#1984]
```julia

function switch(;name)

    @named   p   =  Pin()
    @named   n   =  Pin()

    #@parameters sig = m
    
    sts = @variables begin
        v(t) 
        i(t) 
    end    


    sc = [10] => [i ~ 0]

    eqs = [v ~ p.v - n.v
           0 ~ p.i + n.i
           i ~ p.i]
   
    injection = (t == 10) => [i ~ 0]
           
    modelll=compose(ODESystem(eqs, t, sts, []; name=name), p, n)
    
    @named modelf = ODESystem(modelll, t, [], []; discrete_events = injection)
    
    return modelf

end


@named     igbt1 = switch()

```

**Comment by yanshuchang** [comment]
MethodError: no method matching ODESystem(::ODESystem, ::Num, ::Vector{Any}, ::Vector{Any}; name=:modelf, discrete_events=t == 10 => Equation[i(t) ~ 0])
Closest candidates are:
  ODESystem(::Any, ::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/ModelingToolkit/YHIP8/src/systems/diffeqs/odesystem.jl:119 got unsupported keyword arguments "name", "discrete_events"
  ODESystem(::Any, ::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/ModelingToolkit/YHIP8/src/systems/diffeqs/odesystem.jl:119 got unsupported keyword arguments "name", "discrete_events"
  ODESystem(::Any, ::Any, ::Any, ::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any) at ~/.julia/packages/ModelingToolkit/YHIP8/src/systems/diffeqs/odesystem.jl:119 got unsupported keyword arguments "name", "discrete_events"

**Comment by yanshuchang** [comment]
I got such error, why?

**Comment by YingboMa** [comment]
Your syntax is wrong.
```julia
julia> function switch(;name)

           @named   p   =  Pin()
           @named   n   =  Pin()

           #@parameters sig = m

           sts = @variables begin
               v(t)
               i(t)
           end


           sc = [10] => [i ~ 0]

           eqs = [v ~ p.v - n.v
                  0 ~ p.i + n.i
                  i ~ p.i]

           injection = t == 10.0 => [i ~ 0]
           modelll=compose(ODESystem(eqs, t, sts, []; name=name, discrete_events = injection), p, n)
       end
switch (generic function with 1 method)

julia> function switch(;name)

julia> function switch(;name)

julia> @named     igbt1 = switch()
Model igbt1 with 3 (5) equations
States (6):
  v(t)
  i(t)
  p₊v(t) [defaults to 1.0]
  p₊i(t) [defaults to 1.0]
⋮
Parameters (0):
```

**Comment by yanshuchang** [comment]
Got it，thanks very much ！！
