### ISSUE TITLE
using Matrix

### ISSUE THREAD

**Issue by iremalti** [SciML/ModelingToolkit.jl#2005]
I would like to recreate the FixedTranslation component from the Modelica library Planarmechanics.Parts.FixedTranslation in Julia.  

A link to the Planarmechanics.Parts.FixedTranslation component is  https://github.com/dzimmer/PlanarMechanics/blob/3a90260b9a77850a05d04ad46b19bed6a49738b8/PlanarMechanics/Parts/FixedTranslation.mo#L43

The Code is

@connector function frame_a(;name, pos=[0., 0.], phi=0.0, _f=[0., 0.], tau=0.0)
   
    sts0 = @variables pos(t)[1:2,1]=pos phi(t) f(t)[1:2,1]=_f [connect=Flow] tau(t) [connect=Flow]  
    sts1 =[Symbolics.scalarize.(sts0)...;]
    sts2 =[sts1...;]
    ODESystem(Equation[], t, sts2, []; name=name)
end

function FixedTranslation(;name, r =[0. , 0.5], r0 =[0. , 0.],_R=[0. 0.;0. 0.], u =[0. , 0.])     
    @named fa= frame_a() 
    @named fb= frame_a()
    ps= @parameters r[1:2,1]= r
    sts= @variables  r0(t)[1:2,1]=r0 R(t)[1:2, 1:2]= _R  u(t)[1:2,1] =u
    R= [cos(fa.phi) -sin(fa.phi)
        sin(fa.phi) cos(fa.phi)]
    u = reshape([fb.f[2], -fb.f[1]], (1,2))
    eqs= [ R * r .~ r0                                                        
            fa.pos .+ r0 .~ fb.pos
            fa.phi .~ fb.phi
            fa.f .+ fb.f .~ 0
            fa.tau .+ fb.tau .+ u * r0 .~ 0]
    seqs = [Symbolics.scalarize.(eqs)...;]
    compose(ODESystem(seqs, t, sts, ps; name=name), n)
end

@named l = FixedTranslation()

This  fails with the following message:

ERROR: MethodError: no method matching hasmetadata(::Matrix{Num}, ::Type{Symbolics.VariableDefaultValue})
Closest candidates are:
  hasmetadata(::SymbolicUtils.Symbolic, ::Any) at ~/.julia/packages/SymbolicUtils/qulQp/src/types.jl:15
  hasmetadata(::Complex{Num}, ::Any) at ~/.julia/packages/Symbolics/FGTCH/src/Symbolics.jl:163
  hasmetadata(::Num, ::Any) at ~/.julia/packages/Symbolics/FGTCH/src/Symbolics.jl:163
Stacktrace:
 [1] hasdefault(v::Matrix{Num})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/EUBAR/src/utils.jl:245
 [2] collect_defaults!
   @ ~/.julia/packages/ModelingToolkit/EUBAR/src/utils.jl:259 [inlined]
 [3] process_variables!(var_to_name::Dict{Any, Any}, defs::Dict{Any, Any}, vars::Vector{Matrix{Num}})
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/EUBAR/src/utils.jl:252
 [4] ODESystem(deqs::Vector{Equation}, iv::Num, dvs::Vector{Symbolics.Arr{Num, 2}}, ps::Vector{Symbolics.Arr{Num, 2}}; controls::Vector{Num}, observed::Vector{Equation}, systems::Vector{ODESystem}, tspan::Nothing, name::Symbol, default_u0::Dict{Any, Any}, default_p::Dict{Any, Any}, defaults::Dict{Any, Any}, connector_type::Nothing, preface::Nothing, continuous_events::Nothing, discrete_events::Nothing, checks::Bool, metadata::Nothing)
   @ ModelingToolkit ~/.julia/packages/ModelingToolkit/EUBAR/src/systems/diffeqs/odesystem.jl:189
 [5] FixedTranslation(; name::Symbol, r::Vector{Float64}, r0::Vector{Float64}, _R::Matrix{Float64}, u::Vector{Float64})
   @ Main ~/Desktop/Fahrrad/vehicle/test/start.jl:75
 [6] top-level scope
   @ ~/.julia/packages/ModelingToolkit/EUBAR/src/systems/abstractsystem.jl:868

**Comment by ChrisRackauckas** [comment]
Transform from a symbolic matrix to a matrix of symbolics.
