### ISSUE TITLE
Tests for Index Reduction and SCC fail 

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#2012]
On Julia 1.8.4 and MTK v8.38.0, 

│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
┌ Warning: This method is deprecated in favor of using NonlinearSolve.jl. Note that an ODEProblem
│ can be converted into a steady state NonlinearProblem via
│ `NonlinearProblem(prob::ODEProblem)`. The algorithm `NLSolveJL` as part of the
│ SciMLNLSolve.jl set of nonlinear solvers for NonlinearSolve.jl is equivalent to
│ SteadyStateDiffEq.jl's default `SSRootfind` (with a few improvements).
│
│ See [the documentation of NonlinearSolve.jl](https://docs.sciml.ai/NonlinearSolve/stable/)
│ for more details.
└ @ SteadyStateDiffEq C:\Users\Denis\.julia\packages\SteadyStateDiffEq\1di7r\src\solve.jl:8
Test Summary:          | Pass  Total   Time
SteadyStateSystem Test |   24     24  10.9s
"μ = 0.49 ± 0.05"
"μmod = 0.54 ± 0.02"
Test Summary:  | Pass  Total     Time
SDESystem Test |   95     95  1m18.7s
Test Summary:        | Pass  Total   Time
NonlinearSystem Test |   38     38  22.9s
Test Summary:   | Pass  Total     Time
JumpSystem Test |   23     23  1m28.6s
Test Summary:    |Time
Constraints Test | None  0.2s
Test Summary:  | Pass  Total   Time
Reduction Test |   43     43  28.6s
┌ Info: Expanding
└   namespace = :ground₊g
┌ Info: Expanding
└   namespace = :ground
┌ Info: Expanding
└   namespace = :source₊p
┌ Info: Expanding
└   namespace = :source₊n
┌ Info: Expanding
└   namespace = :source
┌ Info: Expanding
└   namespace = :rc_comp₊p
┌ Info: Expanding
└   namespace = :rc_comp₊n
┌ Info: Expanding
└   namespace = :rc_comp₊resistor₊p
┌ Info: Expanding
└   namespace = :rc_comp₊resistor₊n
┌ Info: Expanding
└   namespace = :rc_comp₊resistor
┌ Info: Expanding
└   namespace = :rc_comp₊capacitor₊p
┌ Info: Expanding
└   namespace = :rc_comp₊capacitor₊n
┌ Info: Expanding
└   namespace = :rc_comp₊capacitor
┌ Info: Expanding
└   namespace = :rc_comp
┌ Info: Expanding
└   namespace = nothing
Test Summary:   | Pass  Total     Time
Components Test |   44     44  1m05.9s
Test Summary: | Pass  Total  Time
print_tree    |    1      1  0.6s
Test Summary:  | Pass  Total  Time
Error Handling |    2      2  0.8s
┌ Warning: Unrecognized keyword arguments found. Future versions will error.
│ The only allowed keyword arguments to `solve` are:
│ (:dense, :saveat, :save_idxs, :tstops, :tspan, :d_discontinuities, :save_everystep, :save_on, :save_start, :save_end, :initialize_save, :adaptive, :abstol, :reltol, :dt, :dtmax, :dtmin, :force_dtmin, :internalnorm, :controller, :gamma, :beta1, :beta2, :qmax, :qmin, :qsteady_min, :qsteady_max, :qoldinit, :failfactor, :calck, :alias_u0, :maxiters, :callback, :isoutofdomain, :unstable_check, :verbose, :merge_callbacks, :progress, :progress_steps, :progress_name, :progress_message, :timeseries_errors, :dense_errors, :weak_timeseries_errors, :weak_dense_errors, :wrap, :calculate_error, :initializealg, :alg, :save_noise, :delta, :seed, :alg_hints, :kwargshandle, :trajectories, :batch_size, :sensealg, :advance_to_tstop, :stop_at_next_tstop, :default_set, :second_time, :prob_choice, :alias_jump, :alias_noise)
│
│ See https://diffeq.sciml.ai/stable/basics/common_solver_opts/ for more details.
│
│ Set kwargshandle=KeywordArgError for an error message.
│ Set kwargshandle=KeywordArgSilent to ignore this message.
└ @ DiffEqBase C:\Users\Denis\.julia\packages\DiffEqBase\wXM5P\src\solve.jl:889
Unrecognized keyword arguments: [:mass_matrix]

┌ Warning: Assignment to `u0` in soft scope is ambiguous because a global variable by the same name exists: `u0` will be treated as a new local. Disambiguate by using `local u0` to suppress this warning or `global u0` to assign to the existing global variable.
└ @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:144
┌ Warning: Assignment to `p` in soft scope is ambiguous because a global variable by the same name exists: `p` will be treated as a new local. Disambiguate by using `local p` to suppress this warning or `global p` to assign to the existing global variable.
└ @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:153
┌ Warning: Assignment to `prob_auto` in soft scope is ambiguous because a global variable by the same name exists: `prob_auto` will be treated as a new local. Disambiguate by using `local prob_auto` to suppress this warning or `global prob_auto` to assign to the existing global variable.
└ @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:158
┌ Warning: Assignment to `sol` in soft scope is ambiguous because a global variable by the same name exists: `sol` will be treated as a new local. Disambiguate by using `local sol` to suppress this warning or `global sol` to assign to the existing global variable.
└ @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:159
┌ Warning: Instability detected. Aborting
└ @ SciMLBase C:\Users\Denis\.julia\packages\SciMLBase\QqtZA\src\integrator_interface.jl:525
Index Reduction & SCC: Test Failed at C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:160
  Expression: sol.retcode == ReturnCode.Success
   Evaluated: SciMLBase.ReturnCode.Unstable == SciMLBase.ReturnCode.Success
Stacktrace:
 [1] macro expansion
   @ C:\Users\Denis\AppData\Local\Programs\Julia-1.8.4\share\julia\stdlib\v1.8\Test\src\Test.jl:464 [inlined]
 [2] top-level scope
   @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:160
Index Reduction & SCC: Test Failed at C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:161
  Expression: norm((sol[x] .^ 2 + sol[y] .^ 2) .- 1) < 0.01
   Evaluated: NaN < 0.01
Stacktrace:
 [1] macro expansion
   @ C:\Users\Denis\AppData\Local\Programs\Julia-1.8.4\share\julia\stdlib\v1.8\Test\src\Test.jl:464 [inlined]
 [2] top-level scope
   @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:161
┌ Warning: Instability detected. Aborting
└ @ SciMLBase C:\Users\Denis\.julia\packages\SciMLBase\QqtZA\src\integrator_interface.jl:525
Index Reduction & SCC: Test Failed at C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:160
  Expression: sol.retcode == ReturnCode.Success
   Evaluated: SciMLBase.ReturnCode.Unstable == SciMLBase.ReturnCode.Success
Stacktrace:
 [1] macro expansion
   @ C:\Users\Denis\AppData\Local\Programs\Julia-1.8.4\share\julia\stdlib\v1.8\Test\src\Test.jl:464 [inlined]
 [2] top-level scope
   @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:160
Index Reduction & SCC: Test Failed at C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:161
  Expression: norm((sol[x] .^ 2 + sol[y] .^ 2) .- 1) < 0.01
   Evaluated: NaN < 0.01
Stacktrace:
 [1] macro expansion
   @ C:\Users\Denis\AppData\Local\Programs\Julia-1.8.4\share\julia\stdlib\v1.8\Test\src\Test.jl:464 [inlined]
 [2] top-level scope
   @ C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\structural_transformation\index_reduction.jl:161
Test Summary:             | Pass  Fail  Broken  Total   Time
StructuralTransformations |   45     4       2     51  45.9s
  Utilities               |    6                    6   0.6s
  Index Reduction & SCC   |    8     4       1     13  29.7s
  Tearing                 |   27             1     28  13.1s
  Bareiss                 |    4                    4   2.4s
ERROR: LoadError: Some tests did not pass: 45 passed, 4 failed, 0 errored, 2 broken.
in expression starting at C:\Users\Denis\.julia\packages\ModelingToolkit\wAABB\test\runtests.jl:29
ERROR: Package ModelingToolkit errored during testing

(@v1.8) pkg>

**Comment by ChrisRackauckas** [comment]
Yes, this one just took a bit to track down because it was so simple and in the numerical details. Solved by https://github.com/SciML/OrdinaryDiffEq.jl/pull/1824
