### ISSUE TITLE
Variable metadata connector documentation

### ISSUE THREAD

**Issue by xlxs4** [SciML/ModelingToolkit.jl#2013]
In the [documentation page](https://docs.sciml.ai/ModelingToolkit/dev/basics/ContextualVariables/#Variable-metadata-[Experimental/TODO]) there's no mention of the two out of the three `connect` metadata. `Equality` and `Stream` are not mentioned/explained in the docs, only `Flow` is. The available metadata are [here](https://github.com/SciML/ModelingToolkit.jl/blob/master/src/variables.jl#L16).
You can also mention what the default behavior is, if none of the three are explicitly passed.

From the respective Discourse thread [here](https://discourse.julialang.org/t/modelingtoolkit-variable-metadata-for-connectors/92056):

It’s the same as Modelica:

- `Equality` variables connect by making values equal. For example, connecting pins in an electrical circuit makes the voltages equal at the junction.
- `Flow` variables connect by making the sum zero. For example, connecting pins in an electrical circuit makes the current sum to zero at the junction.
- `Stream` connectors are for fluids. See [15 Stream Connectors‣ Modelica® Language Specification version 3.6-dev](https://specification.modelica.org/master/stream-connectors.html) and [https://build.openmodelica.org/Documentation/Modelica%204.0.0/Resources/Documentation/Fluid/Stream-Connectors-Overview-Rationale.pdf](https://build.openmodelica.org/Documentation/Modelica%204.0.0/Resources/Documentation/Fluid/Stream-Connectors-Overview-Rationale.pdf).

**Comment by ChrisRackauckas** [comment]
This is all documented now.
