### ISSUE TITLE
Replacing parameters with expressions

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#2037]
It would be good to have support for replacing parameters with more general expressions. This comes up when trying to solve interesting problems using a model from a model library, for instance, from MTK stdlib. It is common practice to simulate things like time varying parameters, and to make, e.g., controller gains functions of some external signal. Currently, I'm aware of no method to achieve this other than to completely redefine the model components, which defeats the purpose of having a component/model library.

Take the [`Rotational.Inertia`](https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/main/src/Mechanical/Rotational/components.jl#L42) component from MTK stdlib  as an example. This component was implemented assuming that the value of the inertia is a constant floating-point value. Trying to pass anything other than a float in for `J` fails due to the check `J > 0`. The constructor also creates `@parameters J=J` so if `J` is not a float, I get into trouble.

MTKstdlib is full of stuff like this, so if I would like to use the stdlib for this kinds of experiments, I'd need to be able to replace the parameter `J` with expressions like `J ~ f(t)` or `J ~ other_component.x` after I have instantiated my model using library components. Ideally, this should promote `J` from a `@parameter´ to an `@variable` as well, so that the results are accessible in the solution.

In this case, it would be nice to have some method to replace the parameter `J` in the instantiated model with any arbitrary expression of time and other `@variables`. It would also be good to come up with best practices for how to implement components like [`Rotational.Inertia`](https://github.com/SciML/ModelingToolkitStandardLibrary.jl/blob/main/src/Mechanical/Rotational/components.jl#L42)  such that we do not assume that the input argument is a floating-point value.

**Comment by baggepinnen** [comment]
Modelica has the [`replacable` keyword](https://mbe.modelica.university/components/architectures/replaceable/) to accomodate usecases like this

and Modia uses something they call [model merging](https://modiasim.github.io/Modia.jl/stable/tutorial/Modeling.html#.2-Merging-models).

**Comment by YingboMa** [comment]
Yes
