### ISSUE TITLE
Add a misc metadata field which allows for taking Any

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#2061]
This is good to be used as a passthrough for upstream libraries to dump metadata that they don't know how to handle.

**Comment by xtalax** [comment]
Isn't this handled already by the metadata fields?

**Comment by YingboMa** [comment]
Yeah https://github.com/SciML/ModelingToolkit.jl/blob/16c1e8ff118cbd8336da74f8cf8c615230f5b9ce/src/systems/diffeqs/odesystem.jl#L113-L116

**Comment by xtalax** [comment]
I'd take this a step further and offer a `Ref{Any}` metadata field to all the SciMLBase types that can be used after creation to save any misc metadata, an issue for elsewhere though

**Comment by ChrisRackauckas** [comment]
`@variable x [misc = some_weird_type]`?

**Comment by YingboMa** [comment]
> I'd take this a step further and offer a Ref{Any} metadata field to all the SciMLBase types that can be used after creation to save any misc metadata, an issue for elsewhere though

You can just do `@set! sys.metadata = something`

**Comment by YingboMa** [comment]
> @variable x [misc = some_weird_type]?

Ah, you are asking for variables.

**Comment by ChrisRackauckas** [comment]
Yes for variables, not systems.
