### ISSUE TITLE
Incorrect Jacobian size with `jac=false` and `sparse=true`

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#2064]
In the following, `osys` has three states but a 2x3 Jacobian prototype is generated via `sparse=true` and `jac=false`, while `sparse=true` and `jac=true` give a 3x3. 
```julia
using Catalyst
using OrdinaryDiffEq
using IfElse

@variables t
@variables T(t) [isbcspecies=true]
@variables (species(t))[1:2]
@variables (k(t))[1:2] [isbcspecies=true, irreducible=false]

heatrate = 1.0
coolrate = -1.0

D = Differential(t)
function Tgrad(t)
    return IfElse.ifelse(t > 15.0, coolrate, 
        IfElse.ifelse(t < 5.0, heatrate, 0.0)
    )
end
function calc_rates(T)
    base_rates = [0.5, 0.5]
    # Only the reverse reaction is temperature dependent for the sake of this example
    return [base_rates[1], base_rates[2] * T]
end

@named rate_model = ODESystem([
    D(T) ~ Tgrad(t);
    k .~ calc_rates(T)
], t)

rxs = [
    Reaction(k[1], [species[1]], [species[2]], [1], [1]),
    Reaction(k[2], [species[2]], [species[1]], [1], [1])
]

T0 = 0.0
u0 = [10.0, 0.0]
u0map = Pair.(collect(species), u0)
kmap = Pair.(collect(k), calc_rates(T0))
u0map = vcat(u0map, kmap)
push!(u0map, Pair(T, T0))

tspan = (0.0, 20.0)

@named rs = ReactionSystem(rxs, t, collect(species), collect(k); checks=false, constraints=rate_model)
osys = structural_simplify(convert(ODESystem, rs))
oprob = ODEProblem(osys, u0map, tspan; sparse=true, jac=false)
```
gives that
```julia
julia> oprob.f.jac_prototype
2×3 SparseArrays.SparseMatrixCSC{Float64, Int64} with 6 stored entries:
 0.0           2.33928e-314  2.37266e-314
 2.37266e-314  0.0           2.37267e-314
```
If `jac=true` then one correctly gets a 3x3 Jacobian.

This is taken from the following Catalyst issue:

https://github.com/SciML/Catalyst.jl/issues/586

@joegilkes I think this has moved beyond a Catalyst issue now, so I'm opening an issue at ModelingToolkit. Hopefully someone here can help with what is going on in your example when `sparse=true` but `jac=false`.

**Comment by isaacsas** [comment]
If it helps, the actual equations are
```julia
julia> equations(osys)
3-element Vector{Equation}:
 Differential(t)((species(t))[1]) ~ (k(t))[2]*(species(t))[2] - (k(t))[1]*(species(t))[1]
 Differential(t)((species(t))[2]) ~ (k(t))[1]*(species(t))[1] - (k(t))[2]*(species(t))[2]
 Differential(t)(T(t)) ~ ifelse(t > 15.0, -1.0, ifelse(t < 5.0, 1.0, 0.0))
```
So the system just has three ODEs.

**Comment by isaacsas** [comment]
This seems related to `jacobian_sparsity`'s current implementation at https://github.com/SciML/ModelingToolkit.jl/blob/af025524ba90cf51f8e5354eb1d0d940c6b06618/src/systems/diffeqs/abstractodesystem.jl#L217

`torn_system_jacobian_sparsity` is being called and returning a 2x3 matrix, while if one jumps to the end of that function and uses `jacobian_sparsity` on the equation's rhs one gets a 3x3.

@YingboMa is this the expected behavior? It seems like `torn_system_jacobian_sparsity` is not including the `T` state row of the Jacobian since its ODE is not dependent on other states (but it does depend on `t`).

**Comment by YingboMa** [comment]
Yeah, this is definitely is a bug.

**Comment by isaacsas** [comment]
OK, thanks for the quick fix!
