### ISSUE TITLE
Compute initial states for `u0` if `u0` is parametric

### ISSUE THREAD

**Issue by MarcBerliner** [SciML/ModelingToolkit.jl#2103]
If `u0` is known to be a parametric function, changing the parameters will affect the initial values (e.g., for ODEs) and/or the initial guess for algebraic equations (e.g., DAEs). This problem can be avoided if MTK detects any parametric initial states (when declaring `@variables u(t) = p` or `ODEProblem(sys, [u => p])`) and generates a function to recompute the initial states upon declaring new parameters.

It would be helpful if this is included in `remake` (e.g., when calling `remake(prob; p=...)`) and as an internal function (e.g., `generate_initial_states!(prob)` or something).

MWE:
```julia
using ModelingToolkit, OrdinaryDiffEq
@parameters p = 1
@variables t u(t)

eqs = [Differential(t)(u) ~ 1]

@named sys = ODESystem(eqs,t,[u],[p],tspan=(0, 10))

prob = ODEProblem(sys, [u => p])

sol = solve(prob, Tsit5())
# sol.u[end] ≈ 11

# remake the problem with new parameters
prob_new = remake(prob; p=[p => 2])
# however, u0 is still 1
# prob_new.u0[1] == 1

sol_new = solve(prob_new, Tsit5())
# sol_new.u[end] ≈ 11, and not 12
```

An ideal workflow where I can define `u(t) = p`:
```julia
using ModelingToolkit, OrdinaryDiffEq
@parameters p = 1
@variables t u(t) = p

eqs = [Differential(t)(u) ~ 1]

@named sys = ODESystem(eqs,t,[u],[p],tspan=(0, 10))

prob = ODEProblem(sys)

sol = solve(prob, Tsit5())
# sol.u[end] ≈ 11

# remake the problem with new parameters
prob_new = remake(prob; p=[p => 2])
# now, u0 is 2
# prob_new.u0[1] == 2

sol_new = solve(prob_new, Tsit5())
# sol_new.u[end] ≈ 12
```

**Comment by baggepinnen** [comment]
Would `get_u0_p` be helpful (available on master only)?
https://docs.sciml.ai/ModelingToolkit/dev/systems/ODESystem/#Composition-and-Accessor-Functions

**Comment by MarcBerliner** [comment]
Note: I edited the first comment

`get_u0_p` can help! It looks like it is doing the same thing under the hood.

I thought about this problem more, and the more significant issue is that I cannot easily abstract away the initial states inside components with parametric `u0`. For complex systems (such as batteries), end users will likely not even know the states inside the battery component and will definitely not know appropriate initial values for them. So, I cannot reasonably expect users to know anything about the states, only the parameters. If `sys` knew the default `u0map`, it would be easy to run something like `get_u0_p` for the new initial states inside `remake(prob; p=...))` or `generate_initial_states!(prob)`

**Comment by baggepinnen** [comment]
We need to step up our game when it comes to initial conditions across the board, I'll create an issue label for this to make sure we track all relevant issues. 

> If sys knew the default u0map

It does, or am I not understanding you correctly? It only knows it in it's symbolic form, i.e., it knows `u = p` in your example, and `get_u0_p` is required to process it into the numeric array. Or are you asking for `remake(prob; p=...))` to automatically handle the fact that `u` depends on `p`, and when new `p` are provided, new `u0` are automatically computed? This feature would indeed be nice to have, and this is most likely what the user would expect to happen when they change the parameters.

**Comment by MarcBerliner** [comment]
>It only knows it in it's symbolic form, i.e., it knows `u = p` in your example

The issue is that I believe it does not store the relationship `u = p`. When `ODEProblem(sys, [u => p])` is evaluated, it computes `u0` using the default or specified parameter values, stores `u0` as an array of floats, and then discards `u => p`. 

>are you asking for `remake(prob; p=...))` to automatically handle the fact that `u` depends on `p`, and when new `p` are provided, new `u0` are automatically computed? This feature would indeed be nice to have, and this is most likely what the user would expect to happen when they change the parameters.

Yeah, this is precisely what I mean. `prob` should store the necessary mapping information to make `remake(prob; p=...))` the only function a user needs to run.

**Comment by manuelbb-upb** [comment]
I am currently playing around with interacting with Function Mockup Units (FMUs) from within Julia/MTK or vice versa. For this reason, I also thought about how to provide initial values to an OD(A)E Problem when the states might be parameter-dependent or to specify which state/parameter to set after simplification, see https://github.com/SciML/ModelingToolkit.jl/issues/1836.

In the lingo of the FMI2 specification, the "ScalarVariable"s of an FMU have properties "causality", "variability" and "initial". Its similar in the [FMI3 spec](https://fmi-standard.org/docs/3.0/#ModelVariables).
These properties define the type of variable, how its value might change and how to set an initial value.
Some properties can be mapped to MTK metadata already, like "causality=parameter", "causality=input", "causality=output", "variability=constant" etc.
The "initial" property allows for 3 modes: provide an exact starting value, compute the starting value with root finding from an approximate starting value and compute the starting value from other variables.

Next week, I'd like to try mimicking some of the logic described in the FMI spec. for OD(A)E Systems.
It'll likely require new metadata, and injection of callbacks as well as some fiddling to circumvent dimensions checks on provided initial values...

Except that all sounds like a stupid idea ?
