### ISSUE TITLE
vars() function when the operation is a variable

### ISSUE THREAD

**Issue by cvanaret** [SciML/ModelingToolkit.jl#211]
Hi,
I noticed a bug in the vars() function that returns the set of variables that occur in an expression:

```
vars(exprs) = foldl(vars!, exprs; init = Set{Variable}())
function vars!(vars, O)
    isa(O, Operation) || return vars
    for arg ∈ O.args
        if isa(arg, Operation)
            isa(arg.op, Variable) && push!(vars, arg.op)
            vars!(vars, arg)
        end
    end
    return vars
end
```

If the expression is a variable, it has no arguments and is therefore not detected:

> julia> ModelingToolkit.vars(x[1])
> Set(Variable[])

on the contrary, this works:

> julia> ModelingToolkit.vars(x[1] + 0)
> Set(Variable[x₁])

Best,

Charlie

**Comment by ChrisRackauckas** [comment]
Interesting. Thanks for the issue. I think we want to rely less and less on this feature. The autodetection was a nice idea, but it ends up giving unintuitive orderings sometimes, and so it's probably best to always require user input there!

**Comment by cvanaret** [comment]
It's actually a nice feature, I wouldn't want to list the variables myself for each equation that I write.
And returning a Set makes it clear that the ordering is arbitrary.

**Comment by ChrisRackauckas** [comment]
Well the difficulty is, when you pass in a number, are you sure you're overwriting the correct parameter? In some sense a vector of pairs is probably what's necessary.

**Comment by cvanaret** [comment]
I'm not sure what you mean, Chris.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/ModelingToolkit.jl/issues/214 is a longer discussion on the main issue here.

**Comment by ChrisRackauckas** [comment]
`convert(Variable,x)` works well now. The package has changed a lot since the issue, so I don't think the core of the issue exists still.
