### ISSUE TITLE
nonlinear solving: x^a * b = c

### ISSUE THREAD

**Issue by thorek1** [SciML/ModelingToolkit.jl#2123]
Is there any capability to solve the problem below with `ModelingToolkit.jl` or `Symbolics.jl`?

I have the following in mind:
```Julia
using SymPy
@syms x a b c
solve(x^a * b - c, x)
# 1-element Vector{Sym}:
#  (c/b)^(1/a)
```
My understanding is that it is not the case (yet).

`Symbolics.jl` so far only handles the linear case and I didn't get to the bottom of `alias_elimination` and related codes, but my understanding here is that it does not cover the above case.

Am I missing something here?

If not, do you plan on implementing this functionality any time soon?

It would be a great addition because I could get rid of the slow `SymPy.jl` dependency for these tasks.

**Comment by ChrisRackauckas** [comment]
This is in the wrong repo. Please ask on Symbolics.jl.
