### ISSUE TITLE
Q: parameters in MTK

### ISSUE THREAD

**Issue by B-LIE** [SciML/ModelingToolkit.jl#2130]
Three questions on `parameters` in MTK.

1. Using the macro to define `parameters`, it seems like the following two syntaxes give the same result - a vector:
```julia
# Option 1
@parameters a b c
# Option 2
@parameters a, b, c
```
[Option 1 where space is used to separate variables -- isn't that more of a row matrix notation?]

**However**: if I add default values, only "Option 1" seems to work:
```julia
# Option 1 -- works
@parameters a=1 b=2 c=3
# Option 2 -- does not work
@parameters a=1, b=2, c=3
```` 
**Question 1**: is this correct? Is there a reason why space separation works, and comma separation does not work?

2. The following code... 
```julia
@parameters t a=10 b=20 c=b-a
@variables x
Dt = Differential(t)
eqs = [Dt(x) ~ -c*x]

sys = ODESystem(eqs)
```

...gives an error message when I convert it to an `ODEProblem` and try to solve it -- I'm told that `c` is not defined, My *guess* is that the problem is that `a` and `b` do not appear explicitly in the `eqs`. Therefore, constructor `ODESystem` strips away parameters `a` and `b`, leaving `c` also undefined??

**Question 2**: would the solution here be to define `a` and `b` as *constants*, i.e., `@constants a=10 b=20`?

3. It seems like the *order* of defining parameters is *important*  if I define one parameter from another. What I mean is:
```julia
# Case 1: This works:
@parameters a b=2*a

# Case 2: This does not work:
@parameters b=2*a a
```

**Questions 3**: Is my observation correct? In other words, MTK does not sort parameters in the background so that both Case 1 and Case 2 works? (Reason for question: Modelica would handle both cases. I'm not sure whether this is important, though. But useful to know the answer...)

**Comment by ggkountouras** [comment]
**Question 1**: I would choose option 1 for a macro that fits in a single line. For macros spanning multiple lines (e.g. a long parameter list) you can do:
`@parameters(a=1, b=2, c=3)`

**Comment by B-LIE** [comment]
Question 1: Should this be interpreted as a function call? [`@parameters(...)`] Or as a macro `@parameters`  operating on a tuple of assignments?

**Comment by ChrisRackauckas** [comment]
Macro.
