### ISSUE TITLE
Incidence matrix structural_simplify

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/ModelingToolkit.jl#2178]
Would it be possible to add some extra information to the docstring of structural_simplify to explain how the incidence matrix should be interpreted: on the left original dependence of equations on variables, on the right simplified...

**Comment by ChrisRackauckas** [comment]
@YingboMa can you take a second to add this?

**Comment by YingboMa** [comment]
The incidence matrix is actually not useful for humans. I am just showing it because it looks cool. We can just disable it if it's confusing.

**Comment by ChrisRackauckas** [comment]
Disable it then from the default printing and surface a function in the docs for showing it.
