### ISSUE TITLE
WARNING: importing deprecated binding Symbolics.@register into ModelingToolkit.

### ISSUE THREAD

**Issue by prbzrg** [SciML/ModelingToolkit.jl#2197]
I got this warning in the precompilation:

```julia
┌ ModelingToolkit [961ee093-0014-501f-94e3-6117800e7a78]
│  WARNING: importing deprecated binding Symbolics.@register into ModelingToolkit.
└  
```

**Comment by ChrisRackauckas** [comment]
@YingboMa do you know the cause of this one? I looked for `@register` in this repo and didn't find it.

**Comment by prbzrg** [comment]
If you need the versions, the warning comes from:
https://github.com/impICNF/ContinuousNormalizingFlows.jl/actions/runs/5296322153/jobs/9587352257#step:6:784

**Comment by ChrisRackauckas** [comment]
@ArnoStrouwen close this when we solve it.

**Comment by ArnoStrouwen** [comment]
Should be good now.
I don't have close rights.
