### ISSUE TITLE
Improved conversion of variables to symbols

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#2205]
Currently
```julia
using ModelingToolkit
@variables t X(t)
Symbol(X)
```
returns `Symbol("X(t)")`. it feels that the most likely desired output is simply `:X`. Would it make sense to modify so that this is the case?

**Comment by YingboMa** [comment]
No, because `X` represents `X(t)`. Perhaps, you are looking for `ModelingToolkit.getname(X)`.
