### ISSUE TITLE
Function Serialization

### ISSUE THREAD

**Issue by bradcarman** [SciML/ModelingToolkit.jl#2209]
Previously one could do...

```julia
open("f.jl","w") do io
   print(io, prob.f.f.f_iip.body)
end
```

or 

```julia
open("jac.jl","w") do io
   print(io, prob.f.jac.jac_iip.body)
end
```

This now just gives `nothing`

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaSymbolics/Symbolics.jl/blob/2f2131dba1f37a8ef58c747228be67ac02e53954/src/build_function.jl#L359

This is from the `drop_expr` that was added to fix GPU usage. We can make that a keyword argument in `build_function` and propagate that up all the way to `ODEProblem`.

**Comment by bradcarman** [comment]
Is there a way I can get the contents back using the `cache_tag`?

**Comment by bradcarman** [comment]
OK, finally got it sorted...

```julia
open("f.jl","w") do io
       show(io, MIME"text/plain"(), prop.f.f.f_iip)
end
```
