### ISSUE TITLE
Error with @register_symbolic when running documentation example

### ISSUE THREAD

**Issue by olsoni** [SciML/ModelingToolkit.jl#2211]
Hello, 

I'm new here so forgive me if this is user error, but trying to run some of the examples to get a sense of how to use this package. I'm following the examples provided in the [docs](https://docs.sciml.ai/ModelingToolkit/stable/tutorials/ode_modeling/#Specifying-a-time-variable-forcing-function) and running into an issue. 

The only difference here is that I've copy pasted the example code into a function that I'm trying to load and run in my REPL rather than running the code directly in the REPL itself. Here's my exact usage : 

```
## SciMLExample.jl
module SciMLExample

using LinearAlgebra

using StableRNGs

using DifferentialEquations
using OrdinaryDiffEq
using ModelingToolkit

using DataDrivenDiffEq
using DataDrivenSparse

using Plots

export forcedCdeqExample

function forcedCdeqExample()
    @variables t x(t)   # independent and dependent variables
    @parameters τ       # parameters
    @constants h = 1    # constants

    D = Differential(t) # define an operator for the differentiation w.r.t. time

    value_vector = randn(10)
    f_fun(t) = t >= 10 ? value_vector[end] : value_vector[Int(floor(t)) + 1]
    @register_symbolic f_fun(t)

    @named fol_external_f = ODESystem([f ~ f_fun(t), D(x) ~ (h + f - x) / τ])
    prob = ODEProblem(structural_simplify(fol_external_f), [x => 0.0], (0.0, 10.0), [τ => 0.75])

    sol = solve(prob)
    plot(sol, vars = [x, f])
end

end
```

After loading that into my REPL and running `forcedCdeqExample`, I get the following error : 
```
julia> forcedCdeqExample()
┌ Error: Failed to revise /home/isaac/Private/repos/foresight/src/julia/SciMLExample.jl
│   exception = lowering returned an error, $(Expr(:error, "Global method definition around /home/isaac/.julia/packages/Symbolics/UrqtQ/src/register.jl:82 needs to be placed at the top level, or use \"eval\"."))
```

I've traced this to the `@register_symbolic` call and my interpretation of the error is that somehow it is invalid to call `@register_symbolic` on the inline function `f_fun`. Given that I copied that straight from the example code, I'm assuming that the only way it's working in the example is if you run all of the example code directly in the REPL. I've tried adding `@eval` in front of that line, but that just produces more errors down the line (though I definitely could be using `@eval` wrong here). 

Any pointers on how to fix this?

**Comment by ChrisRackauckas** [comment]
Registration of functions needs to happen at the top level, not in the function. You're not running the example as the example shows, you put it in a function and so global function definitions are not the same.

**Comment by olsoni** [comment]
@ChrisRackauckas understood, but is there a way to do something similar inside a module? I couldn't figure out how to make a function that could be used with the ODESystem whatsoever. Being forced to put it at the global level seems pretty restrictive, but i couldn't find any other way and the documentation i could find didn't seem to suggest one.
