### ISSUE TITLE
Documentation tab for various API function

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#2224]
As someone who do a decent amount of work with MTK internals, I often find myself looking around for various functions for accessing and converting internal stuff. Usually, I manage by a combination of looking through source code and asking people, however, it seems good to have a list for this in the documentation.

E.g. stuff like getting the names of a parameter/variable as a symbol. Getting their indexes in their vectors, etc. There are probably a lot of convenient functions out there that I don't know about but probably could make use of as well.

**Comment by ChrisRackauckas** [comment]
I think all API docs are up? Let me know if any are missing.
