### ISSUE TITLE
Namespace issues in `remake`

### ISSUE THREAD

**Issue by martincornejo** [SciML/ModelingToolkit.jl#2239]
Related to https://github.com/SciML/ModelingToolkit.jl/issues/1746

`remake`ing the problem using the wrong indexing (`sys.x` instead of `x`) leads to udesired behavior. In this case, it's also problematic because it doesn't throw an error, but silently continues with the defaults...

MWE:
```julia
@variables t
D = Differential(t)
@variables x(t) = 1.0
eqs = [D(x) ~ -x]
@named sys = ODESystem(eqs, t)

tspan = (0.0, 1.0)
prob = ODEProblem(sys, u0, tspan)

prob.u0
# 1-element Vector{Float64}:
#  1.0

## incorrectly change initial conditions
u0 = [sys.x => 2.0]
prob = remake(prob; u0)

prob.u0
# 1-element Vector{Float64}:
#  1.0

## correctly change initial conditions
u0 = [x => 2.0]
prob = remake(prob; u0)

prob.u0
# 1-element Vector{Float64}:
#  2.0
```

**Comment by ChrisRackauckas** [comment]
@TorkelE

**Comment by TorkelE** [comment]
I think this is a known issue? A while ago we fixed quite a few of these cases, but don't think we ver got to remake. It is something I'm happy to see fixed/fix though, as I agree it would be useful to have it working.

**Comment by TorkelE** [comment]
At it. The problem is that currently, `remake` calls `ODEProblem`, which creaets a new `ODEProblem` using the input. However, `ODEProblem`s does not support the notation `ODEProblem(sys, [sys.x => 3.0], tspan).u0`. We could change this, or make `remake` throw an error if the input is of a certain type.

**Comment by TorkelE** [comment]
The MTK PR have tests now as well.

For this example, basically what happens here is that when one calls `sys.x` one basically get a `Num` of the form `sys₊x(t)`, which is not recognised as one of the variables in `sys` (which only have a variable `x(t)`. The resulting phenomenon is the same as if you'd had used
```julia
@variables y
u0 = [y => 5.0]
prob = remake(prob; u0)
prob.u0
```
(with the exception that should be clear to the user that it does not work)
