### ISSUE TITLE
Array parameters/variables with `@mtkmodel`

### ISSUE THREAD

**Issue by ThiagoReschutzegger** [SciML/ModelingToolkit.jl#2269]
With `@mtkmodel`, array parameters and variables doesn't seem to work

This works:
```julia
@mtkmodel AnyModel begin
    @parameters begin
        k₁
        k₂
    end
    @variables begin
        A(t)
    end
    @equations begin
        ∂(A) ~ -k₁ * A + k₂
    end
end
```

This doesn't:
```julia
@mtkmodel AnyModel begin
    @parameters begin
        k[1:2]
    end
    @variables begin
        A(t)
    end
    @equations begin
        ∂(A) ~ -k[1] * A + k[2]
    end
end
```

Any idea why this is the case?

**Comment by YingboMa** [comment]
We haven't added array support yet, but we will.

**Comment by ChrisRackauckas** [comment]
This got added IIUC, @ven-k correct me if I'm wrong.

**Comment by ven-k** [comment]
Yes. This is already added; except that array length can't be specified. But that is tracked by
- https://github.com/SciML/ModelingToolkit.jl/issues/2453
