### ISSUE TITLE
noncanonical docstring

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/ModelingToolkit.jl#2297]
MTK has tons of problems with missing docstrings due to them being present in different places in `@docs` block.
Now there is an option to allow for this:
https://documenter.juliadocs.org/stable/man/syntax/#noncanonical-block

But is there a canonical place for e.g. `structural_simplify`?
https://docs.sciml.ai/ModelingToolkit/stable/systems/ODESystem/#Transformations
https://docs.sciml.ai/ModelingToolkit/stable/systems/SDESystem/#Transformations
Or can some of them be noncanonical everywhere?

**Comment by ChrisRackauckas** [comment]
default to ode

**Comment by ArnoStrouwen** [comment]
Added in #2315.
