### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ufechner7** [SciML/ModelingToolkit.jl#2326]
I was fighting for weeks with the fact that sometimes you need to write `ω(t)` and sometime  `ω` when defining and linearizing models.

This info should be added to the documentation.

Perhaps also a nice example could be added, for example this one:
```julia
using ModelingToolkit

@variables t ω(t) Pgc(t)
@variables R a b ρ U J A s

struct Equilibrium
    a_bar
    b_bar
    pg_bar    # generator power
    ω_bar     # rotor speed
end

mutable struct Settings
    ρ0::Float64
    U0::Float64
    A0::Float64
    R0::Float64
    J0::Float64
end

se::Settings = Settings(1.225, 7.0, 12469.0, 63.0, 4.047e7)
eq = Equilibrium(-0.012273163568697454, 0.5344744027433362, 1132254, 0.88612)
op_ = Dict([R => se.R0, ρ => se.ρ0,  A => se.A0, J => se.J0, U => se.U0, 
            Pgc => eq.pg_bar, ω => eq.ω_bar, a => eq.a_bar, b => eq.b_bar])

function model_turbine_symbolic()
    @variables t ω(t) Pr(t) λ(t) Pgc(t)
    @parameters J R ρ A U a b
    D = Differential(t)
    eqs = [D(ω)  ~ (Pr - Pgc) / (J * ω),
            0     ~ ω * R/U - λ,
            0     ~ 0.5 * ρ * A * U^3 * (a*λ + b) - Pr]
    @named sys = ODESystem(eqs, t)
    sys, Pgc, ω
end

function calc_lin_numeric()
    sys, Pgc, ω = model_turbine_symbolic()
    matrices, simplified_sys = ModelingToolkit.linearize(sys, [Pgc], [ω], op=op_)
    A_, B, C, D = matrices
    A_[1]
end

function calc_lin_symbolic(num=true)
    sys, Pgc, ω = model_turbine_symbolic()
    matrices, simplified_sys = ModelingToolkit.linearize_symbolic(sys, [Pgc], [ω])
    A_, B, C, D = matrices
    if num; return substitute(A_[1], op_); else return A_[1] end
end

println("Symbolic linearization: ", calc_lin_symbolic(false))
println("Symbolic linearization, numeric result: ", calc_lin_symbolic())
println("Numeric linearization:  ", calc_lin_numeric())
```
In this example you can see that in the function that defines the model, but also on global level you need to use:
```julia
@variables t ω(t) Pgc(t)
```
but when defining the dictionary with the operating point you need to use
```julia
Dict([Pgc => eq.pg_bar, ω => eq.ω_bar])
```

I could make a pull request if someone could make a suggestion where in the documentation to add this info.

**Comment by ChrisRackauckas** [comment]
> I was fighting for weeks with the fact that sometimes you need to write ω(t) and sometime ω when defining and linearizing models.

In `@variables` you're adding a default, so `w(t)` just means that the defined variable `w` always refers to `w(t)`. `w(..)` means it's an open operator, so you have to write `w(t)` everywhere. If this isn't clear in the docs, please feel free to open a pull request that clarifies it where you think it needs more clarity.

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal thoughts?

**Comment by AayushSabharwal** [comment]
It's already documented in https://docs.sciml.ai/ModelingToolkit/stable/basics/ContextualVariables/#Wildcard-Variable-Arguments. Maybe some better explanation there if it isn't clear? Or if it's a visibility issue we can document add a section to one of the basic examples.

That said, is this really something people will use outside of PDEs? I understand that it looks a bit inconsistent, but it's an intentional convenience and changing it is breaking for Symbolics and MTK. It's a lot nicer imo to be able to write `w` and not `w(t)` everywhere (the fewer times someone need to use `shift+something` the better)

**Comment by ChrisRackauckas** [comment]
Okay it is documented so closing, but if there's a specific ask we can reopen with a specific todo.
