### ISSUE TITLE
MTK v8.73.1: no support for `@constants` within `@mtkmodel`?

### ISSUE THREAD

**Issue by B-LIE** [SciML/ModelingToolkit.jl#2362]
**Question❓**

I'm trying to use `@constants` with a `begin...end` construct within an MTK model created by `@mtkmodel` [similar to using a `@parameters` construct], but I'm told that `@constants` is not supported. 

*Questions*:
* Isn't there a `@constants` macro within MTK? If yes, is it just that it doesn't work with `@mtkmodel`?
* Is this a design choice, or is the plan to add support for `@constants` at a later stage?

**Comment by ChrisRackauckas** [comment]
@ven-k was this handled?

**Comment by ven-k** [comment]
I have a local build of this; will rebase and open a PR.
