### ISSUE TITLE
How can I return all variable values in a nonlinear system model when using `structural_simplify` which only solves for a reduced number of variables?

### ISSUE THREAD

**Issue by chris-hampel-CA** [SciML/ModelingToolkit.jl#2385]
**Question❓**

Hello, 

I have a question about whether or not a certain feature exists and if not, am making a request for it.

In my example, I am solving a `NonLinearProblem`. I use `structural_simplify` to reduce a large list of equations to just a few equations (or none if the system can be solved in sequence without iteration). This is extremely helpful because it reduces the number of initial guesses required and makes solving faster and more robust. 

```
#eqs, components, guess defined elsewhere
mtk_model = NonlinearSystem(eqs, [], []; systems=components, defaults=guess, name=Symbol(test_sys))
mtk_alias = alias_elimination(expand_connections(mtk_model))
mtk_simp = structural_simplify(mtk_alias; allow_symbolic=true, allow_parameter=true)
prob = NonlinearProblem(mtk_simp, [])
 sol = solve(prob, NewtonRaphson())
```

In my example, let's say I have a system of 3 components connected one after another in sequence starting from an inlet boundary condition. In this case, this system is trivial and requires no iteration because the list of equations can be computed sequentially given the inlet boundary condition.

Let's say this system has 100 variables given by `states(mtk_model)`, then 50 variables given by `states(mtk_alias)` and 0 variables given by `states(mtk_simp)` (because in this example, no iteration is technically required although this same concept is still applicable if I connected the components differently such that iteration was required). The obvious choice is to solve with `mtk_simp` because it's easier to solve and does not require providing 50 to 100 guesses. Then, `sol.u` will return a `Vector{Float64}` corresponding to the 0 variables leftover. Of course, I still want to know the variable values of the other 50 or 100 values. I know I can return these values by doing this:

```
vault = []
for s in states(mtk_alias)
   val = sol[s]
   vault = vcat(vault, val) # or insert  other code to store the value after each iteration
end
```
However, I have found this method to be very inefficient, because this action re-computes all of the equations from the inlet boundary condition to the equation in a downstream component that ultimately provides the value of the requested variable `s`. This is problematic for my case because I have some non-symbolic "expensive" function evaluations in my equation list. This method ends up dramatically blowing up the run time required to see all variable values. I have found this issue to to be less critical in instances where the function evaluations are less expensive but the process is still redundant, nonetheless. 

An analogy I like to use to represent this case comes from a classic basketball conditioning exercise. There is a drill to run from baseline to free throw line and back, then to half court and back, and then to the opposite free throw line and back, and then to the opposite baseline and back. The above method is doing this same thing in terms of equations (i.e., replace court lines on a court with equations in an equation list as we go down the component list in the system). In reality, we only care about going from baseline to baseline (equation 1 to the last equation) and returning all variable values from the sequence of computations along the way. That would be the most efficient way to return all variables values--in one swoop rather than in increments. Does this method exist in MTK or is there a trick that can be coded? Perhaps I am just missing it. 

I know another alternative method to reduce the runtime of grabbing values `sol[s]` is to solve the larger systems like `mtk_alias` or `mtk_model`. In that case, the output `sol.u` already stores all the variable values that I want to see; then using `sol[s]` returns the requested variable value rapidly without having to recompute equations (I have confirmed this). However, I have found that providing large lists of guesses is cumbersome, can affect the robustness of the successful solve if not carefully provided ( it matters alot in my system, maybe not in others), and will take longer to solve. I really would love to find a way to use `structural_simplify` AND find an efficient way to return all variables values. Would help me tremendously! Thanks, Chris

P.S. You can see example code in this forum that demonstrates the issue. https://discourse.julialang.org/t/how-to-return-all-variable-values-of-a-non-simplified-system-of-equations-from-a-structurally-simplified-solution-output/107915/9

**Comment by ChrisRackauckas** [comment]
`sol[allvariables]`, see https://docs.sciml.ai/SymbolicIndexingInterface/stable/
