### ISSUE TITLE
Load error with @mtkbuild

### ISSUE THREAD

**Issue by finmod** [SciML/ModelingToolkit.jl#2390]
Load error with @mtkbuild on the demo.jl of the webminar as reported here https://github.com/bradcarman/ModelingToolkitWebinar/issues/1

Also Load error on `@extend` only takes an assignment expression. Got OnePort()` in the [Acausal Component-Based Modeling](https://docs.sciml.ai/ModelingToolkit/stable/tutorials/acausal_components/#acausal) tutorial.

ModelingToolkit is v8.73.2

**Comment by ChrisRackauckas** [comment]
What was the full error message?

**Comment by finmod** [comment]
This seems to be a kernel problem in VSCode. 
In VSCode with Juliaup\julia-1.9.4 +0.x64.w64.mingw32, it gives a load error
![image](https://github.com/SciML/ModelingToolkit.jl/assets/12710434/8a88af83-0287-4f26-8492-64ea0b4f8135)

whereas with Julia nteract 1.9.4 it runs but does not render properly.
![image](https://github.com/SciML/ModelingToolkit.jl/assets/12710434/870553d0-ce70-4de2-97cd-270c3f864fb9)

**Comment by finmod** [comment]
With Julia v1.10.0 and MTK v8.74.1 the updated RC Circuit tutorial demonstrating @mtkbuild is fine.

**Comment by ChrisRackauckas** [comment]
Seems like a versioning thing.

**Comment by ChrisRackauckas** [comment]
v9 is not the latest version. It has not been released

**Comment by finmod** [comment]
Solved! The problem was HighDimPDE. Once removed HighDimPDE all MTK related packages updated properly.
Current MTK is v8.75.0
