### ISSUE TITLE
"Ignore" option for connectors

### ISSUE THREAD

**Issue by GHE-HS** [SciML/ModelingToolkit.jl#2422]
First of all, thank you for this amazing ecosystem! I especially appreciate the new `@mtkmodel` macro, it has made everything much neater.

However, I have a problem with the **connectors**. I am simulating hydraulic systems and I have used the `@structural_parameters` as a way to pass functions that give thermo-physical properties. It has been working great, with an exception.

The problem is basically that, since the properties (here cp and rho) are a function of the other variables (temperature and pressure), then, they are already fully constrained/defined. However, when connecting this connector to another one, it automatically adds an extra equation between the two connector cp and rho, which over constrains the system.

A solution would be to have an option [connect = Ignore] to just skip those already constrained variables.

MWE:
```
using ModelingToolkit

@connector MWEFluidPort begin
    @structural_parameters begin
        cp_ = (T, p) -> 4180.0
        ρ_ = (T, p) -> 1000.0
    end
    @parameters begin
    end
    @variables begin
        cp(t) = 4180.0, [description = "Thermal capacity"]#, connect = Domain]  -> proposed: connect = Ignore
        ρ(t) = 1000.0, [description = "Density"]#, connect = Domain]                   -> proposed: connect = Ignore
        T(t) = 273, [description = "Temperature", connect = Stream]
        ṁ(t) = 1.0, [description = "Mass flow", connect=Flow]
        p(t) = 1e5, [description = "Absolute pressure"]#, connect = Equality]
    end
    @equations begin
        cp ~ cp_(T, p)
        ρ ~ ρ_(T, p)
    end
end

@named fp1 = MWEFluidPort()
@named fp2 = MWEFluidPort()

@named test_fp = ODESystem([
    connect(fp1,fp2)
    fp1.p ~ 10
    fp1.T ~ 10
    fp1.ṁ ~ 10+sin(t)
    ], t, systems=[fp1, fp2])

sys_simplified = structural_simplify(test_fp)
```

I tried a workaround in the form of a sub component, assuming the sub component variables would not get connected, but that did not work.

A workaround that does work is to manually connect the ports using classic _~_, however it is tedious and against what I think is MTK philosophy.

An issue I had when debugging was also that the `connect()` function does not return equations that could be visualized, it just displays the same statement (here _connect(fp1,fp2_). Only once you try to `structural_simplify()` do the supplementary equation pop-up in the error message.

The doc and issue I found on the topic seem to be incomplete/outdated (the issue mentions _Equality_ and _Domain_ as _connect options, which currently throws an error):
- https://docs.sciml.ai/ModelingToolkit/dev/basics/MTKModel_Connector/
- https://discourse.julialang.org/t/modelingtoolkit-variable-metadata-for-connectors/92056

Is there something I missed/misunderstood?

**Comment by ChrisRackauckas** [comment]
You could also just do this like how the electrical components are structured. That has a connector, and then there's pieces built on that which are extended. You can just have the 4 connection variables in the connector and then extend in an object above that to add cp and p, and you'd get what you want.
