### ISSUE TITLE
Support for simulation of hybrid systems

### ISSUE THREAD

**Issue by ufechner7** [SciML/ModelingToolkit.jl#2423]
** What is the status of the support for the simulation of hybrid systems? **

I have a continues time plant, and use discrete time callbacks to implement a discrete time controller. While this works, it is not straightforward. For example I cannot add discrete time variables to the state and plot them.

Questions:
- is the current best way to implement hybrid systems documented?
- are any improvements to be expected in the near future?

**Comment by ufechner7** [comment]
Related: https://github.com/SciML/ModelingToolkit.jl/issues/894

and https://discourse.julialang.org/t/diffeqs-hybrid-continuous-discrete-system-periodic-callback/23791/38

**Comment by baggepinnen** [comment]
Work in progress, see
https://github.com/SciML/ModelingToolkit.jl/pull/2410

**Comment by ChrisRackauckas** [comment]
See the discussion in https://github.com/SciML/ModelingToolkit.jl/issues/2482 for how this is evolving with the MTK v9, and the PR https://github.com/SciML/ModelingToolkit.jl/pull/2410 which then adds the documentation for the new clocking system. With that, we should have a pretty complete set of functionality for discrete-continuous.

Closing as I think that covers the full question.
