### ISSUE TITLE
Allow variable array length for parameters in `@mtkmodel`

### ISSUE THREAD

**Issue by ven-k** [SciML/ModelingToolkit.jl#2453]
**Is your feature request related to a problem? Please describe.**

Parameters and variables arrays in `@mtkmodel` allows the length to be defined while defining the MTKModel. While  doesn't allow user to specify/modify the length.

**Describe the solution you’d like**

```julia
@mtkmodel A begin
	@parameters begin
        a[1:N] = 10, [description = ""]
     end
end
```
Should add `N` as a kwarg.

```julia
@mtkmodel A begin
    @structural_parameters begin
		N = 5
    end
	@parameters begin
        a[1:N] = 10, [description = ""]
     end
end
```
Should create `a` of length 5, while allowing user to override with `N`.

**Additional context**

X-ref: https://discourse.julialang.org/t/modelingtoolkit-change-parameter-vector-size-based-on-structural-parameter/109914

**Comment by ChrisRackauckas** [comment]
This is simply not possible given how the graph algorithms and the codegen works. In theory JuliaSim Compiler could be able to do something though.

**Comment by ven-k** [comment]
https://github.com/SciML/ModelingToolkit.jl/pull/3107 closes this issue.
