### ISSUE TITLE
Lacking Documentation for using DynamicQuantities (Unitful is still used in dev docs)

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#2462]
The current (dev) documentation demonstrates unit handling for Unitful, instead of DynamicQuantities (which I understand to be the new package for handling units): https://docs.sciml.ai/ModelingToolkit/dev/basics/Validation/

**Comment by ArnoStrouwen** [comment]
The page now uses DynamicQuantities.
