### ISSUE TITLE
MTK 9 migration guide

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#2463]
I know the focus currently is getting MTK 9 done, but it would be very helpful once it is released to put together a brief migration guide for people that have built packages on top of MTK, of which there are now quite a few. Things like how to update parameter handling internally for systems, how to update unit handling, how/when default variables such as the new time variable should be used, the change from states to unknowns, and any other major changes in the API that will likely require MTK systems to be modified.

**Comment by Datseris** [comment]
Do you know where I can follow all this progress? Is there some ongoing NEWS file or something?

**Comment by isaacsas** [comment]
I don’t think there is anything beyond a tracking issue, see below, and lots of merged and soon to be merged PRs.

https://github.com/SciML/ModelingToolkit.jl/issues/2262

**Comment by ChrisRackauckas** [comment]
https://github.com/SciML/ModelingToolkit.jl/blob/master/NEWS.md plus the information in https://github.com/SciML/ModelingToolkit.jl/issues/2483 should cover this.
