### ISSUE TITLE
build hydrological computation module, using Interpolations.jl and ModelingToolkit.jl (new to ModelingToolkit.jl)

### ISSUE THREAD

**Issue by chooron** [SciML/ModelingToolkit.jl#2526]
**Question❓**
I'm a hydrologist that want to use ModelingToolkit.jl to build hydrology model, the following code is a module in the model:
```
@variables t
const D = Differential(t)

function step_func(x; p1=5.0, p2=1.0, p3=0.5)
    (tanh(p1 * x) + p2) * p3
end
@register_symbolic step_func(x)

vars = @variables begin
    prcp(t) # precipitation
    temp(t) # temperature
    snowfall(t)
    melt(t)
    snw(t) # snow water
end

ps = @parameters begin
    tmin
    tmax
    df
end

function snow_water_reservoir(; name::Symbol)
    ## SnowWater Reservoir
    eqs = [
        snowfall ~ step_func(tmin - temp) * prcp,
        melt ~ step_func(temp - tmax) * step_func(snw) * min(snw, df * (temp - tmax)),
        D(snw) ~ snowfall - melt,
    ]
    ODESystem(eqs, t; name=name)
end
```
In snow_water_reservoir, I constructed three formulas, five variables, and three parameters. However, during the construction of the ODEProblem, I encountered a problem and did not find any similar cases to mine. Among these five variables, precipitation and temperature were actually observed, so interpolation was needed when inputting them into the ODE problem. Additionally, how can I obtain the calculation results of snowfall, melt, and snw simultaneously

**Comment by baggepinnen** [comment]
> I encountered a problem and did not find any similar cases to mine

It's not clear to me what problem you encountered

> how can I obtain the calculation results of snowfall, melt, and snow simultaneously

when you solve the resulting ODE you get a solution object which contains information about all variables along the solution trajectory. What have you tried and failed with, your code does not show any simulation being performed

**Comment by chooron** [comment]
I apologizes for not providing a good description of the issue. Let me first list the required data and parameters:
```
prcp_data = [3.1, 4.24, 8.02, 15.27, 8.48, 0.0, 0.0, 2.1, 3.55, 0.0]
temp_data = [6.08, 10.53, 11.83, 7.38, 4.8, 5.41, 6.405, 7.675, 5.48, 3.67]

prcp_itp = linear_interpolation(xs, prcp_data)
temp_itp = linear_interpolation(xs, temp_data)
```
After preparing the data, I called snow_water'reserver to build `ODESystem` and `ODEProblem`. However, when setting the initial value `u0`, I was not quite sure how to set the initial values of each state. `prcp` and `temp` were calculated through interpolation functions, while `snowfall` and `melt` were calculated through `prcp` and `temp`, and they don't have initial values. The known initial values are `snw=0`
```
u0 = [
    prcp => prcp_itp,
    temp => temp_itp,
    snw => 0.0,
]
p = [
    tmin => -2.092959084,
    tmax => 0.175739196,
    df => 2.674548848,
]
@named module_1 = snow_water_reservoir()
prob = ODEProblem(module_1, u0, (0.0, 10.0), p)
ModelingToolkit.parameters(module_1)
```

**Comment by chooron** [comment]
> The model you have only has a single differential equation
> 
> ```julia
> D(snw) ~ snowfall - melt
> ```
> 
> If you call `structural_simplify(module_1)`, I think you'll find that it returns an `ODESystem` that has a single equation only. You are thus only expected to provide the initial condition for the variable `snw`.
> 
> You also need to include some equations to bind the interpolation objects to the variables. For example, the initial condition of a variable cannot be set to an interpolation object like `prcp => prcp_itp`, instead, include the equation
> 
> ```
> prcp ~ prcp_itp(t)
> ```
> 
> in your model.
Thank you for your suggestion, but from what I understand, my current needs might have to be met through the conventional setup method of DifferentialEquation.jl.
