### ISSUE TITLE
Create a function for retrieving the default `t` iv?

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#2552]
Instead of doing
```julia
import ModelingToolkit.t_nounits as t
```
there could be a function
```julia
function default_t()
    return ModelingToolkit.t_nounits
end
```
and then the user could simply do
```julia
t = default_t()
```

We are currently looking at something like this in Catalyst. It is cleaner, also, @isaacsas pointed out that this allows for easier handling of adding metadata to `t`, or getting one with a different unit, e.g. if one wants to have it in units of seconds one could do
```julia
t = default_t(unit=:s) # :s or however units are best provided.
```
(this would require some additional stuff in the `default_t()` function)

**Comment by ChrisRackauckas** [comment]
That's not the default, which is exactly the problem. There is no single default, it's contextual.

> t = default_t(unit=:s) # :s or however units are best provided.

That's not necessarily unique, and makes it difficult to get the default 😅

**Comment by isaacsas** [comment]
@ChrisRackauckas what is the purpose of `t_nounits` and all the MTK examples being switched to import it as `t` then instead of just `@variables t`? If there is no default then should we just ignore it in Catalyst and keep having users define their own `@variables t`?

**Comment by ChrisRackauckas** [comment]
The default is more generally `ModelingToolkit.t`, and all of the standard library examples make use of it. The tutorials are lazy and don't define units so they use the unitless one. And then there's the Unitful default. Catalyst should use the default unitless `t`, but to call it "the default" is really misleading since most libraries require the unitful ones.

**Comment by isaacsas** [comment]
`ModelingToolkit.t` uses units of seconds. What if one wants different default time units?

**Comment by ChrisRackauckas** [comment]
There's an issue open about that, where if you use different units it should auto-convert the rates. We don't have that yet, but that's the plan at least so that if you define `t` and `tau`, some things in `t` and some things in `tau`, it should "just work"
