### ISSUE TITLE
Make replace of  MTKParameters type-stable

### ISSUE THREAD

**Issue by bgctw** [SciML/ModelingToolkit.jl#2608]
**Is your feature request related to a problem? Please describe.**

Currently, `replace(MTKParameters, Tunable(), parameter_values(odeprob), newvals)` is not type-stable, i.e
result type is not inferred.
This is a big performance disadvantage for solving ODEProblems of updated parameters, which is used in
a differentiable cost-function.

**Describe the solution you’d like**

Replacing tunable parameters in a MTKParameters returns a type-stable result and is differentiable.

**Describe alternatives you’ve considered**

One could type-annotate the new MTKParameters object inside the cost-function. However, this would involve internal details
and knowledge on how to construct the updated type when supplying e.g. Dual numbers in newval.

**MWE**

```
Pkg.add(["OrdinaryDiffEq","ComponentArrays","ForwardDiff","SciMLStructures"])
Pkg.develop("SymbolicIndexingInterface")
Pkg.develop("ModelingToolkit")

using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using OrdinaryDiffEq
using SymbolicIndexingInterface: parameter_values, state_values
using SciMLStructures: Tunable, replace, replace!, canonicalize, isscimlstructure

@parameters α β γ δ
@variables x(t) y(t)
eqs = [D(x) ~ (α - β * y) * x
       D(y) ~ (δ * x - γ) * y]
@mtkbuild odesys = ODESystem(eqs, t)


odeprob = ODEProblem(
    odesys, [x => 1.0, y => 1.0], (0.0, 10.0), [α => 1.5, β => 1.0, γ => 3.0, δ => 1.0])

@code_warntype replace(Tunable(), parameter_values(odeprob), collect(1.0:4.0))
```

**Comment by SebastianM-C** [comment]
I think one possible solution is something like https://github.com/SebastianM-C/ModelingToolkit.jl/commit/c5fde3dc03b25cca86bfc43f8099302edac0a5a7

@AayushSabharwal is this a reasonable approach?

**Comment by AayushSabharwal** [comment]
Yep, looks good. Just needs a test
