### ISSUE TITLE
Handle reaction combinatorics 

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#261]
Right now the reaction combinatorics aren't handled, so `2x + y -> z` will just be `alpha*2x*y` which isn't correct.

@isaacsas @TorkelE

**Comment by TorkelE** [comment]
Excited to see things are happening here, but haven't really dug into the MT/Bio codes yet (finalising a paper). Will try to start looking at this soon.

**Comment by isaacsas** [comment]
Should we handle this similarly to DEBio, where stoichiometry vectors are also given, and are used for the combinatorics? Do we want to again allow the rates to be general expressions that multiply the mass action factor?

**Comment by isaacsas** [comment]
@ChrisRackauckas I think this can be closed now (at least for ODE/SDE models).
