### ISSUE TITLE
Support scaled SI units

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#2616]
E.g. this fails:
```
using ModelingToolkit, DynamicQuantities
@parameters p [unit = u"L/s"] d [unit = u"s^(-1)"]
@parameters t [unit = u"s"] 
@variables X [unit = u"L"]
D = Differential(t)
eqs =[D(X) ~ p - d*X]
ModelingToolkit.validate(eqs) # Does not work.
```
Instead, one have to do:
```julia
using ModelingToolkit, DynamicQuantities
@parameters p [unit = u"m^3/s"] d [unit = u"s^(-1)"]
@parameters t [unit = u"s"] 
@variables X [unit = u"m^3"]
D = Differential(t)
eqs =[D(X) ~ p - d*X]
ModelingToolkit.validate(eqs) # Does not work.
```

These are identical. For highly composite units, rather cumbersome expressions will be generated. Allowing composite units should be very desirable (and was how things used to work).

**Comment by ChrisRackauckas** [comment]
@YingboMa do you know why this limitation exists?

**Comment by YingboMa** [comment]
First, `L` is not a SI unit; `m^3` is a SI unit.

In principle, unit checking can pass as long as they have the same dimension, but what happens when there's `x ~ y` where `x` has the unit of `L` but `y` has the unit of `m^3`? The reason that we error for non-SI units is because that requires additional transformation to equations to be correct in general.

**Comment by isaacsas** [comment]
Mixing `L` and `m^3` resulting in an error seems reasonable, but why can't non-SI units be supported anymore? They were supported previously with Unitful, and are incredibly common in chemistry / biology contexts (i.e. Molar concentrations for example which I guess are not SI but the most common concentration measure in most bio papers). @TorkelE's example that uses units of just `L` and `s` seems like it shouldn't require extra transformations to validate, just support for non-SI units.

**Comment by YingboMa** [comment]
There's no way of tell if someone uses constants like `u"cm"` or `1e-2u"m"` though.
```julia
julia> using DynamicQuantities

julia> u"cm"
0.01 m

julia> 1e-2u"m"
0.01 m

julia> 1e-2u"m" === u"cm"
true
```

**Comment by YingboMa** [comment]
To support non-SI units, we need to use `SymbolicDimensions` from `DynamicQuantities`.
