### ISSUE TITLE
Support for arrays of arrays datastructures in output

### ISSUE THREAD

**Issue by jlperla** [SciML/ModelingToolkit.jl#262]
@ChrisRackauckas  As discussed, @arnavs and I have figured out the exact datastructures we would need for going about 2 dimensions for the projects.  You suggested that recursively filling arrays of arrays/etc. is the way to go.   @arnavs will post the test in here shortly.

**Comment by arnavs** [comment]
I uploaded the tests to a gist: https://gist.github.com/arnavs/bde0e13a077b2c6f9b30e6fc762e6170. 

It has the various permutations we need (dense vs sparse, which levels of nesting), and a few additional tests at the end to support things like: 

```
h_empty_vec = [[a, b, c, 0], Vector{Expression}(undef,0)]
ModelingToolkit.build_function(h_empty_vec, [a, b, c])
```

Let me know if anything is unclear or hard to use.
