### ISSUE TITLE
IntervalNonlinearProblem support in MTK

### ISSUE THREAD

**Issue by ashwani-rathee** [SciML/ModelingToolkit.jl#2672]
I had a symbolic equation/function of type 
```
julia> pₜₜ = expand_derivatives(D((pₜ)))
(-L*(k^2)*(log(e)^2)*(e^(-k*(t - t0)))) / ((1 + e^(-k*(t - t0)))^2) + 2(k^2)*(e^(-2k*(t - t0)))*(L / ((1 + e^(-k*(t - t0)))^4))*(log(e)^2)*(1 + e^(-k*(t - t0)))
```
I want to solve for `0 ~ pₜₜ` where trying to find t in a certain interval and for that it needed IntervalNonLinearProblem which is currently not supported in MTK. Specific wanted to use MTK directly because of dictionary like input for parameters.

It would be a great help to have this support, I'll be willing to help if someone can guide me through properly given never contributed before to MTK

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal can you handle getting one for this?
