### ISSUE TITLE
Variables eliminated in `structural_simplify` are not included in simulation plots

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#2678]
MWE:
```julia
using ModelingToolkit, OrdinaryDiffEq, Plots
@parameters p d k
@variables t X(t) Y(t)
D = Differential(t)
eqs = [    
    D(X) ~ p - d*X
    X^2 ~ k*Y
]
@named osys = ODESystem(eqs, t) # Got two equations.
osys = structural_simplify(osys) # Got a single equation.

u0 = [X => 1.0]
tspan = (0.0, 10.0)
ps = [p => 1.0, d => 0.4, k => 2.0]
oprob = ODEProblem(osys, u0, tspan, ps)

sol = solve(oprob, Tsit5())
plot(sol)
```
![image](https://github.com/SciML/ModelingToolkit.jl/assets/18099310/53ab84ca-e314-46a6-b659-c0f4e3045946)

Presumably since `Y` is a declared part of the system, the user would want to have this included in the plot?

**Comment by ChrisRackauckas** [comment]
It's a generally bad idea to plot everything. In many cases it will just stall the plotting system and just cause it crash. `plot(sol, idxs = SymbolicIndexingInterface.allvariables)` is fine, maybe reexport from SciMLBase to make it easier.

**Comment by TorkelE** [comment]
I think that makes sense for large systems, but in that case we might just (quasi-) randomly throw away plotted variables until they reach some small number (say 10), and then let the user decide which to plot. 

In this case, I think the main problem is that (since `structural_simplify`'s exact effect is hidden to the user) the behaviour is not what the user would expect. This is also a case when the external parts of the workflow (not just the internals) is heavily affected by whether `complete` or `structural_simplify` is used.

**Comment by SebastianM-C** [comment]
> (since `structural_simplify`'s exact effect is hidden to the user)

When you structurally simplify the system that you get back has a lower number of variables and one would see that not all of the original model variables are there. Maybe this is more of a problem when using macros to build the system directly, but I think that the effect of `structural_simplify` is visible to the user :sweat_smile:

**Comment by ChrisRackauckas** [comment]
The problem is that common use cases like acausal modeling can have 200 solved variables and 20,000 observed variables just from tearing elimination. It's just impractical to default to plotting them all: this will make standard use cases crash.

**Comment by TorkelE** [comment]
> When you structurally simplify the system that you get back has a lower number of variables and one would see that not all of the original model variables are there. Maybe this is more of a problem when using macros to build the system directly, but I think that the effect of structural_simplify is visible to the user 😅

This is only if one actually looks at the variables of the system, which is not really part of the standard workflow (1) decalre model, (2) Create ODEProblem (3) Solve the problem (4) plot it (But why did the concentration of XY disappear but not X and Y?)

> The problem is that common use cases like acausal modeling can have 200 solved variables and 20,000 observed variables just from tearing elimination. It's just impractical to default to plotting them all: this will make standard use cases crash.

Ok, maybe this is more of a problem to applications such as Catalyst where you have a low number of variables and structural simplify only eliminates a few. However, here it is a problem (not a big one though). Maybe not high priority, but if the intention of this is to reduce the number of plotted thing, it seems like long-term some better heuristic can be created (e.g. also taking into account removing stuff from the plot if there are lots of non-elimianted variables as well).
