### ISSUE TITLE
`structural_simplify` doesn't properly namespace "bare" io variables

### ISSUE THREAD

**Issue by BenChung** [SciML/ModelingToolkit.jl#2682]
The implementation of io arguments for `structural_simplify` acts oddly in that if you mark a system's own parameter as being io then it isn't found (because the variable being compared internally _has not_ been namespaced) but it works when that component is wrapped into a system. Here's a small example:
```julia
@component function SSI(; name)
    vars = @variables x(t) v(t)
    eqs = [
        D(x) ~ v
    ]
    return ODESystem(eqs, t, vars, []; name=name)
end

@named ssi = SSI()
@named sys = ODESystem([], t; systems=[ssi])
structural_simplify(sys, ((ssi.v), ())) # works
structural_simplify(ssi, ((ssi.v), ())) # doesn't work
```
I can mark `v` as an input on the ODE system built with `ssi` as a subsystem but I cannot mark `v` as an input on the system built by `SSI` itself.

**Comment by YingboMa** [comment]
It's not a bug. It's just because `ssi.v` performs namespacing if don't declare `ssi` as completed, i.e., this would work.
```julia
ssi = complete(ssi); structural_simplify(ssi, ((ssi.v), ()))
```
