### ISSUE TITLE
`structural_simplify` uses metadata of the variables instead of what is passed into the system

### ISSUE THREAD

**Issue by sathvikbhagavan** [SciML/ModelingToolkit.jl#2706]
**Describe the bug 🐞**

`structural_simplify` uses metadata of the symbols instead of what is passed into the system. For example if a symbol which is declared as a variable is passed as a parameter into a `NonlinearSystem`, it does not behave like a parameter.

**Expected behavior**

`structural_simplify` should use what was passed in the system.

**Minimal Reproducible Example 👇**

- With scalar symbols

```julia
@variables u1 u2
@parameters k=1.0 r=1.0
eq = [0 ~ -u2 + (k - u1)/r]
@named n = NonlinearSystem(eq, [u1], [u2, k, r])
sys = structural_simplify(n; fully_determined = false)
```

Even though `u2` is passed a parameter, after `structural_simplify`, `u1` isn't elided.

```julia
julia> observed(sys)
1-element Vector{Equation}:
 u2 ~ (k - u1) / r
```

One hack was to use `ModelingToolkit.toparam` to substitute it as a parameter in the equation.

```julia
eq = [substitute(eq[1], u2 => ModelingToolkit.toparam(u2))]
@named ns =  NonlinearSystem(eq, [u1], [u2, k, r])
sys2 = structural_simplify(ns; fully_determined = false)
```

```julia
julia> observed(sys2)
1-element Vector{Equation}:
 u1 ~ r*(-u2 + k / r)
```

Here `u1` is elided.

- with array symbols

With array symbols, it has the same issue and also using `ModelingToolkit.toparam` does not work.

```julia
@variables u1 u2[1:1]
@parameters k=1.0 r=1.0
eq = [0 ~ -u2[1] + (k - u1) / r]
eq = [substitute(eq[1], u2[1] => ModelingToolkit.toparam(u2[1]))]
@named ns =  NonlinearSystem(eq, [u1], [u2[1], k, r])
sys1 = structural_simplify(ns; fully_determined = false)
```

```julia
julia> observed(sys1)
1-element Vector{Equation}:
 u2[1] ~ (k - u1) / r
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
[961ee093] ModelingToolkit v9.12.2
```

  - Output of `versioninfo()`

```julia
julia> versioninfo()
Julia Version 1.10.3
Commit 0b4590a5507 (2024-04-30 10:59 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: Linux (x86_64-linux-gnu)
  CPU: 64 × AMD EPYC 7513 32-Core Processor
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-15.0.7 (ORCJIT, znver3)
Threads: 1 default, 0 interactive, 1 GC (on 64 virtual cores)
```

**Comment by YingboMa** [comment]
This is deliberate and not a bug. `structural_simplify` explicitly doesn't respect user supplied unknowns and parameters.
