### ISSUE TITLE
Pass state and parameter names etc. to modelingtoolkitize so the equations are easier to compare

### ISSUE THREAD

**Issue by sdwfrost** [SciML/ModelingToolkit.jl#2736]
**Is your feature request related to a problem? Please describe.**

modelingtoolkitize produces equations with variables that are named differently than the original ODEProblem.

**Describe the solution you’d like**

I would like to specify the state names, parameter names, etc., so the resulting system has equations that can be more easily interpreted.

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal this should be a quick thing to fix.

We should discuss varnames in a bit though.

**Comment by sdwfrost** [comment]
I see that there are `u_names` and `p_names`; can you also specify the name of the independent variable?
