### ISSUE TITLE
testing against Julia 1.6 LTS dropped

### ISSUE THREAD

**Issue by gszep** [SciML/ModelingToolkit.jl#2854]
**Describe the bug 🐞**

In [October 2023](https://github.com/SciML/ModelingToolkit.jl/commit/c27fb33ac89cc5a96dc35361fd53c333f7b0ec56) the benchmarking against Julia 1.6 LTS was dropped. Perhaps this [blog post](https://sciml.ai/news/2021/12/02/lts/) is out of date but a user would expect to be able to use the most recent version of `ModelingToolkit.jl` with Julia 1.6.

**Expected behavior**

Being able to use `ModelingToolkit@9` with Julia 1.6

**Minimal Reproducible Example 👇**

```julia
pkg> add ModelingToolkit@9
```

**Error & Stacktrace ⚠️**

```julia
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package ModelingToolkit [961ee093]:
 ModelingToolkit [961ee093] log:
 ├─possible versions are: 0.0.1-9.24.0 or uninstalled
 ├─restricted to versions 9 by an explicit requirement, leaving only versions 9.0.0-9.24.0
 └─restricted by julia compatibility requirements to versions: 0.0.1-8.72.2 or uninstalled — no versions left
```

**Comment by thautwarm** [comment]
It seems that Julia 1.9 is not supported as well:

```
(mtk) pkg> add ModelingToolkit@9
   Resolving package versions...
ERROR: Unsatisfiable requirements detected for package Symbolics [0c5d862f]:
 Symbolics [0c5d862f] log:
 ├─possible versions are: 0.1.0-5.33.0 or uninstalled
 ├─restricted by julia compatibility requirements to versions: 0.1.0-5.14.1 or uninstalled
 └─restricted by compatibility requirements with ModelingToolkit [961ee093] to versions: 5.20.1-5.33.0 — no versions left
   └─ModelingToolkit [961ee093] log:
     ├─possible versions are: 0.0.1-9.24.0 or uninstalled
     └─restricted to versions 9 by an explicit requirement, leaving only versions: 9.0.0-9.24.0

(mtk) pkg> st
Status `E:\Git3\station\JuliaCon2024-JuliaAOT\extra\mtk\Project.toml` (empty project)
```

**Comment by baggepinnen** [comment]
Julia 1.10 was announced as new LTS yesterday, so this issue may no longer be relevant?

**Comment by gszep** [comment]
Sure why not 😄

**Comment by ChrisRackauckas** [comment]
Yeah, I thought the announcement was 6 months ago, but 🤷 . Anyways, yes we removed the old LTS when we knew that v1.10 was the new LTS, which was decided by the compiler team almost a year before it was announced at this JuliaCon. There's a lot of things from linear algebra, AOT / static compilation, and package extensions which are just hard to maintain with v1.6 compatibility, so good riddance and welcome the new v1.10 overlords.
