### ISSUE TITLE
Missing whitespace in documentation equations

### ISSUE THREAD

**Issue by ArnoStrouwen** [SciML/ModelingToolkit.jl#2894]
A minor annoyance: the whitespace around equality signs is shorter on the right than the left hand side.
https://docs.sciml.ai/ModelingToolkit/dev/tutorials/ode_modeling/
![missing whitespace](https://github.com/user-attachments/assets/aa162397-8b68-4bae-85ae-908fe04b0829)

**Comment by hersle** [comment]
At least the reason is very simple: the Latex processing turns vectors of equations into `lhs =& rhs` instead of `lhs &= rhs`. The "bug" is probably somewhere upstream?

**Comment by ChrisRackauckas** [comment]
It would be in Latexify.jl

**Comment by hersle** [comment]
Indeed, here: https://github.com/korsbo/Latexify.jl/blob/611244c507ed3ce24f875dac5f1422ab5a30b29d/src/latexalign.jl#L44
