### ISSUE TITLE
provide exported function for generating MTKParameters from user parameter maps

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#2954]
In Catalyst we often found it useful to have functionality to take a parameter map and system defaults (or `u0` map and defaults) and return the parameter representation used in solvers via `varmap_to_vars`. Such functionality doesn't seem to exist anymore with the move to MTKParameters, with one instead needing to build a full `ODEProblem` (or `JumpProblem`, etc) and then extract `oprob.p`. It would be nice to have an exported, user-facing function for building `p` without needing to go through building a full problem.

**Comment by ChrisRackauckas** [comment]
@AayushSabharwal how feasible do you think this is?

**Comment by AayushSabharwal** [comment]
`ModelingToolkit.MTKParameters(sys, p, u0)`. The last argument is optional.

**Comment by ChrisRackauckas** [comment]
Can we get a docstring and a doc page on it? Make it public API?

**Comment by AayushSabharwal** [comment]
Sure

**Comment by isaacsas** [comment]
Awesome, thanks!
