### ISSUE TITLE
Create and use Interpolation in MTK model all from symbolic parameters

### ISSUE THREAD

**Issue by Snowd1n** [SciML/ModelingToolkit.jl#3048]
**Question❓**

Is there a way to convert symbolic parameters and variables into an interpolation using datainterpolations and have a symbolic equation that then evaluates on this? My idea is as follows

```
using DataInterpolations,ModelingToolkit
@variables y(t)[1:10] A B
@parameters xgrid[1:10] C

spl = LinearInterpolation(xgrid,y)
@register_symbolic spl(x::AbstractVector,y::AbstractVector)::LinearInterpolation
B ~ spl(A)*C
```

**Comment by ChrisRackauckas** [comment]
We're working on a solution here, hold your horses 🐴

**Comment by Snowd1n** [comment]
Will do. Thank you
