### ISSUE TITLE
D(x)-like guesses are not respected during initialization

### ISSUE THREAD

**Issue by hersle** [SciML/ModelingToolkit.jl#3049]
$x\prime\prime(t) = 0$ with $x(0) = 0$ and ${x\prime(0)}^2 = 1$ should initialize with $x\prime(0) = \pm 1$ chosen by an initial guess, and solve to $x(t) = \pm t$:
```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using DifferentialEquations
using Test

for sign in [-1.0, +1.0]
    @variables x(t)
    sys = ODESystem(
        [D(D(x)) ~ 0], t;
        initialization_eqs = [D(x)^2 ~ 1, x ~ 0], guesses = [D(x) => sign], name = :sys
    ) |> structural_simplify
    prob = ODEProblem(sys, [], (0.0, 1.0), [])
    sol = solve(prob, Tsit5())
    @test sol(1.0, idxs=sys.x) ≈ sign # system with D(x(0)) = ±1 should solve to x(1) = ±1
end
```
But it always chooses the negative branch:
```
Test Failed at C:\Users\herma\.julia\dev\SymBoltz\bug.jl:14
  Expression: sol(1.0, idxs = sys.x) ≈ sign
   Evaluated: -0.9999999999999956 ≈ 1.0
```
So it looks like the guess for `D(x)` is not respected. Is there a missing dummy derivative substitution somewhere, similar to https://github.com/SciML/ModelingToolkit.jl/issues/3029?

**Comment by ChrisRackauckas** [comment]
Yes, this looks like a substitution miss. We probably need to do a pass over the keys like in that issue you linked, where we pass over it to get the new guesses array before putting that with the NonlinearSystem

**Comment by hersle** [comment]
Ok, thanks! I will try to fix it in a similar way.
