### ISSUE TITLE
HTML for arrays of underscored-parameters is broken

### ISSUE THREAD

**Issue by cstjean** [SciML/ModelingToolkit.jl#3052]
**Describe the bug 🐞**

![image](https://github.com/user-attachments/assets/0d704d1a-10a1-4936-90e2-4c5815ce1971)

**Expected behavior**

Elegant HTML output.

**Minimal Reproducible Example 👇**

```julia
begin
	using ModelingToolkit
	using ModelingToolkit: t_nounits as t, D_nounits as D
	using SymbolicIndexingInterface
	using DataInterpolations, ReadOnlyArrays
	using Symbolics
end

@parameters P_out[1:5]

P_out[1]
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
Status `C:\Users\a1058035\AppData\Local\Temp\jl_tP4Nh4\Project.toml`
  [82cc6244] DataInterpolations v6.4.0
  [961ee093] ModelingToolkit v9.39.1
  [988b38a3] ReadOnlyArrays v0.2.0
  [2efcf032] SymbolicIndexingInterface v0.3.30
  [0c5d862f] Symbolics v6.11.0
  [44cfe95a] Pkg v1.10.0
```

Julia 1.10.5, Windows, Edge.

This is probably a Symbolics/SymbolicsUtils issue? Please move to the appropriate repository.

**Comment by ChrisRackauckas** [comment]
That's a Symbolics issue, though it's odd because that looks like proper latex?

**Comment by cstjean** [comment]
Not sure about proper latex, but FWIW

![image](https://github.com/user-attachments/assets/639c8887-846e-469e-bf27-3246cdfdf3ba)

**Comment by ChrisRackauckas** [comment]
The wrong underscore?

**Comment by SebastianM-C** [comment]
Isn't it that you have 2 underscores instead of just one? I think that the `{` wrapping should cover the entire underscored argument.

**Comment by ChrisRackauckas** [comment]
Can this be recreated with just Symbolics and closed here?

**Comment by cstjean** [comment]
https://github.com/JuliaSymbolics/Symbolics.jl/issues/1288
