### ISSUE TITLE
Clarify DomainConnector error message

### ISSUE THREAD

**Issue by cstjean** [SciML/ModelingToolkit.jl#3064]
**Describe the bug 🐞**

The `ERROR: connect(a₊b,c₊d) contains multiple source domain connectors. There can only be one!` is unclear (this [discourse poster](https://discourse.julialang.org/t/help-needed-for-a-simple-static-sum/99744/5) is also confused). 

This error message was written in https://github.com/SciML/ModelingToolkit.jl/pull/2122 by @YingboMa 

**Expected behavior**

Better explanation of the problem.

**Minimal Reproducible Example 👇**

The [discourse post](https://discourse.julialang.org/t/help-needed-for-a-simple-static-sum/99744/5) has a MWE. Here is mine:

```julia
@connector FlowPin begin
	flow(t), [connect=Flow]
end

@mtkmodel Faucet begin
	@parameters begin
		specified_flow
	end
	@components begin
		outlet = FlowPin()
	end
	@equations begin
		outlet.flow ~ specified_flow
	end
end

@mtkmodel Bath begin
	@components begin
		inlet = FlowPin()
	end
	@variables begin
		water_level(t)
	end
	@equations begin
		D(water_level) ~ inlet.flow
	end
end

@mtkmodel Bathroom begin
	@components begin
		bath = Bath()
		faucet = Faucet()
	end
	@equations begin
                connect(faucet.outlet, bath.inlet)
	end
end

@mtkbuild bathroom = Bathroom()
```

To me it looks like this is a well-specified problem, with equations

```
faucet.outlet.flow = specified_flow
faucet.outlet.flow + bath.inlet.flow = 0
D(bath.water_level) = bath.inlet.flow
```

but I'm probably missing something.

**Error & Stacktrace ⚠️**

```julia
connect(faucet₊outlet,bath₊inlet) contains multiple source domain connectors. There can only be one!

Stack trace
Here is what happened, the most recent locations are first:

error(s::String) @ [error.jl:35](https://github.com/JuliaLang/julia/tree/6f3fdf7b36250fb95f512a2b927ad2518c07d2b5/base/error.jl#L35)
connection2set!(connectionsets::Vector{ModelingToolkit.ConnectionSet}, namespace::Nothing, ss::Tuple{ModelingToolkit.ODESystem, ModelingToolkit.ODESystem}, isouter::ModelingToolkit.var"#isouter#430"{Vector{Symbol}}) @ connectors.jl:240
generate_connection_set!(connectionsets::Vector{ModelingToolkit.ConnectionSet}, domain_csets::Vector{ModelingToolkit.ConnectionSet}, sys::ModelingToolkit.ODESystem, find::Nothing, replace::Nothing, scalarize::Bool, namespace::Nothing) @ connectors.jl:368
generate_connection_set! @ connectors.jl:320
#generate_connection_set#433 @ connectors.jl:310
generate_connection_set @ connectors.jl:306
expand_connections(sys::ModelingToolkit.ODESystem, find::Nothing, replace::Nothing; debug::Bool, tol::Float64, scalarize::Bool) @ connectors.jl:484
expand_connections @ connectors.jl:482
__structural_simplify(sys::ModelingToolkit.ODESystem, io::Nothing; simplify::Bool, kwargs::@Kwargs{allow_symbolic::Bool, allow_parameter::Bool, conservative::Bool, fully_determined::Bool}) @ systems.jl:77
__structural_simplify @ systems.jl:75
structural_simplify(sys::ModelingToolkit.ODESystem, io::Nothing; simplify::Bool, split::Bool, allow_symbolic::Bool, allow_parameter::Bool, conservative::Bool, fully_determined::Bool, kwargs::@Kwargs{}) @ systems.jl:33
structural_simplify @ systems.jl:28
```

**Environment (please complete the following information):**

  - Output of `using Pkg; Pkg.status()`

```julia
ModelingToolkit 9.40.0
```

**Comment by cstjean** [comment]
As suggested by @contradict, adding a dummy variable to the connector makes the problem succeed all the way to `solve`. 

```julia
@connector FlowPin begin
	flow(t), [connect=Flow]
	dummy(t)
end
```

So perhaps it's a deeper problem than just the error message...

**Comment by YingboMa** [comment]
A connector with only a flow variable is a domain connector and not a normal connector.

**Comment by francis-gagnon** [comment]
Perhaps the message could be a little more beginner friendly (i.e. people not used to acausal modeling or modelica) ? What's a domain connector ?

**Comment by cstjean** [comment]
Isn't it confusing that the above `dummy(t)` fixes the problem? Conceptually, why couldn't I have a RegularConnector with only a single Flow variable, as in the above example?

DomainConnector is mentioned, but not explained [here](https://docs.sciml.ai/ModelingToolkit/stable/basics/MTKLanguage/#Connectors). I suppose the [Domain tutorial](https://docs.sciml.ai/ModelingToolkit/stable/tutorials/domain_connections/) is the reference, as it contains a DomainConnector (AFAICT), but I can't quite read it yet.
