### ISSUE TITLE
Add ModelingToolkit.getdefault to public API

### ISSUE THREAD

**Issue by kraqbi** [SciML/ModelingToolkit.jl#3071]
Hello,

I needed to get access to the default values of my parameters. I could not find documentation to do so.
I finally found from here the function ModelingToolkit.get_default() .

Promote that function to public API and adding a documentation could help a lot for similar usage.
The function itself does work quite well right now.

**Comment by hersle** [comment]
`defaults(sys)` is public, though.

**Comment by kraqbi** [comment]
Indeed. Thank you. Sorry for the trouble.

(tutorial for defaults(sys) https://docs.sciml.ai/ModelingToolkit/stable/basics/AbstractSystem/#Composition-and-Accessor-Functions)
