### ISSUE TITLE
Allow providing parameters to ODEProblem as a Dict

### ISSUE THREAD

**Issue by asinghvi17** [SciML/ModelingToolkit.jl#311]
Instead of a Vector{Pair}.  This makes working with Observables much easier, as one need only mutate the Dict and remake the problem instead of replacing an element of an array (and storing indices, etc, etc).

**Comment by ChrisRackauckas** [comment]
Yes, that's a nice suggestion. We generally create the output based on the type of the input here, but in this case we could just assume the user wants an Array. The piece of code in this spot is:

https://github.com/SciML/ModelingToolkit.jl/blob/master/src/variables.jl#L242-L262

I think it would be enough to add a dispatch on Dict that creates the array and loops through the variables picking out the values.

**Comment by ChrisRackauckas** [comment]
This is implemented.
