### ISSUE TITLE
9.46 introduces breaking change in complete

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#3118]
https://github.com/SciML/ModelingToolkit.jl/blame/fcad04c5bef4f27de1245f15b20f6928952cb9fd/src/systems/abstractsystem.jl#L925-L933

This is a change in an exported API function that makes new assumptions on system properties / behavior that were not previously present. Shouldn't this be breaking? The need to explicitly opt JumpSystems out of this change seems telling -- isn't that indicative that this is breaking for anything but an ODE/SDE system? Other system types defined outside of MTK will now have to dispatch and create their own version of this function or the newly introduced functions to avoid issues. Catalyst, for example, is now completely broken with this change on 9.46.

**Comment by ChrisRackauckas** [comment]
Sorry, CI was just weird from the v1.11 so we missed this.
