### ISSUE TITLE
Nicer parameter indexing

### ISSUE THREAD

**Issue by jd-lara** [SciML/ModelingToolkit.jl#318]
It seems from a first look that it isn't possible to define a callback to modify a parameter value like in a regular ODE model where we can intercept `p.value`

**Comment by ChrisRackauckas** [comment]
We can make an index map that's a LabelledArray with the integer indices, and then `idxs.lorenz.x` could lower to the index at compile time with now overhead.

**Comment by ChrisRackauckas** [comment]
```julia
indexof(sym,syms) = findfirst(isequal(sym),syms)
indexof(σ,parameters(sys))
```

is the helper function we should add and document.

**Comment by ChrisRackauckas** [comment]
We can actually handle this nicely by:

1. Adding a `parameter_syms` to the SciMLFunction/SciMLProblem types
2. Overloading getproperty to call into `SciMLBase.sym_to_index`

then `integrator.p[lorenz.x]` would work.

**Comment by ChrisRackauckas** [comment]
Remove from FAQ when fixed.

**Comment by ChrisRackauckas** [comment]
SymbolicIndexingInterface solved these issues.
