### ISSUE TITLE
Observed variable calculated incorrectly using new discrete parameters

### ISSUE THREAD

**Issue by bradcarman** [SciML/ModelingToolkit.jl#3199]
MWE with discrete parameter `heading(t)`...

```julia
using ModelingToolkit
using ModelingToolkit: t_nounits as t, D_nounits as D
using OrdinaryDiffEq
using Plots

inch = 25.4e-3
sec = 1
rate = 2*inch/sec
L = 4*inch

pars = @parameters begin
    heading(t) = 1
end

vars = @variables begin
    x(t) = 0
    dx(t) = rate
end

eqs = [
    dx ~ heading*rate
    D(x) ~ dx
]

events = [
    [x~0] => [heading ~ +1]
    [x~L] => [heading ~ -1]
]

@mtkbuild sys = ODESystem(eqs, t, vars, pars; continuous_events=events)
prob = ODEProblem(sys, [], (0, 8))
sol = solve(prob)
 
plot(sol; idxs=x)
plot(sol; idxs=dx)
plot(sol; idxs=heading)
```

This gives the correct result for `x` and `heading`

![image](https://github.com/user-attachments/assets/31dbd1ce-e19e-4c25-b6ba-c9a5b8b58f8f)
![image](https://github.com/user-attachments/assets/56e6176e-75c9-44cd-b96f-e18bff84e03f)

However, the observed variable `dx` plots a constant value...

![image](https://github.com/user-attachments/assets/a30c1a0c-924d-4dca-bfa7-856b404b0438)

As can be seen, the observed function for `dx` is 

```julia
julia> observed(sys)
1-element Vector{Equation}:
 dx(t) ~ 0.0508heading(t)
```

Which means the calculation of `dx` is not handling the change in `heading` correctly.

**Comment by AayushSabharwal** [comment]
This has been fixed in the PR linked above
