### ISSUE TITLE
Hash of Operations and Equations

### ISSUE THREAD

**Issue by jlperla** [SciML/ModelingToolkit.jl#320]
https://github.com/SciML/ModelingToolkit.jl/pull/312 looks like a good start (though I am not getting "reboot" stable hashes for variables, but perhaps I used it wrong).

For us, the following should cover every use-case

```julia
using ModelingToolkit
@variables x y z
eqs_1 = [0 ~ y - z,
       0 ~ 3 + y^2]
eqs_2 = [z ~ x + y,
         y ~ sin(x) + 4]
hash(x)
hash(ModelingToolkit.Constant(0))
hash([x,y])
hash([y,x])
hash(eqs_1)
hash(eqs_2)
```
If those all gave REPL reboot, and OS independent hashes (at least for the same UInt sized operating systems) we would be in business for our function caching approach.  The hashing of equations doesn't need to be high performance for our applications, so crude hacks are OK.

-------
The only one I could figure out on my own works great
```julia
Base.hash(x::ModelingToolkit.Constant, h::UInt) = hash(x.value, h)
```
For what it is worth, I think that `0 ~ sin(x) + 3 + y^2` etc. could be hashable based entirely on a string representation of that AST if that provides a quick hack to avoid adding too many dispatches.  Note that,
```julia
julia> dump(0 ~ sin(x) + 3 + y^2)
Equation
  lhs: ModelingToolkit.Constant
    value: Int64 0
  rhs: Operation
    op: + (function of type typeof(+))
    args: Array{Expression}((2,)) Expression[sin(x) + 3, y ^ 2]
```
encapsulates everything about the expression and can be comparable across reboots and operating systems.

On this, we do not need hashing of equations to be fast for our applications.

**Comment by jlperla** [comment]
FYI:  For our applications, the following fulfills the test cases:
```julia
hash(x::ModelingToolkit.Operation, h::UInt) = hash(sprint(dump, x), h)
hash(x::ModelingToolkit.Constant, h::UInt) = hash(x.value, h)
```
But since this is a hacky way to do it, possibly to inefficient to hash operations for dictionary lookups, I won't submit as a PR and will leave the issue open in case others have better ideas.

**Comment by ChrisRackauckas** [comment]
Finished by @shashi
