### ISSUE TITLE
Link to stable documentation is broken

### ISSUE THREAD

**Issue by MFairley** [SciML/ModelingToolkit.jl#325]
The link https://mtk.sciml.ai/stable/ results in a 404 error.

**Comment by ChrisRackauckas** [comment]
Yes, we haven't had a release since the documentation was made. The first release after the documentation is released will populate those docs.

**Comment by ChrisRackauckas** [comment]
Hmm, I added a version but didn't get a new version in the docs.

**Comment by ChrisRackauckas** [comment]
Awesome, we have a version now.
