### ISSUE TITLE
Link to SymbolicUtils Substitution

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#339]
When https://github.com/JuliaSymbolics/SymbolicUtils.jl/issues/59 is complete, we should make our substitution tools all make use of it. This includes the substitutions in the jumps (https://github.com/SciML/ModelingToolkit.jl/pull/336/files#diff-4991951911e82642fe59ec98a772f888R47).

@shashi @isaacsas

**Comment by isaacsas** [comment]
Does MT allow Dicts now for the u0 and param maps?

**Comment by ChrisRackauckas** [comment]
Not yet. I need to figure out how to do the checking/hashing: https://github.com/SciML/ModelingToolkit.jl/pull/312

**Comment by shashi** [comment]
```julia
function substitute(x, dict)
    dict1 = Dict(map(Pair,
                       map(to_symbolic, keys(dict)),
                       map(to_symbolic, values(dict))))
    RuleSet([@rule(~x::(x->haskey(dict, x)) => dict[~x])])(to_symbolic(x)) |> to_mtk
end
```

Can be used now.

**Comment by ChrisRackauckas** [comment]
Is that how we should do it? Like, should we just get a PR of this and replace https://github.com/SciML/ModelingToolkit.jl/blob/master/src/utils.jl#L101-L116 ?

**Comment by shashi** [comment]
Yes that would be the way to do it. And you won't even need #312 since I think Symutils will hash converted MTK IR correctly.

And you may want to throw in a `simplify` before `to_mtk` so you can simplify before converting.
