### ISSUE TITLE
Aliases, intermediates, explicit algebraic variables, and system simplification

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#340]
This is a big title but it's because all of these ideas are really the same thing. As a demonstration, let's look at the README example but with a slightly different coupling term:

```julia
using ModelingToolkit, OrdinaryDiffEq

@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

lorenz1 = ODESystem(eqs,name=:lorenz1)
lorenz2 = ODESystem(eqs,name=:lorenz2)

@variables a
@parameters γ
connections = [0 ~ lorenz1.x + lorenz2.y]
connected = ODESystem(connections,t,[],[],systems=[lorenz1,lorenz2])
```

In some sense this is an overdetermined system, but in another sense it's because we just need to simplify. What we need to do is just understand that `lorenz2.y ~ -lorenz1.x`, substitute, and now we have a 5 variable system of ODEs instead of a 6 DAE system. So system simplification is thus the same problem as having intermediate variables or explicit algebraic variables. Aliased variables are just the special case where it can turn out that `lorenz1.x ~ lorenz2.y`. So it's all the same phenomena. The question is then what we do about this case.

In the past we eliminated these from the equations. That may have been short signed, or it may have been a smart idea which just was leaving out a detail. In the end, we have to build an ODE of 5 variables, so we could just perform the the simplification to get 5 ODEs and solve it. But what do we do about:

```julia
u0 = [lorenz1.x => 1.0,
      lorenz1.y => 0.0,
      lorenz1.z => 0.0,
      lorenz2.x => 0.0,
      lorenz2.z => 0.0,
      a => 2.0]

p  = [lorenz1.σ => 10.0,
      lorenz1.ρ => 28.0,
      lorenz1.β => 8/3,
      lorenz2.σ => 10.0,
      lorenz2.ρ => 28.0,
      lorenz2.β => 8/3,
      γ => 2.0]

tspan = (0.0,100.0)
prob = ODEProblem(connected,u0,tspan,p)
sol = solve(prob,Rodas5())
using Plots; plot(sol,vars=(a,lorenz1.x,lorenz2.z))
```

If we simplified out `lorenz2.y` and the user gives us `lorenz1.x` we're good! If we simplified out `lorenz1.x` and kept `lorenz2.y`, well, then we have an issue:

- How do we know how to set the initial condition if `lorenz1.x` isn't a variable anymore?
- How do we know how to plot or output when `lorenz1.x` doesn't exist?

Of course the answer is that, if we have `lorenz1.x ~ ...` as one of the explicit algebraic equations that we used to simplify it out of the system, then we also know, given the solution of the system, how to map it back to get the plot of the output. Possibly a little bit harder is how to allow `lorenz1.x` as the initial condition if we only have `lorenz2.y`: we would have to invert the algebraic expressions, and possibly have a nonlinear system to solve.

## How to handle this issue

I think the way to handle this issue is two-fold. Not allowing these equations into `eqs` is really nice for the equation building and system lowering, so I think that what we can do is allow algebraic variables in `ODESystem(eqs)`, the "simplified" form, but the true lowered form of the system should never keep the two together. Instead, what we'd add to the `AbstractSystem` interface is `sys.aliases` and `aliases(sys)` for these alternative variables. Then we would need to add a few conveniences based on this:

- [ ] Improve the compatibility of `DESolution` with `syms`: `sol[:x]` should return the timeseries for `:x`, and things like `sol[:x,1:5]` should all work just like how plotting doesn't require you to know the variable indices.
- [ ] Make this compatibility all automatically `convert(Symbol,x)` so that `sol[x]` for standard MTK variables and operations works.
- [ ] Support this syms stuff in the interpolations, i.e. `sol(t;idxs=x)`
- [ ] Allow the `DEFunction`s to have an `outputmap`. This would go along with the `syms` argument. This would allow for `outputmap(u,:x) = u[vars[x]]` etc. By making it one step removed, this outputmap would then allow `outputmap(u,lorenz2.x)` to perform a substitution on the fly.
- [ ] Integrate `outputmap` throughout the solution interface. This way `plot(sol,vars=(x,lorenz2.y))` automatically uses the alias to perform the conversion and make the plot, and so does `sol[lorenz2.y]` to get the timeseries. In this way, users never have to know about what variables are eliminated and which are real.
- [ ]  `build_function` will need a keyword argument for algebraic equations which it just slaps in before the real equations.
- [x] In all of the auxiliary functions (Jacobians, Wfact, etc.), need to make sure their `build_function` calls add the `aliases` expressions as algebraic equations. 
- [ ] Handle aliased variables in initial conditions. This may even need to get its own issue since it'll take more time and is more complex than the other steps. Basically, if it doesn't find the value as one of the real values, then it needs to check the aliases before erroring. This can be done for every value, and then all of the alias values can be substituted into the alias expressions, and then here we do a nonlinear solve (symbolically or numerically) to get the initial conditions of the true variables.

This also allows for CSE on the Julia side, and the long requested interface for explicit algebraic variables to be handled nicely.

The real question that is still somewhat lingering is how this design interacts with dynamic selection of states. This is all thinking about static state selection. However, in dynamic selection of states we still just need to know the same total set of functions and it's the job of `build_function` to swap between alias and eqs. In this case, it's possible that `alias` could have implicit alias expressions instead of just explicit, in which case the `outputmap` becomes more complex but it's all generally the same strategy.

**Comment by FHell** [comment]
+ 1 on aliases and keeping equations around and outputmaps (as I understand it). In NetworkDynamics.jl / PowerDynamics.jl we are working around these type of issues all the time. Having that built in to DEFunctions/solution objects would be great functionality.

I think for many compositional tasks it would be more natural to express components with inputs and outputs though. It might be more appropriate to write another issue for that.

**Comment by ChrisRackauckas** [comment]
Yeah the probably this doesn't solve yet is that I think @asinghvi17 needs something like a "reduction node", where it can be an open list of things that are then summed to become the input `F` forcing term. Using our current style, I think all of the inputs into `F` have to be known at the same time in order to write the equation for `F ~ ...`, which might be less than ideal, so I'm trying to think about how to handle that problem simultaneously. Any suggestions would be welcome of course.

**Comment by ChrisRackauckas** [comment]
Copying over from https://github.com/SciML/ModelingToolkit.jl/issues/362 since this now has a prototype of what this will look and feel like:

We can lower this to just be an algebraic equation without a differential part if we notice that it's an `aliasvar`, so again no extra machinery required and this'll work on all equation types. A well-formed system that is numerically computable then just has, at it's highest level, all aliasvars must have an aliaseq associated with it. These are then just dropped in above the DE calculation and computed in the let expansion.

We can then put a `ControlSystem` above this setup that makes it nicer to write such control models with a `u` part etc. but it would be good to have the compilation process all target `ODESystem` so that way we have a common spot to put all of our optimization and transformation logic. If I'm not mistaken, this handles all of your concerns and is what is proposed in https://github.com/SciML/ModelingToolkit.jl/issues/340.

The only thing that isn't handled is this open "reduce by sum" thing. Now that you all have seen the syntax, maybe you all might have a suggestion.

**Comment by ChrisRackauckas** [comment]
For reductions, what about adding in a `pin`, where a `pin` is considered open and then requires access by reduction. For example:

```julia
@variables x(t) y(t) z(t) J(t)
@derivatives D'~t

eqs = [D(x) ~ σ*(reduce(+,y)-J),
           D(z) ~ x*reduce(+,y) - β*z]
vars = [x,z]
aliasvars = [J]
aliaseqs = [J ~ x - 0.05sin(x)]
c1 = ODESystem(eqs,t,vars,[],aliasvars = aliasvars, aliaseqs = aliaseqs, pin = [y], name = :c1)
c2 = ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c2)
c3 = ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c3)
c4 = ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c4)
c5 = ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c5)

connectioneqs = [c1.y ~ c2.y, c2.J ~ c1.J,  c2.z ~ c1.z,
                             c1.y ~ c3.y, c3.J ~ c1.J,  c3.z ~ c1.z,
                             c1.y ~ c4.y, c4.J ~ c1.J,  c4.z ~ c1.z,
                             c1.y ~ c5.y, c5.J ~ c1.J,  c5.z ~ c1.z]
connected = ODESystem(connectioneqs,t,[],[],name = :connected)
```

Or maybe

```julia
c1 = ODESystem(eqs,t,vars,[],aliasvars = aliasvars, aliaseqs = aliaseqs, pin = [y ~ +], name = :c1)
```

**Comment by FHell** [comment]
I think I slightly misunderstood what you were proposing here, it's clearer now, thanks.

Something like `ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c2)` could not be turned into a DEFunction, right?

I am out of the office for now and have a day full of meetings tomorrow, but will give the other two issues a careful read again and report back ASAP. We should have gotten in touch about all this sooner, sorry about that.

**Comment by ChrisRackauckas** [comment]
>Something like ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c2) could not be turned into a DEFunction, right?

Yes, only the system above it that defines how its aliases get their values would be a computable system.

>I am out of the office for now and have a day full of meetings tomorrow, but will give the other two issues a careful read again and report back ASAP. We should have gotten in touch about all this sooner, sorry about that.

No worries at all! We should've contacted you once we started going this direction with MTK. It's realy just quickly evolving almost out of nowhere.

**Comment by FHell** [comment]
If we could turn incomplete ODESystems into incomplete DEFunctions (what I called IOFunctions) of the form `f(dx, x, p, t, u)` we could immediately-ish start supporting MTK components in ND.jl. I think this has additional uses, too, for example if you want to input a random function into u that you draw later. I will edit the other issue to talk about this.

A point on naming this functionality: In the form `ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c2)` it is very strange to think of `[J, z]` as aliases. What they really are is unspecified/open/input variables. In fact I would not expect an alias to occur in the primary equations at all but be specified by the alias equations.

**Comment by ChrisRackauckas** [comment]
>A point on naming this functionality: In the form ODESystem([D(y) ~ J*(ρ-z)-y],t,[y],aliasvars = [J,z], name= :c2) it is very strange to think of [J, z] as aliases. What they really are is unspecified/open/input variables. In fact I would not expect an alias to occur in the primary equations at all but be specified by the alias equations.

Yeah, I was thinking about it the other day... unspecified open variables is just an input variable, and the explicit algebraic variables are just output variables, so we might as well just have input/output variables already split in the system since that would make parsing easier. Symbolic designation of an alias would then amount of the derivation that something that was implicit could instead be rewritten as an output variable, so we would still have alias machinery (remember, thinking about MTK is not just the front-end but it's also the transform-invariant IR). So I'll do this as input/output instead. The on inputs we can have a `reduction` designation which defaults to `+` for what `reduce` function to do for multiple equations into the input. Does that cover everything?

>If we could turn incomplete ODESystems into incomplete DEFunctions (what I called IOFunctions) of the form f(dx, x, p, t, u) we could immediately-ish start supporting MTK components in ND.jl. I think this has additional uses, too, for example if you want to input a random function into u that you draw later. I will edit the other issue to talk about this.

You can already do this via `build_function` since it takes any amount of args. `build_function(x,p,t,u;...)` would make `f(dx, x, p, t, u)`. The real question is just how to make a nicer interface to control problems that then knows how to translate itself to a standard ODE.

**Comment by FHell** [comment]
> So I'll do this as input/output instead. The on inputs we can have a reduction designation which defaults to + for what reduce function to do for multiple equations into the input. Does that cover everything?

Sounds excellent. One thing we have in flow networks is a fiducial orientation on the edge. The flow is calculated once and then subtracted at the source and added at the edge (so the direction of the flow is encoded in the sign). LightGraphs already comes with this fiducial information (even for undirected graphs) as they have a source and destination function. I don't think at first glance that that will require additional support from pins though as we can use an alias to always get the outgoing flow instead.

> The real question is just how to make a nicer interface to control problems that then knows how to translate itself to a standard ODE.

Yes I see, this is what I was trying for with the IOSystem thing, having it inside ODESystem directly would be great of course, and keeping track of aliases/outputs will make it much more powerful. One of the issues we noticed when combining controllers is that we need access to the variables we have eliminated mathematically....

**Comment by ChrisRackauckas** [comment]
>One of the issues we noticed when combining controllers is that we need access to the variables we have eliminated mathematically....

Why? Do you need their outputs or do you actually need their values? Those are two separate things and I would like to understand how or why you'd need the latter.

**Comment by FHell** [comment]
> Why? Do you need their outputs or do you actually need their values? Those are two separate things and I would like to understand how or why you'd need the latter.

I am not sure I understand your distinction. This occurs in more complex controller designs, when we're trying to debug why the controller isn't doing what it's supposed to be doing. Mostly it comes from designs we have to implement that people came up with with point and click tools (Simulink, Modelica), by chaining blocks. When translating them to equations we might not have the variable that connected them explicitly any more.

E.g. I have a measurement block that is maybe something like y = f(x) and a control block that does \dot z = g(z, y). So I combine them into \dot z = h(x, z) = g(z, f(x)). So now we simulate and get trajectories x(t) and z(t) that don't do what we expect, and to debug (and compare to the point and click tools) it would be useful to have y(t). Right now when we need this we implement f(x) separately again and then wrap it with the solution. It's not the biggest issue by itself, but it's a bit challenging to provide a seamless experience for people who are not developers. Which is why this bit in your initial feature list list: "Integrate outputmap throughout the solution interface" will make things much smoother for us. :)

**Comment by ChrisRackauckas** [comment]
This has all finally been completed by @YingboMa 's work on transformations like `alias_elimination`, StructuralTransformations.jl, and finally https://github.com/SciML/SciMLBase.jl/pull/9
