### ISSUE TITLE
ModelingToolkit.jl name

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#352]
It was supposed to be a DSL so it was SciCompDSL.jl, then it was supposed to just be a backend so it became ModelingToolkit.jl, and now it's becoming much more forward-facing as a symbolic-numeric modeling language for the SciML ecosystem. It probably needs a full name to cover the big role it's starting to play. What's a good name for it?

**Comment by Vaibhavdixit02** [comment]
I like the name ModelingToolkit. It does lack a certain glitz but I think it gets the functionality across pretty well.

If there is a need for a change though, NumSym sounds good. 

Going for something funkier I find Etna.jl a good fit (https://en.wikipedia.org/wiki/Mount_Etna) specifically the part

>and the forges of Hephaestus were said also to be underneath it 

Or Fornax.jl, which is Latin for a forge/furnance.

**Comment by ChrisRackauckas** [comment]
I talked with a few people privately, and everyone kind of liked it. But Etna will be a good one for the future.
