### ISSUE TITLE
Compiler Target: Dagger or Neural Schedulers

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#366]
It would be nice to target dagger as one of the output possibilities. Right now our parallelism utilizes static scheduling, but since we have access to the graph we could use Dagger or smarter scheduling techniques for producing the output and splitting apart the equations. It would be nice to make this option accessible to users for very large problems. A good application here would be large chemical reaction networks.

**Comment by ChrisRackauckas** [comment]
@shashi @jpsamaroo

**Comment by jpsamaroo** [comment]
I can take a stab at this. How shall I include Dagger: Direct dependency, or lazy loading via Requires?

**Comment by ChrisRackauckas** [comment]
Requires

**Comment by shashi** [comment]
I would say if you have 8 equations and 2 procs, we just create 8 dagger tasks and let Dagger do the scheduling real time. Right?

**Comment by jpsamaroo** [comment]
IMO we create 8 `Dagger.delayed` calls, and 1 "reducer" `delayed` call to tie them together so a single scheduler instance gets used.

**Comment by shashi** [comment]
Ah yeah I meant 8 Dagger.delayed.

You may want to create multiple reducers (`Dagger.treereduce(delayed(combine)...)`) if the combining task is chunky enough, that gives more parallelism.
