### ISSUE TITLE
Extend dependency graphs to AbstractSystems and document them

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#368]
https://github.com/SciML/ModelingToolkit.jl/pull/353 is a good start in this direction, but we should cover `AbstractSystem` and add it to the docs.

**Comment by isaacsas** [comment]
How would it work for AbstractSystems? It seems like one needs context for the `eqs` to calculate dependencies?

**Comment by isaacsas** [comment]
BTW, for SDESystems should the dependency graph include dependencies through the noise terms (i.e. `g`), or should it be the same as the ODE dependencies with the noise dependencies handled separately?

**Comment by ChrisRackauckas** [comment]
I think same as the ODE graph and handle the noise on separately.

>How would it work for AbstractSystems? It seems like one needs context for the eqs to calculate dependencies?

IIUC, `get_variables!` just needs an overload on `Equation`? 

On the same note, we need to unify `get_variables!` and `get_variables`. The latter should just allocate and call `get_variables!`, and `get_variables!` needs to get the dispatches of `get_variables` and add one for `Equation`. Then I don't think anything else is context dependent?

https://github.com/SciML/ModelingToolkit.jl/blob/master/src/utils.jl#L86-L99
https://github.com/SciML/ModelingToolkit.jl/blob/master/src/systems/dependency_graphs.jl#L9

**Comment by isaacsas** [comment]
Yeah, that should be all that is needed for both the `get_variables!` and `modified_states!` functions. I didn't touch that before as I didn't want to break the current API. If breaking changes are ok I'm happy to make such a change.

**Comment by ChrisRackauckas** [comment]
It wouldn't be breaking if `get_variables` just allocates and calls `get_variables!`

**Comment by isaacsas** [comment]
I was going to ditch the `vars = operation[]` arg.

**Comment by ChrisRackauckas** [comment]
Then isn't it just `get_variables`?

**Comment by isaacsas** [comment]
Right now the original version is `get_variables(e, vars=Operation[])`.

There is no need for the second argument if we add `get_variables!` since `get_variables` will always allocate if called. I could add a depreciation warning about the two argument form?

**Comment by isaacsas** [comment]
I'll just put in the PR and you can comment there. This is too trivial for a back and forth :)

**Comment by ChrisRackauckas** [comment]
Yeah deprecate it.
