### ISSUE TITLE
SDESystems don't set noise_rate_prototype 

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#375]
Seems like this is something that should be handled in the problem creation automatically based on `sparse` being true or false.

**Comment by ChrisRackauckas** [comment]
Agreed. This should be automatic. Though we do want to handle diagonal noise correctly as well: set it to nothing if `neqs` is an AbstractVector, otherwise match size of neqs and use sparsity.

Do you have a good integration test case in mind?

**Comment by isaacsas** [comment]
Maybe we could use the BCR network? That certainly works with Gillespie and ODE, so SDE should work hopefully too, baring problems with going negative. Probably not good for including in day to day tests though as the overhead on creating everything is pretty big.

Otherwise I was just going through @TorkelE's DEBio PR and noticing that he was having to set this manually, so thought it was worth mentioning here.

**Comment by ChrisRackauckas** [comment]
>Otherwise I was just going through @TorkelE's DEBio PR and noticing that he was having to set this manually, so thought it was worth mentioning here.

Oh yes, he definitely shouldn't be doing that 😆 . I thought you might've been working on an example that you could just paste in, but I can build one for testing on.

>Maybe we could use the BCR network? That certainly works with Gillespie and ODE, so SDE should work hopefully too, baring problems with going negative. Probably not good for including in day to day tests though as the overhead on creating everything is pretty big.

Yeah, that's a good benchmark but a scary unit test.

**Comment by ChrisRackauckas** [comment]
Fixed and tested in https://github.com/SciML/ModelingToolkit.jl/pull/376
