### ISSUE TITLE
Support for events

### ISSUE THREAD

**Issue by AleMorales** [SciML/ModelingToolkit.jl#38]
State and time-triggered events are common in dynamical models, so modelling frameworks that generate SciComp IR may want to pass this information along, rather than hook the callbacks after code generation. After all, events are part of a model definition even if they are stored separately. I don't how abstract the event support should be, maybe for now we could allow storing a `CallbackSet`?

**Comment by ChrisRackauckas** [comment]
While the goal isn't to re-create Modia.jl at all (if it ever gets released), this is another spot where I think we should look to Modia/Modelica for inspiration, along with Tensorflow.

https://link.springer.com/chapter/10.1007%2F978-3-319-47169-3_15

They treat if statements specially and make people opt-out with a `NoEvent()`.

I have been thinking of doing something like `ContinuousEvent(x>y,rho = 3)` and one for `DiscreteEvent`. We could add to this repo a few `<:AbstractDiscreteEvent`s, like `PeriodicEvent` and `TimedEvent` (whose implementation in DiffEq would of course just be via the appropriate callbacks in DiffEqCallbacks.jl). They should allow for an initialization as well. Then we can add an `@continuous` etc. macro which essentially just expands to creating a parameter, creating a ContinuousEvent which changes the parameter (and initializes it appropriately), and if there are any equations in there it would make an `ifelse` operation. i.e.

```julia
@continuous if x > 5
   D*x == x*y
else
   D*x == x - 3
end
```

would expand to:

```julia
Parameter(:if1) # Some gensym name
ContinuousEvent(x>5,if1==1,if1==0,if1==x>5) # condition, upcrossing, downcrossing, initialization
ifelse(if1,D*x == x*y,D*x == x - 3)
```

It probably needs some bikeshedding to handle more combinations of models well, but you can see where this is going.

**Comment by ChrisRackauckas** [comment]
Now that https://github.com/JuliaDiffEq/SciCompDSL.jl/issues/41 is through, it's clear that a `ContinuousEvent` should be defined via a rootfinding equation with `~`. But inequality equations are necessary and I'm not sure about the syntax.

**Comment by ChrisRackauckas** [comment]
Welp, answered myself. 

https://github.com/JuliaDiffEq/SciCompDSL.jl/issues/43

And that's all we needed. Now all of the conditionals are `Operations` which specify equality or inequality equations. This means:

```julia
@continuous if x > 5
   D*x ~ x*y
else
   D*x ~ x - 3
end
```

gives

```julia
Parameter(:if1) # Some gensym name
ContinuousEvent(x>5,if1~1,if1~0,if1~x>5) # condition, upcrossing, downcrossing, initialization
ifelse(if1,D*x ~ x*y,D*x ~ x - 3)
```

are all well-defined functions and types on `Operation`. This can be implemented.

**Comment by ufechner7** [comment]
Any progress on event support or any documented workaround?

**Comment by ChrisRackauckas** [comment]
The workaround is just to do it directly in the problem construction, just https://diffeq.sciml.ai/stable/features/callback_functions/ . But we're going to start automating discontinuity handling which will do this.

**Comment by ChrisRackauckas** [comment]
@YingboMa and I talked about this and we have a plan for what to do.
