### ISSUE TITLE
Symbolic derivation of Jacobian no longer working

### ISSUE THREAD

**Issue by anvima** [SciML/ModelingToolkit.jl#403]
Example for symbolic jacobian derivation [(Jacobian_example)](https://docs.sciml.ai/stable/tutorials/advanced_ode_example/index.html#Speeding-Up-Jacobian-Calculations-1) no longer working. Was still working on: 19.05.2020. Did not do any manual package updates from 19.05. to today. 
```
using ModelingToolkit
de = modelingtoolkitize(prob) # prob: ODEproblem 
_jac = ModelingToolkit.generate_jacobian(de...)[2]  # **error**; see below
```
**Error:** 
> MethodError: no method matching iterate(::ODESystem)

Previously (when linked example was still working), `modelingtoolkitize(prob) ` returned ODESystem **+ 2 additional arguments.**. Now (starting 25.5.) it returns **only** ODESystem. 
Current (26.05.) ModelingToolkit version: v3.6.4. Also tried manually adding version v3.6.0, v3.5.0 and v3.4.0. 

Please include new docu example or change code in a way that renders the linked example usable again. Thanks!

Installed packages: 
  [c52e3926] Atom v0.12.11
  [6e4b80f9] BenchmarkTools v0.5.0
  [336ed68f] CSV v0.6.2
  [5ae59095] Colors v0.12.1
  [a93c6f00] DataFrames v0.21.1
  [1130ab10] DiffEqParamEstim v1.14.1
  [41bf760c] DiffEqSensitivity v6.17.0
  [0c46a032] DifferentialEquations v6.14.0
  [5789e2e9] FileIO v1.3.0
  [f6369f11] ForwardDiff v0.10.10
  [916415d5] Images v0.22.2
  [e5e0dc1b] Juno v0.8.2
  [b964fa9f] LaTeXStrings v1.1.0
  [2fda8390] LsqFit v0.10.0
  [961ee093] ModelingToolkit v3.6.4
  [429524aa] Optim v0.21.0
  [91a5bcdd] Plots v1.3.2
  [f27b6e38] Polynomials v1.1.0
  [d330b81b] PyPlot v2.9.0
  [731186ca] RecursiveArrayTools v2.3.3
  [fdbf4ff8] XLSX v0.7.0
  [10745b16] Statistics

**Comment by ChrisRackauckas** [comment]
It should be `ModelingToolkit.generate_jacobian(de)`

**Comment by ChrisRackauckas** [comment]
Let me know if you need anything else.

**Comment by anvima** [comment]
Thanks a lot!
