### ISSUE TITLE
Arrays of sparse matrices not sparse

### ISSUE THREAD

**Issue by jlperla** [SciML/ModelingToolkit.jl#407]
It appears that the zeros are being written out for sparse arrays of arrays so that the number of `nzval` wouldn't match

```julia
using ModelingToolkit, SparseArrays
@variables a b c
h_1 = sparse([a 0; b c])
h_2 = sparse.([[a 0; b c], [1 0; c 0]])
display(build_function(h_1, [a, b, c], linenumbers = false)[2])
display(build_function(h_2, [a, b, c], linenumbers = false)[2])
```
Shows the sparse matrix first, which is correct,
```julia
:((var"##MTIIPVar#311", var"##MTKArg#309")->begin
          @inbounds begin
                  let (a, b, c) = (var"##MTKArg#309"[1], var"##MTKArg#309"[2], var"##MTKArg#309"[3])
                      (var"##MTIIPVar#311").nzval[1] = a
                      (var"##MTIIPVar#311").nzval[2] = b
                      (var"##MTIIPVar#311").nzval[3] = c
                  end
              end
          nothing
      end)
```

But note what happens with the array of arrays
```julia
:((var"##MTIIPVar#315", var"##MTKArg#313")->begin
          @inbounds begin
                  let (a, b, c) = (var"##MTKArg#313"[1], var"##MTKArg#313"[2], var"##MTKArg#313"[3])
                      (var"##MTIIPVar#315"[1]).nzval[1] = a
                      (var"##MTIIPVar#315"[1]).nzval[2] = b
                      (var"##MTIIPVar#315"[1]).nzval[3] = 0
                      (var"##MTIIPVar#315"[1]).nzval[4] = c
                      (var"##MTIIPVar#315"[2]).nzval[1] = 1
                      (var"##MTIIPVar#315"[2]).nzval[2] = c
                      (var"##MTIIPVar#315"[2]).nzval[3] = 0
                      (var"##MTIIPVar#315"[2]).nzval[4] = 0
                  end
              end
          nothing
      end)
```

**Comment by jlperla** [comment]
Going back to the tests in https://github.com/SciML/ModelingToolkit.jl/blob/master/test/build_function_arrayofarray.jl#L117  This means that the following @test_broken need to work and should be turned back on:
- The arrays of sparse matrices in https://github.com/SciML/ModelingToolkit.jl/blob/master/test/build_function_arrayofarray.jl#L117-L118 
- Same thing for arrays of arrays of sparse matrices.  See https://github.com/SciML/ModelingToolkit.jl/blob/master/test/build_function_arrayofarray.jl#L180     and the PR in https://github.com/SciML/ModelingToolkit.jl/pull/413

**Comment by wupeifan** [comment]
I think a fix could be change https://github.com/SciML/ModelingToolkit.jl/blob/master/src/build_function.jl#L177 to
``` Julia
ip_sys_exprs = reduce(vcat,[vec(reduce(vcat,[vec([:($X[$i][$j].nzval[$k] = $(conv(rhs))) for (k, rhs) ∈ enumerate(rhsel2)]) for (j, rhsel2) ∈ enumerate(rhsel.nzval)])) for (i,rhsel) ∈ enumerate(_rhss)])
```

**Comment by jlperla** [comment]
Awesome.  If that passes the unit tests with them those key `@test_broken` fixed up then we could be in business.  Are you able to give it a shot?

**Comment by wupeifan** [comment]
Sure, let me try it out
