### ISSUE TITLE
Unit tests for arrays of matrices not hooked up

### ISSUE THREAD

**Issue by jlperla** [SciML/ModelingToolkit.jl#408]
See #407 for a case covered in the https://github.com/SciML/ModelingToolkit.jl/blob/master/test/build_function_arrayofarray.jl unit tests

**Comment by ChrisRackauckas** [comment]
Could you send a quick PR to enable it so we can get that merged?

**Comment by jlperla** [comment]
@arnavs: can you work on the this tomorrow and see how we are doing?  #407 is known to fail at this point.

**Comment by arnavs** [comment]
Did the PR. 

Note that both lines that don't execute (i.e., errors) and actual unequal comparisons are flagged with `@test_broken`. 

Couldn't figure out what's wrong with line 117 (which errors), but maybe @ChrisRackauckas can see it.
