### ISSUE TITLE
Use substitute() in convert(::Type{<:NonlinearSystem},rs::ReactionSystem)

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#419]
The function for converting ReactionSystems to NonlinearSystem currently have a naive version of the substitute function implemented:
```
function make_sub!(eq,states_swaps)
	for (i,arg) in enumerate(eq.args)
		if any(isequal.(states_swaps,arg))
			eq.args[i] = var2op(arg.op)
		else
			make_sub!(arg,states_swaps)
		end
	end
	return eq
end
```
This is used to recursively replacement to replace things like X(t) with X in the equations. It should use a version of `substitute()`, however, the initial implementation of this,
```
swaps = Dict(zip(map(state -> Operation(state,[var2op(rs.iv,)]), rs.states),map(state -> var2op(state), rs.states)))
substitute(eq,swaps)
```
yielded an error
```
map is not defined on sets
in top-level scope at test.jl:28
in substitute at dev/ModelingToolkit/src/utils.jl:121
in _substitute at dev/ModelingToolkit/src/utils.jl:125
in map at base/abstractarray.jl:2101
in error at base/error.jl:33
```
and I implemented the temporary function `make_subs!()` instead. At some point, this should be remedied and it should use `substitute()` instead.

Reference: https://github.com/SciML/ModelingToolkit.jl/pull/417

**Comment by isaacsas** [comment]
@ChrisRackauckas I think this is fixed. I got rid of `make_subs` I thought. (Though we need a NonlinearSystem test as it wasn't realized when I updated the conversion...)
