### ISSUE TITLE
Slow jump construction likely due to substitute

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#426]
On Discourse, [here](https://discourse.julialang.org/t/lightgraph-modeltoolkit-optimization/40696), a graph SIR model was reported to take an exceptionally long time to construct the JumpProblem (18.55s out of a total time to run a simulation of 18.85s).

On running the profiler it seems the overwhelming majority of the time is being taken in the `substitute` call within `assemble_maj` at https://github.com/SciML/ModelingToolkit.jl/blob/6afdbd252096c05e7fd03a9a05e60456da43332f/src/systems/jumps/jumpsystem.jl#L97

I'll look into whether we can detect that the `rate` is just a symbol and skip this call, which should be the case for this example, but more generally is there anything that can be done about this?

**Comment by ChrisRackauckas** [comment]
@shashi could you take a look at this? `substitute` shouldn't take that much time here.

**Comment by isaacsas** [comment]
FWIW it is just simplifying essentially `p/1` for `p` different parameters, so nothing complicated.

**Comment by ChrisRackauckas** [comment]
Yeah, so if we need an alternative implementation for this kind of thing that's fine, but I'm curious how any library can take 18 seconds on that.

**Comment by erlebach** [comment]
You were able to duplicate my timings?

**Comment by isaacsas** [comment]
Yes. and the issue is clear. We can fix it easily, it is just a matter of trying to avoid a temp fix for a more robust solution.

@ChrisRackauckas is that same section of code a `Dict` is being built that is keyed by `Operation`s. Is that a good idea? I usually use `Variable`s as keys.

**Comment by ChrisRackauckas** [comment]
It's probably not a good idea to hit a dictionary here, though hashing may be useful when there's tons of variables? There just has to be a better way.

**Comment by isaacsas** [comment]
But is hashing on an `Operation` ok to do?

**Comment by ChrisRackauckas** [comment]
Maybe

**Comment by isaacsas** [comment]
I think I had originally written this to take a premade `Dict` mapping `Variable`s to numeric values when it used evaluation in a Module context. That's basically what we used in DEBio with `Symbol`s and it had good performance (note the Dict is only built once in the `JumpProblem` call, not constructed each time within the jump call).

**Comment by ChrisRackauckas** [comment]
We might need to revert back to that.

**Comment by isaacsas** [comment]
I'm happy to revert it back if @shashi thinks getting a more permanent fix will take a while. Just let me know.

**Comment by ChrisRackauckas** [comment]
Let's revert for now and not wait on a permanent fix. The dict construction cost makes me think that the symbolicutils direction might just be a bad idea for substitution.

**Comment by isaacsas** [comment]
@erlebach https://github.com/SciML/ModelingToolkit.jl/pull/427 gives a big improvement. I can let you know once there is a new release with this fix.

There are some more optimizations we can do so we should leave this issue open for now. I'll try to profile some more to see what is rate limiting now over the next few days or on the weekend.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/ModelingToolkit.jl/pull/427

**Comment by shashi** [comment]
is it possible to send me an MWE?

**Comment by shashi** [comment]
Oh never mind, I missed the discourse link.

**Comment by isaacsas** [comment]
Substitute is called a lot. We want to support systems with tens to hundreds of thousands of jumps, and maybe more. For each of them it was getting called.
