### ISSUE TITLE
Harmonise parameter input praxis into Problems

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#428]
Currently, this is the way to create an ODEProblem using MTK:
```julia
using ModelingToolkit

@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t
eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]
de = ODESystem(eqs,t,[x,y,z],[σ,ρ,β])

ODEProblem(de,[x => 1., y => .2, z => 3.],(0.,10.),[σ => 1.,ρ => 1.,β => 1.])
```
while this is an incorrect notation
```julia
ODEProblem(de,[1., .2, 3.],(0.,10.),[1.,1.,1.])
```

When creating `ReactionSystem`s using the new DiffEqBio rework one does not declare the variables and parameters, hence I enabled the notation
```julia
ODEProblem(rs,[1., .2, 3.],(0.,10.),[1.,1.,1.])
```
where `rs` is a `ReactionSystem`. This is the only type of system where this is possible.

We will need to decide on an input praxis, and ensure that it is similar across all system types.

Reference: https://github.com/SciML/ModelingToolkit.jl/pull/425

**Comment by isaacsas** [comment]
Best issue title I've seen this year!

**Comment by ChrisRackauckas** [comment]
Fixed by lowering via conversions.
