### ISSUE TITLE
ReactionSystem -> Affine Noise? (as well as non parameterized noise)

### ISSUE THREAD

**Issue by TorkelE** [SciML/ModelingToolkit.jl#456]
By default the DSL generates noise term likes:
```julia
g[n,m] = stoch_nm * sqrt(rate_m)
```
It is possible the declare a special noise scaling parameter eta so that the term rather becomes
```julia
g[n,m] = eta * stoch_nm * sqrt(rate_m)
```
An improvement as mentioned in the previous PR would be to have affine noise a la
```julia
g[n,m] = eta1 * stoch_nm * sqrt(rate_m) + eta2
```
(I hope that I understood this right)

the new call would be
```julia
rn = @reaction_network rType (eta1,eta2) begin
    ...
end
```
alternatively
```julia
rn = @reaction_network rType begin
    ...
end
```
if no noise customization is desired.

On the same topic. Now noise is automatically stored as a parameter (default the last parameter in the parameter array). This is advantageous since you can the change the noise rate without redoing the DSL call. However in some cases you want a fixed value. I think it would be advantageous to allow for number as well, like:
```julia
rn = @reaction_network rType (2.0,eta2) begin
    ...
end
```
now the multiplicative scaling would be 2.0, with no changing that. This can be especially usefull if you are only interested in using parts of the affine noise, like:
```julia
rn = @reaction_network rType (0.0,eta2) begin
    ...
end
```

**Comment by ChrisRackauckas** [comment]
Supersceded by https://github.com/SciML/ModelingToolkit.jl/issues/405
