### ISSUE TITLE
Simplification only occurs for variables which are functions (but not constants)

### ISSUE THREAD

**Issue by dcabecinhas** [SciML/ModelingToolkit.jl#468]
```julia
julia> @variables a b t
(a, b, t)

julia> @variables c(t) d(t)
(c(t), d(t))

julia> a*b - b*a
a * b - b * a

julia> simplify(a*b - b*a)
a * b + -1 * b * a

julia> c*d - d*c
c(t) * d(t) - d(t) * c(t)

julia> simplify(c*d - d*c)
ModelingToolkit.Constant(0)
```

SymbolicUtils does it right.

```julia
julia> @syms a b 
(a, b)

julia> a*b - b*a
0
```

See also JuliaSymbolics/SymbolicUtils.jl#72 and linked MT issue therein.

**Comment by ChrisRackauckas** [comment]
@shashi

**Comment by dcabecinhas** [comment]
Bumped into this bug again. Seems like on the roundtrip to SymbolicUtils the repeating parameters/variables are treated as distinct.

```julia
julia> get_variables(a*b-b*a)
2-element Array{Operation,1}:
 a
 b

julia> get_variables(simplify((a*b-b*a)))
4-element Array{Operation,1}:
 a
 b
 b
 a

julia> get_variables(simplify(a+(b+a)))
3-element Array{Operation,1}:
 a
 b
 a
```

**Comment by shashi** [comment]
Oh thanks for this clue! I'll fix this soon.

**Comment by isaacsas** [comment]
Actually, could this be from calling `unique` instead of `unique!` in `get_variables!`? I ran into this earlier today. I was going to put in a fix as part of a PR, but could put a separate PR for this through first if helpful:
https://github.com/SciML/ModelingToolkit.jl/blob/c9678ab460d3a059c1d4c911c97e89308326159f/src/utils.jl#L100

**Comment by isaacsas** [comment]
Nevermind, that doesn't fix it as `unique!` seems unable to determine uniqueness of the Operations (i.e. a vector like `[a,b,b,a]`).

**Comment by shashi** [comment]
This could be because hashing in MTK is not correct. SymUtils will
construct new Operation objects which don't hash to the same variable.

**Comment by ChrisRackauckas** [comment]
What do we need to do in order to fix the hashing?

**Comment by shashi** [comment]
I'm working on it
