### ISSUE TITLE
Expose Dagger scheduler options in DaggerForm

### ISSUE THREAD

**Issue by jpsamaroo** [SciML/ModelingToolkit.jl#483]
Dagger has a number of options for controlling which compute resources are available for usage, among other things, and more options will be added in the future. We should expose these as kwargs to the `DaggerForm()` constructor and pass them straight to the scheduler in the `collect` call.

**Comment by ChrisRackauckas** [comment]
Indeed, I think those should just be options in the `DaggerForm` constructor that then get passed into the `collect` calls.

**Comment by ChrisRackauckas** [comment]
Do we need an issue on Dagger about the in-place updating form?

**Comment by jpsamaroo** [comment]
> Do we need an issue on Dagger about the in-place updating form?

No, I don't think Dagger is where such support needs to go, since Dagger doesn't do shared memory. Looking at the code, it appears that IIP is actually properly supported, since all `setindex!` calls are done on the master process. Regardless, if that isn't actually the case, we should workaround it in the `DaggerForm` implementation.

**Comment by ChrisRackauckas** [comment]
On yes, that is the case.
