### ISSUE TITLE
build_function doesn't like array expressions with single scalar variable

### ISSUE THREAD

**Issue by dcabecinhas** [SciML/ModelingToolkit.jl#495]
I sometimes use `build_function` and ModelingToolkit as a `lambdify` and SymEngine/Sympy alternative. However, currently it errors in simple examples as

```julia
@parameters t
f = eval(build_function([t, t],t)[1])
julia> f(0.0)
ERROR: MethodError: Cannot `convert` an object of type Array{Float64,1} to an object of type Float64
```

I was going around this with the `constructor` keyword arg but it got removed today.

A simple fix would to avoid calling `convert` if the variable is a scalar, here done with `!(typeof($(fargs.args[1]))) <: Number`. This creates an SA if the function is a SA or LA and normal Array in other cases.

```diff
diff --git a/src/build_function.jl b/src/build_function.jl
index 12c7fa3..7bf4a2b 100644
--- a/src/build_function.jl
+++ b/src/build_function.jl
@@ -336,14 +336,14 @@ function _build_function(target::JuliaTarget, rhss, args...;
        arr_sys_expr = (typeof(rhss) <: Vector || typeof(rhss) <: Matrix) && !(eltype(rhss) <: AbstractArray) ? quote
                if typeof($(fargs.args[1])) <: Union{ModelingToolkit.StaticArrays.SArray,ModelingToolkit.LabelledArrays.SLArray}
                        $xname = ModelingToolkit.StaticArrays.@SArray $arr_sys_expr
-                       if $(typeof(rhss) <: Vector) # Only try converting if it should match `u`
+      if ($(typeof(rhss) <: Vector) && !(typeof($(fargs.args[1]))) <: Number) # Only try converting if it should match `u` and argument is not a scalar
                                convert(typeof($(fargs.args[1])),$xname)
                        else
                                $xname
                        end
                else
                        $xname = $arr_sys_expr
-                       if !(typeof($(fargs.args[1])) <: Array) && $(typeof(rhss) <: Vector)
+                       if !(typeof($(fargs.args[1])) <: Array) && $(typeof(rhss) <: Vector) && !(typeof($(fargs.args[1])) <: Number)
                                convert(typeof($(fargs.args[1])),$xname)
                        else
                                $xname

```

I know this is not the core of Modeling Toolkit but it is a simple change that can make `build_function` somewhat more useful.

**Comment by ChrisRackauckas** [comment]
yes, sorry about that. I actually have a PR making these cases a lot more robust and that PR will be coming in a second. The constructor route was surprisingly unoptimized, so it was removed so that everything could compile to full optimality, but I realized that the way it was done led to a few downstream hiccups so I'll get those patched ASAP.

**Comment by ChrisRackauckas** [comment]
This was added to https://github.com/SciML/ModelingToolkit.jl/pull/496

**Comment by dcabecinhas** [comment]
Great! Thanks.

**Comment by dcabecinhas** [comment]
Is it possible to return the same type Array as the operation when the argument is a scalar?

With this patch it defaults to a standard Array only, it is not possible to get a SA.

**Comment by ChrisRackauckas** [comment]
Hmm, bringing back the massive tuple construction won't work because that has some compile time nastiness, but we can add an option to handle this.
