### ISSUE TITLE
fail to generate jacobian

### ISSUE THREAD

**Issue by JianghuiDu** [SciML/ModelingToolkit.jl#503]
The reported error was `expression too large` or something like that. (I accidentally closed the window so forgot to copy the message. But it's very short and only said `expression too large`. )
My ODE is quite big, about 3000 equations. Some expressions in the ODE function is already quite long. So any suggestions? Would using lots of intermediate calculations help?

Another question is what is the advantage of `ModelingToolkit` compared with `ParameterizedFunctions` in generating the jacobian?

This is a piece of the code that calculates the `du` for one variable. 
```julia
        dC[(i-1)nspec+nnoneq+1] += ((rNC-rPC)*RO2POC[i]*dstopw[i] + (rNC-rPC+4/3)*RNO2POC[i]*dstopw[i] + (rNC-rPC)*RNO3POC[i]*dstopw[i] + (rNC-rPC+4.0)*RMnO2POC[i]*dstopw[i] + (rNC-rPC+8.0)*RFeOOHPOC[i]*dstopw[i] + (rNC-rPC+1.0)*RSO4POC[i]*dstopw[i] + (rNC-rPC)*RCH4POC[i]*dstopw[i] + -2.0*RO2NH4[i] + -2.0*RO2Mn[i] + -1.0*RO2Mn_ads[i] + -2.0*RO2Fe[i] + -1.0*RO2Fe_ads[i] + -2.0*RO2H2S[i] + -2.0*RO2FeS[i]*dstopw[i] + -8/5*RNO3Mn[i] + -1.80*RNO3Fe[i] + 2.0*RSO4CH4[i] + -1.0*RMnO2Fe[i]*dstopw[i] + 2.0*RMnO2H2S[i]*dstopw[i] + 4.0*RFeOOHH2S[i]*dstopw[i] + -2.0*RFeS_pre[i]*dstopw[i] + 2.0*RFeS_dis[i]*dstopw[i] + 2.0*RCaCO3_dis[i]*dstopw[i] + -2.0*RCaCO3_pre[i]*dstopw[i] + 2.0*RMnCO3_dis[i]*dstopw[i] + -2.0*RMnCO3_pre[i]*dstopw[i] + 2.0*RFeCO3_dis[i]*dstopw[i] + -2.0*RFeCO3_pre[i]*dstopw[i] + 10.0*RAnnite_dis[i])/dTA_dH[i] 
        dC[(i-1)nspec+nnoneq+1] += -1.0*(1.0*RO2POC[i]*dstopw[i] + 1.0*RNO2POC[i]*dstopw[i] + 1.0*RNO3POC[i]*dstopw[i] + 1.0*RMnO2POC[i]*dstopw[i] + 1.0*RFeOOHPOC[i]*dstopw[i] + 1.0*RSO4POC[i]*dstopw[i] + 0.50*RCH4POC[i]*dstopw[i] + 1.0*RO2CH4[i] + 1.0*RSO4CH4[i] + 1.0*RCaCO3_dis[i]*dstopw[i] + -1.0*RCaCO3_pre[i]*dstopw[i] + 1.0*RMnCO3_dis[i]*dstopw[i] + -1.0*RMnCO3_pre[i]*dstopw[i] + 1.0*RFeCO3_dis[i]*dstopw[i] + -1.0*RFeCO3_pre[i]*dstopw[i])*dTA_dTCO2[i]/dTA_dH[i] 
        dC[(i-1)nspec+nnoneq+1] += -1.0*(rNC*RO2POC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + rNC*RNO2POC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + rNC*RNO3POC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + rNC*RMnO2POC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + rNC*RFeOOHPOC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + rNC*RSO4POC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + rNC*RCH4POC[i]*dstopw[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + -1.0*RO2NH4[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + -1.0*RNO2NH4[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i] + 1.0*RNO3H2S[i]*phi_f_cen[i]/phi_TNH4_ads_cen[i])*dTA_dTNH4[i]/dTA_dH[i] 
        dC[(i-1)nspec+nnoneq+1] += -1.0*(rPC*RO2POC[i]*dstopw[i] + rPC*RNO2POC[i]*dstopw[i] + rPC*RNO3POC[i]*dstopw[i] + rPC*RMnO2POC[i]*dstopw[i] + rPC*RFeOOHPOC[i]*dstopw[i] + rPC*RSO4POC[i]*dstopw[i] + rPC*RCH4POC[i]*dstopw[i])*dTA_dTH3PO4[i]/dTA_dH[i]
        dC[(i-1)nspec+nnoneq+1] += -1.0*(0.50*RSO4POC[i]*dstopw[i] + -1.0*RO2H2S[i] + -1.0*RNO3H2S[i] + 1.0*RSO4CH4[i] + -1.0*RMnO2H2S[i]*dstopw[i] + -1.0*RFeOOHH2S[i]*dstopw[i] + -1.0*RFeS_pre[i]*dstopw[i] + 1.0*RFeS_dis[i]*dstopw[i] + -1.0*RFeSH2S[i]*dstopw[i] + -4.0*RMoS4_pre[i])*dTA_dTH2S[i]/dTA_dH[i]
        dC[(i-1)nspec+nnoneq+1] += -1.0*(-0.50*RSO4POC[i]*dstopw[i] + 1.0*RO2H2S[i] + 1.0*RO2FeS[i]*dstopw[i] + 1.0*RNO3H2S[i] + -1.0*RSO4CH4[i])*dTA_dTHSO4[i]/dTA_dH[i]
        dC[(i-1)nspec+nnoneq+1] += -1.0*(1.0*RBSi_dis[i]*dstopw[i] + -1.0*RASi_pre[i] + 3.0*RAnnite_dis[i])*dTA_dTH4SiO4[i]/dTA_dH[i]	#7 
```

**Comment by ChrisRackauckas** [comment]
>Another question is what is the advantage of ModelingToolkit compared with ParameterizedFunctions in generating the jacobian?

ParameterizedFunctions just uses ModelingToolkit under the hood.

>My ODE is quite big, about 3000 equations. Some expressions in the ODE function is already quite long. So any suggestions? Would using lots of intermediate calculations help?

Is it sparse? Did you try adding the `sparse=true` option? Another option to try is `skipzeros` depending on how you're generating it.

>The reported error was expression too large or something like that. (I accidentally closed the window so forgot to copy the message. But it's very short and only said expression too large. )

Yeah, if you generate all 9,000,000 equations you go above some threshold in Julia. If it's not sparse, I would love to see the example to try and convince the core devs to remove it, but we could also work around it in MTK itself. That said, all of these cases have come from sparse Jacobians, and the options mentioned above will fix that.

**Comment by JianghuiDu** [comment]
Is the sparse detection automatic? No need for a sparse pattern? What does `skipzeros` do? Couldn't find an explanation.

**Comment by ChrisRackauckas** [comment]
Sparsity patterns are automatic. No need for a sparsity pattern, just do `sparse=true` inside of the `ODEProblem` construction. We should probably put together a tutorial on this, but I'll need to find an easy to write down large sparse ODE system.

`skipzeros` just doesn't add the `=0` lines to the function, so it's like `sparse` but it doesn't actually make the object a sparse matrix (for when it's not sparse enough)

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/SciML/ModelingToolkit.jl/pull/508

**Comment by JianghuiDu** [comment]
OK. Using `sparse=true` made it work. It took a really long time. Is there a way to save the jacobian for future use. I tried different tools (`writedlm`,`CSV`,`JLD2`), but none of them accept `Expr`. Do you have any suggestions?

**Comment by YingboMa** [comment]
You can try to print Expr to a file.

**Comment by ChrisRackauckas** [comment]
I quickly snuck some documentation for how to do this: https://github.com/SciML/ModelingToolkit.jl/commit/1e54e9d166b7c1f5500c4d6d16742fbf0f1177b5 . Saving the expr is much better than trying JLD2 and stuff like that.
