### ISSUE TITLE
 Mixed derivatives

### ISSUE THREAD

**Issue by KirillZubov** [SciML/ModelingToolkit.jl#520]
I noticed that ModelingToolKit doesn't support mixed derivatives.
`@derivatives Dxy''~x,y` 

We can define them only directly:
`derivative(derivative(u(x, y, θ), x), y)`

**Comment by ChrisRackauckas** [comment]
@YingboMa @shashi I know we want to change the syntax here, and whatever we change the syntax to should make sure to incorporate this.

**Comment by shashi** [comment]
We should probably do that in a separate PR, it should be orthogonal to #518

**Comment by jebej** [comment]
It seems like a better syntax would be:
```
@derivative D ~ x^2 y
```

**Comment by ChrisRackauckas** [comment]
We now just do `Differential(x)*Differential(y)`
