### ISSUE TITLE
Support for piecewise functions

### ISSUE THREAD

**Issue by thowell** [SciML/ModelingToolkit.jl#531]
Is it possible to use this package with piecewise functions (e.g., [Huber loss](https://en.wikipedia.org/wiki/Huber_loss))?

```JULIA
@variables a
function huber(a)
    δ = 1.0
    if abs(a) <= δ
        return 0.5*a^2
    else
        return δ*(abs(a) - 0.5*δ)
    end
end
da = huber(a)
```

This errors on the last line:
> TypeError: non-boolean (Operation) used in boolean context

**Comment by ChrisRackauckas** [comment]
For that it's probably best to `@register` it. You cannot directly trace a function with branches right now, though we're working on that.

**Comment by ChrisRackauckas** [comment]
`@register` and `IfElse.ifelse` are the solutions.
