### ISSUE TITLE
Latexify for ODEs uses inconsistent notation for variables.

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#533]
Example:
```julia
using Catalyst, Latexify
repressilator = @reaction_network begin
           hillr(P₃,α,K,n), ∅ --> m₁
           hillr(P₁,α,K,n), ∅ --> m₂
           hillr(P₂,α,K,n), ∅ --> m₃
           (δ,γ), m₁ ↔ ∅
           (δ,γ), m₂ ↔ ∅
           (δ,γ), m₃ ↔ ∅
           β, m₁ --> m₁ + P₁
           β, m₂ --> m₂ + P₂
           β, m₃ --> m₃ + P₃
           μ, P₁ --> ∅
           μ, P₂ --> ∅
           μ, P₃ --> ∅
       end α K n δ γ β μ
osys = Convert(ODESystem, repressilator)
latexify(osys, cdot=false)
```
gives the following:

![image](https://user-images.githubusercontent.com/9385167/87876454-2aeab380-c9a6-11ea-9843-c26110d71856.png)

where some variables are in `mathrm` and some are italic.

**Comment by isaacsas** [comment]
I posted here as I assume this is an issue with the recipe, otherwise I can move to Latexify.jl's issues.

**Comment by ChrisRackauckas** [comment]
Related: https://github.com/SciML/ModelingToolkit.jl/pull/502

**Comment by isaacsas** [comment]
@TorkelE Mentioned that @korsbo is in his thesis crunch, and so might not be around for a while. Is there anyone else that maintains Latexify besides him we could ping?

**Comment by isaacsas** [comment]
Looking at the repo, I've got the second most commits, so I'd say there don't appear to be any other maintainers.

**Comment by ChrisRackauckas** [comment]
I think the Latexify issues were handled, open a new issue if there's more to do.
