### ISSUE TITLE
Add a function to extract all the variables used in an expression

### ISSUE THREAD

**Issue by dpsanders** [SciML/ModelingToolkit.jl#549]
A simple, presumably not very efficient, method is

```jl
function extract_variables(ex::Operation)
    if ex.op isa Variable
        return Set([ex.op])

    elseif ex.op isa ModelingToolkit.Constant
        return Set([])

    else 
        return reduce(∪, extract_variables.(ex.args))

    end
end
```

**Comment by isaacsas** [comment]
Does this `get_variables` not work for you?
https://github.com/SciML/ModelingToolkit.jl/blob/baf293257840466882f1191e51985156e6e162c2/src/utils.jl#L96

**Comment by isaacsas** [comment]
We should probably get it fixed up to appear in the docs though... For some reason there is an error message where it should be currently...

**Comment by dpsanders** [comment]
It does indeed, thanks!
