### ISSUE TITLE
More simplification routines

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#55]
We need more routines to simplify equations down to common forms. It doesn't need to cover all of the fancy cases, but we should be able to have `-x` be the same as `-1 * x`.

**Comment by ChrisRackauckas** [comment]
Thanks. It's interesting they have so many pointers. I've been wondering about that for `Variable`, because then `Variable`s as references would be unique instead of copied all around. This would be helpful for making components.

**Comment by smldis** [comment]
Given julia's similarities with C++ and its current lack of capability of avoiding copies in this case, refs make sense. Is using refs going to also simplify expression manipulation algorithms? (unique means it is easy to check for equality right?)
This could be also handled at a lower level representation, I don't know what the current plans are.

**Comment by ChrisRackauckas** [comment]
>unique means it is easy to check for equality right?

Yeah it would just be references.
