### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by devmotion** [SciML/ModelingToolkit.jl#557]
Is it possible to release a new version that is compatible with DataStructures 0.18? I'm in the process of upgrading DiffEq packages, and currently I have to check out the master branch of ModelingToolkit to tests packages locally (see https://github.com/SciML/DiffEqCallbacks.jl/pull/87#issuecomment-677771501).

**Comment by ChrisRackauckas** [comment]
@JuliaRegistrator register()
