### ISSUE TITLE
Comment on terminology: parameter vs. (independent) variable t 

### ISSUE THREAD

**Issue by hurak** [SciML/ModelingToolkit.jl#564]
Reading the [docs for ODESystem](https://mtk.sciml.ai/stable/systems/ODESystem/), I am somewhat puzzled by the use of the term `parameter` for time `t`. In the "hello world" example

```julia
using ModelingToolkit

@parameters t σ ρ β
@variables x(t) y(t) z(t)
@derivatives D'~t

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

de = ODESystem(eqs,t,[x,y,z],[σ,ρ,β])
```
the time `t` is defined as a *parameter* (using `@parameter`), and yet in the documentation for `ODESystem()`, the second input argument is named as 
- **iv** independent variable.

Do I understand it correctly that we use `@parameters` for true "physical" parameters (such as `σ, ρ, β` that do not change during simulation) AND the independent variable (perhaps mostly time `t` in ODEs), and we use `@variables` for the dependent variables (functions of the independent variable)?

EDIT: Now I see that the independent variable (time) `t` is cast as a variable in [the section on Derivatives](https://mtk.sciml.ai/stable/tutorials/symbolic_functions/#Derivatives-1). 

```julia
@variables t
@derivatives D'~t
```
This is indeed somewhat confusing. Many thanks for clarification.

**Comment by ChrisRackauckas** [comment]
`t` can be a variable. It's just for the automated system definition, i.e. `de = ODESystem(eqs)`, and could possibly be removed since it's one of the archaic things that hasn't really added much value in any recent versions.

**Comment by ChrisRackauckas** [comment]
```julia
using ModelingToolkit

@variables t x(t) y(t) z(t)
@parameters σ ρ β
@derivatives D'~t

eqs = [D(x) ~ σ*(y-x),
       D(y) ~ x*(ρ-z)-y,
       D(z) ~ x*y - β*z]

de = ODESystem(eqs)
```

Works, so I'll call this a documentation issue. We should probably just move it over as I agree it's a bit confusing.

**Comment by ChrisRackauckas** [comment]
Just use `using ModelingToolkit: t_nounits as t, D_nounits as D`
