### ISSUE TITLE
Bug in creating an ODESystem from an array of equations (incorrect parsing of summation of terms)

### ISSUE THREAD

**Issue by hurak** [SciML/ModelingToolkit.jl#565]
I am trying to model a set of differential equations in `ModelingToolkit`. And I want to formulate it using vector variables. Namely, I will have a variable vector ``z = [z₁, z₂, z₃]`` (just a minimal example):

```julia
julia> using ModelingToolkit, OrdinaryDiffEq

julia> @parameters t
(t,)

julia> @variables z[1:3](t)
(Operation[z₁(t), z₂(t), z₃(t)],)

julia> @derivatives D'~t
((D'~t),)

julia> eqs = [D(z[i]) + z[i] ~ 0 for i in 1:3]
3-element Array{Equation,1}:
 Equation(derivative(z₁(t), t) + z₁(t), ModelingToolkit.Constant(0))
 Equation(derivative(z₂(t), t) + z₂(t), ModelingToolkit.Constant(0))
 Equation(derivative(z₃(t), t) + z₃(t), ModelingToolkit.Constant(0))
```
However, I am failing to create an `ODESystem` from the equations:

```julia
julia> sys = ODESystem(eqs)
ERROR: MethodError: Cannot `convert` an object of type 
  typeof(+) to an object of type 
  Variable
Closest candidates are:
  convert(::Type{Variable}, ::Operation) at /home/hurak/.julia/packages/ModelingToolkit/kfLoQ/src/ModelingToolkit.jl:77
  convert(::Type{T}, ::T) where T at essentials.jl:171
  Variable(::Any) at /home/hurak/.julia/packages/ModelingToolkit/kfLoQ/src/variables.jl:50
  ...
Stacktrace:
 [1] setindex!(::OrderedCollections.OrderedDict{Variable,Nothing}, ::Nothing, ::Function) at /home/hurak/.julia/packages/OrderedCollections/b4td4/src/ordered_dict.jl:292
 [2] push!(::OrderedCollections.OrderedSet{Variable}, ::Function) at /home/hurak/.julia/packages/OrderedCollections/b4td4/src/ordered_set.jl:25
 [3] ODESystem(::Array{Equation,1}, ::Nothing; kwargs::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}) at /home/hurak/.julia/packages/ModelingToolkit/kfLoQ/src/systems/diffeqs/odesystem.jl:122
 [4] ODESystem at /home/hurak/.julia/packages/ModelingToolkit/kfLoQ/src/systems/diffeqs/odesystem.jl:89 [inlined] (repeats 2 times)
 [5] top-level scope at none:1
```
If instead I formulate the equations with one term on each side 
```julia
eqs = [D(z[i]) ~ -z[i] for i in 1:3]
```
things are fine. 

Obviously the culprit is the summation on the left hand sides.

**Comment by hurak** [comment]
I was just wondering if somebody (the authors of ModelingToolkit?) would be so kind and fix this. This bug is a stopper for me, and I am not able to fix it myself.

As a reciprocal service, I will prepare and submit a fine practical example for the ModelingToolkit documentation (in the past I submitted https://diffeq.sciml.ai/stable/tutorials/ode_example/#Example-3:-Solving-Nonhomogeneous-Equations-using-Parameterized-Functions). The example will revolve around building a model of very long mass-spring chain. I might be interesting, I guess. I can proceed without ModelingToolkit but I hoped to demonstrate how convenient it is (in contrast with building the function for the right hand side of the ODE manually).

**Comment by YingboMa** [comment]
We currently force the differential term to be isolated on the left hand side. Generalization is planned, but not a priority for now.

**Comment by ChrisRackauckas** [comment]
Closing because https://github.com/SciML/ModelingToolkit.jl/issues/860 is the same issue. If we don't get to fixing it this week, ping me a reminder and I'll just do it.
