### ISSUE TITLE
Handling of independent variables in OptimizationSystems

### ISSUE THREAD

**Issue by AlCap23** [SciML/ModelingToolkit.jl#574]
I ran into a problem while working on https://github.com/SciML/DataDrivenDiffEq.jl/issues/146 , but I think this is also relevant for MTK in general ( at least for the OptimizationSystem ).

Normally I would assume that all variable used to construct an Optimization system to be independent. However, MTK allows variables also to be dependent on other variables, which throws me an error if I want to generate functions.

A MWE would be 

```julia
using ModelingToolkit

@parameters a b t
@variables x y
loss = (a - x)^2 + b * (y - x^2)^2
sys1 = OptimizationSystem(loss,[x,y],[a,b, t],name=:sys1)

f_ = generate_function(sys1, expression = Val{false})
f_(randn(2), randn(3)) # Works

@parameters a b t
@variables x(t) y(t)
loss = (a - x)^2 + b * (y - x^2)^2
sys1 = OptimizationSystem(loss,[x,y],[a,b,t],name=:sys1)

f_ = generate_function(sys1, expression = Val{false})
f_(randn(2), randn(3)) # Fails

```

Due to the error 

```julia
ERROR: LoadError: MethodError: objects of type Float64 are not callable
Stacktrace:
 [1] macro expansion at /home/alcapitan/.julia/packages/ModelingToolkit/kgI0m/src/build_function.jl:105 [inlined]
 [2] macro expansion at /home/alcapitan/.julia/packages/GeneralizedGenerated/wp5nX/src/ngg/runtime_fns.jl:72 [inlined]
 [3] (::ggfunc)(::Array{Float64,1}, ::Array{Float64,1}) at /home/alcapitan/.julia/packages/GeneralizedGenerated/wp5nX/src/ngg/runtime_fns.jl:64
 [4] top-level scope at /home/alcapitan/Documents/code/tests/mtk_playground.jl:17
 [5] include_string(::Function, ::Module, ::String, ::String) at ./loading.jl:1088
 [6] include_string(::Module, ::String, ::String) at ./loading.jl:1096
in expression starting at /home/alcapitan/Documents/code/tests/mtk_playground.jl:17
```

I fiddled a little bit around and the only solutions I can come up with is either to disallow variables with a dependency or to strip them of this dependency explicitly while generating the function. The first one works but is somewhat restrictive and might lead to more workload in advance. The second one is done in `ODESystems` as well I think. Should this be an individual function like `strip_dependency(eqs, states, parameters, iv)` ?

**Comment by ChrisRackauckas** [comment]
it's `convert(Variable,x)` or `convert(Variable,x)()`, but yes it's odd and we need a better solution.

**Comment by AlCap23** [comment]
Alright! This works. Thanks!

```julia
using ModelingToolkit

@parameters a b t
@variables x y
loss = (a - x)^2 + b * (y - x^2)^2
sys1 = OptimizationSystem(loss,[x,y],[a,b, t],name=:sys1)
u0 = randn(2)
p0 = randn(3)
f_ = generate_function(sys1, expression = Val{false})
f_(u0, p0) # Works

@parameters a b t
@variables x(t) y(t)
loss = (a - x)^2 + b * (y - x^2)^2
subs = Dict([i => convert(Variable, i)() for i in [x, y]]...)
sys1 = OptimizationSystem(l_,values(subs),[a,b,t],name=:sys1)
equations(sys1)
f_2 = generate_function(sys1, expression = Val{false})
f_2(u0, p0)
```

So we do not even need the variables to match the equations here ?
I will dig a little bit around :)

**Comment by AlCap23** [comment]
With the recent releases, this is fixed.
