### ISSUE TITLE
MT ODE solution very different from manual OrdinaryDiffEq

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#585]
Below, I simulate the same system using the standard ODE approach through OrdinaryDiffEq, and then using ModelingToolkit. Using the manual approach, the system behaves exactly as I expect, but I can't for the life of me get the same solution out of MT.
```julia
using OrdinaryDiffEq, Plots
function dynamics(dx, x, p, t)
      k, Jₘ, Jₐ, c = p
      q, θ, q̇, θ̇ = x
      Δq = q - θ
      Δv = q̇ - θ̇
      dx[1] = q̇
      dx[2] = θ̇
      dx[3] = -(k * Δq + c * (Δv)) / Jₘ
      dx[4] = (k * Δq + c * (Δv)) / Jₐ
end

x0 = Float64[1,-1,0,0]

p = [2e4,11,11,6]
tspan = (0.0, 1)
prob = ODEProblem(dynamics, x0, tspan, p)
sol = solve(prob, Tsit5(), abstol=1e-4, reltol=1e-4)
plot(sol, layout=4)

## Using ModelingToolkit
using ModelingToolkit, OrdinaryDiffEq, Interact
const MT = ModelingToolkit
@parameters t, k, k₃, Jₘ, Jₐ, c
@variables θ(t) q(t)
@derivatives D'~t

Δq = q - θ
Δv = (D(q) - D(θ))
eqs = [
    D(D(q)) ~ (-(k * Δq + c * (Δv))) / Jₘ
    D(D(θ)) ~ ((k * Δq + c * (Δv))) / Jₐ
]
sys = ODESystem(eqs, name=:DMM) |> ode_order_lowering

u0 = [D(q) => 0.0,
      D(θ) => 0.0,
      q    => 1.0,
      θ    => -1.0]

p = [Jₘ => 11, Jₐ => 11, k => 2e4, c => 6]
prob = ODEProblem(sys, u0, tspan, p, jac = true)
sol = solve(prob, Tsit5(), abstol=1e-4, reltol=1e-4)
plot!(sol.t, Array(sol)')
```
The solution using MT is just zeros (almost)

**Comment by AlCap23** [comment]
Works for me. The indices are not equal.

```julia
using OrdinaryDiffEq, Plots

function dynamics(dx, x, p, t)
      k, Jₘ, Jₐ, c = p
      q, θ, q̇, θ̇ = x
      Δq = q - θ
      Δv = q̇ - θ̇
      dx[1] = q̇
      dx[2] = θ̇
      dx[3] = -(k * Δq + c * (Δv)) / Jₘ
      dx[4] = (k * Δq + c * (Δv)) / Jₐ
end

x0 = Float64[1,-1,0,0]

p = [2e4,11,11,6]
tspan = (0.0, 1)
prob = ODEProblem(dynamics, x0, tspan, p)
sol = solve(prob, Tsit5(), abstol=1e-4, reltol=1e-4)
plot(sol)

## Using ModelingToolkit
using ModelingToolkit, OrdinaryDiffEq

@parameters t, k, k₃, Jₘ, Jₐ, c
@variables θ(t) q(t)
@derivatives D'~t

Δq = q - θ
Δv = (D(q) - D(θ))
eqs = [
    D(D(q)) ~ (-(k * Δq + c * (Δv))) / Jₘ
    D(D(θ)) ~ ((k * Δq + c * (Δv))) / Jₐ
]
sys = ode_order_lowering(ODESystem(eqs, name=:DMM))
sys.eqs

u0 = [D(q) => 0.0,
      D(θ) => 0.0,
      q    => 1.0,
      θ    => -1.0]

p = [Jₘ => 11, Jₐ => 11, k => 2e4, c => 6]
prob = ODEProblem(sys, u0, tspan, p, jac = true)
sol_ = solve(prob, Tsit5(), abstol=1e-4, reltol=1e-4)
sol_a = [0 0 1 0; 0 0 0 1; 1 0 0 0; 0 1 0 0] *sol
plot(sol)
plot!(sol_.t, sol_a')
```

![image](https://user-images.githubusercontent.com/20998300/93236786-8905fe00-f77f-11ea-9cc3-8d9f14227cbc.png)

With 

```julia
(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [6e4b80f9] BenchmarkTools v0.5.0
  [1e616198] COSMO v0.7.4
  [052768ef] CUDA v1.3.3
  [861a8166] Combinatorics v1.0.2
  [2445eb08] DataDrivenDiffEq v0.3.3
  [aae7a2af] DiffEqFlux v1.21.0
  [41bf760c] DiffEqSensitivity v6.31.1
  [0c46a032] DifferentialEquations v6.15.0
  [587475ba] Flux v0.11.1
  [033835bb] JLD2 v0.1.14
  [50d2b5c4] Lazy v0.15.1
  [898213cb] LowRankApprox v0.4.1
  [961ee093] ModelingToolkit v3.19.0
  [429524aa] Optim v0.22.0
  [1dea7af3] OrdinaryDiffEq v5.42.3
  [14b8a8f1] PkgTemplates v0.7.10
  [91a5bcdd] Plots v1.6.0
  [92933f4c] ProgressMeter v1.3.2
  [d1185830] SymbolicUtils v0.5.1
  [5d786b92] TerminalLoggers v0.1.2
```

**Comment by ChrisRackauckas** [comment]
Yeah we're going to handle the indexing from the solution with MTK variables soon since with things like alias elimination we cannot guarantee that we're solving on the same basis, so keeping the MTK variable naming at the analysis part is pretty necessary.

**Comment by baggepinnen** [comment]
Running the posted code, I get
![mt](https://user-images.githubusercontent.com/3797491/93299820-fbb1c080-f7f5-11ea-8338-874376f88668.png)
```
(@v1.5) pkg> st -m ModelingToolkit
Status `~/.julia/environments/v1.5/Manifest.toml`
  [961ee093] ModelingToolkit v3.20.0 `~/.julia/dev/ModelingToolkit`
```
with an up-to-date master of MTK

**Comment by baggepinnen** [comment]
> Works for me. The indices are not equal.
> 
> ```julia
> using OrdinaryDiffEq, Plots
> 
> function dynamics(dx, x, p, t)
>       k, Jₘ, Jₐ, c = p
>       q, θ, q̇, θ̇ = x
>       Δq = q - θ
>       Δv = q̇ - θ̇
>       dx[1] = q̇
>       dx[2] = θ̇
>       dx[3] = -(k * Δq + c * (Δv)) / Jₘ
>       dx[4] = (k * Δq + c * (Δv)) / Jₐ
> end
> 
> x0 = Float64[1,-1,0,0]
> 
> p = [2e4,11,11,6]
> tspan = (0.0, 1)
> prob = ODEProblem(dynamics, x0, tspan, p)
> sol = solve(prob, Tsit5(), abstol=1e-4, reltol=1e-4)
> plot(sol)
> 
> ## Using ModelingToolkit
> using ModelingToolkit, OrdinaryDiffEq
> 
> @parameters t, k, k₃, Jₘ, Jₐ, c
> @variables θ(t) q(t)
> @derivatives D'~t
> 
> Δq = q - θ
> Δv = (D(q) - D(θ))
> eqs = [
>     D(D(q)) ~ (-(k * Δq + c * (Δv))) / Jₘ
>     D(D(θ)) ~ ((k * Δq + c * (Δv))) / Jₐ
> ]
> sys = ode_order_lowering(ODESystem(eqs, name=:DMM))
> sys.eqs
> 
> u0 = [D(q) => 0.0,
>       D(θ) => 0.0,
>       q    => 1.0,
>       θ    => -1.0]
> 
> p = [Jₘ => 11, Jₐ => 11, k => 2e4, c => 6]
> prob = ODEProblem(sys, u0, tspan, p, jac = true)
> sol_ = solve(prob, Tsit5(), abstol=1e-4, reltol=1e-4)
> sol_a = [0 0 1 0; 0 0 0 1; 1 0 0 0; 0 1 0 0] *sol
> plot(sol)
> plot!(sol_.t, sol_a')
> ```
> 
> ![image](https://user-images.githubusercontent.com/20998300/93236786-8905fe00-f77f-11ea-9cc3-8d9f14227cbc.png)
> 
> With
> 
> ```julia
> (@v1.5) pkg> st
> Status `~/.julia/environments/v1.5/Project.toml`
>   [6e4b80f9] BenchmarkTools v0.5.0
>   [1e616198] COSMO v0.7.4
>   [052768ef] CUDA v1.3.3
>   [861a8166] Combinatorics v1.0.2
>   [2445eb08] DataDrivenDiffEq v0.3.3
>   [aae7a2af] DiffEqFlux v1.21.0
>   [41bf760c] DiffEqSensitivity v6.31.1
>   [0c46a032] DifferentialEquations v6.15.0
>   [587475ba] Flux v0.11.1
>   [033835bb] JLD2 v0.1.14
>   [50d2b5c4] Lazy v0.15.1
>   [898213cb] LowRankApprox v0.4.1
>   [961ee093] ModelingToolkit v3.19.0
>   [429524aa] Optim v0.22.0
>   [1dea7af3] OrdinaryDiffEq v5.42.3
>   [14b8a8f1] PkgTemplates v0.7.10
>   [91a5bcdd] Plots v1.6.0
>   [92933f4c] ProgressMeter v1.3.2
>   [d1185830] SymbolicUtils v0.5.1
>   [5d786b92] TerminalLoggers v0.1.2
> ```
> 
> Okay, if you use `plot(sol, layout=2)` it works without the rotation ;)

In your code, the code that plots for MTK you save the solution in `sol_` but you multiply the rotation with `sol`, hence you´re plotting the manual solution twice?

**Comment by AlCap23** [comment]
Uh. I played around a little. I will check in a Minute and update the post.

**Comment by ChrisRackauckas** [comment]
This was an ordering issue, which is now fixed by the whole `u0map` stuff.
