### ISSUE TITLE
build_function (CTarget) generates wrong code

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#586]
The following model contains the cubic term `Δq^3 = (q - θ)^3`. This term does not appear to be present in the generated c-code, reproduced below
```julia
@parameters t, k, k₃, Jₘ, Jₐ, c, tx
@variables θ(t) q(t) #u(t)
@derivatives D'~t

Δq = q - θ
Δv = (D(q) - D(θ))

eqs = [
    D(D(q)) ~ -(k * Δq + k₃ * Δq^3 + c * (Δv)) / Jₘ
    D(D(θ)) ~ (k * Δq + k₃ * Δq^3 + c * (Δv)) / Jₐ
]

sys = ODESystem(eqs, name=:DMM) |> ode_order_lowering

ccode = build_function(
      sys.eqs,
      states(sys),
      parameters(sys),
      t,
      target = ModelingToolkit.CTarget(),
)
```

```c
void diffeqf(double* du, double* RHS1, double* RHS2, double RHS3) {
  du[0] = RHS1[2];
  du[1] = RHS1[3];
  du[2] = -((RHS2[0] * (RHS1[0] - RHS1[1]) + RHS2[3] * (RHS1[2] - RHS1[3]))) / RHS2[1];
  du[3] = (RHS2[0] * (RHS1[0] - RHS1[1]) + RHS2[3] * (RHS1[2] - RHS1[3])) / RHS2[2];
}
```
The `sys.eqs` does correctly contain the cubic terms
```julia
julia> sys.eqs
4-element Array{Equation,1}:
 Equation(derivative(qˍt(t), t), -(((k * (q(t) - θ(t)) + k₃ * (q(t) - θ(t)) ^ 3) + c * (qˍt(t) - θˍt(t)))) / Jₘ)
 Equation(derivative(θˍt(t), t), ((k * (q(t) - θ(t)) + k₃ * (q(t) - θ(t)) ^ 3) + c * (qˍt(t) - θˍt(t))) / Jₐ)
 Equation(derivative(q(t), t), qˍt(t))
 Equation(derivative(θ(t), t), θˍt(t))
```

**Comment by ChrisRackauckas** [comment]
As mentioned in the other issue, `build_function` wants `Operation`s, not `Equation`.s

**Comment by ChrisRackauckas** [comment]
Though this does look odd anyways... I don't get why `string` of and `expr` would drop `^`... seems like it might be a `literal_pow` issue.

**Comment by baggepinnen** [comment]
Here https://mtk.sciml.ai/dev/tutorials/converting_to_C/ it says that one should provide `Equations`?

**Comment by ChrisRackauckas** [comment]
>Here https://mtk.sciml.ai/dev/tutorials/converting_to_C/ it says that one should provide Equations? 

Ahh thanks, that's not conforming to the interface then. That's not good.

**Comment by ChrisRackauckas** [comment]
This moved to Symbolics.jl and was rewritten: https://github.com/JuliaSymbolics/Symbolics.jl/pull/72
