### ISSUE TITLE
ODESystem does not accept matrix variables

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#604]
I had to call `vec` below for the constructor to accept my parameter `K`, which is a matrix.
```julia
ODESystem(connections, t, ϕ, vec(K), systems=[armsys,motorsys])
```
It's not a huge problem, but the friction could be reduced by handling that automatically.

**Comment by ChrisRackauckas** [comment]
Yes, this one should have a good quick solution. Thanks for the issue. We should just `vec` internally.

**Comment by ChrisRackauckas** [comment]
I'm going to lump this into https://github.com/SciML/ModelingToolkit.jl/issues/605, which is all that array symbolics needs to change.
