### ISSUE TITLE
Symbolic arrays instead of arrays of symbolics

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#605]
I find that the friction associated with working with arrays of parameters and variables is very large. Consider the following example
```julia
using ModelingToolkit, OrdinaryDiffEq

@parameters t M[1:2,1:2] Dq[1:2,1:2] Dθ[1:2,1:2] B[1:2,1:2] K[1:2,1:2]
@variables q[1:2](t) θ[1:2](t) τ[1:2](t) ϕ[1:2](t)
@derivatives D'~t


arm_eqs   = D.(D.(q)) .~ -M\Dq*D.(q)   .|> simplify
armsys    = ODESystem(arm_eqs, name=:arm) |> ode_order_lowering
motor_eqs = D.(D.(θ)) .~ -B\Dθ*D.(θ) + τ   .|> simplify
motorsys  = ODESystem(motor_eqs, name=:motor) |> ode_order_lowering


connections = 0 .~ K*(q - θ + ϕ)
connected = ODESystem(connections, t, ϕ, vec(K), systems=[armsys,motorsys])

x0 = [
      armsys.q       => zeros(2),
      D.(armsys.q)   => zeros(2),
      motorsys.q     => zeros(2),
      D.(motorsys.q) => zeros(2),
      ϕ              => 0,
]
```
Here, there is no variable `armsys.q` (`ERROR: Variable q does not exist`), instead there are
```julia
julia> armsys.states
4-element Array{Variable,1}:
 q₁ˍt
 q₂ˍt
 q₁
 q₂
```
How do I provide initial states for this variable if instead of two, there are 100 of them?
I can inspect `armsys.states` and figure out what order the states have been put in, but that feels like an implementation detail and not something I want to rely on. 

The same here:
```julia
p = [
      armsys.M    => [1 0.1; 0.1 1],
      armsys.Dq   => [1 0; 0 1],
      motorsys.Dθ => [1 0; 0 1],
      motorsys.B  => [1 0; 0 1],
      connected.K => [1 0; 0 1],
]

ERROR: Variable M does not exist
```

Maybe an example in the docs using array-valued parameters would be beneficial for both users and finding bugs etc.?

**Comment by ChrisRackauckas** [comment]
This issue stems from the fact that we currently currently have to represent it as an array of structs instead of a struct of array, but this should be changing fairly soon. @shashi this is something to keep in mind for after https://github.com/SciML/ModelingToolkit.jl/pull/518

**Comment by baggepinnen** [comment]
Any news on this? I tried the same example as above but am still seeing the same behavior.

**Comment by ChrisRackauckas** [comment]
It's bubbling up. https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/123 is where it's at.

**Comment by ChrisRackauckas** [comment]
We have them. Concrete issues about them should be surfaced as new issues.
