### ISSUE TITLE
Differential & expand_derivatives missing derivatives of linear terms

### ISSUE THREAD

**Issue by michakraus** [SciML/ModelingToolkit.jl#624]
I came across a strange issue when computing derivatives of linear terms. Consider the following MWE:
```julia
@variables x
@derivatives Dx'~x
@parameters a, b
a₀ = 1; b₀ = -2;
```
If I define an expression with unspecified parameters `(a,b)`, everything works as expected:
```julia
julia> H = a * x + b * log(x)
(a * x) + (b * log(x))

julia> expand_derivatives(Dx(H))
a + (b * inv(x))
```

But when I define the same expression with fixed parameters `(a₀,b₀)`, the derivatives are missing some terms:
```julia
julia> H₀ = a₀ * x + b₀ * log(x)
(1 * x) + (-2 * log(x))

julia> expand_derivatives(Dx(H₀))
-2 * inv(x)
```
Funnily, if I have an expression with only the linear terms, everything is fine as well:
```julia
julia> K₀ = a₀ * x
1 * x

julia> expand_derivatives(Dx(K₀))
1
```
I am on the latest #master as of this morning.

Edit: Simplified MWE.

**Comment by ChrisRackauckas** [comment]
Yeah, that's strange. @shashi let's discuss this one in 15.

**Comment by shashi** [comment]
This is fixed by #627

**Comment by michakraus** [comment]
It seems a variant of this error has resurfaced in MTK v5.0 (the following still worked in v4.5):
```julia
@variables X[1:4]
@variables V[1:4]
DX = Differential.(X)

H(x) = sum(x)
K(x,v) = sum(log.(x) .* v)

let K = K(X, V), H = H(X)
    f = [expand_derivatives(DX[i](K-H)) for i in eachindex(DX)]
    f̄ = [expand_derivatives(DX[i](K+H)) for i in eachindex(DX)]
    println("f-f̄ = ", f.-f̄)

    g = [expand_derivatives(DX[i](-H)) for i in eachindex(DX)]
    ḡ = [expand_derivatives(DX[i](+H)) for i in eachindex(DX)]
    println("g+ḡ = ", g.+ḡ)
end
```
yields
```
f-f̄ = Num[0, 0, 0, 0]
g+ḡ = Num[0, 0, 0, 0]
```
where the latter is correct, but the former is nonsense. Specifically, the derivative of `K-H` is identical to the derivative of `K+H`, while the derivative of `-H` is indeed the negation of the derivative of `+H`.

**Comment by shashi** [comment]
@michakraus thanks for the report, the problem turned out to be that K-H itself is wrong! fixed here https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/176

**Comment by michakraus** [comment]
Thanks for the quick fix!

**Comment by shashi** [comment]
This scared me so we wrote a fuzzer for the construction https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/177 -- this would have caught this bug emphatically.
