### ISSUE TITLE
Simplifying floating point exponents sometimes doesn't cancel terms

### ISSUE THREAD

**Issue by MarcBerliner** [SciML/ModelingToolkit.jl#630]
E.g.

```
julia> @variables x y
(x, y)

julia> simplify(x^2.0/(x*y)^2.0)
x ^ 2.0 * inv((x * y) ^ 2.0) ^ 1
```
compared to
```
julia> simplify(x^2/(x*y)^2)
inv(y) ^ 2
```
Removing the parentheses works as well 
```
julia> simplify(x^2.0/x^2.0/y^2.0)
inv(y ^ 2.0) ^ 1
```

**Comment by ChrisRackauckas** [comment]
@shashi you know about this one?

**Comment by YingboMa** [comment]
This is because to simplify this expression, it needs to expand `(x*y)^2` to `x^2 + y^2`
```julia
julia> simplify((x*y)^2)
(x ^ 2) * (y ^ 2)
```
When the exponent is not an integer, we assume that this transformation will be too expensive to be beneficial. This can be fixed by using the `isinteger` check instead of `isa Integer`.

**Comment by YingboMa** [comment]
It's still highly not recommend to write `.0` in Julia unnecessarily. It doesn't make anything faster, but sometimes it definitely makes the code slower.
