### ISSUE TITLE
Enhancement -- Full differentials and Delta

### ISSUE THREAD

**Issue by BrettKnoss** [SciML/ModelingToolkit.jl#635]
Currently there is a differential function

```
c=diff(x^3,x)
```
c=3x^2

I would like to not have to specify x, if there is only one variable, and I'm not doing partial differentiation.

I would also like to be able to use delta in place of diff

```
c=Δ(x^3+5x)
c=3x^2+5

δ=(x^3+5x,x)
3x^2+5
```
I think this would create a more realistic looking code and would be faster to type, with a keyboard that has Greek Polytonic.

**Comment by ChrisRackauckas** [comment]
>I would also like to be able to use delta in place of diff

That's up the user. You can name it whatever you want. 

>I would like to not have to specify x, if there is only one variable, and I'm not doing partial differentiation.

That's surprisingly expensive to support. What's wrong with just declaring an operator `const Δ = y -> expand_derivatives(Differential(x)(y))`?
