### ISSUE TITLE
Variable names incorrect in plot legends on 4.0+

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#636]
On Catalyst master
```julia
rs = @reaction_network begin
  c1, X --> 2X
  c2, X --> 0
  c3, 0 --> X
end c1 c2 c3
p = (1.0,2.0,50.) # [c1,c2,c3]
tspan = (0.,4.)
u0 = [5.]         # [X]

# solve ODEs
oprob = ODEProblem(rs, u0, tspan, p)
osol  = solve(oprob, Tsit5())
plot(osol)

# solve SDEs
sprob = SDEProblem(rs, u0, tspan, p)
ssol  = solve(sprob, EM(), dt=.01)
plot(ssol)

# solve JumpProblem
u0 = [5]
dprob = DiscreteProblem(rs, u0, tspan, p)
jprob = JumpProblem(rs, dprob, Direct())
jsol = solve(jprob, SSAStepper())
plot(jsol)
```
gives
![osol](https://user-images.githubusercontent.com/9385167/97916225-b18e8b00-1d20-11eb-9782-d5c65bd48fcd.png)
![ssol](https://user-images.githubusercontent.com/9385167/97916230-b3584e80-1d20-11eb-823d-0ec5a5041723.png)
![jsol](https://user-images.githubusercontent.com/9385167/97916235-b5221200-1d20-11eb-877f-0db38a844296.png)

**Comment by ChrisRackauckas** [comment]
@shashi @YingboMa should be easy to fix with a find replace heuristic in the DiffEq plot recipe

**Comment by isaacsas** [comment]
@YingboMa Legends are now incorrect again.

ODE
![ode](https://user-images.githubusercontent.com/9385167/100883381-469ab600-347e-11eb-9ed2-257c223578aa.png)

SDE
![sde](https://user-images.githubusercontent.com/9385167/100883400-4bf80080-347e-11eb-8466-8ff4f49ba0bd.png)

Jump
![jump](https://user-images.githubusercontent.com/9385167/100883416-4ef2f100-347e-11eb-807e-072b1de829d2.png)

**Comment by isaacsas** [comment]
Maybe we need a test for the generated string / Symbol?

**Comment by YingboMa** [comment]
This is not from MTK. DiffEqBase add the extra `(t)`. I will make a PR to fix it.

**Comment by isaacsas** [comment]
Great, thanks!
