### ISSUE TITLE
Fix and/or test NonlinearSystem conversion from ReactionSystems

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#639]
Needs tests to see if it is working with MT v4.0+.

**Comment by ChrisRackauckas** [comment]
ODESystem -> SteadyStateProblem is tested and should be fine.

**Comment by isaacsas** [comment]
We need tests for the direct ReactionSystem conversion though since it the problem type was only recently setup.

**Comment by ChrisRackauckas** [comment]
This is now in Catalyst and IIUC tested well there.
