### ISSUE TITLE
logorithms not differentiated

### ISSUE THREAD

**Issue by BrettKnoss** [SciML/ModelingToolkit.jl#641]
```
@variables x
@derivatives δx~x

δx(log(x))
```
gives Derivative(log(x))

I take it that this means no one has yet defined the opperations, to find the derivative of log(x), but the operation has been put in.

**Comment by ChrisRackauckas** [comment]
did you mean to expand the derivative?

**Comment by BrettKnoss** [comment]
Yes. I used expand_derivatives I thought. I could go check.

**Comment by ChrisRackauckas** [comment]
```
@variables x
@derivatives δx'~x
expand_derivatives(δx(log(x))) # inv(x)
```

works fine.
