### ISSUE TITLE
What to do with `derivative`

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#684]
Should we define `ModelingToolkit.derivative(f, x) = expand_derivatives(Differential(x)(f))`? It's technically breaking, but I doubt the current behavior of not using chain rules is desirable.

**Comment by ChrisRackauckas** [comment]
The current `derivative` is "symbolic rules", not the derivative function. We should definitely change this because it's a confusing trap for most users.
