### ISSUE TITLE
Alias elimination

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#686]
Aliasing cases:
1. `u = number` => replace `u` with `number`
2. `u1 = u2` => replace `u1` with `u2`
3. `u = x` => when `u` is a differential variable and `x` is an algebraic variable, then replace `x` with `u`

**Comment by shashi** [comment]
`u1 = u2 => replace u1 with u2`

here do you allow `u2` to be any expression? (I'm guessing not., it just has to be a variable?)

**Comment by YingboMa** [comment]
Yes, that's correct.

**Comment by YingboMa** [comment]
Ah, actually, we allow u2 to be any expr but `u1` must be a simple expr, like `alpha * x`, where `x` is a symbol.
