### ISSUE TITLE
expand_derivatives issues

### ISSUE THREAD

**Issue by KirillZubov** [SciML/ModelingToolkit.jl#688]
I face up with two problems, using`expand_derivatives`

```julia
@parameters x
@variables u(..)
@derivatives Dx'~x
julia> expand_derivatives(Dx(u(1)))
0
```     
but it should probably work out `Differential(u(1))`
e.g. if u(x) = x+x^2,
then Dx(u(1)) = 1+2x(where x=1) = 3 but not 0 .
The same, if `u` is `Flux.chain `.

Second, with mixed derivative.
```julia
@parameters x y
@variables u(..)
@derivatives Dy'~y
@derivatives Dx'~x
julia> expand_derivatives(Dx(Dy(u(x,y))) )

Julia has exited.
Press Enter to start a new session.
```

 ModelingToolkit v4.3.0

**Comment by ChrisRackauckas** [comment]
You need to plug in the symbol to differentiate, then substitute.
