### ISSUE TITLE
AutoOptimize produces wrong results, ode_order_lowering produces defect model,  StructuralTransformations.dae_index_lowering fails

### ISSUE THREAD

**Issue by freemin7** [SciML/ModelingToolkit.jl#708]
Hello,

i've found this model on Twitter https://twitter.com/pepijndevos/status/1344213591176654849  @pepijndevos and tried to optimize it using MTK tools.
https://gist.github.com/freemin7/565c10a948d7540ac59bf13657196dca

Notice that
 - the plots are different
 - ModelingToolkit.ode_order_lowering produces a bad model which blows up in StructuralTransformations.dae_index_lowering (error could be detected earlier) and fails to be solved due to an undefined variable
 - Doing StructuralTransformations.dae_index_lowering on the model and not ode_order_lowering first, nothing blows up.

**Comment by ChrisRackauckas** [comment]
@YingboMa this is worth looking into since it seems to give a completely different solution, so I think this found a bug but I don't know where it would've.
