### ISSUE TITLE
Alias elimination can miss an equality?

### ISSUE THREAD

**Issue by FHell** [SciML/ModelingToolkit.jl#725]
When connecting two systems, parameters that occur in the observed equations but are not explicitly declared don't show up in the final ODESystem.

```julia
## Setup
using ModelingToolkit
const MTK = ModelingToolkit

@parameters t
@derivatives D'~t

## Define an open loop control system:

@variables x(t), u(t), y(t)
@parameters a, b, c, d
ol = ODESystem([D(x) ~ a * x + b * u], t, pins=[u], observed=[y ~ c * x], name=:ol)

## Define a proportional control law

@variables u_c(t), y_c(t)
@parameters k_P
pc = ODESystem(Equation[], t, [y_c], [k_P], pins=[y_c], observed=[u_c ~ k_P * y_c],  name=:pc)

# Where we explicitly add k_P to the parameters

## Connect them
connections = [
    ol.u ~ pc.u_c,
    pc.y_c ~ ol.y
]

connected = MTK.ODESystem(Equation[],t, observed=connections, systems=[ol, pc])

## Get the flattened system

flattened_system = MTK.flatten(connected) # Turns the composite system into one
aliased_flattened_system = MTK.alias_elimination(flattened_system)

##

@show aliased_flattened_system.ps # [ol₊b, ol₊a, pc₊k_P] ol.c is missing, pc.k_P is present

##

of = ODEFunction(aliased_flattened_system)
of(ones(1), ones(5), 0.) # ERROR: UndefVarError: ol₊c not defined
```

**Comment by ChrisRackauckas** [comment]
We probably need a whole `remake` system on `AbstractSystem` instead of using the constructor?

**Comment by sdwfrost** [comment]
Is there a particular branch that implements `pins` and `observed`?

**Comment by ChrisRackauckas** [comment]
`pins` were removed: they aren't needed (well, big story there. Won't be needed by the end of today if @YingboMa 's estimates are correct). `observed` has been in releases for a few months now, but should generally be handled by the alias elimination system. I would say, hold off about one more week until we get this big new tutorial out that shows "the full system": I have a call with @YingboMa later today to see if the last piece is done.

**Comment by ChrisRackauckas** [comment]
@sdwfrost and @FHell you probably want to take a look at https://github.com/SciML/ModelingToolkit.jl/issues/803 which shows an example of the whole system in action on a small example.

**Comment by ChrisRackauckas** [comment]
This is a simplified example which shows why `pins` were no longer needed after alias_elimination got good enough:

```julia
using ModelingToolkit, OrdinaryDiffEq
@parameters t a
@variables x(t) f(t)
D = Differential(t)
eqs = [
  D(x) ~ -a*x + f
]
decay = name -> ODESystem(eqs, name=name)
decay1 = decay(:decay1)
connected = ODESystem([
  decay1.f ~ sin(t)
], t, systems=[decay1])
reduced_system = alias_elimination(connected)
@show reduced_system
x0 = [
  decay1.x => 1.0
]
p = [
  decay1.a => 0.1
]
prob = ODEProblem(reduced_system, x0, (0.0, 20.0), p)
sol = solve(prob, Tsit5())
```

```julia
julia> equations(reduced_system)
1-element Vector{Equation}:
 Differential(t)(decay1₊x(t)) ~ sin(t) - (decay1₊a*(decay1₊x(t)))
```

**Comment by ChrisRackauckas** [comment]
BTW, the original issue here looks like a user error. It should've been defined as:

```julia
ol = ODESystem([D(x) ~ a * x + b * u], t,  [x,u,y], [a,b,c,d], pins=[u], observed=[y ~ c * x], name=:ol)
```

**Comment by FHell** [comment]
> BTW, the original issue here looks like a user error. It should've been defined as:
> 
> ```julia
> ol = ODESystem([D(x) ~ a * x + b * u], t,  [x,u,y], [a,b,c,d], pins=[u], observed=[y ~ c * x], name=:ol)
> ```

I will have a look at the other issue. But what you are saying here is that using the constructor without explicitly declaring variables is unsupported? As it says at the very top, the issue was explicitly about constructing the system and not explicitly declaring the parameters (and the constructor not automatically detecting parameters in observed equations...).

**Comment by ChrisRackauckas** [comment]
I see what you mean. Okay, in the v5 system, the model looks like:

```julia
using ModelingToolkit
const MTK = ModelingToolkit

@parameters t
@derivatives D'~t

@variables x(t), u(t), y(t)
@parameters a, b, c, d
ol = ODESystem([D(x) ~ a * x + b * u
                                 y ~ c * x], name=:ol)

@variables u_c(t), y_c(t)
@parameters k_P
pc = ODESystem(Equation[u_c ~ k_P * y_c], name=:pc)

connected = MTK.ODESystem(Equation[
                                   ol.u ~ pc.u_c
                                   pc.y_c ~ ol.y], t,
                                   systems=[ol, pc])

sys = MTK.alias_elimination(connected)

@show MTK.get_ps(sys) # [ol₊b, ol₊a, ol.c, pc₊k_P]
@show states(sys)     # [pc₊u_c(t), ol₊x(t)]
@show equations(sys)  # [Differential(t)(ol₊x(t)) ~ ol₊a*ol₊x(t) + ol₊b*pc₊u_c(t), 0 ~ ol₊c*pc₊k_P*ol₊x(t) - (pc₊u_c(t))]

of = ODEFunction(sys)
of(ones(2), ones(4), 0.)
```

What I wrote currently "works", but `alias_elimination` is missing the elimination of `pc.u_c` so I'll reopen this (@YingboMa can you take a look here?).

**Comment by YingboMa** [comment]
Alias elimination doesn't guarantee any elimination. It is not as simple as just eliminate all equations in the form of `x ~ ...`.

**Comment by ChrisRackauckas** [comment]
As mentioned in the chat, it is due to the cycle.

**Comment by ChrisRackauckas** [comment]
This was fixed by `structural_simplify` using tearing internally for cycle detection.
