### ISSUE TITLE
@variable docstring mentions Operation

### ISSUE THREAD

**Issue by mforets** [SciML/ModelingToolkit.jl#730]
The `@variable` docstring mentions `Operation` (see https://mtk.sciml.ai/dev/highlevel/#High-Level-API-Documentation-1 and https://github.com/SciML/ModelingToolkit.jl/blob/master/src/variables.jl#L166), but such type is from a previous version of the library and it is no longer available. (Incidentally this is a good reason to annotate docstring examples with `jldoctest`).

**Comment by pbouffard** [comment]
I'm thinking of opening an issue and corresponding branch to collect one-off documentation improvements that can be occasionally PR'd into master when there's enough such edits to make it worthwhile. 

I mean for example I'd like to add to the `ode_order_lowering` docstring something that describes how the newly created states are named. And I'd like to properly understand what `@nonamespace` does and give it a docstring.

@ChrisRackauckas I know you're not a fan of catch-all issues but is there a better workflow to handle this sort of thing?

**Comment by YingboMa** [comment]
Right. Working for a few hours to close one issue isn't very satisfying. Gotta make one PR that closes a dozen or sth. :p

**Comment by ChrisRackauckas** [comment]
That's the spirit.

**Comment by david-hofmann** [comment]
Just noting that this issue can be closed, seems to be outdated as far as I can see (following the links above).
