### ISSUE TITLE
Differentiation Test: Test Failed at test/derivatives.jl:76

### ISSUE THREAD

**Issue by cadojo** [SciML/ModelingToolkit.jl#737]
I hope this isn't a double issue, this seems to be a (very) new problem.

Tests started failing for `test/derivatives.jl:76` in `master` today. I came across this during checks for PR #736, which should not change any `derivatives` functionality.

**Comment by ChrisRackauckas** [comment]
@YingboMa was this from the SymbolicUtils.jl patch?

**Comment by YingboMa** [comment]
Yeah, it should be fixed
