### ISSUE TITLE
CTarget, MATLABTarget, StanTarget Rewrite

### ISSUE THREAD

**Issue by cadojo** [SciML/ModelingToolkit.jl#745]
### Overview

Non-Julia `build_function` targets currently use outdated function signatures, which were first introduced with `ModelingToolkit` around two years ago (as described in #736).

A rewrite for these `_build_function` implementations would be useful. Improvements could include...

* Supporting the `_build_function(::JuliaTarget)` function signature, e.g. `_build_function(::CTarget, ex, args)`
* Support for matrix and vector equations (described in #735 and PR #736)

**Comment by ChrisRackauckas** [comment]
Done!
