### ISSUE TITLE
warnings when accessing system fields

### ISSUE THREAD

**Issue by isaacsas** [SciML/ModelingToolkit.jl#796]
I noticed in the Catalyst tests the following warnings:
```julia
┌ Warning: `sys.name` like `sys.eqs` is deprecated. Use getters like `get_eqs` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: `sys.name` like `sys.iv` is deprecated. Use getters like `get_iv` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: `sys.name` like `sys.states` is deprecated. Use getters like `get_states` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: `sys.name` like `sys.ps` is deprecated. Use getters like `get_ps` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: `sys.name` like `sys.name` is deprecated. Use getters like `get_name` instead.
│   caller = ip:0x0
└ @ Core :-1
┌ Warning: `sys.name` like `sys.systems` is deprecated. Use getters like `get_systems` instead.
│   caller = ip:0x0
└ @ Core :-1
```
What's the reason for depreciating direct field access for all systems? Among other things I think this warning is coming from using the unpack macro; it would be a shame if that is no longer usable.

**Comment by ChrisRackauckas** [comment]
On master? I thought I had fixed these.

**Comment by isaacsas** [comment]
No, this is with the latest release, not master. (It was in the test output for the PR I made to add back coverage.)

I'll close this for now, and reopen if this reappears.

**Comment by ChrisRackauckas** [comment]
Latest release should be fine too?

**Comment by isaacsas** [comment]
Hmm, then it seems this is an issue: https://github.com/SciML/ModelingToolkit.jl/runs/1910720386?check_suite_focus=true#step:6:292

That's coming, I think, from https://github.com/SciML/Catalyst.jl/blob/27c1502eb6c792835c656c3fa2e6a44b33b31579/test/make_model.jl#L35

**Comment by ChrisRackauckas** [comment]
Seems like it might be an issue on the Catalyst side? I think I got everything in ReactionSystem.

**Comment by isaacsas** [comment]
Right, so accessing fields directly is no longer allowed? Why is that? It breaks stuff like unpack, which is pretty useful for users.

**Comment by isaacsas** [comment]
Or are you saying that unpack should still work?

**Comment by ChrisRackauckas** [comment]
When would users be using unpack? We have a bunch of getters, but relying on `.` breaks the nesting syntax in some cases.

**Comment by isaacsas** [comment]
Sorry, I'm not up on all the recent changes since so much has been pushed through in the past month. In Catalyst it sounds like a lot of updates are needed. Our tests, for example, all use unpack to bring many fields of test networks in as local variables before using them. We also still, internally, use field access a bunch. 

With the getters, is it still possible to modify field values (i.e. changing the `iv` or pushing on a new parameter)?

**Comment by isaacsas** [comment]
Most of the Catalyst API, particularly for programmatic system construction, relies on being able to directly modify the eqs, states and parameters of a given system.

**Comment by isaacsas** [comment]
OK, it seems we can mimic the previous functionality and update field values by just directly using `setfield!` (I'd never used it before...). So I'll close this. Catalyst will need an update at some point to switch to using the getters and `setfield!`.
