### ISSUE TITLE
Matrix differential equations

### ISSUE THREAD

**Issue by seadra** [SciML/ModelingToolkit.jl#797]
Hi,

I'm trying to solve a matrix PDE. Is it possible to write the whole matrix equation as-is, or do we have to write each scalar component separately?

Currently when I try

```julia
@parameters x y
@variables u[1:2,1:2](..)
Dx = Differential(x)

A =  [1.0 2.0; 3.0 4.0];
eq  = Dx(u(x,y)) ~ A*u(x,y)
```

it gives the error

```
MethodError: objects of type Array{Variable{Number},2} are not callable
Use square brackets [] for indexing an Array.

Stacktrace:
 [1] top-level scope at In[51]:6
```

but it would be nice this just worked

**Comment by sdwfrost** [comment]
Do you mean this?

```julia
@parameters x y
@variables u[1:2,1:2]
Dxy = Differential(x)*Differential(y)
A =  [1.0 2.0; 3.0 4.0];
eq  = Dxy(u .~ A*u)
```

**Comment by seadra** [comment]
Thanks for the response! I'm actually looking to solve `Dt(u(x,t)) = A Dxx(u(x,t))` where both A and u(x,t) are matrices. The code you posted fails with a different error:

```
MethodError: no method matching *(::Differential, ::Differential)
Closest candidates are:
  *(::Any, ::Any, ::Any, ::Any...) at operators.jl:538
  *(::MutableArithmetics.Zero, ::Any) at /home/user/.julia/packages/MutableArithmetics/bPWR4/src/rewrite.jl:49
  *(::LightGraphs.LinAlg.Noop, ::Any) at /home/user/.julia/packages/LightGraphs/IgJif/src/linalg/graphmatrices.jl:226
  ...
Stacktrace:
 [1] top-level scope at In[7]:3
```

**Comment by ChrisRackauckas** [comment]
You accidentally made `bcs` an array of arrays. It should be:

```julia
bcs = [u(0,y) .~ 0.f0*B; u(1,y) .~ -sin(pi*1)*sin(pi*y)*B;
           u(x,0) .~ 0.f0*B; u(x,1) .~ -sin(pi*x)*sin(pi*1)*B]
```

`;` lowers to `vcat`, which then concatenates all of the arrays into a single array and works fine.

**Comment by seadra** [comment]
@ChrisRackauckas Could you post the full code that worked for you?

```julia
@parameters x y
@variables u[1:2,1:2]
Dx = Differential(x)
A =  [1.0 2.0; 3.0 4.0];
eq  = Dx(u) .~ A*u

bcs = [u(0,y) .~ 0.f0*B; u(1,y) .~ -sin(pi*1)*sin(pi*y)*B;
           u(x,0) .~ 0.f0*B; u(x,1) .~ -sin(pi*x)*sin(pi*1)*B]
```

This code already fails at the `eq = ...` line

**Comment by ChrisRackauckas** [comment]
`eq  = Dx.(u) .~ A*u`. The other part is an issue because the representation of `u` needs to change though, which is https://github.com/SciML/ModelingToolkit.jl/issues/605

**Comment by seadra** [comment]
Ah, right, I copy-pasted the wrong code.

I just tried the bcs from your post in Julia, and it fails with the similar error on that line:

```julia
@parameters x y
@variables u[1:2,1:2]
Dx = Differential(x)
A =  [1.0*x 2.0*y; 3.0 4.0];
eq  = Dx.(u) .~ A*u

B =  [1.0 2.0; 3.0 4.0];

bcs = [u(0,y) .~ 0.f0*B; u(1,y) .~ -sin(pi*1)*sin(pi*y)*B; u(x,0) .~ 0.f0*B; u(x,1) .~ -sin(pi*x)*sin(pi*1)*B]
```

```
MethodError: objects of type Array{Operation,2} are not callable
Use square brackets [] for indexing an Array.
```

Am I doing something differently?

**Comment by ChrisRackauckas** [comment]
No, that needs array symbolics, or `getindex.(...)`.

**Comment by seadra** [comment]
Ah, got it! I presume it's [this PR](https://github.com/JuliaSymbolics/Symbolics.jl/issues/94) Looking forward to that!

**Comment by seadra** [comment]
It seems [this PR](https://github.com/JuliaSymbolics/SymbolicUtils.jl/pull/123) was merged in 0.11.3. I gave the most recent code above another try, but I got the same error, so I assume it's not yet completely hooked up.

**Comment by ChrisRackauckas** [comment]
It's in SymbolicUtils and Symbolics but not MTK yet. https://github.com/SciML/ModelingToolkit.jl/pull/989

**Comment by seadra** [comment]
@ChrisRackauckas Given all the PRs mentioned here are now merged, is this supposed to work?

I just updated the package & gave it another try, but unfortunately, I'm still getting the same error

```julia
@parameters x y
@variables u[1:2,1:2]
Dx = Differential(x)
A =  [1.0*x 2.0*y; 3.0 4.0];
eq  = Dx.(u) .~ A*u

B =  [1.0 2.0; 3.0 4.0];

bcs = [u(0,y) .~ 0.f0*B; u(1,y) .~ -sin(pi*1)*sin(pi*y)*B; u(x,0) .~ 0.f0*B; u(x,1) .~ -sin(pi*x)*sin(pi*1)*B]
```

```
MethodError: objects of type Symbolics.Arr{Num, 2} are not callable
Use square brackets [] for indexing an Array.
```

Should I open a new issue for this, or can we reopen this?
