### ISSUE TITLE
Documentation revamping

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#806]
So there's been a lot of moving parts, but we're reaching a final state. Here's the general parts:

- [x] The CAS documentation needs to move over to Symbolics.jl. That could happen even before Symbolics.jl is completed as a project.
- [x] There needs to be a new opening tutorial that showcase more with alias elimination and model building. https://github.com/SciML/ModelingToolkit.jl/issues/803 is a good candidate. 
- [x] There needs to be a tutorial showcasing https://github.com/JuliaComputing/StructuralTransformations.jl for index reduction and tearing
- [x] Tutorial for automated sparsity detection
- [x] Optimization problem example showing how to essentially "do JuMP" with OptimizationSystem + GalacticOptim
- [x] Update the nonlinear example to use the standard NonlinearProblem that now exists
- [x] There should be a whole section on the AbstractSystem interface. Page include:
    - [x] General Overview
    - [x] Setting default values in components with details about https://github.com/SciML/ModelingToolkit.jl/pull/777
    - [x] I think alias elimination needs its own full page with its assumptions and all of that. While technically only on ODESystem right now... it should get expanded.
    - [x] The graphs page should go in this section
    - [x] Page for all of the derivative tooling
- [x] The Systems subsection should then have a page for each of the AbstractSystems
- [x] The ODESystem docs should be updated to mention the detection functions, i.e. `islinear` and `isautonomous`.
- [x] Comparisons subsection
    - [x] Comparison against Simulink
    - [x] Comparison against Modelica
    - [x] Comparison against CASADI
 - [x] Add a utilities page with:
   - [x] https://github.com/SciML/ModelingToolkit.jl/issues/318
   - [x] https://github.com/SciML/ModelingToolkit.jl/issues/472

**Comment by ChrisRackauckas** [comment]
@shashi @YingboMa am I missing anything?

**Comment by ChrisRackauckas** [comment]
Document modelingtoolitize in its own page.

**Comment by pbouffard** [comment]
Not about a specific piece of documentation, but, I've seen at least a few times that new, user-visible functionality gets added without any update to documentation. Maybe sometimes the docs already existed so it was really more of a bugfix but I don't think that's always the case. 

So for example, `@named` was added recently and I think I get the gist of it from the example, but it really should be possible to `?@named`, and this should be included in the docs in more than just an example. This example is pretty trivial of course and probably most users wouldn't be bothered by it, but just browsing closed PRs I could pick on e.g. https://github.com/SciML/ModelingToolkit.jl/pull/840 which doesn't itself update the docs to include the new functionality. Yes, in this case 5b573981aa6ce508c31f7341dc3226a0861a62e4 does add to the docs, and actually did so before the PR was merged. But arguably this is the same situation, just reversed, i.e. either way the code isn't yet in sync with the docs. Also in this case the docs are updated only in an example, and IMO one shouldn't have to browse through every example to discover something like this that is generally applicable. 

You might argue that one should read all the docs and I'd agree that that is ideal, but it probably will never happen as often as you'd like, and also after a user has read all the docs once it's not reasonable to ask them to re-read them with every release, in case something pertinent to them shows up in an example only.

I expect that to move as fast as you are, which is tremendous, it's distracting to always have to commit docs updates and code updates always perfectly in sync. That's not ideal in general but I wouldn't want you to be slown down either. But can I suggest the following to help the docs eventually catch up to the code or vice versa:

* make it a coding standard (in a `CONTRIBUTORS` file) that:
    * docs and code are in sync
    * all functionality should be documented in API reference docs (i.e. users shouldn't have to read every docs page, after every update, to discover new functionality and understand how to use it)
    * instances where master commits/PRs don't follow the above are OK (maintaners' prerogative), but in these cases the commits should include a `TODO (doc)` note so that these instances can be followed up on. Ideally the TODO's themselves are visible in the online help (`?<whatever>`) which will encourage users to contribute by adding docs.
    * New functionality is mentioned in the Changelog
* open a catch-all issue, something like "Documentation TODO's resolution", that can be mentioned in a PR template (see below)
* start a Changelog file to help communicate new functionality; if it's not yet documented that could be noted, which would encourage community docs contributions
* add a [PR template](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) with a checklist that includes something like:
    * Is new user-visible functionality documented, or if not, has a `TODO (docs):` been included in the source for easy later reference?
    * Have documentation updates been reflected in the code, or if not, has a `TODO (docs):` been included in the source for easy later reference?
    * For any examples added to docs are all the features used included in the API documentation, or if not, has a `TODO (docs):` been included in the source for easy later reference?
    * Has the Changelog been updated to mention any new functionality?
* add an issue template that asks if the issue relates to missing documentation, and if so has an easy checklist to allow the reporter to describe in what way the docs are missing. It can also point to the catch-all docs issue as a place to note minor docs issues (and see if they've already been reported)
* add a "documentation" label in GitHub to encourage contributors to fix these TODO's

Really none of this is unique to this repo and is just IMO good software engineering practice. I'd be happy to make a PR to add the above (or whatever it becomes after discussion). And to be clear the state of the docs is already much better than I've seen in many projects. I'd just like to help it stay that way, and ideally while leaning on the community to help this happen so the core contributors can mostly focus on the core development that only they can do. Finally apologies if any or all of this has already been discussed somewhere before that I didn't find in a relatively quick search!

**Comment by ChrisRackauckas** [comment]
These last few weeks have been absolutely crazy because we were trying to hit a very narrow deadline on a paper, and we finished a few minutes before the deadline. The documentation got a little messed up here, since part of the reason for the TODO's in the docs is because they were direct messages to collaborators like @YingboMa to document design decisions that we're going to execute in the near future.

So, it's all part of the coding standard, but we broke it for a rush and it might take a few weeks to sort through all of it. I plan to add a few tutorials today though.

**Comment by pbouffard** [comment]
Totally get it, and I didn't mean to suggest that anyone wasn't doing a good job on docs in general or in terms of what's mentioned in this issue specifically. I'm just suggesting some ways that might help lift some of the burden from you all who are doing all the really hard work.

In case you can't tell I'm pretty excited about what MTK and related packages can enable and want to help out where I can, but not having a deep background in the tech that it all is based on, I probably for now at least can largely contribute in terms of things like doc updates, so my suggestions are offered with helping myself and others to do just that. :)

**Comment by ChrisRackauckas** [comment]
I added a link to https://github.com/SciML/ColPrac for the contributor's guide.

>open a catch-all issue, something like "Documentation TODO's resolution", that can be mentioned in a PR template (see below)

Catch-all issues are bad. Docs issues should just get issues.

>start a Changelog file to help communicate new functionality; if it's not yet documented that could be noted, which would encourage community docs contributions

We will get there. We aren't quite there yet. But we should stop breaking things about now. https://sciml.ai/news/ is a good source for big things though.

>add a PR template with a checklist that includes something like:
>add an issue template that asks if the issue relates to missing documentation, and if so has an easy checklist to allow the reporter to describe in what way the docs are missing. It can also point to the catch-all docs issue as a place to note minor docs issues (and see if they've already been reported)

I've never found these helpful, but if you want to add one go for it.

>add a "documentation" label in GitHub to encourage contributors to fix these TODO's

Done!

**Comment by ChrisRackauckas** [comment]
The opening tutorial issue was moved to https://github.com/SciML/ModelingToolkit.jl/issues/874

The rest are completed in https://github.com/SciML/ModelingToolkit.jl/pull/873
