### ISSUE TITLE
Ambiguous method error

### ISSUE THREAD

**Issue by ctessum** [SciML/ModelingToolkit.jl#823]
When using: 

```
[deps]
Catalyst = "479239e8-5488-4da2-87a7-35f2df7eef83"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqFlux = "aae7a2af-3d4f-5e19-a356-7da93b79d9d0"
Flux = "587475ba-b771-5e3f-ad9e-33799f191a9c"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
```

I get an ambiguous method error when creating a Catalyst reaction network, saying that there is more than one candidate for the `Symbol` method. However, both of the listed candidates are identical, i.e. they both refer to the same line in the same file:

https://github.com/SciML/ModelingToolkit.jl/blob/a9584055ad88563614ab526d3e931dd2beddb305/src/systems/diffeqs/abstractodesystem.jl#L171

Replacing this section with:

``` julia
    ODEFunction{iip}(
                     f,
                     jac = _jac === nothing ? nothing : _jac,
                     tgrad = _tgrad === nothing ? nothing : _tgrad,
                     mass_matrix = _M,
                     jac_prototype = sparse ? similar(get_jac(sys)[],Float64) : nothing,
                     syms = ModelingToolkit.Symbol.(states(sys)),
                     indepsym = ModelingToolkit.Symbol(independent_variable(sys)),
                    )
```

(i.e., adding `ModelingToolkit` in 2 places) fixes the problem.

Would it be useful for me to make a pull request with this change?

**Comment by ChrisRackauckas** [comment]
Do you have a reproducer? This seems odd... that shouldn't be a fix.

**Comment by ctessum** [comment]
Hmm, I can't get it to reproduce. I'll reopen if it pops up again.
