### ISSUE TITLE
Images for documentation

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#833]
![rc_circuit_odaeproblem](https://user-images.githubusercontent.com/1814174/109416294-55184100-798b-11eb-9f05-766a793f0ba2.png)
![rc_circuit_odeproblem](https://user-images.githubusercontent.com/1814174/109416295-55184100-798b-11eb-96d1-5bb7e40135ba.png)

**Comment by ChrisRackauckas** [comment]
![better_double_lorenz](https://user-images.githubusercontent.com/1814174/110242538-87461780-7f24-11eb-983c-4b2c93cfc909.png)

**Comment by ChrisRackauckas** [comment]
![mtkitized_pantelides_tsit5](https://user-images.githubusercontent.com/1814174/110587362-9524b400-8141-11eb-8b77-d940f108ae72.png)
![mtkitized_pantelides_rodas](https://user-images.githubusercontent.com/1814174/110587364-9524b400-8141-11eb-91c7-4e56ce4fa20b.png)

**Comment by ChrisRackauckas** [comment]
![Capture](https://user-images.githubusercontent.com/1814174/110589027-d4ec9b00-8143-11eb-8880-651da986504d.PNG)

**Comment by ChrisRackauckas** [comment]
![Discharging_capacitor svg](https://user-images.githubusercontent.com/1814174/172466302-907d39f3-6d2c-4d16-84a8-6de32bca757e.png)

**Comment by YingboMa** [comment]
![ll](https://user-images.githubusercontent.com/17304743/187790221-528046c3-dbdb-4853-b977-799596c147f3.png)

**Comment by bradcarman** [comment]
![plot1](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/5335827c-0f62-4aef-90dd-0e54432bf642)

**Comment by bradcarman** [comment]
![plot2](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/189212b9-2246-4322-97eb-df6086fb4574)

**Comment by bradcarman** [comment]
![plot3](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/493ba855-2fc4-4c5b-9e95-b0a0cab67dc6)

**Comment by bradcarman** [comment]
![plot4](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/79ea26b7-37ff-4093-9056-6f6da08d208c)

**Comment by bradcarman** [comment]
![odesys](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/d19fbcf4-781c-4743-87b7-30bed348ff98)

**Comment by bradcarman** [comment]
![actsys2](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/d59c1eff-5b1a-4260-94e3-40e596c7e578)

**Comment by bradcarman** [comment]
![actsys2](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/8ed50035-f6ac-48cb-a585-1ef415154a02)

**Comment by bradcarman** [comment]
![actsys1](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/054404eb-dbb7-4b85-95c0-c9503d0c4d00)

**Comment by bradcarman** [comment]
![ressys](https://github.com/SciML/ModelingToolkit.jl/assets/40798837/3740f0e2-7324-4c1f-af8b-eba02cfece81)

**Comment by ChrisRackauckas** [comment]
[DAE_slides.pdf](https://github.com/SciML/ModelingToolkit.jl/files/12829393/DAE_slides.pdf)
