### ISSUE TITLE
Default value metadata

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#846]
When the user set `@parameters R = 1` and `@variables x = 1`, then when we construct an ODESystem, we should be able to get `default_u0` and `default_p` from the metadata.

**Comment by pepijndevos** [comment]
What's the status of metadata in general? I was trying to play with this a bit, but can't seem to find much about it. SymbolicUtils.jl seems to have it
https://github.com/JuliaSymbolics/SymbolicUtils.jl/blob/b8945de5c1696b0563384313e747efcf67e053c6/src/types.jl#L169-L172
But on the latest git master of ModelingToolkit.jl I have `Sym{T}`

**Comment by ChrisRackauckas** [comment]
You're going to need to wait until @shashi or @YingboMa do a PR adding a few pieces to the `@variables` macro. Then there will be a good template for how metadata works to use it in other things. Until it's used there, think of it as in flux and could possibly change at any time.
