### ISSUE TITLE
New opening tutorial

### ISSUE THREAD

**Issue by ChrisRackauckas** [SciML/ModelingToolkit.jl#874]
We want a longer opening tutorial that progresses like:

- Defines and solves a simple ODE
- Adds some output observables?
- Adds some connections?

I kind of think @pbouffard's example is something nice to show off:

```julia
using ModelingToolkit, OrdinaryDiffEq

@parameters t a
@variables x(t) f(t)
D = Differential(t)

function decay(;name)
  eqs = [
    D(x) ~ -a*x + f
  ]
  ODESystem(eqs, name=name)
end

@named decay1 = decay()
@named decay2 = decay()

@named connected = ODESystem([
  decay2.f ~ decay1.x
  D(decay1.f) ~ 0
], t, systems=[decay1, decay2])

reduced_system = structural_simplify(connected)

x0 = [
  decay1.x => 1.0
  decay1.f => 0.0
  decay2.x => 1.0
]
p = [
  decay1.a => 0.1
  decay2.a => 0.2
]

prob = ODEProblem(reduced_system, x0, (0.0, 20.0), p)
sol = solve(prob, Tsit5())
```

as something that is useful to show too, since forcing functions and using another system to complete a system is a standard practice that should be demonstrated.

**Comment by asprionj** [comment]
Also show...?

- Macro-free usage (for dynamically defined stuff); at least mention / quickly show the possibility
- Vector-valued parameters, variables (probably wait for new handling of this before showing it)

**Comment by ChrisRackauckas** [comment]
>Macro-free usage (for dynamically defined stuff); at least mention / quickly show the possibility

Separate tutorial, not the opening tutorial.

>Re-running simulations with changed initial state and/or parameters without recompilation (the thing with the state/parameter mapping)

I don't think we want to keep that API (we want to just fix it), so I'd exclude it from the first tutorial and keep it in the FAQ.

**Comment by asprionj** [comment]
Ok, I'll give it a shot. When working on the docs anyway, I'll probably also address #564. Anything else that could be worth cleaning up (and at the same time helping me getting into MTK)?

**Comment by asprionj** [comment]
Plots for new example
![PLOT1](https://user-images.githubusercontent.com/13935112/111958369-703f2200-8aed-11eb-8bb4-0abe9652e850.png)
![PLOT2](https://user-images.githubusercontent.com/13935112/111958403-7e8d3e00-8aed-11eb-9d18-08b5180a59f9.png)
![PLOT3](https://user-images.githubusercontent.com/13935112/111958424-83ea8880-8aed-11eb-8f42-489f4b44c3bc.png)
![PLOT4](https://user-images.githubusercontent.com/13935112/111958439-877e0f80-8aed-11eb-9074-9d35458459a4.png)

**Comment by asprionj** [comment]
Anything left to do (just let me know...) or can we close this?
