### ISSUE TITLE
calling structural_simplify(sys) leads to InexactError: Int64(float)

### ISSUE THREAD

**Issue by lungd** [SciML/ModelingToolkit.jl#879]
I get the following error (with [961ee093] ModelingToolkit v5.13.0):
```
InexactError: Int64(-0.005182134942172038)
in top-level scope at main.jl:61
in structural_simplify at ModelingToolkit/0BgwD/src/systems/abstractsystem.jl:483
in alias_elimination at ModelingToolkit/0BgwD/src/systems/alias_elimination.jl:13
in find_linear_equations at ModelingToolkit/0BgwD/src/systems/systemstructure.jl:203
in push! at base/array.jl:934
in convert at base/number.jl:7 
in Int64 at base/float.jl:710 
```

Inside find_linear_equations, there is
https://github.com/SciML/ModelingToolkit.jl/blob/c868bf1bb327c3099bd0e8661c0d769c11a6139a/src/systems/systemstructure.jl#L181
and 
https://github.com/SciML/ModelingToolkit.jl/blob/c868bf1bb327c3099bd0e8661c0d769c11a6139a/src/systems/systemstructure.jl#L196-L204

@YingboMa did you mean to do something like the following?
```
if !(c isa Symbolic) && c isa Number
    if isinteger(c)
        c = convert(Integer, c)
        linear_term += c * var
        push!(coeffs, c)
    else
        all_int_algvars = false
    end
end
```

**Comment by jonniedie** [comment]
I'm getting this same error as well.

**Comment by ChrisRackauckas** [comment]
Any reproducer?

**Comment by lungd** [comment]
Not that easy to make a MWE from the code I have at the moment. Maybe @jonniedie can help?

**Comment by YingboMa** [comment]
Try #880 to see if that fixes the problem

**Comment by lungd** [comment]
Thanks @YingboMa. Can confirm that it works with that commit
