### ISSUE TITLE
Use metadata to store "parameter" flag

### ISSUE THREAD

**Issue by shashi** [SciML/ModelingToolkit.jl#881]
instead of `Symbolic{Parameter{Real}}`.

This will allow us to restrict number methods by default to `Symbolic{<:Number}`

**Comment by YingboMa** [comment]
This could be breaking. We might want to have an overload that makes `Symbolic{Parameter{Real}}(:x)` build `Symbolic{Real}(:x, metadata=Parameter)`

**Comment by ChrisRackauckas** [comment]
I think we should break it though. It's internally breaking, but not necessarily very breaking downstream if we overload it correctly.
