### ISSUE TITLE
Component library

### ISSUE THREAD

**Issue by baggepinnen** [SciML/ModelingToolkit.jl#883]
I couldn't find any issue explicitly discussing this so here we go

How do plans for building a library of models/components that users can piece together to build models look? I would argue that the component library is a very important part of why tools like simulink and modelica are popular and think that MT would benefit greatly from having an early component library as soon as possible. The number of early adopters would go way up if there was something to build from, and such a library would provide valuable testing, not only in the traditional unit-testing sense, but also that MT handles models that users commonly want to simulate.

Coming from a background with many years of industrial experience, TinyModia already has a quite functional, but small, component library
https://github.com/ModiaSim/TinyModia.jl/tree/main/models
enough to build some interesting models for early adopters
https://github.com/ModiaSim/TinyModia.jl/tree/main/examples

The same goes for media, which could be considered components or its own thing, a library of media would also be highly useful, similar to
https://github.com/ModiaSim/ModiaMedia.jl

**Comment by ChrisRackauckas** [comment]
I'll just say, there's going to be a huge announcement about this very soon, so questions will be answered when that happens.

**Comment by ohmsweetohm1** [comment]
If `TinyModia.jl` and `ModelingToolkit.jl` would join efforts it would be great.

Consider the RC example:

- `TinyModia.jl`
```julia
Filter = Model(
    R = Resistor | Map(R=0.5u"Ω"),
    C = Capacitor | Map(C=2.0u"F", init=Map(v=0.1u"V")),
    V = ConstantVoltage | Map(V=10.0u"V"),
    ground = Ground,
    connect = :[
      (V.p, R.p)
      (R.n, C.p)
      (C.n, V.n, ground.p)
    ]
)
```

- `ModelingToolkit.jl`
```julia
@named resistor = Resistor(R=0.5)
@named capacitor = Capacitor(C=2e-6)
@named source = ConstantVoltage(V=10)
@named ground = Ground()
connections = [
    connect_pins(source.p, resistor.p)
    connect_pins(resistor.n, capacitor.p)
    connect_pins(capacitor.n, source.n, ground.g)
 ]

@named model = ODESystem(connections, t, systems=[resistor, capacitor, source, ground])
```

It is very similar.
But I like that pretty much everything is user-defined and MTK is only the tool that supports all this - hence the name I guess. 😄 
So whatever the _huge announcement_ is, if it is from the SciML community it has to be great.

**Comment by ViralBShah** [comment]
TinyModia and MTK teams regularly interact with each other.

**Comment by longemen3000** [comment]
in the compound property calculation front, at first glance, we could do much better, as we could plug modern compound models (SAFT models, empiric helmholtz models) directly, instead of hoping for a third party to do the integration

**Comment by ChrisRackauckas** [comment]
[JuliaSim](https://juliacomputing.com/products/juliasim/) is launching to be a fully-featured library of premade components, some shipped in a way that is already pre-accelerated via ML tools, along with all of the other goodies required in order to be in the full Simulink or Modelica type of space. It's looking at a lot of models, like pharma/biophysics models, the Modelica standard library, etc. and should cover what is requested here.

As for this issue, I'm going to close it because a library of components would not go into this repo anyways. It's too big and needs to be a separate project. This of course doesn't preclude SciML from having a small premade library similar to https://github.com/SciML/DiffEqProblemLibrary.jl in the future, but what this does mean is, if you're looking for a dedicated team to make a huge curated model library, translate and test thousands of models, create a system for sharing models with restricted IP, etc. then that will be precisely what is releasing soon. 

And of course, because it's built on top of these open source modeling tools, it'll play nicely with all that is out there and help keep the development going strong.

**Comment by Sciemon** [comment]
> 
> 
> [JuliaSim](https://juliacomputing.com/products/juliasim/) is launching to be a fully-featured library of premade components, some shipped in a way that is already pre-accelerated via ML tools, along with all of the other goodies required in order to be in the full Simulink or Modelica type of space. It's looking at a lot of models, like pharma/biophysics models, the Modelica standard library, etc. and should cover what is requested here.

Will this component library (or parts of it) be free and open source?

**Comment by ChrisRackauckas** [comment]
The JuliaSim component library is a cloud computing product, and its curated model library will not be FOSS. However, it is built using a lot of open source tools, and this tooling (ModelingToolkit.jl, Symbolics.jl, etc.) will continue to be open source. This includes a lot of model importers. For example, CellMLToolkit.jl, the work going on with SBML readers, etc. will continue to be available. And then there's a bunch of domain-specific academic component libraries in power systems, neuroscience models, etc. which are being built as open source.

With these tools we are scouring all of the academic and industry work we can find to generate a model library where everything is already converted to documentation Julia packages and a distribution network for handling the thousands of models, along with pre-trained machine learning accelerated versions of the models. That is JuliaSim, and of course that then becomes of a product given the compute and manpower required to maintain such a library, and hopefully that provides a value to the industry users who tend to be most in need of the pre-made models.

That said, this does not preclude other standard libraries popping up, even in SciML, for specific domains and uses and all of that. In fact, we encourage the larger community to keep building open tools around the open tools.

**Comment by asprionj** [comment]
I guess the structure of the model library will be open / accessible, and even documented? That is, one (single person, company) could build his own library of specific components and combine it (nicely) with some of the commercial JuliaSim libraries?

**Comment by ChrisRackauckas** [comment]
Yes, the structure will be documented and I'm working with authors in areas like power systems to develop open libraries in the same form that will all play nicely together. From this and some Julia Lab grants, I'm hoping we get a few component libraries up and running with similar syntax to be a model for how the rest of the ecosystem can start building out such component libraries.
