### ISSUE TITLE
Building ODEProblem of non-simplified, connected system: cryptic error

### ISSUE THREAD

**Issue by asprionj** [SciML/ModelingToolkit.jl#890]
```julia
@parameters t τ
@variables x(t) u(t)
D = Differential(t)

PT1_eq = D(x) ~ (u - x)/τ

@named sys_A = ODESystem(PT1_eq)
@named sys_B = ODESystem(PT1_eq)

@named sys_con = ODESystem([sys_A.u ~ 1.0, sys_B.u ~ sys_A.x], systems=[sys_A, sys_B])
prob = ODEProblem(sys_con, [sys_A.x => 0.0, sys_B.x => 0.0], (0.0, 10.0), [sys_A.τ => 2.0, sys_B.τ => 5.0])
```
Gives:
```
ERROR: ArgumentError: Term{Real,Nothing}[sys_A₊u(t), sys_B₊u(t)] are missing from the variable map.
```

Obviously, the two pure "connecting variables" have to be explicitly eliminated from the resulting system. This works as it should:
```julia
sys_simp = structural_simplify(sys_con)
prob = ODEProblem(sys_simp, [sys_A.x => 0.0, sys_B.x => 0.0], (0.0, 10.0), [sys_A.τ => 2.0, sys_B.τ => 5.0])
```

- This behaviour / necessity is not mentioned in the docs. Add it?
- Can a more concise error message be thrown, i.e. can the underlying problem be detected before the problem with the variable map becomes apparent (I guess at a rather low level)?

**Comment by YingboMa** [comment]
We did explain `structural_simplify` in https://mtk.sciml.ai/stable/tutorials/acausal_components/#Connecting-and-Simulating-Our-Electrical-Circuit-1 . Could you make a PR to improve the wording if it is unclear? Also, I should stress that optimal eliminations are NP-hard and we don't guarantee `structural_simplify` eliminates all variables that can be eliminated.

What error message do you like?

**Comment by asprionj** [comment]
Thanks; it's true, it is explained in detail there. The problem probably is that the opening example (with the two lorenz systems) also is a connected system but does not require this step. So if one just starts there, he'll fall into this trap. Maybe just add a little note with a link to the RC-circuit example?

So I could also make a `DAEProblem` of the non-simplified system and solve it? Have to try that :wink:
(But I guess the performance would be worse and structural simplifaction to an ODE, if possible, is preferable in almost all cases...?)

**Comment by ChrisRackauckas** [comment]
>Thanks; it's true, it is explained in detail there. The problem probably is that the opening example (with the two lorenz systems) also is a connected system but does not require this step. So if one just starts there, he'll fall into this trap. Maybe just add a little note with a link to the RC-circuit example?

Hence the issue https://github.com/SciML/ModelingToolkit.jl/issues/874 . It would be really helpful if someone took a stab at writing a new opening tutorial for "what they think the average user needs to know". We're a few years deep into it so it's a bit hard to see what needs to be shown, but I think we need something simpler than the RC circuit but touches on observables (i.e. `y ~ 2x` where `y` isn't solved for, like in control problems), connections, completing systems, forcing functions. I think 99% of our issues are because we need a new tutorial, and a few ergonomic issues.

>So I could also make a DAEProblem of the non-simplified system and solve it? Have to try that 😉

Yeah... that's one of the ergonomic issues. We should solve that this week, it's not hard.

**Comment by YingboMa** [comment]
Can this issue be closed? It's not clear what we need to fix.

**Comment by ChrisRackauckas** [comment]
Yes, it doesn't seem like an issue, other than we need a new first tutorial.
