### ISSUE TITLE
remake ODEProblem or solve with changed parameters

### ISSUE THREAD

**Issue by asprionj** [SciML/ModelingToolkit.jl#891]
The case where only one (or some) of the parameters (and/or initial values for the state variables) need to be changed occurs frequently (parameter studies, manual "tuning", etc.). Considering the setup given in #890 (two parameters set as `[sys_A.τ => 2.0, sys_B.τ => 5.0]`), it would be awesome to be able to do (or similar):

```julia
solve(prob; p = [sys_A.τ => 1.0])
```
That is:
- Only provide a subset of the parameters, to only update those.
- Provide a mapping as when defining the `ODEProblem`

Currently, one would have to

```julia
using ModelingToolkit: varmap_to_vars
solve(prob; p=varmap_to_vars([sys_A.τ => 8.0, sys_B.τ => 0.5], parameters(sys_simp)))
```

which is OK from a performance-overhead view (somewhat like 0.5ms), but is just a pain to write. Also, it still is not possible to only update a subset of the parameters:
```repl
julia> varmap_to_vars([sys_B.τ => 3.0],parameters(sys_simp))
ERROR: ArgumentError: Sym{ModelingToolkit.Parameter{Real},Nothing}[sys_A₊τ] are missing from the variable map.
```

Since `(parameters(sys_simp) .=> prob.p)[2] == (sys_B.τ => 5.0) #true`, could `merge` be implemented for such pairs and used to allow for a partial update of parameters?

**Comment by YingboMa** [comment]
Good question. Indeed, we need better support for this. Converting an ODESystem into an ODEProblem drops information. It'll be good to preserve the map.

**Comment by ChrisRackauckas** [comment]
See https://github.com/SciML/ModelingToolkit.jl/issues/472 for the discussion. This workaround was added to the FAQ because indeed it's something we really need to fix. It is a good issue for someone to dig into though: we should transfer enough information to the ODEProblem/ODEFunction so that the varmaps work out in SciMLBase.
