### ISSUE TITLE
Conditional statements / branching in equations

### ISSUE THREAD

**Issue by asprionj** [SciML/ModelingToolkit.jl#893]
Sometimes, branching (with continuous transitions) is required in models to approximate the "real" physical behaviour. Think of laminar vs. turbulent flow regimes, fluid and solid properties, etc.

Can this already be represented in MTK, or is it intended to implement it?
Probably, all combinations of branches would have to be considered during manipulations, and the results "merged" again (e.g. into an overall sparsity structure, with structurally non-empty elements where any of the branch combinations is structurally non-zero).

**Comment by YingboMa** [comment]
See #38

**Comment by asprionj** [comment]
Let's see if I get things (in #38) right: If I do know what I'm doing and the transitions between the branches are Ck _(what's required at least for explicit / implicit solvers to work fine? C1, C2?)_, I could use `ifelse(equation_for_condition,equation_if_true,equation_if_false)` directly? In that case, the solver does not need to hit the transition point, so no need for a `ContinuousEvent`, right?

**Comment by ChrisRackauckas** [comment]
It still would be better to hit that point directly because of the order loss, but our goal will be to handle that automatically when we see `ifelse` in the RHS, so yes go for it. IfElse.ifelse

**Comment by asprionj** [comment]
Should we add (at least a a hint to) this in the introductory example? For many "real-world" problems, the ability to have piecewise functions is compulsory...
