### ISSUE TITLE
`default_u0` and `default_p` -> `defaults`

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#898]
I become increasingly convinced that we should just have `defaults`.

**Comment by anandijain** [comment]
like `defaults=(u0=>[sigma=>5...], p=>[beta=>2])`?

**Comment by YingboMa** [comment]
Just `defaults=(Dict(sigma=>5, beta=>2))`, we know states and parameters must be disjoint anyway.

**Comment by anandijain** [comment]
that's clean, I like it.

**Comment by pepijndevos** [comment]
#840 already effectively merged them anyway.

**Comment by ChrisRackauckas** [comment]
👍
