### ISSUE TITLE
Documenting how to generate namespaced names for AbstractSystem variables

### ISSUE THREAD

**Issue by Dhruva2** [SciML/ModelingToolkit.jl#902]
Suppose I have a ModelingToolkit ODESystem 

```
od::ODESystem
```
To interactively access a state V(t) or a state W(t) in the subsystem sub, I need only write the following code

```
od.V
od.sub.W
```
It would be good to have documentation on best practice to non-interactively access a state, and to control the namespace (i.e. to be able to switch between getting `sub.w` and `od.sub.w`). The solution I have seen so far is
```
getproperty(od, :V)
```
and
```
getproperty(getproperty(od, :sub), od, :W ; namespace = true)
```
where the keyword argument namespace switches between od.sub.W and sub.W.
Thanks!

**Comment by YingboMa** [comment]
Could you make a PR to the docs to document this behavior?
