### ISSUE TITLE
Formalism around models 

### ISSUE THREAD

**Issue by jpfairbanks** [SciML/ModelingToolkit.jl#91]
I am wondering about for modeling toolkit. Is there a mathematical formalism for “what is a model?”  I’ve worked with different groups of scientists and it seems like every field has an informal definition for their field.

I’m working on making scientific models more amenable to analysis and machine reasoning about the model semantics. I’d like rigorously analyze the problems and algorithms we work with, and I think formalizing the objects under investigation.

This is related to why I asked about “what does context mean” (#83)

Is anyone working on anchoring modeling toolkit to some formalization of general modeling?

**Comment by ChrisRackauckas** [comment]
I was going to make a package that does what I need, and then let someone build a formalization around it. Sounds like you're the guy.

**Comment by jpfairbanks** [comment]
That is the engineering pragmatism that gets things done, which I like. It would also be nice to generate some outputs that can be appreciated by the CS community. I think that requires either a horserace  paper that shows that ModelingToolkit makes scientific programmers (in the broad sense) more productive, or a theoretical contribution that grapples with "scientific modeling" in a formal sense and proves some theorems about it.

Mathematical functions are a good formalism, but modeling needs its own language of variables and composition rules. One would like to talk about how to compose and transform models in a valid way. For example, Unitful.jl does a great job of implementing the formalism of "Dimensional Analysis", which is a composition rule for *valid* scientific models. Type systems or category theory people have probably thought about this a good bit.

**Comment by ChrisRackauckas** [comment]
We've had quite a few discussions over the years, and I think we've settled on something good. Thanks @jpfairbanks . I think our current documentation is a lot more clear about the "what ModelingToolkit" than before.
