### ISSUE TITLE
Error in modelingtoolkitize, if no parameters are provided in ODEProblem

### ISSUE THREAD

**Issue by SLiemann** [SciML/ModelingToolkit.jl#911]
Hi,

modelingtoolkitize throws an error if no parameters are set in the ODEProblem and p is set to its default value DiffEqBase.NullParameters(). Here, the function does not need any parameters, which is different to #863 .
So this fails:
```Julia
function f(du,u,p,t)
    du[1] = u[2] + 1.0
    du[2] = u[1] - 1.0
end

prob = ODEProblem(f, rand(2,1), (0, 1.0))
test = modelingtoolkitize(prob)
```
```Julia
MethodError: no method matching length(::SciMLBase.NullParameters)
Closest candidates are:
  length(!Matched::Cmd) at process.jl:638
  length(!Matched::CompositeException) at task.jl:41
  length(!Matched::CSTParser.EXPR) at C:\Users\liemann\.julia\packages\CSTParser\uIeiO\src\spec.jl:306
  ...
in modelingtoolkitize at ModelingToolkit\Dr53c\src\systems\diffeqs\modelingtoolkitize.jl:56
```

But this works with a trivial paramemeter:
```Julia
prob = ODEProblem(f, rand(2,1), (0, 1.0),1)
test = modelingtoolkitize(prob)
```

So is this intentional or have I done something wrong?

**Comment by anandijain** [comment]
this may be intentional as having a lot of different constructors can get messy. just provide an `[]` or `NullParameters` as the fourth argument if there are no parameters used in `f`.
