### ISSUE TITLE
broadcasted component instantiation

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#912]
`@named resistors .= Resistor.(R=rand(10))` and make ten resistors, where I can index into resistors.

Alternatively it might be nice to make consistent with `@variables` and be able to:
`@named resistors(..) .= Resistor.(R=sth)`.
I'm not sure exactly how this one would work.

This version might make the most sense

`@named resistors[1:10] .= Resistor.(R=rand(10))`

**Comment by anandijain** [comment]
or use `@. @named` maybe

**Comment by YingboMa** [comment]
I don't want to keep adding macros to do this kind of stuff. Writing a loop isn't that hard.

**Comment by anandijain** [comment]
Haha all g
