### ISSUE TITLE
Visual model representation and interaction

### ISSUE THREAD

**Issue by asprionj** [SciML/ModelingToolkit.jl#918]
History cf. #907, for some ideas see [this comment therein](https://github.com/SciML/ModelingToolkit.jl/issues/907#issuecomment-802651432).

It would be desirable to have some sort of visual representation of a model, ideally interactive. Interactivity in a unidirectional sense (from model to visualization) that "browsing" through the model is possible, as well as copying to clipboard paths to state variables, parameters, etc.

The goal is to get the important benefits of a visual representation (such as in Simulink), namely understandig the structure of a complex model, without the hassle of full-fledged (i.e. bidirectional) interaction.

**Comment by anandijain** [comment]
@asprionj https://github.com/SciML/ModelingToolkit.jl/pull/919#issue-596754630 
does this get you part of the way there?

it's not interactive, but should at least give you a way of cleanly viewing states and subsystems

**Comment by asprionj** [comment]
Sure, it's a beginning :wink:
BTW, this issue is not primarily "about me"; it's just an idea that came up which would probably be appreciated by many working with large / complex systems (that they got from someone else and need to understand it).

**Comment by anandijain** [comment]
What's the next step you'd like to see?

**Comment by asprionj** [comment]
This is not a concrete goal with a predefined path. So I think next steps could be:

- Discussing how to get as much benefit with the least amount of work
- Brainstorming ideas for possible solutions / approaches
- Collect actual wishes / requirements / potential features

So I'll try to start a feature list here. One could (and I will, if I find the time) just go through some existing tools, e.g. the [OpenModelica Connection Editor](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/omedit.html), and sort all features of those tools into the categories below...

However, I'd suggest to stick to a unidirectional information flow (from the model to the visualization) for now. That means also to exclude the notion of a "visual modelling tool"; i.e. having a model-component library and being able to fully define new components in the tool, building up models from components, visually add connections, etc. This is a tremendous amount of work, and IMO it does not add much benefit - all of this can be (at least as) efficiently done in code. Do you agree?

So here's the lists for the features and possible approaches for implementation. I'll add whatever comes up from further discussions.

---

# Features

**Required (base)**
- Visualization of the entire model hierarchy (tree view)
- Visualization of the connections within one system (i.e. hierarchy level)

**Very helpful / important**
- List of state variables and parameters per (sub-)system (like opening a dialog box or something)
- Default values indicated for those variables/parameters for which they're set
- Indication which are algebraic variables / observables and were structurally eliminated (for simulation)
- Option to display full paths and to copy them to clipboard (e.g. to access specific variables in simulation results in the code)

**Nice to have**
- Simulation interface (bidirectional!)
  - Set initial state and parameter values
  - Set simulation parameters (start/stop times, solver)
  - Show timeseries plots for all variables in the model (e.g. from the hierarchy tree)

# Approaches
In order of increasing complexity, but also with increasing possibility of extension towards bi-directional information flow.
- Static HTML + JavaScript (e.g. one `div` per "view" (system), which is just made visible when this one is active in the tree view)
- Live server (e.g. using [LiveServer.jl](https://github.com/tlienart/LiveServer.jl)) serving a temporary folder containing all static HTML files (one per view/system).
- Client-side JavaScript framework that dynamically builds the visualisation of a serialized model.

**Comment by ChrisRackauckas** [comment]
See JuliaSim

**Comment by bradcarman** [comment]
There is also ModelingToolkitDesigner.jl which achieves most of the objectives in the list.  https://github.com/bradcarman/ModelingToolkitDesigner.jl
