### ISSUE TITLE
Testing equality of `Reaction`s

### ISSUE THREAD

**Issue by paulflang** [SciML/ModelingToolkit.jl#945]
I am failing to test the equality of two reactions. Here is a MWE that should reproduce the problem
```
julia> @parameters k, t
(k, t)

julia> @variables X(t)
(X(t),)

julia> reaction = Reaction(k, [X], nothing)
Reaction{Any,Int64}(k, Term{Real,Nothing}[X(t)], Term[], [1], Int64[], Pair{Any,Int64}[X(t) => -1], false)

julia> isequal(reaction, deepcopy(reaction))
false
```

**Comment by isaacsas** [comment]
This works for me if I load Catalyst first, where we define `==` for `Reaction`s and `ReactionSystem`s.

**Comment by isaacsas** [comment]
The plan is to ultimately move all the reaction functionality to Catalyst, so what is in ModelingToolkit is just a minimal set of components for defining reaction systems and converting them. All the other API-related functionality is / will go in Catalyst.

**Comment by isaacsas** [comment]
Ok, I’ll close this then. Feel free if to reopen if you encounter other issues.
