### ISSUE TITLE
Creating `ODESystem` with defaults from `ReactionSystem` and default u0/pars

### ISSUE THREAD

**Issue by paulflang** [SciML/ModelingToolkit.jl#947]
Is there a way to create an `ODESystem` from a `ReactionSystem` and also add defaults. This does not work:
```
convert(ODESystem, rs, defaults=append!(u0map, parammap))
```

**Comment by anandijain** [comment]
closed by #948

**Comment by isaacsas** [comment]
@paulflang should be fixed on master now courtesy of @anandijain.

**Comment by paulflang** [comment]
Thanks, brilliant!
