### ISSUE TITLE
PDAESystem and Index Reduction

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#961]
Out of curiosity I googled if PDAEs are a thing and they are, but the DAE meaning of index breaks down

I'm wondering if methods for tearing these systems and representing them in MTK will be cool or good to have. 

https://en.wikipedia.org/wiki/Partial_differential_algebraic_equation

**Comment by ChrisRackauckas** [comment]
Yes, you can just use PDESystem for that. PINNs already solve it.

**Comment by anandijain** [comment]
So close or leave open for the other index reduction methods?

**Comment by ChrisRackauckas** [comment]
Not much to say here. Index reduction is fine on the semi-discretizations.
