### ISSUE TITLE
logo?

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#970]
Currently docs just use DiffEq logo but this project getting big enough to warrant something cool for itself

I don't have any ideas currently

**Comment by asprionj** [comment]
What about something in this direction?
Or should it be more abstract?

![grafik](https://user-images.githubusercontent.com/13935112/118043741-0ff29100-b376-11eb-96b1-1bab3f5c9d37.png)

**Comment by anandijain** [comment]
imo this is too goofy 😆 personally the shading and 3d doesn't fit w the broader sciml branding

**Comment by asprionj** [comment]
Hehe, thought so :wink:. Was just having some fun fast-3D-modelling a toolbox.
But it seems that currently, all SciML-packages just use the DiffEq-logo...? So probably this is the time to think of a "generic logo template / guideline" for all related packages...?
