### ISSUE TITLE
Error when specifying a time variable forcing function if ModelingToolkit.jl is only imported (instead of using) 

### ISSUE THREAD

**Issue by agcmoser** [SciML/ModelingToolkit.jl#975]
Following the example [here](https://mtk.sciml.ai/stable/tutorials/ode_modeling/#Specifying-a-time-variable-forcing-function-1) I found out that everything works just fine when using ModelingToolkit but not when importing it

This works:
```julia
using ModelingToolkit
@variables t, x(t)
@parameters τ
D = Differential(t) # define an operator for the differentiation w.r.t. time
@named fol_variable_f = ODESystem([f ~ sin(t), D(x) ~ (f - x)/τ])

value_vector = randn(10)
f_fun3(t) = t >= 10 ? value_vector[end] : value_vector[Int(floor(t))+1]
@register f_fun2(t)

@named fol_external_f = ODESystem([f ~ f_fun3(t), D(x) ~ (f - x)/τ])
```
This does not work:
```julia
import ModelingToolkit
ModelingToolkit.@variables t, x(t)
ModelingToolkit.@parameters τ
D = ModelingToolkit.Differential(t) # define an operator for the differentiation w.r.t. time
ModelingToolkit.@named fol_variable_f = ModelingToolkit.ODESystem([f ~ sin(t), D(x) ~ (f - x)/τ])

value_vector = randn(10)
f_fun3(t) = t >= 10 ? value_vector[end] : value_vector[Int(floor(t))+1]
ModelingToolkit.@register f_fun3(t)

ModelingToolkit.@named fol_external_f = ModelingToolkit.ODESystem([f ~ f_fun3(t), D(x) ~ (f - x)/τ])

ERROR: UndefVarError: Num not defined
Stacktrace:
 [1] #45
   @ ~/.julia/packages/Symbolics/PwPtX/src/register.jl:43 [inlined]
 [2] _any
   @ ./reduce.jl:876 [inlined]
 [3] any
   @ ./reduce.jl:871 [inlined]
 [4] f_fun3(t::Symbolics.Num)
   @ Main ~/.julia/packages/Symbolics/PwPtX/src/register.jl:43
 [5] top-level scope
   @ REPL[104]:1
```

Am I doing something wrong or is this a bug? Thanks in advance and for the great effort you guys put into the whole SciML eco-system.

**Comment by ChrisRackauckas** [comment]
@shashi @YingboMa this boils down to an issue that `Symbolics.@register` requires `Num` and `Term` to be defined in the calling module. But it's a bit harder than that since if you just stick `Symbolics.Num` in the quotes in https://github.com/JuliaSymbolics/Symbolics.jl/blob/master/src/register.jl#L43 then you still get the issue that Symbolics.jl is not defined since ModelingToolkit is what's in Main. It needs to use the current module somehow to find Symbolics? 🤔
