### ISSUE TITLE
Better variable identification

### ISSUE THREAD

**Issue by YingboMa** [SciML/ModelingToolkit.jl#981]
Since `structural_simplify` is now reasonably robust, and we have to traverse the whole system when instantiating the graph representation. We might want to remove our current automatic state/parameter/independent variables detection, and always use `structural_simplify` to find them.

@ChrisRackauckas what do you think?

**Comment by ChrisRackauckas** [comment]
Sounds interesting. How does that apply to non ODE systems?

**Comment by YingboMa** [comment]
The other systems don't have automatic variable identification yet, so we can add automatic variable identification when we add `structural_simplify` support for them.
