### ISSUE TITLE
`ArgumentError: Term are missing from the variable map` when trying to supply defaults for subsystems

### ISSUE THREAD

**Issue by anandijain** [SciML/ModelingToolkit.jl#987]
```julia
using ModelingToolkit, LinearAlgebra, DifferentialEquations

function Pendulum(;name, g=9.81, r=1.)
    @parameters g r
    @variables x(t) y(t) T(t)
    D2 = Differential(t)^2
    eqs = [ 0 ~ T * x - D2(x)
            0 ~ T * y - D2(y) - g ]
    ODESystem(eqs, t, [x, y, T], [g, r]; name=name)
end

function ModelingToolkit.connect(a, b)
    [ 0 ~ a.x^2 + a.y^2 - a.r^2 
      0 ~ (a.x - b.x)^2 + (a.y - b.y)^2 - b.r^2 ]
end

@parameters t
D = Differential(t)

@named a = Pendulum(;g=9.81, r=1)
@named b = Pendulum(;g=9.81, r=1)
@named double = ODESystem(connect(a, b), t, systems=[a, b])

# o--a--b. horizontal initial condition
defaults = Pair[
    double.a₊x => 1,
    double.a₊y => 0,
    double.b₊x => 2,
    double.b₊y => 0,
    D(double.a₊x)=> 0,
    D(double.a₊y)=> 0,
    D(double.b₊x)=> 0,
    D(double.a₊y)=> 0
]

defaults = Pair[
    a.x => 1,
    a.y => 0,
    b.x => 2,
    b.y => 0,
    D(a.x)=> 0,
    D(a.y)=> 0,
    D(b.x)=> 0,
    D(b.y)=> 0
]

pendulum_sys = structural_simplify(dae_index_lowering(double))
prob = ODAEProblem(pendulum_sys, Pair[], (0, 1.); defaults=defaults)
sol = solve(prob)
```

Consider this double pendulum. I saw in the tests you sometimes do `x_t(t)`, couldn't figure that out though.
Neither of the `defaults` work (both failing with the same error): 
`ERROR: ArgumentError: Term{Real, Nothing}[a₊x(t), a₊y(t), b₊x(t), b₊y(t)] are missing from the variable map.`

I cannot do 
```julia
defaults = Pair[
    a₊x => 1,
...
]
```
because these variables don't exist globally.

I think other users will fall into this confusion. It may be obvious to the creators 😉 @YingboMa but is not obvious to me. 
Although I do understand how to supply the u0's for Differential states now (thanks!).

Note: I am also aware that the connection mechanism is wrong, this is unrelated I think, and doesn't affect my issue/question.

Edit: I believe composition and the inheritance issue may be related, but I think this is still worth posting

**Comment by anandijain** [comment]
Additionally https://github.com/SciML/ModelingToolkit.jl/blob/d6bb4b65fae7c288e462daa66b47bc2311a2c639/test/structural_transformation/index_reduction.jl#L101-L108
does not answer the question

**Comment by anandijain** [comment]
DataFrames recently started allowing just using strings in column names and makes life a lot easier.
I'm wondering if maybe we could allow people to pass `Vector{Pair{String, Real}}` 
where strings identify subsystems in sort of oop namespaced way, ie `"a.x" => 1` would work as a valid u0. 
Just brainstorming

**Comment by anandijain** [comment]
basically doing the vcat and fixing the `\_+` selector char

**Comment by YingboMa** [comment]
Defaults only works on the current level of the model by design.

**Comment by anandijain** [comment]
Reopen it you bully 😆 

What do you think of the string selecting at multiple levels?

Parsing would be annoying but it'd make it so much easier for new users

**Comment by YingboMa** [comment]
```julia
using ModelingToolkit, LinearAlgebra, OrdinaryDiffEq

function Pendulum(;name, g=9.81, r=1.)
    gval, rval = g, r
    @parameters g r
    @variables x(t) y(t) T(t)
    D2 = Differential(t)^2
    eqs = [ D2(x) ~ T * x
            D2(y) ~ T * y - g ]
    ODESystem(eqs, t, [x, y, T], [g, r]; name=name, defaults=(g=>gval, r=>rval))
end

function connect_pendulum(a, b)
    [ 0 ~ a.x^2 + a.y^2 - a.r^2
      0 ~ (a.x - b.x)^2 + (a.y - b.y)^2 - b.r^2 ]
end

@parameters t
D = Differential(t)

@named a = Pendulum(;g=9.81, r=1)
@named b = Pendulum(;g=9.81, r=1)
@named double = ODESystem(connect_pendulum(a, b), t, systems=[a, b])

u0 = Pair[
    a.x => 1
    a.y => 0
    b.x => 2
    b.y => 0
    D(a.x) => 0
    D(a.y) => 0
    D(b.x) => 0
    D(b.y) => 0
    a.T => 0
    b.T => 0
]

pendulum_sys = structural_simplify(ode_order_lowering(flatten(double)))
prob = ODAEProblem(pendulum_sys, u0, (0, 100.0))
sol = solve(prob, Tsit5())
```

and `using Plots; plot(sol)` gives
![Uploading dp.png…]()

**Comment by YingboMa** [comment]
Use `u0` for specifying initial conditions on the top level. `defaults` sets the default on the current level.

**Comment by YingboMa** [comment]
```julia
prob = ODEProblem(pendulum_sys, u0, (0, 100.0))
sol = solve(prob, Rodas5())
plot(sol, vars=(b.x, b.y), xlab="x", ylab="y", dpi=300)
```
gives a pretty nice plot
![dp_xy](https://user-images.githubusercontent.com/17304743/116010580-d4be3700-a5ed-11eb-83a0-f43325391a97.png)

Note that since we don't have a state selection pass, `ODAEProblem` produces serious numerical drifts.
